### ISSUE TITLE
Error: could not detect network

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1041]
**Describe the bug**
Got this issue in my environment after upgrading ethers to 5.0.2 when I run e2e chain.test.ts:

```
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.0.2)
      at Logger.makeError (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/logger/lib/index.js:179:21)
      at Logger.throwError (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/logger/lib/index.js:188:20)
      at JsonRpcProvider.<anonymous> (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:335:54)
      at step (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:46:23)
      at Object.throw (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:27:53)
      at rejected (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:19:65)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
**Expected behavior**
Tests should pass in any environment

**Steps to Reproduce**
+ Go to packages/lodestar
+ `yarn test:e2e`

**Comment by twoeths** [comment]
This does not happen on CI e2e test but in my environment, we should figure out when this happens. The failed tests are chain.test.ts and deploy.test.ts.

**Comment by dapplion** [comment]
I've noticed that `ethers` throws this error (`event="noNetwork", code=NETWORK_ERROR`) whenever it can't connect to the given provider. So DNS errors, refused connection errors all will be shown as `could not detect network`.

To what Eth1.x provider are you connecting to in your local environment?

**Comment by mpetrunic** [comment]
@dapplion @tuyennhv is this resolved?

**Comment by dapplion** [comment]
No, and it's more an issue on ethers side, which reports networks errors in this very unspecific way

**Comment by wemeetagain** [comment]
Leaving open so @dapplion can open issue w ethers
