### ISSUE TITLE
Cannot read property 'fork' of null

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1045]
Syncing witti, started a node, then stopped.
On re-start hit this error, which crashed and stopped the node:
```
...
2020-06-24 20:09:00  [CHAIN]            info: Epoch 29 is justified! 
2020-06-24 20:09:00  [CHAIN]            info: Epoch 28 is finalized! 
2020-06-24 20:09:00  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x055ae68f7ff2da84ef8192fe2b587701fec57a3631878f6180df9fe55240d7a3, slot=962, epoch=30
2020-06-24 20:09:00  [CHAIN]            info: Processed new chain head newChainHeadRoot=0xcd1b6e12075a04b26ae1fa616642f5e61f23f079339f04d17ba894ac6eb2fdc6, slot=964, epoch=30
2020-06-24 20:09:01  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x9aaa2fe92de92cc55dfca434e21e0fc35b0dfc9e8fbf80b0e833704ab0f6779a, slot=968, epoch=30
2020-06-24 20:09:01  [CHAIN]            info: Finish restoring chain head from 68 blocks 
2020-06-24 20:09:01  [CHAIN]            info: restoreHeadState - duration=7321ms
  discv5:service Starting discv5 service +0ms
TypeError: Cannot read property 'fork' of null
    at BeaconChain.getENRForkID (/home/cayman/Code/lodestar/packages/lodestar/lib/chain/chain.js:239:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async MetadataController.start (/home/cayman/Code/lodestar/packages/lodestar/lib/network/metadata/metadata.js:35:79)
    at async Libp2pNetwork.start (/home/cayman/Code/lodestar/packages/lodestar/lib/network/network.js:128:5)
    at async BeaconNode.start (/home/cayman/Code/lodestar/packages/lodestar/lib/node/nodejs.js:158:5)
    at async Object.run [as handler] (/home/cayman/Code/lodestar/packages/lodestar-cli/lib/lodecli/cmds/beacon/cmds/run/run.js:77:3)
```

**Comment by twoeths** [comment]
I cannot reproduce this issue in my environment, need to try some more times...

**Comment by wemeetagain** [comment]
I think this happens when the chain runs for a while, and the node is not cleanly shutdown (but rather killed). Then on the next bootup this error happens.

**Comment by twoeths** [comment]
what made me surprised is 
```
   const state = await this.getHeadState();
    const currentVersion = state.fork.currentVersion;
```
the `getHeadState()` call returned null!!

**Comment by dapplion** [comment]
`lodestar/src/chain/chain.ts` is a typing nightmare! Set `strictNullChecks` = true PRs should shed some light on the issue
