### ISSUE TITLE
Inconsistent sync

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1047]
Syncing witti, sync is slow and inconsistent. There are many times where it seems to get 'stuck', where it is waiting for blocks and has errors like below. See https://discordapp.com/channels/593655374469660673/593655641445367808/725543186512216204

```
2020-06-24 20:37:36  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x6f6ea9419ccc6ef9d6b903d931007fc25e67dc0c88edbbe7c206a9cc55d29659, slot=319, epoch=9         
2020-06-24 20:37:36  [CHAIN]            info: Processed new chain head newChainHeadRoot=0xf13ab8f5af9119719d3a5e18d4001d5cb9de2835e9bf349142a8e90e06f83716, slot=320, epoch=10        
2020-06-24 20:37:36  [SYNC]             info: Fetching blocks for 321...384 slot range                                                                                                
2020-06-24 20:37:36  [SYNC]             info: Sync progress - currentEpoch=10, targetEpoch=6535, speed=27.6 slots/s, estimateTillComplete=2.1 hours                                   
2020-06-24 20:37:36  [CHAIN]            info: Epoch 8 is justified!                                                                                                                   
2020-06-24 20:37:36  [CHAIN]            info: Epoch 7 is finalized!                                                                                                                   
2020-06-24 20:37:36  [CHORES]           info: Started archiving states (finalized epoch #7)...                                                                                        
2020-06-24 20:37:36  [CHORES]           info: Started archiving 27 blocks from slot 192 to 223(finalized epoch #7)...                                                                 
2020-06-24 20:37:36  [CHORES]           info: Archiving of finalized states completed (finalized epoch #7)                                                                            
2020-06-24 20:37:36  [CHORES]           info: Archiving of 27 finalized blocks from slot 192 to 223 completed (finalized epoch #7)                                                    
2020-06-24 20:37:37  [SYNC]             info: Received goodbye request from 16Uiu2HAkzCkq7GNsZx7kuGiEpwT4ZfDC2ZdnE935tUYsSCTqV1s6, reason=2                                           
2020-06-24 20:37:37  [NETWORK]         error: failed to send request 24c20fbacbe451d2 to peer 16Uiu2HAkzCkq7GNsZx7kuGiEpwT4ZfDC2ZdnE935tUYsSCTqV1s6 Error: read ECONNRESET            
Error: read ECONNRESET                                                                                                                                                                
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)                                                                                                                      
2020-06-24 20:37:38  [SYNC]             info: Received goodbye request from 16Uiu2HAm6irZGcHgkqHsx4Q7u9umkSWvGEY4ZQgJoXjoBZA1Knnz, reason=1                                           
2020-06-24 20:37:46  [NETWORK]         error: failed to send request 1a2ad9defbcdb809 to peer 16Uiu2HAmBqaNcNitjW1kar4voXHhuHoJkfqr8yS4s1xCSqJVM3Vb Error: response timeout           
Error: response timeout                                                                                                                                                               
    at nextAbortHandler (/home/cayman/Code/lodestar/node_modules/abortable-iterator/index.js:37:20)                                                                                   
    at AbortSignal.abortHandler (/home/cayman/Code/lodestar/node_modules/abortable-iterator/index.js:16:29)                                                                           
    at AbortSignal.dispatchEvent (/home/cayman/Code/lodestar/node_modules/event-target-shim/dist/event-target-shim.js:818:35)                                                         
    at abortSignal (/home/cayman/Code/lodestar/node_modules/abort-controller/dist/abort-controller.js:52:12)                                                                          
    at AbortController.abort (/home/cayman/Code/lodestar/node_modules/abort-controller/dist/abort-controller.js:91:9)                                                                 
    at Timeout._onTimeout (/home/cayman/Code/lodestar/packages/lodestar/lib/network/util.js:119:53)                                                                                   
    at listOnTimeout (internal/timers.js:531:17)                                                                                                                                      
    at processTimers (internal/timers.js:475:7)                                                                                                                                       
2020-06-24 20:37:46  [SYNC]             warn: Failed to obtain chunk {"start":354,"end":384} from peer 16Uiu2HAmBqaNcNitjW1kar4voXHhuHoJkfqr8yS4s1xCSqJVM3Vb                  
2020-06-24 20:38:04  [NETWORK]         error: failed to send request 0e708c68d877f4e2 to peer 16Uiu2HAmVKjTm3YePQgQLxm3fsfAUVgE58opRHZGDXRNLNsqvzBv Error: response timeout   
Error: response timeout                                                                                                                                                               
    at nextAbortHandler (/home/cayman/Code/lodestar/node_modules/abortable-iterator/index.js:37:20)                                                                                   
    at AbortSignal.abortHandler (/home/cayman/Code/lodestar/node_modules/abortable-iterator/index.js:16:29)                                                                           
    at AbortSignal.dispatchEvent (/home/cayman/Code/lodestar/node_modules/event-target-shim/dist/event-target-shim.js:818:35)                                                         
    at abortSignal (/home/cayman/Code/lodestar/node_modules/abort-controller/dist/abort-controller.js:52:12)                                                                          
    at AbortController.abort (/home/cayman/Code/lodestar/node_modules/abort-controller/dist/abort-controller.js:91:9)                                                                 
    at Timeout._onTimeout (/home/cayman/Code/lodestar/packages/lodestar/lib/network/util.js:119:53)                                                                                   
    at listOnTimeout (internal/timers.js:531:17)                                                                                                                                      
    at processTimers (internal/timers.js:475:7)                                                                                                                                       
2020-06-24 20:38:04  [SYNC]             warn: Failed to obtain chunk {"start":321,"end":353} from peer 16Uiu2HAmVKjTm3YePQgQLxm3fsfAUVgE58opRHZGDXRNLNsqvzBv                  
2020-06-24 20:38:13  [SYNC]             info: Received goodbye request from 16Uiu2HAm853KbH6H4Cs7d5ChM4vTBjYekBfPTedDo7zBQtagWsAY, reason=2                                           
2020-06-24 20:38:13  [NETWORK]         error: failed to send request 1dbff99222604ecc to peer 16Uiu2HAm853KbH6H4Cs7d5ChM4vTBjYekBfPTedDo7zBQtagWsAY No response returned for method st
atus. request=1dbff99222604ecc                                                                                                                                                        
2020-06-24 20:38:16  [NETWORK]         error: failed to send request e845db025ec15c5a to peer 16Uiu2HAmBqaNcNitjW1kar4voXHhuHoJkfqr8yS4s1xCSqJVM3Vb Error: response timeout           
Error: response timeout                                                                                                                                                               
    at nextAbortHandler (/home/cayman/Code/lodestar/node_modules/abortable-iterator/index.js:37:20)                                                                                   
    at AbortSignal.abortHandler (/home/cayman/Code/lodestar/node_modules/abortable-iterator/index.js:16:29)                                                                           
    at AbortSignal.dispatchEvent (/home/cayman/Code/lodestar/node_modules/event-target-shim/dist/event-target-shim.js:818:35)                                                         
    at abortSignal (/home/cayman/Code/lodestar/node_modules/abort-controller/dist/abort-controller.js:52:12)                                                                          
    at AbortController.abort (/home/cayman/Code/lodestar/node_modules/abort-controller/dist/abort-controller.js:91:9)                                                                 
    at Timeout._onTimeout (/home/cayman/Code/lodestar/packages/lodestar/lib/network/util.js:119:53)                                                                                   
    at listOnTimeout (internal/timers.js:531:17)                                                                                                                                      
    at processTimers (internal/timers.js:475:7)                                                                                                                                       
2020-06-24 20:38:16  [SYNC]             warn: Failed to obtain chunk {"start":354,"end":384} from peer 16Uiu2HAmBqaNcNitjW1kar4voXHhuHoJkfqr8yS4s1xCSqJVM3Vb                  
2020-06-24 20:38:34  [NETWORK]         error: failed to send request 1a65b8bd2cf2ec09 to peer 16Uiu2HAmVKjTm3YePQgQLxm3fsfAUVgE58opRHZGDXRNLNsqvzBv Error: response timeout   
Error: response timeout                                                                                                                                                               
    at nextAbortHandler (/home/cayman/Code/lodestar/node_modules/abortable-iterator/index.js:37:20)                                                                                   
    at AbortSignal.abortHandler (/home/cayman/Code/lodestar/node_modules/abortable-iterator/index.js:16:29)                                                                           
    at AbortSignal.dispatchEvent (/home/cayman/Code/lodestar/node_modules/event-target-shim/dist/event-target-shim.js:818:35)                                                         
    at abortSignal (/home/cayman/Code/lodestar/node_modules/abort-controller/dist/abort-controller.js:52:12)                                                                          
    at AbortController.abort (/home/cayman/Code/lodestar/node_modules/abort-controller/dist/abort-controller.js:91:9)                                                                 
    at Timeout._onTimeout (/home/cayman/Code/lodestar/packages/lodestar/lib/network/util.js:119:53)                                                                                   
    at listOnTimeout (internal/timers.js:531:17)                                                                                                                                      
    at processTimers (internal/timers.js:475:7)                                                                                                                                       
2020-06-24 20:38:34  [SYNC]             warn: Failed to obtain chunk {"start":321,"end":353} from peer 16Uiu2HAmVKjTm3YePQgQLxm3fsfAUVgE58opRHZGDXRNLNsqvzBv                  
2020-06-24 20:39:04  [NETWORK]         error: failed to send request 5ecc023a7aac136e to peer 16Uiu2HAmVKjTm3YePQgQLxm3fsfAUVgE58opRHZGDXRNLNsqvzBv Error: response timeout   
Error: response timeout                                                                                                                                                               
    at nextAbortHandler (/home/cayman/Code/lodestar/node_modules/abortable-iterator/index.js:37:20)                                                                                   
    at AbortSignal.abortHandler (/home/cayman/Code/lodestar/node_modules/abortable-iterator/index.js:16:29)                                                                           
    at AbortSignal.dispatchEvent (/home/cayman/Code/lodestar/node_modules/event-target-shim/dist/event-target-shim.js:818:35)                                                         
    at abortSignal (/home/cayman/Code/lodestar/node_modules/abort-controller/dist/abort-controller.js:52:12)                                                                          
    at AbortController.abort (/home/cayman/Code/lodestar/node_modules/abort-controller/dist/abort-controller.js:91:9)                                                                 
    at Timeout._onTimeout (/home/cayman/Code/lodestar/packages/lodestar/lib/network/util.js:119:53)                                                                                   
    at listOnTimeout (internal/timers.js:531:17)                                           
    at processTimers (internal/timers.js:475:7)                                            
2020-06-24 20:39:04  [SYNC]             warn: Failed to obtain chunk {"start":321,"end":353} from peer 16Uiu2HAmVKjTm3YePQgQLxm3fsfAUVgE58opRHZGDXRNLNsqvzBv 
2020-06-24 20:39:05  [SYNC]            error: Max req retry for blocks by range. Failed chunks: [{"start":321,"end":353}]                                                             
2020-06-24 20:39:34  [NETWORK]         error: failed to send request 394c049ad000db54 to peer 16Uiu2HAmVKjTm3YePQgQLxm3fsfAUVgE58opRHZGDXRNLNsqvzBv Error: response timeout
Error: response timeout                      
    at nextAbortHandler (/home/cayman/Code/lodestar/node_modules/abortable-iterator/index.js:37:20)                                                                                   
    at AbortSignal.abortHandler (/home/cayman/Code/lodestar/node_modules/abortable-iterator/index.js:16:29)                                                                           
    at AbortSignal.dispatchEvent (/home/cayman/Code/lodestar/node_modules/event-target-shim/dist/event-target-shim.js:818:35)                                                         
    at abortSignal (/home/cayman/Code/lodestar/node_modules/abort-controller/dist/abort-controller.js:52:12)                                                                          
    at AbortController.abort (/home/cayman/Code/lodestar/node_modules/abort-controller/dist/abort-controller.js:91:9)                                                                 
    at Timeout._onTimeout (/home/cayman/Code/lodestar/packages/lodestar/lib/network/util.js:119:53)                                                                                   
    at listOnTimeout (internal/timers.js:531:17)                                           
    at processTimers (internal/timers.js:475:7)                                            
2020-06-24 20:39:34  [SYNC]             warn: Failed to obtain chunk {"start":321,"end":353} from peer 16Uiu2HAmVKjTm3YePQgQLxm3fsfAUVgE58opRHZGDXRNLNsqvzBv 
2020-06-24 20:39:35  [SYNC]            error: Max req retry for blocks by range. Failed chunks: [{"start":321,"end":353}]                                                             
2020-06-24 20:39:51  [SYNC]            error: Max req retry for blocks by range. Failed chunks: []                                                                                    
2020-06-24 20:39:51  [SYNC]             info: Imported blocks for slots: 321,322,323,325,329,330,331,332,333,334,336,337,338,339,340,341,344,345,346,347,348,349,350,352,354,355,356,3
57,358,359,361,362,365,366,367,368,370,371,372,373,375,376,377,379,381,383,384             
2020-06-24 20:39:51  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x16b6c37626da8cebf7ccfbf1141366a0f526064b50ccc67976b5319bac32ac6a, slot=321, epoch=10
2020-06-24 20:39:51  [CHAIN]            info: Processed new chain head newChainHeadRoot=0xd887647b7014d8be909a8301424dce35707eea02bbedb352868908fd67e4989b, slot=322, epoch=10

```

**Comment by dapplion** [comment]
@wemeetagain Is this issue obsolete?
