### ISSUE TITLE
Stalled sync

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1048]
Probably related to #1047 

Syncing witti, eventually the initial sync stalled completely, no further progress, even with 4 peers

the last logs present:

```
2020-06-24 20:55:07  [CHAIN]            info: Epoch 29 is justified! 
2020-06-24 20:55:07  [CHAIN]            info: Epoch 28 is finalized! 
2020-06-24 20:55:07  [CHORES]           info: Started archiving states (finalized epoch #28)... 
2020-06-24 20:55:07  [CHORES]           info: Archiving of finalized states completed (finalized epoch #28) 
2020-06-24 20:55:07  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x055ae68f7ff2da84ef8192fe2b587701fec57a3631878f6180df9fe55240d7a3, slot=962, epoch=30
2020-06-24 20:55:08  [CHAIN]            info: Processed new chain head newChainHeadRoot=0xcd1b6e12075a04b26ae1fa616642f5e61f23f079339f04d17ba894ac6eb2fdc6, slot=964, epoch=30
2020-06-24 20:55:08  [CHORES]           info: Started archiving 32 blocks from slot 864 to 895(finalized epoch #28)... 
2020-06-24 20:55:08  [CHORES]           info: Archiving of 32 finalized blocks from slot 864 to 895 completed (finalized epoch #28) 
2020-06-24 20:55:08  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x9aaa2fe92de92cc55dfca434e21e0fc35b0dfc9e8fbf80b0e833704ab0f6779a, slot=968, epoch=30
2020-06-24 20:55:18  [NETWORK]         error: failed to send request bd3fc69fcad56f2e to peer 16Uiu2HAmBqaNcNitjW1kar4voXHhuHoJkfqr8yS4s1xCSqJVM3Vb Error: response timeout
Error: response timeout
    at nextAbortHandler (/home/cayman/Code/lodestar/node_modules/abortable-iterator/index.js:37:20)
    at AbortSignal.abortHandler (/home/cayman/Code/lodestar/node_modules/abortable-iterator/index.js:16:29)
    at AbortSignal.dispatchEvent (/home/cayman/Code/lodestar/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
    at abortSignal (/home/cayman/Code/lodestar/node_modules/abort-controller/dist/abort-controller.js:52:12)
    at AbortController.abort (/home/cayman/Code/lodestar/node_modules/abort-controller/dist/abort-controller.js:91:9)
    at Timeout._onTimeout (/home/cayman/Code/lodestar/packages/lodestar/lib/network/util.js:115:55)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:416273) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at BeaconChain.<anonymous> (/home/cayman/Code/lodestar/packages/lodestar/lib/sync/sync.js:65:78)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:416273) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:416273) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-06-24 20:59:22  [SYNC]             info: Received goodbye request from 16Uiu2HAkvDJV2wMEgLVEjuUdtjpg5ejreWxJNYZ7zEFJyRwGrnxW, reason=1 
2020-06-24 21:01:24  [SYNC]             info: Received goodbye request from 16Uiu2HAmMz8b8cha8FLnCG6x6L5uU8YqfauLnUcnCCeNsLFEJVwY, reason=2 
2020-06-24 21:01:24  [NETWORK]         error: failed to send request 1b5f6986603cca0a to peer 16Uiu2HAmMz8b8cha8FLnCG6x6L5uU8YqfauLnUcnCCeNsLFEJVwY Error: read ECONNRESET
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
2020-06-24 21:25:17  [SYNC]             info: Received goodbye request from 16Uiu2HAkxM6gf6qNaVPPkREf1AyS8D7gAj75j4Cf5oy8Ch7FqzV5, reason=1 


```

**Comment by wemeetagain** [comment]
Resolved in #1130
