### ISSUE TITLE
await async functions to prevent unhandled rejections

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1063]
As of now, some expected errors such as a wrongly configured deposit contract cause an unhandled rejection. It would be best to handle this as expected errors by catching them at the CLI level and then do a clean process exit.
```
2020-06-26 16:14:13  [NODE]             info: Starting eth2 beacon node - LODESTAR! 
2020-06-26 16:14:13  [DB]               info: Connected to LevelDB database at .lodestar/dev/beacon/db-16Uiu2HAmLXTUhNJZgYayrQc2EkRLbrHU49EqFfiE8pffrzJchVDq 
2020-06-26 16:14:13  [CHAIN]            info: Chain not started, listening for genesis block 
2020-06-26 16:14:13  [ETH1]             info: Eth1 notifier is disabled but starting it to build genesis state 
(node:14720) UnhandledPromiseRejectionWarning: Error: There is no deposit contract at given address: TBD
    at EthersEth1Notifier.initContract (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/eth1/impl/ethers.ts:247:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at EthersEth1Notifier.startProcessEth1Blocks (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/eth1/impl/ethers.ts:265:7)
(node:14720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
However, in this case doing a try / catch won't save the unhandled rejection because the causing function is not awaited
https://github.com/ChainSafe/lodestar/blob/e247acf95db46133d6766458c3414ea77dc393f7/packages/lodestar/src/eth1/impl/ethers.ts#L94-L95

There are other instances of this happening in the codebase, detected with the rule [@typescript-eslint/no-floating-promises](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md)

```
@chainsafe/lodestar-validator: 
@chainsafe/lodestar-validator: /home/lion/Code/eth2.0/lodestar/packages/lodestar-validator/src/services/attestation.ts
@chainsafe/lodestar-validator:   66:5  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar-validator: 
@chainsafe/lodestar-validator: /home/lion/Code/eth2.0/lodestar/packages/lodestar-validator/src/services/block.ts
@chainsafe/lodestar-validator:   57:5  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar-validator: 
@chainsafe/lodestar-validator: /home/lion/Code/eth2.0/lodestar/packages/lodestar-validator/src/validator.ts
@chainsafe/lodestar-validator:   65:5  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar-validator:   66:5  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar-validator: 
@chainsafe/lodestar: 
@chainsafe/lodestar: /home/lion/Code/eth2.0/lodestar/packages/lodestar/src/api/rest/routes/validator/publishAggregateAndProof.ts
@chainsafe/lodestar:   25:11  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar: 
@chainsafe/lodestar: /home/lion/Code/eth2.0/lodestar/packages/lodestar/src/chain/blocks/processor.ts
@chainsafe/lodestar:   64:5  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar: 
@chainsafe/lodestar: /home/lion/Code/eth2.0/lodestar/packages/lodestar/src/chain/chain.ts
@chainsafe/lodestar:   129:5  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar:   233:5  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar:   281:5  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar: 
@chainsafe/lodestar: /home/lion/Code/eth2.0/lodestar/packages/lodestar/src/chain/genesis/genesis.ts
@chainsafe/lodestar:   66:5  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar: 
@chainsafe/lodestar: /home/lion/Code/eth2.0/lodestar/packages/lodestar/src/eth1/impl/ethers.ts
@chainsafe/lodestar:    95:5  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar:   278:5  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar: 
@chainsafe/lodestar: /home/lion/Code/eth2.0/lodestar/packages/lodestar/src/network/network.ts
@chainsafe/lodestar:   58:7  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar: 
@chainsafe/lodestar: /home/lion/Code/eth2.0/lodestar/packages/lodestar/src/node/nodejs.ts
@chainsafe/lodestar:   151:5  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar: 
@chainsafe/lodestar: /home/lion/Code/eth2.0/lodestar/packages/lodestar/src/tasks/index.ts
@chainsafe/lodestar:   62:5  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar:   63:5  error  Promises must be handled appropriately  @typescript-eslint/no-floating-promises
@chainsafe/lodestar: 
```

I would like to discuss what's the best route to deal with this issue
1. Make sure that all error throwing async functions are awaited so the error can be catched upstream
2. It's okay to have unhandled rejection warnings
3. Handle the [event](https://nodejs.org/api/process.html#process_event_unhandledrejection) at the process level (not recommended)

**Comment by wemeetagain** [comment]
I think its best to not have unhandled rejections, but rather ensure that all errors can be caught. (1)
:+1: for the linter rule, so we can catch all existing and future unawaited return values.

**Comment by 3xtr4t3rr3str14l** [comment]
i think catching the errors is the best method too.  i'll also add that linter rule
