### ISSUE TITLE
Altona: Initial Sync suspends with timeout

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1127]
**Describe the bug**
Sync Altona and the process suspends, there are a couple of `response timeout` errors

**Steps to Reproduce**
Sync Altona

**Logs**
This seems to be too slow to detect req/resp timeout as it took almost 1h (09:51:11 - 10:49:34):
```
2020-07-10 09:51:11  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAm6FBad3xnXj4WkkjpjaQQedn4rCmh8jCww2uw6MSSFNs2 requestId=6d3dc33918668bed, encoding=ssz_snappy
...
2020-07-10 10:49:34  [NETWORK]         error: failed to send request 6d3dc33918668bed to peer 16Uiu2HAm6FBad3xnXj4WkkjpjaQQedn4rCmh8jCww2uw6MSSFNs2 Error: response timeout
Error: response timeout
    at nextAbortHandler (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/abortable-iterator/index.js:37:20)
```

This seems to be too fast to detect req/resp timeout as it happens in same second (10:52:26):
```
2020-07-10 10:52:26  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmV2BjFPcY4QYRuWE5DxpS2KpfLogiSmVKe9Lp9mTt3XBU requestId=2e576ea0a9ed7b15, encoding=ssz_snappy
...
2020-07-10 10:52:26  [NETWORK]         error: failed to send request 2e576ea0a9ed7b15 to peer 16Uiu2HAmV2BjFPcY4QYRuWE5DxpS2KpfLogiSmVKe9Lp9mTt3XBU Error: response timeout
Error: response timeout
    at nextAbortHandler (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/abortable-iterator/index.js:37:20
```

**Comment by twoeths** [comment]
resolved by #1130

**Comment by twoeths** [comment]
Still see the issue today in my local environment with no special log (so probably same issue with another different root cause?)

**Comment by twoeths** [comment]
It's the same issue at the below log

```
2020-07-14 10:55:06  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmHyJyTFwEuuhVnysuX6GD79UH7McKjijm8EfBh1rj9XHb requestId=d3eb6e2bf7ed8206, encoding=ssz_snappy
2020-07-14 10:55:07  [NETWORK]       verbose: receive beacon_blocks_by_range response from 16Uiu2HAm9phNDb4SXXTDoMJDS2mLCGyf5LLTh6ZyxF8LdiGMTDNf requestId=a6aec67e558a252d, encoding=ssz_snappy
2020-07-14 10:55:07  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmVGeUeVEiCiibd19hjyhAQatre3jF8nZfsAYKgukXCDhS requestId=6aa4b105571bcb17, encoding=ssz_snappy
2020-07-14 10:55:11  [NETWORK]       verbose: receive beacon_blocks_by_range response from 16Uiu2HAmDuf2Aa7p1Q16bp18z7nw9omHoxqfih6i926VvDyEkA4f requestId=020efed2607b16d2, encoding=ssz_snappy
2020-07-14 10:55:11  [NETWORK]       verbose: receive beacon_blocks_by_range response from 16Uiu2HAmKvyXP7YTcKfyKHfssLVQDKbCSEMSnf6RnAbwynuBmkE5 requestId=6400698c0e2f01a3, encoding=ssz_snappy
2020-07-14 10:55:11  [NETWORK]       verbose: receive beacon_blocks_by_range response from 16Uiu2HAmKdp1hCGAw3AyZ3K7Ruoi6LjxDyan7p1UhtVkg9ACuGvK requestId=577bb67d513643ea, encoding=ssz_snappy
2020-07-14 10:55:12  [NETWORK]       verbose: receive ping request from 16Uiu2HAmKdp1hCGAw3AyZ3K7Ruoi6LjxDyan7p1UhtVkg9ACuGvK requestId=3203dfee9bb8275e, encoding=ssz_snappy
2020-07-14 10:55:12  [NETWORK]       verbose: Sent response for request 3203dfee9bb8275e
2020-07-14 10:55:12  [NETWORK]       verbose: receive status request from 16Uiu2HAmHyJyTFwEuuhVnysuX6GD79UH7McKjijm8EfBh1rj9XHb requestId=7c2b5668c0b7c126, encoding=ssz_snappy
```

So it's more than 5s already and 16Uiu2HAmHyJyTFwEuuhVnysuX6GD79UH7McKjijm8EfBh1rj9XHb did not response us but there is no timeout error throwed.

**Comment by mpetrunic** [comment]
Seems like we didn't send status response back. Maybe we have some silent error there?

**Comment by twoeths** [comment]
we sent status response back as the next log:
```
2020-07-14 10:55:12  [NETWORK]       verbose: Sent response for request 7c2b5668c0b7c126
```
so it's not related to status request/response.

**Comment by twoeths** [comment]
Only after I press `Ctrl + C`, I can see the timeout error:
```
2020-07-14 11:01:36  [NETWORK]         error: failed to send request d3eb6e2bf7ed8206 to peer 16Uiu2HAmHyJyTFwEuuhVnysuX6GD79UH7McKjijm8EfBh1rj9XHb Error: response timeout
Error: response timeout
    at nextAbortHandler (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/abortable-iterator/index.js:37:20)
    at AbortSignal.abortHandler (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/abortable-iterator/index.js:16:29)
    at AbortSignal.dispatchEvent (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
    at abortSignal (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/abort-controller/dist/abort-controller.js:52:12)
    at AbortController.abort (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/abort-controller/dist/abort-controller.js:91:9)
    at Timeout._onTimeout (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/network/util.js:95:51)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by mpetrunic** [comment]
I wonder if we need to call close on stream explicitly?

Like pass stream to eth2ResponseTimer as param, and close it manually on timeout?

**Comment by twoeths** [comment]
I suspect we use `abortable-iterator` too much. The way we handle timeout is straightforward but we have to base on AbortController to throw Error for pipe, and in my case I can only see timeout error if I press `Ctrl + C`. Having a look at `abortable-iterator`, I found quite complex code there with `while(true)` and it has to handle multiple abort signals..

Since our case is quite simple, I'd like to handle aborting async iterator ourself instead of keeping `abortable-iterator` busy ...

**Comment by mpetrunic** [comment]
I don't think we can do better abortable iterator (we could just introduce more edge cases and weird bugs). We also always create new abortable iterator.

I'm pretty sure if you call break in async iterator iterating stream, that it doesn't close stream but it waits for stream to close itself.
It's easy to try though.

**Comment by twoeths** [comment]
we can just return a reject promise in the middle as in this document: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of

I'll try closing streams way too ..
