### ISSUE TITLE
Winston type error: can't read property 'levels' of undefined

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1169]
**Describe the bug**
This does not happen in my local environments, just in CI unit tests:

```
chainsafe/lodestar: 2020-07-15 23:23:54  []                error: uncaughtException: Cannot read property 'levels' of undefined
@chainsafe/lodestar: TypeError: Cannot read property 'levels' of undefined
@chainsafe/lodestar:     at WinstonLogger.levels [as createLogEntry] (/home/runner/work/lodestar/lodestar/packages/lodestar-utils/src/logger/winston.ts:110:37)
@chainsafe/lodestar:     at WinstonLogger.createLogEntry [as verbose] (/home/runner/work/lodestar/lodestar/packages/lodestar-utils/src/logger/winston.ts:66:10)
@chainsafe/lodestar:     at ReqResp.sendResponseStream (/home/runner/work/lodestar/lodestar/packages/lodestar/src/network/reqResp.ts:4:3251)
```

It caused unit tests failed

**Comment by dapplion** [comment]
The error seems to come from this function.

```ts
  private createLogEntry(level: LogLevel, message: string, context?: Context|Error): void {
    if (this.silent || this.winston.levels[level] > this.winston.levels[this._level]) {
      return;
    }
    this.winston[level](message, {context});
  }
```
and `this.winston` is assigned in the constructor.

@tuyennhv Has this happened again? Did this error happen at the end or start of a test?

**Comment by twoeths** [comment]
@dapplion I haven't monitored it for a while, will add more info once I see it again.

**Comment by wemeetagain** [comment]
best guess, winston being stubbed somewhere, not stubbing out levels
