### ISSUE TITLE
reduce TypeError on produceAggregateAndProof if no attestationData match

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1182]
**Describe the bug**

If a validator calls `produceAggregateAndProof` with an `attestationData` that does not match any attestation a TypeError will happen while trying to reduce an empty array with no initial value.

```
2020-07-18 20:29:33  [VALIDATOR #0-13] error: Failed to produce aggregate and proof Error: Reduce of empty array with no initial value
TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at ValidatorApi.produceAggregateAndProof (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/api/impl/validator/validator.ts:110:12)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Timeout._onTimeout (/home/lion/Code/eth2.0/lodestar/packages/lodestar-validator/src/services/attestation.ts:188:27)
```

https://github.com/ChainSafe/lodestar/blob/1068d6e828699df04cd606ad5498ef7a85720ce8/packages/lodestar/src/api/impl/validator/validator.ts#L183

**Expected behavior**

This occurrence should be handled better.

1. A more clear error should be thrown, i.e. `No matching attestations found for attestationData`
2. Return the original attestation data without any extra aggregated signature.

This error can potentially prevent the validator from submitting the attestation? If so we should go with 2.

**Steps to Reproduce**

It's a common occurrence when running this test in a 1 node, 8 validators configuration
https://github.com/ChainSafe/lodestar/blob/6d13626135948786682379c36a65f9f0ea9c70e4/packages/lodestar/test/e2e/noEth1Sim.test.ts

**Comment by dapplion** [comment]
Resolved in current master
https://github.com/ChainSafe/lodestar/blob/f5d368eef5798902c563d968b3eeeffd23ecac10/packages/lodestar/src/api/impl/validator/validator.ts#L211-L213
