### ISSUE TITLE
Node or validator is not properly cleaned up in test

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1185]
**Describe the bug**

When running the tests in https://github.com/ChainSafe/lodestar/compare/dapplion/e2e+?expand=1 and successfully complete them, some component is not properly cleaned up and spam the terminal with this repeating error that never stops.

```
(node:3148) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `state` of 'undefined' or 'null'.
    at Timeout._onTimeout (/home/lion/Code/eth2.0/lodestar/packages/lodestar/test/e2e/noEth1Sim.test.ts:55:19)
(node:3148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:3148) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `state` of 'undefined' or 'null'.
    at Timeout._onTimeout (/home/lion/Code/eth2.0/lodestar/packages/lodestar/test/e2e/noEth1Sim.test.ts:55:19)
(node:3148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
``` 

**Expected behavior**

`stop` methods should clean and stop all components
```js
  after("Stop nodes and validators", async () => {
    for (const node of nodes) {
      await node.stop();
    }
    for (const validator of validators) {
      await validator.stop();
    }
  });
```

**Steps to Reproduce**

Checkout branch https://github.com/ChainSafe/lodestar/compare/dapplion/e2e+?expand=1 and
```
cd packages/lodestar
yarn test:e2e
```
Wait for the test to complete

**Comment by dapplion** [comment]
Still happening
```
2020-08-09 12:50:46  [VALIDATOR 8-16]  error: Failed to produce attestation slot=24, committee=0, error=Cannot read property 'state' of null
(node:10304) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'state' of null
    at BeaconChain.getHeadState (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/chain/chain.ts:44:80)
    at NaiveRegularSync.getNewTarget (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/sync/regular/naive/naive.ts:134:23)
    at NaiveRegularSync.start (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/sync/regular/naive/naive.ts:114:27)
    at BeaconSync.startRegularSync (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/sync/sync.ts:120:9)
    at BeaconSync.start (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/sync/sync.ts:57:9)
(node:10304) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10304) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10304) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'state' of null
    at BeaconChain.getHeadState (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/chain/chain.ts:44:80)
    at NaiveRegularSync.getNewTarget (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/sync/regular/naive/naive.ts:134:23)
    at NaiveRegularSync.start (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/sync/regular/naive/naive.ts:114:27)
    at BeaconSync.startRegularSync (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/sync/sync.ts:120:9)
    at BeaconSync.start (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/sync/sync.ts:57:9)
(node:10304) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10304) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit

**Comment by wemeetagain** [comment]
closing in favor of #1437
