### ISSUE TITLE
Initial Sync: Cannot read property 'state' of null

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1245]
**Describe the bug**
Initial Sync stopped in the middle with below logs:

```
2020-07-28 14:32:34  [CHAIN]            info: Processed new chain head newChainHeadRoot=0xab78bf9671359caa348741b72a8a7e8fe6fd742d14b7782d46a7810660d95e5a, slot=206805, epoch=6462
(node:38282) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'state' of null
    at BeaconChain.getHeadState (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/chain/chain.js:100:76)
    at async LocalClock.<anonymous> (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/sync/utils/attestation-collector.js:31:25)

(node:38282) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'state' of null
    at BeaconChain.getHeadState (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/chain/chain.js:100:76)
    at async LocalClock.<anonymous> (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/sync/utils/attestation-collector.js:31:25)
```

**Comment by twoeths** [comment]
and when I restart, I get this
```
2020-07-28 14:41:05  [CHAIN]            info: Processed new chain head newChainHeadRoot=0xab78bf9671359caa348741b72a8a7e8fe6fd742d14b7782d46a7810660d95e5a, slot=206805, epoch=6462
2020-07-28 14:41:05  [CHAIN]            info: Finish restoring chain head from 70 blocks
2020-07-28 14:38:18  [CHAIN]            info: restoreHeadState - duration=4826ms
 ✖ TypeError: Cannot read property 'state' of null
    at BeaconChain.getHeadState (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/chain/chain.js:100:76)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async BeaconChain.getENRForkID (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/chain/chain.js:238:19)
    at async MetadataController.start (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/network/metadata/metadata.js:35:79)
    at async Libp2pNetwork.start (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/network/network.js:112:5)
    at async BeaconNode.start (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/node/nodejs.js:158:5)
    at async Object.runHandler [as handler] (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar-cli/lib/cmds/beacon/cmds/run/run.js:75:3)
```

**Comment by twoeths** [comment]
This is interesting: block.message.stateRoot - which is added to forkchoice is
```
@@@ forkchoice toHexString block.message.stateRoot.valueOf() as Uint8Array 0x0d9b11fa0871e8a94f53563b61894566f6c8bdf20a99d32f280f6de47a48933b
```

while stateContext.state.hashTreeRoot() - which is added to state cache is
```
@@@ 206805 toHexString(item.state.hashTreeRoot()) 0x2b336be4a93dc7428379f8f4424245af71c495e6956598dd8f167c0ef4f9ac4d
```

**Comment by twoeths** [comment]
According to https://altona.beaconcha.in/block/206805, the one added to forkchoice is correct, meaning that block.message.stateRoot is correct.
So after we run stateTransition, somehow the post state hashTreeRoot() is not correct.

**Comment by mpetrunic** [comment]
maybe we forgot to copy state or block in chain restoration?

**Comment by twoeths** [comment]
this happens in both init sync and chain restoration with same error at exact same slot 206805

Do you know where can I query state of block 206805? I want to compare that with my environment.

**Comment by mpetrunic** [comment]
Either ask on discord or run some other client and query state. I would go first first solution :smile:

**Comment by wemeetagain** [comment]
alternatively, dump the prestate and block, use pyspec or zrnt to do the transition

**Comment by wemeetagain** [comment]
I managed to sync beyond 206805 on master

**Comment by twoeths** [comment]
The block root of 206805 and state root of parent block (206804) are correct
```
@@@ getPreState 206805 0xab78bf9671359caa348741b72a8a7e8fe6fd742d14b7782d46a7810660d95e5a
@@@ getPreState 206805 parentRoot=0xf6415bd6463b7b857187298400cc9bcdae0145adf367e483bebbe80c7cb81449
@@@ getPreState 206805 stateRoot of parent 0x6948adf489608c8b905b56e07da6e5e392559f8b5fb182d3a4bc9ba554e37cf3
```

I guess it's an issue with EpochContext of 206804?

**Comment by twoeths** [comment]
oh found out that I have wrong `config` object, using `--testnet altona` help me get through the issue

**Comment by 3xtr4t3rr3str14l** [comment]
@tuyennhv , what did you change in your config to fix this issue?  I just ran into the issue, and I'm not sure yet if I'm experiencing it for the same reason you were.  I generated my config using `--testnet altona` and still ran into this issue

**Comment by twoeths** [comment]
@3xtr4t3rr3str14l  I just do `--testnet altona` and I can get through it. The way I debug is to verify https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar-cli/src/cmds/beacon/cmds/run/run.ts#L35

we want the config of altona, for example MIN_GENESIS_TIME. Previously it got the mainnet config.
