### ISSUE TITLE
Cannot read property 'justifiedCheckpoint' of undefined

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1253]
While synced to the head of Altona, head was at 213631 at the time:
```
2020-07-28 23:36:30  [GOSSIP]        verbose: Incoming block at slot: 213632 
2020-07-28 23:36:30  [CHORES]           info: Started archiving states (finalized epoch #6673)...                
(node:427112) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'justifiedCheckpoint' of undefine
d
    at ArrayDagLMDGHOST.isCandidateForBestTarget (/home/cayman/Code/lodestar/packages/lodestar/lib/chain/forkChoi
ce/arrayDag/lmdGhost.js:528:17)
    at /home/cayman/Code/lodestar/packages/lodestar/lib/chain/forkChoice/arrayDag/lmdGhost.js:343:67
    at Array.filter (<anonymous>)
    at ArrayDagLMDGHOST.ensureCorrectBestTargets (/home/cayman/Code/lodestar/packages/lodestar/lib/chain/forkChoi
ce/arrayDag/lmdGhost.js:343:47)
    at ArrayDagLMDGHOST.addBlock (/home/cayman/Code/lodestar/packages/lodestar/lib/chain/forkChoice/arrayDag/lmdG
host.js:306:12)
    at updateForkChoice (/home/cayman/Code/lodestar/packages/lodestar/lib/chain/blocks/process.js:132:14)
    at /home/cayman/Code/lodestar/packages/lodestar/lib/chain/blocks/process.js:67:36
    at Generator.next (<anonymous>)
    at resume (/home/cayman/Code/lodestar/packages/lodestar/lib/chain/blocks/process.js:19:362)
    at /home/cayman/Code/lodestar/packages/lodestar/lib/chain/blocks/process.js:19:540
(node:427112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by thro
wing inside of an async function without a catch block, or by rejecting a promise which was not handled with .cat
ch(). (rejection id: 36)
```

**Comment by twoeths** [comment]
not sure how this happened, should be something in `forkchoice.prune()`.

when I run initial sync through the same block, I don't see the issue happened.

**Comment by twoeths** [comment]
If nodeA is parent of nodeB the  aIndex < bIndex. This does not means that the `nodes` array is sorted by slot. This was wrong: https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/chain/forkChoice/arrayDag/lmdGhost.ts#L618
