### ISSUE TITLE
Initial sync stall

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1268]
Syncing stopped after hitting this:
```
2020-07-30 20:03:16  [NETWORK]       verbose: receive beacon_blocks_by_range response with 4 chunks from 16Uiu2HA
kxrb8ataJCsFd5SZZBQV7NLKnqsP1ZXLsdqMTKXzgbnjM requestId=f2dcc7373c103c4c, encoding=ssz_snappy, body={"startSlot":
"213507","count":"6","step":"1"}                                                                                 
2020-07-30 20:03:16  [NETWORK]         error: failed to send request 7e2a0afa3bfeb1f6 to peer 16Uiu2HAmJWDU4pQZ4W
tYr9vJbK6NyztwUijGotxureNmbxS6qcaw Error: Failed to validate decrypted chunk             
Error: Failed to validate decrypted chunk                                                                        
    at /home/cayman/Code/lodestar/node_modules/libp2p-noise/dist/crypto.js:108:21
    at Generator.next (<anonymous>)                                                                              
    at resume (/home/cayman/Code/lodestar/node_modules/libp2p-noise/dist/crypto.js:17:362)
    at /home/cayman/Code/lodestar/node_modules/libp2p-noise/dist/crypto.js:17:540
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-07-30 20:03:16  [SYNC]             warn: Failed to obtain chunk {"start":213537,"end":213542} from peer 16Ui
u2HAmJWDU4pQZ4WtYr9vJbK6NyztwUijGotxureNmbxS6qcaw 
2020-07-30 20:03:16  [NETWORK]       verbose: receive beacon_blocks_by_range response with 5 chunks from 16Uiu2HA
mNKLWtiSgEef8nWzXJv4QxxFXSvBEFoDA1mQ8HuxtwFnv requestId=e7cd73b6d05e5d77, encoding=ssz_snappy, body={"startSlot":
"213519","count":"6","step":"1"}
2020-07-30 20:03:17  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmPKGjTX6KAoZ3o972
m7WFE5Wew53E3XNMvDvUwR8mnyNm requestId=cb514a41992522f2, encoding=ssz_snappy
2020-07-30 20:03:17  [NETWORK]       verbose: receive beacon_blocks_by_range response with 4 chunks from 16Uiu2HA
mPKGjTX6KAoZ3o972m7WFE5Wew53E3XNMvDvUwR8mnyNm requestId=cb514a41992522f2, encoding=ssz_snappy, body={"startSlot":
"213537","count":"6","step":"1"}
2020-07-30 20:03:17  [SYNC]             info: Imported blocks for slots: 213496,213498,213499,213505,213506,21350
7,213509,213511,213512,213513,213514,213515,213516,213517,213518,213519,213521,213522,213523,213524,213525,213526
,213527,213528,213529,213530,213531,213532,213533,213535,213536,213537,213538,213539,213540,213543,213544,213546,
213547,213548,213549,213550,213551,213552,213553,213555,213556 
2020-07-30 20:03:17  [SYNC]          verbose: last processed slot=213556 
2020-07-30 20:03:17  [SYNC]          verbose: updating block target 213556 
2020-07-30 20:03:17  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x702256938c4f3114230b211
054d95049cc4d9ab9619c30f19a66f9e68481db6f, slot=213496, epoch=6671                                               2020-07-30 20:03:17  [NETWORK]       verbose: receive ping request from 16Uiu2HAmP8XvBJgUWpW9acyjPuwS7hyCeiMAxVGJ
RyVaDqizynza requestId=159915aa892892e4, encoding=ssz_snappy                                                     2020-07-30 20:03:17  [NETWORK]       verbose: Sent response for request 159915aa892892e4                         
2020-07-30 20:03:17  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x7b00fe37df26f0bea0a800a58385de73030d6b2bbb390b9e18f53b8df1dd9a20, slot=213498, epoch=6671                                               
2020-07-30 20:03:17  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x8ada3c2fed97f1cc66f7590a382c3d4d675957dab7b5902858f151a0810b8eda, slot=213499, epoch=6671                                               
2020-07-30 20:03:17  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x73ce3c479a280f02fe1ea822d2f6ef8ec33a16091153b01ae8b93b6d6b923c69, slot=213505, epoch=6672                                               

...

2020-07-30 20:03:19  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x6b6b3a4dc13a1948579cbc86573b1b5477e7c0fe1f42237dee3ddee1bc497e6c, slot=213553, epoch=6673                                               
2020-07-30 20:03:19  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x4e21c2b27922539ebf133ff
85e0502e43630a9c6bb90cf761633b0053f053be3, slot=213555, epoch=6673                                               
2020-07-30 20:03:19  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x4867e0ed941d6519b3aa176
1c27119ab402a4e201c058b8a3a27d65aeb0eec06, slot=213556, epoch=6673     
2020-07-30 20:03:19  [SYNC]             info: Fetching blocks for 213557...213620 slot range                     2020-07-30 20:03:19  [SYNC]          verbose: updating block target 213620                                       
2020-07-30 20:03:19  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmB694Fo2V3cMbypUx
5YqrPqUr5TJ79kCAqTJmH8qbbQd4 requestId=b154ae26c1fdacad, encoding=ssz_snappy                                     2020-07-30 20:03:19  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAkxrb8ataJCsFd5SZZ
BQV7NLKnqsP1ZXLsdqMTKXzgbnjM requestId=ebf36593fff6d51a, encoding=ssz_snappy                                     
2020-07-30 20:03:19  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmKvyXP7YTcKfyKHfssLVQDKbCSEMSnf6RnAbwynuBmkE5 requestId=1ed302828f376db4, encoding=ssz_snappy                                     
2020-07-30 20:03:19  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmPKGjTX6KAoZ3o972
m7WFE5Wew53E3XNMvDvUwR8mnyNm requestId=55cf7c98836798de, encoding=ssz_snappy                                     2020-07-30 20:03:19  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmNKLWtiSgEef8nWzX
Jv4QxxFXSvBEFoDA1mQ8HuxtwFnv requestId=15a146c8d78de13e, encoding=ssz_snappy                                     
2020-07-30 20:03:19  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmP8XvBJgUWpW9acyjPuwS7hyCeiMAxVGJRyVaDqizynza requestId=0348802f447cce5e, encoding=ssz_snappy                                     
2020-07-30 20:03:19  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmL1NkfjbdtmNvSZab
88wAYsb9WvkA7Nen8yoPhagtEAUj requestId=37e31d2dec7b6325, encoding=ssz_snappy                                     2020-07-30 20:03:19  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmJWDU4pQZ4WtYr9vJ
bK6NyztwUijGotxureNmbxS6qcaw requestId=810f582d6beec7f7, encoding=ssz_snappy                                     
2020-07-30 20:03:19  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmTtkch9k5XCbedbiekqwspEpMinQDTkVR57GLDC3Fhokr requestId=6e7ea022f583ce46, encoding=ssz_snappy                                     
2020-07-30 20:03:19  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAm9ysN2Sqn8kD8Wa41
5sjJXhgaxxSLq1XCKXvGV9UN4Sn1 requestId=9948d595a1fab1a8, encoding=ssz_snappy                                     2020-07-30 20:03:19  [NETWORK]       verbose: sending beacon_blocks_by_range request to 16Uiu2HAmSat7rvSYMsyNCsnL
ZCwhzKrfNPsTb4yRb346vmUq83Sw requestId=e481d2716fe77db1, encoding=ssz_snappy                                     2020-07-30 20:03:19  [NETWORK]       verbose: receive beacon_blocks_by_range response with 3 chunks from 16Uiu2HA
mSat7rvSYMsyNCsnLZCwhzKrfNPsTb4yRb346vmUq83Sw requestId=e481d2716fe77db1, encoding=ssz_snappy, body={"startSlot":"213617","count":"4","step":"1"}                                                                                 
2020-07-30 20:03:19  [NETWORK]       verbose: receive beacon_blocks_by_range response with 6 chunks from 16Uiu2HAmKvyXP7YTcKfyKHfssLVQDKbCSEMSnf6RnAbwynuBmkE5 requestId=1ed302828f376db4, encoding=ssz_snappy, body={"startSlot":
"213569","count":"6","step":"1"}                                                                                 2020-07-30 20:03:19  [NETWORK]       verbose: receive beacon_blocks_by_range response with 6 chunks from 16Uiu2HA
mTtkch9k5XCbedbiekqwspEpMinQDTkVR57GLDC3Fhokr requestId=6e7ea022f583ce46, encoding=ssz_snappy, body={"startSlot":"213605","count":"6","step":"1"}                                                                                 
2020-07-30 20:03:19  [NETWORK]       verbose: receive beacon_blocks_by_range response with 5 chunks from 16Uiu2HAmPKGjTX6KAoZ3o972m7WFE5Wew53E3XNMvDvUwR8mnyNm requestId=55cf7c98836798de, encoding=ssz_snappy, body={"startSlot":
"213575","count":"6","step":"1"}                                                                                 2020-07-30 20:03:19  [NETWORK]       verbose: receive beacon_blocks_by_range response with 5 chunks from 16Uiu2HA
mL1NkfjbdtmNvSZab88wAYsb9WvkA7Nen8yoPhagtEAUj requestId=37e31d2dec7b6325, encoding=ssz_snappy, body={"startSlot":"213593","count":"6","step":"1"}                                                                                 
2020-07-30 20:03:20  [NETWORK]       verbose: receive beacon_blocks_by_range response with 3 chunks from 16Uiu2HAmB694Fo2V3cMbypUx5YqrPqUr5TJ79kCAqTJmH8qbbQd4 requestId=b154ae26c1fdacad, encoding=ssz_snappy, body={"startSlot":
"213557","count":"6","step":"1"}                                                                                 2020-07-30 20:03:20  [NETWORK]       verbose: receive beacon_blocks_by_range response with 4 chunks from 16Uiu2HA
mP8XvBJgUWpW9acyjPuwS7hyCeiMAxVGJRyVaDqizynza requestId=0348802f447cce5e, encoding=ssz_snappy, body={"startSlot":"213587","count":"6","step":"1"}                                                                                 
2020-07-30 20:03:20  [NETWORK]       verbose: receive beacon_blocks_by_range response with 6 chunks from 16Uiu2HAm9ysN2Sqn8kD8Wa415sjJXhgaxxSLq1XCKXvGV9UN4Sn1 requestId=9948d595a1fab1a8, encoding=ssz_snappy, body={"startSlot":
"213611","count":"6","step":"1"}                                                                                 

...
```

**Comment by twoeths** [comment]
I don't see a response for request `15a146c8d78de13e`, should  be a timeout issue but somehow it did not trigger error.

**Comment by twoeths** [comment]
There are multiple logs like below
```
2020-08-01 09:59:08  [NETWORK]       verbose: sending status request to 16Uiu2HAm1gPDqPY4qkMvyjSjXWESF8U9S72KesxRxENSYw3QViBD requestId=fc645b2b89bd5dfa, encoding=ssz_snappy
...
2020-08-01 09:59:22  [NETWORK]       verbose: got stream to 16Uiu2HAm1gPDqPY4qkMvyjSjXWESF8U9S72KesxRxENSYw3QViBD requestId=fc645b2b89bd5dfa, encoding=ssz_snappy
```
after I add more log to `sendRequestStream`
```
logger.verbose(`sending ${method} request to ${peerId.toB58String()}`, {requestId, encoding});
      const {stream} = await dialProtocol(libp2p, peerId, protocol, TTFB_TIMEOUT) as {stream: Stream};
      logger.verbose(`got stream to ${peerId.toB58String()}`, {requestId, encoding});
```
it's been more than 10secs and no error thrown
so the issue is `dialProtocol()` did not throw error even it's a timeout issue

**Comment by twoeths** [comment]
this one is even worse
```
2020-08-01 10:03:42  [NETWORK]       verbose: sending status request to 16Uiu2HAm1gPDqPY4qkMvyjSjXWESF8U9S72KesxRxENSYw3QViBD requestId=9f2b35a4816bf97c, encoding=ssz_snappy
...
2020-08-01 10:06:17  [NETWORK]       verbose: got stream to 16Uiu2HAm1gPDqPY4qkMvyjSjXWESF8U9S72KesxRxENSYw3QViBD requestId=9f2b35a4816bf97c, encoding=ssz_snappy
```
