### ISSUE TITLE
--testnet flag does not work: There is no deposit contract at given address: TBD

### ISSUE THREAD

**Issue by q9f** [ChainSafe/lodestar#1298]
**Describe the bug**
I cannot seem to figure out how to connect to the Medalla or Altona testnets.

**Expected behavior**
Run `lodestar beacon run --testnet medalla` to connect to the testnet.

**Steps to Reproduce**
1. Run `lodestar beacon run --testnet medalla`
2. See error

```
2020-08-03 00:24:14  [NODE]             info: Starting eth2 beacon node - LODESTAR! 
2020-08-03 00:24:14  [DB]               info: Connected to LevelDB database at .lodestar/beacon/chain-db 
2020-08-03 00:24:14  [CHAIN]            info: Chain not started, listening for genesis block 
(node:52833) UnhandledPromiseRejectionWarning: Error: There is no deposit contract at given address: TBD
    at EthersEth1Notifier.initContract (/usr/local/share/.config/yarn/global/node_modules/@chainsafe/lodestar/lib/eth1/impl/ethers.js:343:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async EthersEth1Notifier.startProcessEth1Blocks (/usr/local/share/.config/yarn/global/node_modules/@chainsafe/lodestar/lib/eth1/impl/ethers.js:366:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:52833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:52833) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Branch: `master`
 - Commit hash: 02d82b2d550c596fa91ced65194ccb9c33f58175

**Comment by q9f** [comment]
Same with init:

```
~/.opt/chainsafe/lodestar master
❯ lodestar beacon init --testnet medalla --rootDir $HOME/.lodestar

~/.opt/chainsafe/lodestar master
❯ lodestar beacon run --testnet medalla --rootDir $HOME/.lodestar 
2020-08-03 00:31:25  [NODE]             info: Starting eth2 beacon node - LODESTAR! 
2020-08-03 00:31:25  [DB]               info: Connected to LevelDB database at /home/user/.lodestar/beacon/chain-db 
2020-08-03 00:31:25  [CHAIN]            info: Chain not started, listening for genesis block 
(node:53863) UnhandledPromiseRejectionWarning: Error: There is no deposit contract at given address: TBD
    at EthersEth1Notifier.initContract (/usr/local/share/.config/yarn/global/node_modules/@chainsafe/lodestar/lib/eth1/impl/ethers.js:343:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async EthersEth1Notifier.startProcessEth1Blocks (/usr/local/share/.config/yarn/global/node_modules/@chainsafe/lodestar/lib/eth1/impl/ethers.js:366:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:53863) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:53863) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dapplion** [comment]
This issue has been fixed with recent patches. @q9f if you experience it again from the latest master, please reopen
