### ISSUE TITLE
--testnet flag does not work: no such file or directory, open '.lodestar/beacon/beacon.config.json'

### ISSUE THREAD

**Issue by q9f** [ChainSafe/lodestar#1299]
**Describe the bug**
I cannot seem to figure out how to connect to the Medalla or Altona testnets.

**Expected behavior**
Run `lodestar beacon run --testnet altona` to connect to the testnet.

**Steps to Reproduce**
1. Run `lodestar beacon run --testnet altona`
2. See error

```
usr/local/share/.config/yarn/global/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: ENOENT: no such file or directory, open '.lodestar/beacon/beacon.config.json'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at readFileSync (/usr/local/share/.config/yarn/global/node_modules/@chainsafe/lodestar-cli/lib/util/file.js:90:23)
    at readBeaconConfig (/usr/local/share/.config/yarn/global/node_modules/@chainsafe/lodestar-cli/lib/cmds/beacon/config.js:49:33)
    at builder (/usr/local/share/.config/yarn/global/node_modules/@chainsafe/lodestar-cli/lib/cmds/beacon/cmds/run/index.js:24:87)
    at Object.runCommand (/usr/local/share/.config/yarn/global/node_modules/yargs/build/lib/command.js:152:35)
    at Object.parseArgs [as _parseArgs] (/usr/local/share/.config/yarn/global/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.runCommand (/usr/local/share/.config/yarn/global/node_modules/yargs/build/lib/command.js:157:36)
    at Object.parseArgs [as _parseArgs] (/usr/local/share/.config/yarn/global/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.parse (/usr/local/share/.config/yarn/global/node_modules/yargs/build/lib/yargs.js:558:31) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '.lodestar/beacon/beacon.config.json'
}
```

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Branch: `master`
 - Commit hash: 02d82b2d550c596fa91ced65194ccb9c33f58175

**Comment by q9f** [comment]
Or trying to copy-paste the exact command from the Documentation, https://chainsafe.github.io/lodestar/usage/altona/:

```
~/.opt/chainsafe/lodestar master
❯ yarn run cli beacon run --testnet altona
yarn run v1.5.1
$ node --trace-deprecation ./packages/lodestar-cli/bin/lodestar beacon run --testnet altona
 ✖ TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.parse (path.js:1283:5)
    at downloadGenesisFile (/home/user/.opt/chainsafe/lodestar/packages/lodestar-cli/lib/cmds/beacon/testnets/index.js:77:41)
    at initHandler (/home/user/.opt/chainsafe/lodestar/packages/lodestar-cli/lib/cmds/beacon/cmds/init/init.js:54:47)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.runHandler [as handler] (/home/user/.opt/chainsafe/lodestar/packages/lodestar-cli/lib/cmds/beacon/cmds/run/run.js:51:5)

error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c node --trace-deprecation ./packages/lodestar-cli/bin/lodestar beacon run --testnet altona
Directory: /home/user/.opt/chainsafe/lodestar
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/user/.opt/chainsafe/lodestar/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by q9f** [comment]
Same also happens when using a custom `--rootDir`, the documentation does not really tell how to create that. Maybe merge the init and the run step into one process?

**Comment by dapplion** [comment]
@q9f Thanks for the suggestions! We've merged `init` and `run` into one command and updated the docs. Closing issue
