### ISSUE TITLE
Eth1 connection uncatched exception

### ISSUE THREAD

**Issue by protolambda** [ChainSafe/lodestar#1333]
**Describe the bug**

```
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 699)
(node:1) UnhandledPromiseRejectionWarning: Error: missing response (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":887,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"code":"ECONNRESET","path":null,"host":"goerli.prylabs.net","port":443}, url="https://goerli.prylabs.net", code=SERVER_ERROR, version=web/5.0.1)
    at Logger.makeError (/usr/app/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/usr/app/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at /usr/app/node_modules/@ethersproject/web/lib/index.js:142:36
    at step (/usr/app/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.throw (/usr/app/node_modules/@ethersproject/web/lib/index.js:14:53)
    at rejected (/usr/app/node_modules/@ethersproject/web/lib/index.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 700)
```
Getting this error on Medalla

**Expected behavior**

Stable eth1 connection, or handled errors

**Steps to Reproduce**

Connect with a loaded eth1 node, like prysmatic eth1 endpoint, and sometimes get an error. Lodestar can't handle it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu, running docker image
 - Version: `sha256:6680b25b46c5f8f1c951cb567242f50cf53055fda58ffcf98dbbae1874b969de` docker image (master branch ~10 hours ago)
 - Branch: master
 - Commit hash: Not sure which commit exactly, see docker image hash

**Comment by 3xtr4t3rr3str14l** [comment]
Might be worth including the solution for this issue into #1179
