### ISSUE TITLE
Cannot read property 'message' of null

### ISSUE THREAD

**Issue by protolambda** [ChainSafe/lodestar#1337]
**Describe the bug**

```
2020-08-04 15:23:02  [CHAIN]         verbose: Starting chain 
2020-08-04 15:23:14  [CHAIN]            info: Chain started, waiting blocks and attestations 
2020-08-04 15:23:14  [CHAIN]            info: Found last known finalized state at epoch #0 root 0x0000000000000000000000000000000000000000000000000000000000000000 
2020-08-04 15:23:15  [CHAIN]            info: Found 79 nonfinalized blocks in database from slot 192 to 303 
2020-08-04 15:23:15  [CHAIN]            info: Found finalized block at slot 192,
        root=0x5ce25fca09469f8473c31213a213b8ebbd76eebc41b47c19f984c5dabee6fe3a 
 ✖ TypeError: Cannot read property 'message' of null
    at BeaconChain.initForkChoice (/usr/app/packages/lodestar/lib/chain/chain.js:336:31)
    at async BeaconChain.restoreHeadState (/usr/app/packages/lodestar/lib/chain/chain.js:308:5)
    at async BeaconChain.start (/usr/app/packages/lodestar/lib/chain/chain.js:162:5)
    at async BeaconNode.start (/usr/app/packages/lodestar/lib/node/nodejs.js:157:5)
    at async Object.run [as handler] (/usr/app/packages/lodestar-cli/lib/cmds/beacon/run.js:87:3)

```

This error popped up after restarting and crashes the client shortly after starting.

**Expected behavior**

Load forkchoice data and/or blocks correctly during start.

**Steps to Reproduce**

Not sure.

**Screenshots**

x

**Desktop (please complete the following information):**
 - OS: ubuntu, running docker image
 - Version: `sha256:6680b25b46c5f8f1c951cb567242f50cf53055fda58ffcf98dbbae1874b969de` docker image (master branch ~10 hours ago)
 - Branch: master
 - Commit hash: Not sure which commit exactly, see docker image hash

**Comment by wemeetagain** [comment]
```
2020-08-05 13:29:14  [CHAIN]            info: Finish restoring chain head from 7 blocks
2020-08-05 13:29:14  [CHAIN]            info: restoreHeadState - duration=803ms
2020-08-05 13:29:16  [SYNC]            error: Can't find new peers, stopping sync
2020-08-05 13:29:16  [SYNC]             warn: Didn't receive any valid block in given range
2020-08-05 13:29:16  [SYNC]             info: Fetching blocks for 3335...3398 slot range
(node:37484) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'message' of null
    at BeaconSync.start (/Users/gary/dev/lodestar/packages/lodestar/lib/sync/sync.js:107:60)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by wemeetagain** [comment]
Iikely fetching a block from db that doesn't exist

**Comment by dapplion** [comment]
Should we add a check for variable `x` before calling `x.message`?

**Comment by dapplion** [comment]
Issue might be fixed, unclear. Chain will be refactored soon too,
