### ISSUE TITLE
Cannot convert null to bigint

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/lodestar#1358]
You'll notice a line break, the top half is the beacon node, and the bottom half is the validator.

```
2020-08-06 17:38:42  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x6f9306ab79b6cd008bd1a80bf7893db762b3f9fa1fecbf19b4e6b5a583d4819e, slot=9002, epoch=281
2020-08-06 17:38:42  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x98469686182406ff2c73628c98f15fe305d113822dc984f76d42dd3cf61ea554, slot=9003, epoch=281
2020-08-06 17:38:42  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x9fcd7909be9f854c0661df77ce325a40a03d737eb5fb8a56349a20d2464cd8e8, slot=9005, epoch=281
2020-08-06 17:38:42  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x0b8f3c93446a9216b50af658ac56ec36713c6101461a5b07e1ed43982072cc93, slot=9006, epoch=281
2020-08-06 17:38:43  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x3fd198bfe846f5df6d1c8664e5c409b7e2ce1635b87b981e6f85e51462c5fae2, slot=9008, epoch=281
2020-08-06 17:38:43  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x5b36f378aecf2b304640ba4a8e3995518e531651ca187cc0ad29bc5c3997d969, slot=9009, epoch=281
2020-08-06 17:38:43  [CHAIN]            info: Processed new chain head newChainHeadRoot=0xb2c56adcb7a7147773762e48711f5490b7464c01ee4d04324d7a65091e6a1249, slot=9010, epoch=281
2020-08-06 17:38:43  [CHAIN]            info: Processed new chain head newChainHeadRoot=0xee0a5c287da88838a36125af062fdfa9cc0e4123ff1b06abc26dbfd4600d5fd3, slot=9011, epoch=281
2020-08-06 17:38:43  [CHAIN]            info: Processed new chain head newChainHeadRoot=0xf82b135b41b760fd218defe99ca43fb4dc49a15e8bd12e6c945e4ad7e8642c8a, slot=9012, epoch=281
2020-08-06 17:38:44  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x5fea52a2f1d30ad067ba68d51079ee404cdfd61ab968b87325df7f507d5ffe01, slot=9013, epoch=281
2020-08-06 17:38:44  [CHAIN]            info: Processed new chain head newChainHeadRoot=0xe8f3543e539704f54260e409e7c446eb7ce696595e5f8b9292a8a2eff48bc84c, slot=9014, epoch=281
2020-08-06 17:38:44  [API]             error: Request 3 failed with unexpected error:  Cannot get duties for epoch more than two ahead: 493 <= 283 Error: Cannot get duties for epoch more than two ahead: 493 <= 283
    at Object.lte (/root/lodestar/packages/lodestar-utils/lib/assert.js:40:13)
    at ValidatorApi.getProposerDuties (/root/lodestar/packages/lodestar/lib/api/impl/validator/validator.js:99:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.<anonymous> (/root/lodestar/packages/lodestar/lib/api/rest/routes/validator/duties/proposer.js:27:27)
2020-08-06 17:42:28  [NETWORK]          warn: failed to send request d56f23ec68847a2c to peer 16Uiu2HAmAyvvREyrXPS9sSmNarrFodhPju6iyEDFRDhgZeK7UAQN reason=Failed to dial peer (ERR_UNSUPPORTED_PROTOCOL)
2020-08-06 17:42:28  [NETWORK]          warn: failed to send request 07f3f4c2b52edf6e to peer 16Uiu2HAm2YYCyEb5Y8s2sBNMYBn7Ys8B6dWreSRiN6uJ9SYrRkcG reason=Failed to dial peer (ERR_UNSUPPORTED_PROTOCOL)
2020-08-06 17:42:28  [NETWORK]          warn: failed to send request 9ed11d4c7bcc06a1 to peer 16Uiu2HAkyaZ3HU3raRP3j5G8CQR7wFvxGp7FHZEx7Ya3iv98H3aT reason=Failed to dial peer (ERR_UNSUPPORTED_PROTOCOL)
2020-08-06 17:42:28  [NETWORK]          warn: failed to send request 02efa879dfb256b3 to peer 16Uiu2HAmLPDjXtPnXzaPUv9LPTvaypV7f3PGduRCmReGCtwVPTXN reason=Failed to dial peer (ERR_UNSUPPORTED_PROTOCOL)
2020-08-06 17:42:28  [API]             error: Request 5 failed with unexpected error:  Cannot get duties for epoch more than two ahead: 494 <= 283 Error: Cannot get duties for epoch more than two ahead: 494 <= 283
    at Object.lte (/root/lodestar/packages/lodestar-utils/lib/assert.js:40:13)
    at ValidatorApi.getProposerDuties (/root/lodestar/packages/lodestar/lib/api/impl/validator/validator.js:99:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.<anonymous> (/root/lodestar/packages/lodestar/lib/api/rest/routes/validator/duties/proposer.js:27:27)

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2020-08-06 17:41:44  [VALIDATOR 0X9967166C] info: on new block epoch epoch=494, validator=0x9967166cce5fda95392bf8e65b4da7126c2120b0f2105cdc11e0d6bbc8a4f0343fa2c0778bc0c9ec2e741a3229894b98
2020-08-06 17:42:27  [VALIDATOR 0X9967166C] error: Failed to obtain attester duty for epoch 493 Error: Cannot convert null to a BigInt
SyntaxError: Cannot convert null to a BigInt
    at BigInt (<anonymous>)
    at NumberUintType.fromJson (/root/lodestar/node_modules/@chainsafe/ssz/lib/types/basic/uint.js:113:18)
    at /root/lodestar/node_modules/@chainsafe/ssz/lib/backings/structural/container.js:216:36
    at Array.forEach (<anonymous>)
    at ContainerStructuralHandler.fromJson (/root/lodestar/node_modules/@chainsafe/ssz/lib/backings/structural/container.js:208:39)
    at ContainerType.fromJson (/root/lodestar/node_modules/@chainsafe/ssz/lib/types/composite/abstract.js:183:28)
    at /root/lodestar/packages/lodestar-validator/lib/api/impl/rest/validator/validator.js:42:69
    at Array.map (<anonymous>)
    at RestValidatorApi.getAttesterDuties (/root/lodestar/packages/lodestar-validator/lib/api/impl/rest/validator/validator.js:42:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-06 17:42:28  [VALIDATOR 0X9967166C] error: Failed to obtain proposer duties Error: Cannot get duties for epoch more than two ahead: 494 <= 283

2020-08-06 17:46:14  [VALIDATOR 0X9967166C] error: Failed to obtain attester duty for epoch 495 Error: Cannot convert null to a BigInt
SyntaxError: Cannot convert null to a BigInt
    at BigInt (<anonymous>)
    at NumberUintType.fromJson (/root/lodestar/node_modules/@chainsafe/ssz/lib/types/basic/uint.js:113:18)
    at /root/lodestar/node_modules/@chainsafe/ssz/lib/backings/structural/container.js:216:36
    at Array.forEach (<anonymous>)
    at ContainerStructuralHandler.fromJson (/root/lodestar/node_modules/@chainsafe/ssz/lib/backings/structural/container.js:208:39)
    at ContainerType.fromJson (/root/lodestar/node_modules/@chainsafe/ssz/lib/types/composite/abstract.js:183:28)
    at /root/lodestar/packages/lodestar-validator/lib/api/impl/rest/validator/validator.js:42:69
    at Array.map (<anonymous>)
    at RestValidatorApi.getAttesterDuties (/root/lodestar/packages/lodestar-validator/lib/api/impl/rest/validator/validator.js:42:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Desktop (please complete the following information):**
 - OS:  ubuntu18
 - Version: 
 - Branch:  master
 - Commit hash:  bac8e4cbf5d1572c0082d5505ffd30e2b611c848

**Comment by mpetrunic** [comment]
Huh, looks like when received bad attester duties request we return 200 instead of 400^^

**Comment by dapplion** [comment]
This means that the lodestar API is returning `null[]` instead of `AttesterDuty[]` from the `getAttesterDuties()` endpoint `/duties/$epoch/attester`?

**Comment by dapplion** [comment]
Same as https://github.com/ChainSafe/lodestar/issues/1040 ?
