### ISSUE TITLE
Validator can trigger errors in Beacon Node

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1391]
**Describe the bug**
See https://discordapp.com/channels/593655374469660673/593655641445367808/742868789452079194

> So everytime I get one of these in the validator

![](https://cdn.discordapp.com/attachments/593655641445367808/742868789204484106/unknown.png)

> It freezes up the beacon chain for 5-10 mins with this:

![](https://cdn.discordapp.com/attachments/593655641445367808/742868961875460272/unknown.png)

> so i have shut down the validator just so the beacon can catch back up

**Expected behavior**
Validator cannot cause errors in the beacon node

**Comment by twoeths** [comment]
I can't reproduce the issue, being at epoch ~1300 and issued http://localhost:9596/validator/duties/3000/proposer to get proposer duties at epoch 3000, I got the log

```
2020-08-13 14:01:05  [API]             error: Request 4 failed with unexpected error:  Cannot get duties for epoch more than two ahead: 3000 <= 1302 Error: Cannot get duties for epoch more than two ahead: 3000 <= 1302
    at Object.lte (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar-utils/lib/assert.js:40:13)
    at ValidatorApi.getProposerDuties (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/api/impl/validator/validator.js:112:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.<anonymous> (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/api/rest/routes/validator/duties/proposer.js:27:27)
```

at browser side
```
{"statusCode":500,"error":"Internal Server Error","message":"Cannot get duties for epoch more than two ahead: 3000 <= 1302"}
```

so our node handles it pretty well with checking epoch before calling `processSlots` https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/api/impl/validator/validator.ts#L144

**Comment by twoeths** [comment]
At `onNewEpoch`, validators try to get proposer duties and attester duties. For proposer duties, we have a check that if `epoch > headEpoch + 2` then we return error as above but for attester duties, we don't have that check and blindly do `processSlots` until currentSlot.

So we need to have a check before doing `processSlots()` for attester duties, and also for other places using `processSlots()` as well.
