### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by q9f** [ChainSafe/lodestar#1396]
Running the beacon chain cli through yarn get's me an `Error: Could not locate the bindings file.`

**Describe the bug**
```
~/.opt/chainsafe/lodestar master*
❯ yarn run build                                                                 
yarn run v1.22.4
$ lerna run build
lerna notice cli v3.20.2
lerna info Executing command in 10 packages: "yarn run build"
@chainsafe/benchmark-utils: $ yarn build:lib && yarn build:types
@chainsafe/lodestar-utils: $ yarn build:lib && yarn build:types
@chainsafe/lodestar-params: $ yarn build:lib && yarn build:types
@chainsafe/benchmark-utils: $ babel src -x .ts -d lib --source-maps
@chainsafe/lodestar-utils: $ babel src -x .ts -d lib --source-maps
@chainsafe/lodestar-params: $ babel src -x .ts -d lib --source-maps
@chainsafe/benchmark-utils: Successfully compiled 3 files with Babel.
@chainsafe/lodestar-params: Successfully compiled 7 files with Babel.
@chainsafe/benchmark-utils: $ tsc --declaration --incremental --emitDeclarationOnly
@chainsafe/lodestar-utils: Successfully compiled 17 files with Babel.
@chainsafe/lodestar-params: $ tsc --incremental --declaration --outDir lib --emitDeclarationOnly
@chainsafe/lodestar-utils: $ tsc --incremental --project tsconfig.build.json --declaration --outDir lib --emitDeclarationOnly
@chainsafe/lodestar-types: $ yarn build:lib && yarn build:types
@chainsafe/lodestar-types: $ babel src -x .ts -d lib --source-maps
@chainsafe/lodestar-spec-test-util: $ yarn build:lib && yarn build:types
@chainsafe/lodestar-spec-test-util: $ babel src -x .ts -d lib --source-maps
@chainsafe/lodestar-types: Successfully compiled 24 files with Babel.
@chainsafe/lodestar-spec-test-util: Successfully compiled 6 files with Babel.
@chainsafe/lodestar-types: $ tsc --incremental --declaration --outDir lib --project tsconfig.build.json --emitDeclarationOnly
@chainsafe/lodestar-spec-test-util: $ tsc --incremental --declaration --project tsconfig.build.json --emitDeclarationOnly
@chainsafe/lodestar-config: $ yarn build:lib && yarn build:types
@chainsafe/lodestar-config: $ babel src -x .ts -d lib --source-maps
@chainsafe/lodestar-config: Successfully compiled 4 files with Babel.
@chainsafe/lodestar-config: $ tsc --incremental --declaration --outDir lib --emitDeclarationOnly
@chainsafe/lodestar-beacon-state-transition: $ yarn build:lib && yarn build:types
@chainsafe/lodestar-beacon-state-transition: $ babel src -x .ts -d lib --source-maps
@chainsafe/lodestar-beacon-state-transition: Successfully compiled 75 files with Babel.
@chainsafe/lodestar-beacon-state-transition: $ tsc --incremental --declaration --outDir lib --project tsconfig.build.json --emitDeclarationOnly
@chainsafe/lodestar-validator: $ yarn run build:lib && yarn run build:types
@chainsafe/lodestar-validator: $ babel src -x .ts -d lib --source-maps
@chainsafe/lodestar-validator: Successfully compiled 27 files with Babel.
@chainsafe/lodestar-validator: $ tsc --incremental --declaration --outDir lib --project tsconfig.build.json --emitDeclarationOnly
@chainsafe/lodestar: $ yarn run build:lib && yarn run build:types
@chainsafe/lodestar: $ babel src -x .ts -d lib --source-maps
@chainsafe/lodestar: Successfully compiled 238 files with Babel.
@chainsafe/lodestar: $ tsc --incremental --declaration --outDir lib --project tsconfig.build.json --emitDeclarationOnly
@chainsafe/lodestar-cli: $ yarn run build:lib && yarn run build:types
@chainsafe/lodestar-cli: $ babel src -x .ts -d lib --source-maps
@chainsafe/lodestar-cli: Successfully compiled 76 files with Babel.
@chainsafe/lodestar-cli: $ tsc --project tsconfig.build.json --incremental --declaration --outDir lib --emitDeclarationOnly
lerna success run Ran npm script 'build' in 10 packages in 22.8s:
lerna success - @chainsafe/benchmark-utils
lerna success - @chainsafe/lodestar-beacon-state-transition
lerna success - @chainsafe/lodestar-cli
lerna success - @chainsafe/lodestar-config
lerna success - @chainsafe/lodestar-params
lerna success - @chainsafe/lodestar-spec-test-util
lerna success - @chainsafe/lodestar-types
lerna success - @chainsafe/lodestar-utils
lerna success - @chainsafe/lodestar-validator
lerna success - @chainsafe/lodestar
Done in 23.18s.

~/.opt/chainsafe/lodestar master* 23s
❯ yarn run cli beacon --testnet medalla --eth1.provider.url http://127.0.0.1:9779
yarn run v1.22.4
$ node --trace-deprecation ./packages/lodestar-cli/bin/lodestar beacon --testnet medalla --eth1.provider.url http://127.0.0.1:9779
/home/user/.opt/chainsafe/lodestar/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /home/user/.opt/chainsafe/lodestar/node_modules/snappy/build/binding.node
 → /home/user/.opt/chainsafe/lodestar/node_modules/snappy/build/Debug/binding.node
 → /home/user/.opt/chainsafe/lodestar/node_modules/snappy/build/Release/binding.node
 → /home/user/.opt/chainsafe/lodestar/node_modules/snappy/out/Debug/binding.node
 → /home/user/.opt/chainsafe/lodestar/node_modules/snappy/Debug/binding.node
 → /home/user/.opt/chainsafe/lodestar/node_modules/snappy/out/Release/binding.node
 → /home/user/.opt/chainsafe/lodestar/node_modules/snappy/Release/binding.node
 → /home/user/.opt/chainsafe/lodestar/node_modules/snappy/build/default/binding.node
 → /home/user/.opt/chainsafe/lodestar/node_modules/snappy/compiled/12.14.1/linux/x64/binding.node
 → /home/user/.opt/chainsafe/lodestar/node_modules/snappy/addon-build/release/install-root/binding.node
 → /home/user/.opt/chainsafe/lodestar/node_modules/snappy/addon-build/debug/install-root/binding.node
 → /home/user/.opt/chainsafe/lodestar/node_modules/snappy/addon-build/default/install-root/binding.node
 → /home/user/.opt/chainsafe/lodestar/node_modules/snappy/lib/binding/node-v72-linux-x64/binding.node
    at bindings (/home/user/.opt/chainsafe/lodestar/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/user/.opt/chainsafe/lodestar/node_modules/snappy/snappy.js:2:34)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/.opt/chainsafe/lodestar/node_modules/@chainsafe/snappy-stream/lib/compress-stream.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:955:30) {
  tries: [
    '/home/user/.opt/chainsafe/lodestar/node_modules/snappy/build/binding.node',
    '/home/user/.opt/chainsafe/lodestar/node_modules/snappy/build/Debug/binding.node',
    '/home/user/.opt/chainsafe/lodestar/node_modules/snappy/build/Release/binding.node',
    '/home/user/.opt/chainsafe/lodestar/node_modules/snappy/out/Debug/binding.node',
    '/home/user/.opt/chainsafe/lodestar/node_modules/snappy/Debug/binding.node',
    '/home/user/.opt/chainsafe/lodestar/node_modules/snappy/out/Release/binding.node',
    '/home/user/.opt/chainsafe/lodestar/node_modules/snappy/Release/binding.node',
    '/home/user/.opt/chainsafe/lodestar/node_modules/snappy/build/default/binding.node',
    '/home/user/.opt/chainsafe/lodestar/node_modules/snappy/compiled/12.14.1/linux/x64/binding.node',
    '/home/user/.opt/chainsafe/lodestar/node_modules/snappy/addon-build/release/install-root/binding.node',
    '/home/user/.opt/chainsafe/lodestar/node_modules/snappy/addon-build/debug/install-root/binding.node',
    '/home/user/.opt/chainsafe/lodestar/node_modules/snappy/addon-build/default/install-root/binding.node',
    '/home/user/.opt/chainsafe/lodestar/node_modules/snappy/lib/binding/node-v72-linux-x64/binding.node'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

~/.opt/chainsafe/lodestar master*
❯ git log -n1
commit b4eec8b1a02197b905243135385d132b32f3f16c (HEAD -> master, origin/master, origin/HEAD)
Merge: 096ea27a9 e98e04548
Author: Cayman <caymannava@gmail.com>
Date:   Tue Aug 11 13:56:19 2020 -0500

    Merge pull request #1357 from ChainSafe/dapplion/cli-docs
    
    CliCommand builder
```

**Expected behavior**
Should run the beacon chain.

**Steps to Reproduce**
1. `yarn run cli beacon --testnet medalla`
2. `Error: Could not locate the bindings file.`

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Branch: master
 - Commit hash: b4eec8b1a02197b905243135385d132b32f3f16c
 - NodeJS: 12.14.1

**Comment by q9f** [comment]
Apparently, my `yarn` uses a different nodejs version.

https://stackoverflow.com/questions/52174381/yarn-not-installing-in-nvm-version-node-version

**Comment by q9f** [comment]
Well, same issue with the correct nodejs version.

```
~/.opt/chainsafe/lodestar master*
❯ which yarn                                                                     
/home/user/.nvm/versions/node/v12.14.1/bin/yarn
```

**Comment by wemeetagain** [comment]
This is likely from npm native bindings not properly built.
You should run `npm rebuild` to rebuild these bindings. (Note: this must be done with npm even tho we're using yarn)

**Comment by q9f** [comment]
Yes, completely removing system foo and pedantically installing everything though nvm versions fixed that.
