### ISSUE TITLE
Error: lastJustifiedBlock not in db

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1402]
Started node, stopped, restarted to this message:
```
2020-08-13 11:58:29  [CHAIN]            info: Found finalized state at slot 192, starting chain from there 
2020-08-13 11:58:29  [NODE]             info: Starting eth2 beacon node - LODESTAR! 
2020-08-13 11:58:29  [METRICS]          info: Starting metrics HTTP server on port 8008 
2020-08-13 11:58:29  [DB]               info: Connected to LevelDB database at .medalla/chain-db 
2020-08-13 11:58:37  [CHAIN]            info: Chain started, waiting blocks and attestations 
2020-08-13 11:58:37  [CHAIN]            info: Found last known finalized state at epoch #0 root 0x0000000000000000000000000000000000000000000000000000000000000000 
2020-08-13 11:58:38  [CHAIN]            info: Found 85 nonfinalized blocks in database from slot 192 to 316 
2020-08-13 11:58:38  [CHAIN]            info: Found finalized block at slot 192,
        root=0x5ce25fca09469f8473c31213a213b8ebbd76eebc41b47c19f984c5dabee6fe3a 
 ✖ Error: lastJustifiedBlock not in db
    at BeaconChain.initForkChoice (/home/cayman/Code/lodestar/packages/lodestar/lib/chain/chain.js:348:37)
    at async BeaconChain.restoreHeadState (/home/cayman/Code/lodestar/packages/lodestar/lib/chain/chain.js:321:5)
    at async BeaconChain.start (/home/cayman/Code/lodestar/packages/lodestar/lib/chain/chain.js:176:5)
    at async BeaconNode.start (/home/cayman/Code/lodestar/packages/lodestar/lib/node/nodejs.js:157:5)
    at async Object.run [as handler] (/home/cayman/Code/lodestar/packages/lodestar-cli/lib/cmds/beacon/run.js:96:3)
```

**Comment by wemeetagain** [comment]
Closing this, I was on this branch: https://github.com/ChainSafe/lodestar/pull/1378
