### ISSUE TITLE
Unit test failure

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#1416]
See https://github.com/ChainSafe/lodestar/pull/1398/checks?check_run_id=995835869#step:9:1490

**Comment by dapplion** [comment]
```
2020-08-17T22:47:47.1796376Z: [31m  2 failing[0m
2020-08-17T22:47:47.1803356Z: [0m  1) BeaconChain
2020-08-17T22:47:47.1804130Z:        "before each" hook for "should get enr fork id if found next fork":
2020-08-17T22:47:47.1805081Z: [0m[31m     Error: Validator indices must not be empty: 0 > 0[0m[90m
2020-08-17T22:47:47.1807480Z:       at Object.gt (/home/runner/work/lodestar/lodestar/packages/lodestar-utils/src/assert.ts:67:13)
2020-08-17T22:47:47.1808974Z:       at gt (/home/runner/work/lodestar/lodestar/packages/lodestar-beacon-state-transition/src/util/proposer.ts:43:10)
2020-08-17T22:47:47.1812196Z:       at EpochContext._resetProposers (/home/runner/work/lodestar/lodestar/packages/lodestar-beacon-state-transition/src/fast/util/epochContext.ts:212:9)
2020-08-17T22:47:47.1815302Z:       at EpochContext._resetProposers [as loadState] (/home/runner/work/lodestar/lodestar/packages/lodestar-beacon-state-transition/src/fast/util/epochContext.ts:76:10)
2020-08-17T22:47:47.1816286Z:       at BeaconChain.start (src/chain/chain.ts:10:255)
2020-08-17T22:47:47.1816881Z:       at Context.<anonymous> (test/unit/chain/chain.test.ts:33:9)
2020-08-17T22:47:47.1817597Z: [0m
2020-08-17T22:47:47.1819305Z: [0m  2) BeaconChain
2020-08-17T22:47:47.1820035Z:        "after each" hook for "should get enr fork id if found next fork":
2020-08-17T22:47:47.1820965Z: [0m[31m     TypeError: Cannot read property 'unsubscribeFromNewSlot' of undefined[0m[90m
2020-08-17T22:47:47.1821413Z:       at AttestationProcessor.stop (src/chain/attestation/pool.ts:2:120)
2020-08-17T22:47:47.1822728Z:       at BeaconChain.stop (src/chain/chain.ts:10:1393)
2020-08-17T22:47:47.1823254Z:       at Context.<anonymous> (test/unit/chain/chain.test.ts:36:9)
2020-08-17T22:47:47.1823803Z: [0m
2020-08-17T22:47:51.3753557Z: (node:3727) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'peerStore' of undefined
2020-08-17T22:47:51.3756796Z:     at Libp2pNetwork.getPeers (/home/runner/work/lodestar/lodestar/packages/lodestar/src/network/network.ts:4:2867)
2020-08-17T22:47:51.3757302Z:     at FastSync.getInitialSyncPeers (/home/runner/work/lodestar/lodestar/packages/lodestar/src/sync/initial/fast/index.ts:13:135)
2020-08-17T22:47:51.3757655Z:     at /home/runner/work/lodestar/lodestar/packages/lodestar/src/sync/utils/sync.ts:2:563
2020-08-17T22:47:51.3757996Z:     at /home/runner/work/lodestar/lodestar/packages/lodestar/src/sync/utils/sync.ts:13:327
2020-08-17T22:47:51.3758367Z:     at /home/runner/work/lodestar/lodestar/packages/lodestar/src/sync/initial/fast/index.ts:14:1010
2020-08-17T22:47:51.3758748Z:     at FastSync.sync (/home/runner/work/lodestar/lodestar/packages/lodestar/src/sync/initial/fast/index.ts:14:208)
2020-08-17T22:47:51.3759289Z:     at FastSync.start (/home/runner/work/lodestar/lodestar/packages/lodestar/src/sync/initial/fast/index.ts:13:2436)
2020-08-17T22:47:51.3760006Z: (node:3727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
2020-08-17T22:47:51.3760948Z: (node:3727) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-08-17T22:47:51.3913314Z: (node:3727) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'peerStore' of undefined
2020-08-17T22:47:51.3913681Z:     at Libp2pNetwork.getPeers (/home/runner/work/lodestar/lodestar/packages/lodestar/src/network/network.ts:4:2867)
2020-08-17T22:47:51.3914039Z:     at FastSync.getInitialSyncPeers (/home/runner/work/lodestar/lodestar/packages/lodestar/src/sync/initial/fast/index.ts:13:135)
2020-08-17T22:47:51.3914525Z:     at /home/runner/work/lodestar/lodestar/packages/lodestar/src/sync/utils/sync.ts:2:563
2020-08-17T22:47:51.3915023Z:     at /home/runner/work/lodestar/lodestar/packages/lodestar/src/sync/utils/sync.ts:13:327
2020-08-17T22:47:51.3915388Z:     at /home/runner/work/lodestar/lodestar/packages/lodestar/src/sync/initial/fast/index.ts:14:1010
2020-08-17T22:47:51.3915929Z:     at FastSync.sync (/home/runner/work/lodestar/lodestar/packages/lodestar/src/sync/initial/fast/index.ts:14:208)
2020-08-17T22:47:51.3916343Z:     at FastSync.start (/home/runner/work/lodestar/lodestar/packages/lodestar/src/sync/initial/fast/index.ts:13:2436)
2020-08-17T22:47:51.3916956Z: (node:3727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
