### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: write EPIPE

### ISSUE THREAD

**Issue by SeaMonkey82** [ChainSafe/lodestar#1498]
**Describe the bug**
Error recevied while syncing beacon
```
(node:107746) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:150:25)
    at writeGeneric (internal/stream_base_commons.js:141:3)
    at Socket._writeGeneric (net.js:770:11)
    at Socket._write (net.js:782:8)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at Socket.Writable.write (_stream_writable.js:305:11)
    at /home/seamonkey/Downloads/lodestar/packages/lodestar/node_modules/libp2p-tcp/node_modules/stream-to-it/sink.js:71:20
    at async Object.sink (/home/seamonkey/Downloads/lodestar/packages/lodestar/node_modules/libp2p-tcp/src/socket-to-conn.js:31:9)
```

**Expected behavior**
no error

**Steps to Reproduce**
Sync beacon

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 20
 - Branch: Master
 - Commit hash: 78b3764349b12651ddfc0fb15ff537aea9231217

**Comment by dapplion** [comment]
EPIPE = Broken pipe. @mpetrunic is it possible to turn stack tracing on by default for UnhandledPromiseRejectionWarning so we can have more info on this type of issues?

**Comment by mpetrunic** [comment]
From what I can tell we already have stack tracing it just not deep enough.
Maybe setting --stack-trace-limit= 50 would help. I was under impression that we handle all exceptions from libp2p.

**Comment by twoeths** [comment]
this happens more frequently in regular sync

**Comment by twoeths** [comment]
This happened to me bc I tried libp2p 0.29 branch and I only have only 1 "best peer" in regular sync

**Comment by twoeths** [comment]
closing this as the issue was resolved in the above 2 PRs and haven't seen it again since then
