### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: No state cache in db for finalized stateRoot

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#1508]
**Describe the bug**
I see this error when running the beacon node:

```
2020-09-03 17:01:18  [SYNC]             info: Fetching blocks for 299...362 slot range 
2020-09-03 17:01:19  [CHORES]           info: Started archiving 119 blocks from slot 1 to 192(finalized epoch #6)... 
2020-09-03 17:01:19  [CHORES]           info: Archive Blocks - duration=1602ms
2020-09-03 17:01:19  [CHORES]           info: Archiving of 119 finalized blocks from slot 1 to 192 completed (finalized epoch #6) 
2020-09-03 17:01:19  [CHORES]           info: Started archiving states (finalized epoch #6)... 
(node:25025) UnhandledPromiseRejectionWarning: Error: No state cache in db for finalized stateRoot 0xb434bb06e0df4b367999cb99642db708d17dfd596acc21fe43ce3069a2d2d59f
    at ArchiveStatesTask.run (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/lib/tasks/tasks/archiveStates.js:46:13)
    at async ChainEventEmitter.<anonymous> (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/lib/tasks/index.js:49:7)
(node:25025) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25025) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**

Not see the error and/or handle the rejection properly

**Comment by twoeths** [comment]
should be resolved by #1517

**Comment by twoeths** [comment]
@3xtr4t3rr3str14l can you verify this issue again?  With latest master, I can sync smoothly without seeing this anymore.

**Comment by 3xtr4t3rr3str14l** [comment]
haven't been seeing this issue anymore.  closing
