### ISSUE TITLE
"headStateRoot does not exist" error after restoring chain

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1511]
**Describe the bug**
This is the log I have after restoring my chain
```
2020-09-04 09:54:22  [CHAIN]         verbose: No pre-state found, dropping block slot=74693, blockRoot=0xe40332fe2f4daf2987396d0546b47f38b8a61fa7e327a9aa7b49c334c5c0c1f3, parentRoot=0x2a6be8ec75b7fd2a01b043b0784c19b8541c6473cc085ed00329dbf540ad4010

2020-09-04 10:21:17  [CHAIN]            info: Finish restoring chain head from 4326 blocks
2020-09-04 10:21:17  [CHAIN]            info: restoreHeadState - duration=1710133ms
 ✖ Error: headStateRoot does not exist
    at BeaconChain.getHeadStateContext (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/chain/chain.js:112:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async BeaconChain.getHeadState (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/chain/chain.js:118:13)
    at async BeaconChain.getENRForkID (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/chain/chain.js:287:19)
    at async MetadataController.start (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/network/metadata/metadata.js:35:79)
    at async Libp2pNetwork.start (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/network/network.js:136:5)
    at async BeaconNode.start (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/lib/node/nodejs.js:138:5)
    at async Object.beaconHandler [as handler] (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar-cli/lib/cmds/beacon/handler.js:86:3)
```

**Expected behavior**
No error

**Comment by twoeths** [comment]
closing as we have different caching machenism and state regen now, not happen anymore in my environment
