### ISSUE TITLE
Error: The operation was aborted

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#1515]
saw this error log when running `./bin/lodestar beacon --testnet medalla`

```
2020-09-08 18:54:47  [SYNC]             info: Received goodbye request from 16Uiu2HAmMzgyRh7FNm6F6SpuAnLtiP8HTNPX1mLWHtRaAjNj6amf, reason=129 
2020-09-08 18:54:47  [NETWORK]          warn: failed to send request ffc6f3dd55a7e275 to peer 16Uiu2HAm4WFowtSG8mVNn5K1TXn1vzt1A7GWhddKVBkY6z29FTgP reason=Failed to dial peer 16Uiu2HAm4WFowtSG8mVNn5K1TXn1vzt1A7GWhddKVBkY6z29FTgP (
    Error: The operation was aborted
        at AbortSignal.onAbort (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/node_modules/libp2p-tcp/src/index.js:86:14)
        at AbortSignal.dispatchEvent (/home/seraph/work/ChainSafe/lodestar/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
        at abortSignal (/home/seraph/work/ChainSafe/lodestar/node_modules/abort-controller/dist/abort-controller.js:52:12)
        at AbortController.abort (/home/seraph/work/ChainSafe/lodestar/node_modules/abort-controller/dist/abort-controller.js:91:9)
        at AbortSignal.onAbort (/home/seraph/work/ChainSafe/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/home/seraph/work/ChainSafe/lodestar/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
        at abortSignal (/home/seraph/work/ChainSafe/lodestar/node_modules/abort-controller/dist/abort-controller.js:52:12)
        at AbortController.abort (/home/seraph/work/ChainSafe/lodestar/node_modules/abort-controller/dist/abort-controller.js:91:9)
        at AbortSignal.onAbort (/home/seraph/work/ChainSafe/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/home/seraph/work/ChainSafe/lodestar/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
    Error: The operation was aborted
        at nextAbortHandler (/home/seraph/work/ChainSafe/lodestar/node_modules/abortable-iterator/index.js:37:20)
        at AbortSignal.abortHandler (/home/seraph/work/ChainSafe/lodestar/node_modules/abortable-iterator/index.js:16:29)
        at AbortSignal.dispatchEvent (/home/seraph/work/ChainSafe/lodestar/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
        at abortSignal (/home/seraph/work/ChainSafe/lodestar/node_modules/abort-controller/dist/abort-controller.js:52:12)
        at AbortController.abort (/home/seraph/work/ChainSafe/lodestar/node_modules/abort-controller/dist/abort-controller.js:91:9)
        at AbortSignal.onAbort (/home/seraph/work/ChainSafe/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/home/seraph/work/ChainSafe/lodestar/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
        at abortSignal (/home/seraph/work/ChainSafe/lodestar/node_modules/abort-controller/dist/abort-controller.js:52:12)
        at AbortController.abort (/home/seraph/work/ChainSafe/lodestar/node_modules/abort-controller/dist/abort-controller.js:91:9)
        at AbortSignal.onAbort (/home/seraph/work/ChainSafe/lodestar/node_modules/any-signal/index.js:13:16)) protocol: /eth2/beacon_chain/req/beacon_blocks_by_range/1/ssz_snappy
```

**Comment by 3xtr4t3rr3str14l** [comment]
probably too vague to do anything with, i think.  closing
