### ISSUE TITLE
CI test failure: "Node is stopped"

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#1529]
Just ran into an error when running a test in #1525 .  It was resolved by restarting the test, but maybe we should figure out why it was happening in the first place.

```
@chainsafe/lodestar: 2020-09-09 23:56:48  [VALIDATOR]        info: Signed new attestation for block 0x319cd01ef1755e42cd5a2c7f2dd726a3ffae91d4e0f725e27840d73b424fe5ba and committee 0 at slot 36 
@chainsafe/lodestar: 2020-09-09 23:56:48  [VALIDATOR]       error: Failed to publish attestation Error: Node is stopped
@chainsafe/lodestar: Error: Node is stopped
@chainsafe/lodestar:     at ValidatorApi.checkSyncStatus (/home/runner/work/lodestar/lodestar/packages/lodestar/src/api/impl/validator/validator.ts:266:15)
@chainsafe/lodestar:     at runMicrotasks (<anonymous>)
@chainsafe/lodestar:     at processTicksAndRejections (internal/process/task_queues.js:94:5)
@chainsafe/lodestar: (node:4912) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'message' of null
@chainsafe/lodestar:     at BeaconSync.start (/home/runner/work/lodestar/lodestar/packages/lodestar/src/sync/sync.ts:76:61)
@chainsafe/lodestar:     at runMicrotasks (<anonymous>)
@chainsafe/lodestar:     at processTicksAndRejections (internal/process/task_queues.js:94:5)
@chainsafe/lodestar:     at runNextTicks (internal/process/task_queues.js:63:3)
```

**Comment by mpetrunic** [comment]
Hmm hard to tell from this log snippet, probably something errored earlier and caused non finalization in required time

**Comment by 3xtr4t3rr3str14l** [comment]
yeah these logs are a little bit out of context and too long ago for me to remember much about it.  closing
