### ISSUE TITLE
Error updating eth1 chain cache

### ISSUE THREAD

**Issue by SeaMonkey82** [ChainSafe/lodestar#1580]
**Describe the bug**
```
2020-09-22 23:11:36  [ETH1]            error: Error updating eth1 chain cache Error: missing response (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":958516,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8545}, url="http://localhost:8545", code=SERVER_ERROR, version=web/5.0.1)
Error: missing response (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":958516,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8545}, url="http://localhost:8545", code=SERVER_ERROR, version=web/5.0.1)
    at Logger.makeError (/home/seamonkey/Downloads/lodestar/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/home/seamonkey/Downloads/lodestar/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at /home/seamonkey/Downloads/lodestar/node_modules/@ethersproject/web/lib/index.js:142:36
    at step (/home/seamonkey/Downloads/lodestar/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.throw (/home/seamonkey/Downloads/lodestar/node_modules/@ethersproject/web/lib/index.js:14:53)
    at rejected (/home/seamonkey/Downloads/lodestar/node_modules/@ethersproject/web/lib/index.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Expected behavior**
No error

**Steps to Reproduce**
Goerli Geth launched with...
```
geth --goerli --datadir="$HOME/Goerli" --http --http.addr=earth.thegalaxy --http.port=8545 --ws --ws.addr=earth.thegalaxy --ws.port=8546 --syncmode=full --nat=extip:1.2.3.4 --port=13431
```
earth.thegalaxy resolves to 192.168.0.2
```
➜  lodestar git:(master) nslookup earth.thegalaxy
Server:         192.168.0.1
Address:        192.168.0.1#53

Name:   earth.thegalaxy
Address: 192.168.0.2
```

Beacon launched with...
```
node --trace-deprecation --stack-size=6000 --max-old-space-size=9192 ./packages/lodestar-cli/bin/lodestar beacon --rootDir=/home/seamonkey/.eth2/lodestar --metrics.enabled=true --metrics.serverPort=8010 --testnet=medalla --network.discv5.bindAddr='/ip4/0.0.0.0/udp/13430' --network.localMultiaddrs='/ip4/0.0.0.0/tcp/13430' --api.enabled=true --enr-ip='1.2.3.4' --logFile=/home/seamonkey/.eth2/lodestar/lodestar.log --network.maxPeers=1000 --api.port=9596 --eth1.enabled=true --eth1.provider.url=http://192.168.0.2:8545
```

```
➜  lodestar git:(master) ss -tulnp | grep geth
udp   UNCONN 0      0                                      *:13431            *:*         users:(("geth",pid=11327,fd=62))
tcp   LISTEN 0      4096                         192.168.0.2:8545       0.0.0.0:*         users:(("geth",pid=11327,fd=39))
tcp   LISTEN 0      4096                         192.168.0.2:8546       0.0.0.0:*         users:(("geth",pid=11327,fd=68))
tcp   LISTEN 0      4096                                   *:13431            *:*         users:(("geth",pid=11327,fd=61))
```

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 20
 - Branch: Master
 - Commit hash: 7885cc5370d158577b72286f1ea81f22e213aadd

**Comment by dapplion** [comment]
@SeaMonkey82 The flag to for the eth1 provider URL is not right, can you try with this one?
```
--eth1.providerUrl=http://192.168.0.2:8545
```

**Comment by SeaMonkey82** [comment]
```
node --trace-deprecation --stack-size=6000 --max-old-space-size=9192 ./packages/lodestar-cli/bin/lodestar beacon --rootDir=/home/seamonkey/.eth2/lodestar --metrics.enabled=true --metrics.serverPort=8010 --testnet=medalla --network.discv5.bindAddr='/ip4/0.0.0.0/udp/13430' --network.localMultiaddrs='/ip4/0.0.0.0/tcp/13430' --api.enabled=true --enr-ip='1.2.3.4' --logFile=/home/seamonkey/.eth2/lodestar/lodestar.log --network.maxPeers=1000 --api.port=9596 --eth1.enabled=true --eth1.providerUrl=http://192.168.0.2:8545
```

results in

```
2020-09-23 02:00:19  [ETH1]            error: Error updating eth1 chain cache Error: Incorrect data length 72, expect 80
Error: Incorrect data length 72, expect 80
    at ContainerStructuralHandler.validateBytes (/home/seamonkey/Downloads/lodestar/node_modules/@chainsafe/ssz/lib/backings/structural/abstract.js:82:13)
    at ContainerStructuralHandler.fromBytes (/home/seamonkey/Downloads/lodestar/node_modules/@chainsafe/ssz/lib/backings/structural/container.js:101:10)
    at ContainerStructuralHandler.deserialize (/home/seamonkey/Downloads/lodestar/node_modules/@chainsafe/ssz/lib/backings/structural/abstract.js:95:17)
    at ContainerType.deserialize (/home/seamonkey/Downloads/lodestar/node_modules/@chainsafe/ssz/lib/types/composite/abstract.js:128:28)
    at Eth1DataRepository.decodeValue (/home/seamonkey/Downloads/lodestar/packages/lodestar/lib/db/api/beacon/repositories/abstract.js:59:22)
    at /home/seamonkey/Downloads/lodestar/packages/lodestar/lib/db/api/beacon/repositories/abstract.js:173:42
    at Array.map (<anonymous>)
    at Eth1DataRepository.values (/home/seamonkey/Downloads/lodestar/packages/lodestar/lib/db/api/beacon/repositories/abstract.js:173:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by dapplion** [comment]
Can you clear the DB if possible?
```
rm -rf /home/seamonkey/.eth2/lodestar/chain-db
```

**Comment by SeaMonkey82** [comment]
Cleared the db and ran with the same flags.  Result:

```
2020-09-23 02:07:59  [ETH1]            error: Error updating eth1 chain cache Error: No deposits found for block range [0, 999]
Error: No deposits found for block range [0, 999]
    at getEth1DataForBlocks (/home/seamonkey/Downloads/lodestar/packages/lodestar/lib/eth1/utils/eth1Data.js:44:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Eth1DepositsCache.getEth1DataForBlocks (/home/seamonkey/Downloads/lodestar/packages/lodestar/lib/eth1/eth1DepositsCache.js:81:12)
    at async Eth1ForBlockProduction.updateBlockCache (/home/seamonkey/Downloads/lodestar/packages/lodestar/lib/eth1/eth1ForBlockProduction.js:183:23)
    at async Eth1ForBlockProduction.update (/home/seamonkey/Downloads/lodestar/packages/lodestar/lib/eth1/eth1ForBlockProduction.js:136:29)
    at async Eth1ForBlockProduction.runAutoUpdate (/home/seamonkey/Downloads/lodestar/packages/lodestar/lib/eth1/eth1ForBlockProduction.js:116:28)
```
