### ISSUE TITLE
Eth1 errors during initial sync

### ISSUE THREAD

**Issue by ec2** [ChainSafe/lodestar#1599]
I'm trying to sync with Medalla and my node seems to be throwing some errors. It is worth noting that it still continues to sync fine despite these errors. 
**Describe the bug**

I start up a node by running `yarn run cli beacon --testnet medalla --weakSubjectivityStateFile state-11185.ssz`. Then  I get errors that look like this 
```
2020-09-28 20:10:46  [SYNC]             info: Received goodbye request from 16Uiu2HAmKz9RsaA48TkM6Y4FMUpGa733DBcQiJTU8zcsvfG1DB4z, reason=129 
2020-09-28 20:10:47  [SYNC]             info: Fetching blocks for 358641...358704 slot range 
2020-09-28 20:10:47  [SYNC]             info: Received goodbye request from 16Uiu2HAmKAGHQpBgav3pyyPkN4kS819cbhTyj95fTbqKibw1m2XX, reason=2 
2020-09-28 20:10:47  [CHORES]           info: Archive Blocks - duration=3039ms
2020-09-28 20:10:47  [CHORES]           info: Archiving of finalized blocks complete. totalArchived=22, finalizedEpoch=11205
2020-09-28 20:10:47  [CHORES]           info: Started archiving states (finalized epoch #11205)... 
2020-09-28 20:10:48  [ETH1]            error: Error updating eth1 chain cache Error: Error parsing JSON: Unexpected end of JSON input
[{"jsonrpc":"2.0","id":0,"result":{"difficulty":"0x1","extraData":"0x696e667572612d696f00000000000000000000000000000000000000000000005c5e7065135cbcd8410d00129ef26962ab7aeb66a465198a217397cf8109cde4421e8595f69fbc4a74056e02dd4568ae4d2d30438d5cebf45be2497d0e5dbc3301","gasLimit":"0x7a1200","gasUsed":"0x13c10b","hash":"0x13f10a6aa198da21b4a42ff5ad901692f507712c4f5d4fa6fe54aac642f58428","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Error: Error parsing JSON: Unexpected end of JSON input
[{"jsonrpc":"2.0","id":0,"result":{"difficulty":"0x1","extraData":"0x696e667572612d696f00000000000000000000000000000000000000000000005c5e7065135cbcd8410d00129ef26962ab7aeb66a465198a217397cf8109cde4421e8595f69fbc4a74056e02dd4568ae4d2d30438d5cebf45be2497d0e5dbc3301","gasLimit":"0x7a1200","gasUsed":"0x13c10b","hash":"0x13f10a6aa198da21b4a42ff5ad901692f507712c4f5d4fa6fe54aac642f58428","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
    at parseJson (/Users/erictu/git-repos/chainsafe/lodestar/packages/lodestar/lib/eth1/jsonRpcHttpClient.js:104:11)
    at fetchJson (/Users/erictu/git-repos/chainsafe/lodestar/packages/lodestar/lib/eth1/jsonRpcHttpClient.js:91:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async JsonRpcHttpClient.fetchBatch (/Users/erictu/git-repos/chainsafe/lodestar/packages/lodestar/lib/eth1/jsonRpcHttpClient.js:51:20)
    at async Eth1Provider.getBlocksByNumber (/Users/erictu/git-repos/chainsafe/lodestar/packages/lodestar/lib/eth1/eth1JsonRpcClient.js:33:23)
    at async Eth1ForBlockProduction.updateBlockCache (/Users/erictu/git-repos/chainsafe/lodestar/packages/lodestar/lib/eth1/eth1ForBlockProduction.js:184:24)
    at async Eth1ForBlockProduction.update (/Users/erictu/git-repos/chainsafe/lodestar/packages/lodestar/lib/eth1/eth1ForBlockProduction.js:137:29)
    at async Eth1ForBlockProduction.runAutoUpdate (/Users/erictu/git-repos/chainsafe/lodestar/packages/lodestar/lib/eth1/eth1ForBlockProduction.js:117:28)
2020-09-28 20:10:48  [CHORES]           info: Archiving of finalized states completed (finalized epoch #11205) 
2020-09-28 20:10:48  [CHORES]           info: Archive States - duration=1187ms
```

Also potentially related are these types of errors:
```
359155,359164,359168,359169,359170,359171,359172,359173,359175,359176,359178,359179,359182,359183,359184,359186,359187 
2020-09-28 20:16:13  [SYNC]             info: Sync progress currentEpoch=11223, targetEpoch=12475, speed=2.1 slots/s, estimatedTillComplete=5.3 hours
2020-09-28 20:16:14  [SYNC]             info: Peer status activePeers=23, syncPeers=22
2020-09-28 20:16:15  [ETH1]            error: Error updating eth1 chain cache Error: request to https://goerli.prylabs.net/ failed, reason: read ECONNRESET
FetchError: request to https://goerli.prylabs.net/ failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/erictu/git-repos/chainsafe/lodestar/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:210:5)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket.EventEmitter.emit (domain.js:476:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2020-09-28 20:16:15  [CHAIN]            info: Epoch 11222 is justified at root     0xf75a1b3a0df5b9057efdbba97482392ceb18b4f70505040a79ccc6cc3027a9ce! 
2020-09-28 20:16:15  [CHAIN]            info: Epoch 11221 is finalized at root     0x05f6699c423833e5f41c5d37ea6d6bc0c2c253d88844fa54e9aff0c9ccdefb7a! 
2020-09-28 20:16:18  [SYNC]             info: Received goodbye request from 16Uiu2HAm6eyBvfAueyvmg9UFomAk6eMkDAkmvPcavEN62BJ3RonW, reason=251 
```
**Expected behavior**

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX Catalina
 - Version: 
 - Branch: Master 
 - Commit hash: 422140d6e4f96a765001ae5eeae91ee246dc3440

**Comment by dapplion** [comment]
I'm getting the same error building genesis for Spadina
```
 ✖ Error: Error parsing JSON: Unexpected end of JSON input
{"jsonrpc":"2.0","id":1,"result":[{"address":"0x48b597f4b53c21b48ad95c7256b49d1779bd5890","topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"],"data":"0x00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001800000000000000000000000000000000000000000000000000000000000000200
    at parseJson (/home/lion/Code/eth2.0/lodestar/packages/lodestar/lib/eth1/jsonRpcHttpClient.js:104:11)
    at fetchJson (/home/lion/Code/eth2.0/lodestar/packages/lodestar/lib/eth1/jsonRpcHttpClient.js:91:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async JsonRpcHttpClient.fetch (/home/lion/Code/eth2.0/lodestar/packages/lodestar/lib/eth1/jsonRpcHttpClient.js:37:17)
    at async Eth1Provider.getLogs (/home/lion/Code/eth2.0/lodestar/packages/lodestar/lib/eth1/eth1JsonRpcClient.js:74:21)
    at async Eth1Provider.getDepositEvents (/home/lion/Code/eth2.0/lodestar/packages/lodestar/lib/eth1/eth1Provider.js:40:18)
    at async Promise.all (index 0)
```

**Comment by dapplion** [comment]
Should be handled by current code, retrying a smaller request if it gets truncated
