### ISSUE TITLE
Empty ENR breaks lodestar

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1641]
When running and stopping lodestar quickly the ENR file is empty and while loading this happens
```
  ✖ SyntaxError: Unexpected end of JSON input
lodestar_1    |     at JSON.parse (<anonymous>)
lodestar_1    |     at parse (/usr/app/packages/lodestar-cli/src/util/file.ts:35:19)
lodestar_1    |     at readFile (/usr/app/packages/lodestar-cli/src/util/file.ts:76:10)
lodestar_1    |     at readEnr (/usr/app/packages/lodestar-cli/src/network/enr.ts:17:24)
lodestar_1    |     at Object.beaconHandler [as handler] (/usr/app/packages/lodestar-cli/src/cmds/beacon/handler.ts:32:15)
```

The ENR loader should validate it better and create a new one if corrupt or empty instead of stalling the entire process

**Comment by 3xtr4t3rr3str14l** [comment]
resolved via FileENR implementation
