### ISSUE TITLE
No state in cache for finalized checkpoint state

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1653]
**Describe the bug**
This happens in Medalla Initial Sync:
```
(node:11438) UnhandledPromiseRejectionWarning: Error: No state in cache for finalized checkpoint state
    at ArchiveStatesTask.run (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/tasks/tasks/archiveStates.ts:41:13)
    at ChainEventEmitter.<anonymous> (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/tasks/index.ts:83:5)
(node:11438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 467)
(node:11438) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11438) UnhandledPromiseRejectionWarning: Error: No state in cache for finalized checkpoint state
    at ArchiveStatesTask.run (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/tasks/tasks/archiveStates.ts:41:13)
    at ChainEventEmitter.<anonymous> (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/tasks/index.ts:83:5)
(node:11438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 487)
(node:11438) UnhandledPromiseRejectionWarning: Error: No state in cache for finalized checkpoint state
    at ArchiveStatesTask.run (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/tasks/tasks/archiveStates.ts:41:13)
    at ChainEventEmitter.<anonymous> (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/tasks/index.ts:83:5)
(node:11438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 509)
(node:11438) UnhandledPromiseRejectionWarning: Error: No state in cache for finalized checkpoint state
    at ArchiveStatesTask.run (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/tasks/tasks/archiveStates.ts:41:13)
    at ChainEventEmitter.<anonymous> (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/tasks/index.ts:83:5)
(node:11438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 510)
```

**Expected behavior**
ArchiveState task runs without error

**Comment by twoeths** [comment]
as a result of this, when I restart the node I have to start from an old checkpoint

**Comment by twoeths** [comment]
should be resolved by https://github.com/ChainSafe/lodestar/pull/1656

**Comment by 3xtr4t3rr3str14l** [comment]
I just saw this again when running the beacon node on master.
