### ISSUE TITLE
Error: DuplicateDistinctLog

### ISSUE THREAD

**Issue by SeaMonkey82** [ChainSafe/lodestar#1705]
**Describe the bug**
I'm getting a flood of this now.
```
Error: DuplicateDistinctLog
    at Eth1DepositsCache.add (/home/seamonkey/Downloads/lodestar/packages/lodestar/src/eth1/eth1DepositsCache.ts:42:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Eth1ForBlockProduction.updateDepositCache (/home/seamonkey/Downloads/lodestar/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:147:5)
    at Eth1ForBlockProduction.update (/home/seamonkey/Downloads/lodestar/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:130:31)
    at Eth1ForBlockProduction.runAutoUpdate (/home/seamonkey/Downloads/lodestar/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:112:28)
```

**Expected behavior**
No error

**Steps to Reproduce**
```
node --trace-deprecation --stack-size=6000 --max-old-space-size=9192 ./packages/lodestar-cli/bin/lodestar beacon --rootDir=/home/seamonkey/.eth2/lodestar --metrics.enabled=true --metrics.serverPort=8010 --testnet=medalla --network.discv5.bindAddr='/ip4/0.0.0.0/udp/13430' --network.localMultiaddrs='/ip4/0.0.0.0/tcp/13430' --api.enabled=true --enr-ip='1.2.3.4' --logFile=/home/seamonkey/.eth2/lodestar/lodestar.log --network.maxPeers=1000 --api.port=9596 --eth1.enabled=true --eth1.providerUrl=http://192.168.0.2:8545 --eth1.depositContractDeployBlock 3085928
```
**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 20
 - Branch: Master
 - Commit hash: 16d3a422d8e50c63891fcb0ea0e903815913f106

**Comment by SeaMonkey82** [comment]
Restarted and haven't noticed this error since.

**Comment by dapplion** [comment]
Thanks for updating, closing for now re-open if it happens again

**Comment by SeaMonkey82** [comment]
I had this happen again and realized this happens when geth and lodestar are started at the same time.  Even after geth is caught up, the error persists until lodestar is restarted.
