### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#1711]
I saw this last night while I was running the beacon node, and while I was away, the beacon node stopped syncing when I ran out of disk space, and then when I hit Ctrl+C, it spit this out:

```
(node:28161) UnhandledPromiseRejectionWarning: Error: ENOSPC: no space left on device, write
    at Object.writeSync (fs.js:589:3)
    at writeFileSync (fs.js:1258:26)
    at Map.saveToFile (/home/seraph/work/ChainSafe/lodestar/packages/lodestar-cli/src/network/fileEnr.ts:41:5)
    at Map.set (/home/seraph/work/ChainSafe/lodestar/packages/lodestar-cli/src/network/fileEnr.ts:46:10)
    at MetadataController.set attnets [as attnets] (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/src/network/metadata/metadata.ts:55:16)
    at InteropSubnetsJoiningTask.cleanUpCurrentSubscriptions (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/src/tasks/tasks/interopSubnetsJoiningTask.ts:118:5)
    at InteropSubnetsJoiningTask.stop (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/src/tasks/tasks/interopSubnetsJoiningTask.ts:51:17)
    at TasksService.stop (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/src/tasks/index.ts:66:35)
    at BeaconNode.stop (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/src/node/nodejs.ts:161:23)
    at /home/seraph/work/ChainSafe/lodestar/packages/lodestar-cli/src/cmds/beacon/handler.ts:53:29
(node:28161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1319)
 ```

It's an edge case and is something that is maybe hard to test for, but it would probably be good to handle the error and let the user know more kindly, imo.

**Comment by 3xtr4t3rr3str14l** [comment]
on second thought, it's probably not bad to have the stack trace.  closing this
