### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by SeaMonkey82** [ChainSafe/lodestar#1732]
**Describe the bug**
```
 ✖ TypeError: Cannot read property 'toString' of undefined
    at Map.get id [as id] (/home/seamonkey/Downloads/lodestar/node_modules/@chainsafe/discv5/lib/enr/enr.js:84:30)
    at Map.get nodeId [as nodeId] (/home/seamonkey/Downloads/lodestar/node_modules/@chainsafe/discv5/lib/enr/enr.js:109:22)
    at Function.create (/home/seamonkey/Downloads/lodestar/node_modules/@chainsafe/discv5/lib/service/service.js:138:55)
    at new Discv5Discovery (/home/seamonkey/Downloads/lodestar/node_modules/@chainsafe/discv5/lib/libp2p/discv5.js:25:40)
    at setupService (/home/seamonkey/Downloads/lodestar/node_modules/libp2p/src/index.js:569:30)
    at NodejsNode._setupPeerDiscovery (/home/seamonkey/Downloads/lodestar/node_modules/libp2p/src/index.js:584:7)
    at NodejsNode._onDidStart (/home/seamonkey/Downloads/lodestar/node_modules/libp2p/src/index.js:503:16)
    at NodejsNode.start (/home/seamonkey/Downloads/lodestar/node_modules/libp2p/src/index.js:230:18)
    at Libp2pNetwork.start (/home/seamonkey/Downloads/lodestar/packages/lodestar/src/network/network.ts:85:5)
    at Function.init (/home/seamonkey/Downloads/lodestar/packages/lodestar/src/node/nodejs.ts:197:5)
```

**Expected behavior**
No error

**Steps to Reproduce**
`node --trace-deprecation --stack-size=6000 --max-old-space-size=9192 ./packages/lodestar-cli/bin/lodestar beacon --rootDir=/home/seamonkey/.eth2/lodestar --metrics.enabled=true --metrics.serverPort=8010 --testnet=medalla --network.discv5.bindAddr='/ip4/0.0.0.0/udp/13430' --network.localMultiaddrs='/ip4/0.0.0.0/tcp/13430' --api.rest.enabled=true --enr.ip='1.2.3.4' --logFile=/home/seamonkey/.eth2/lodestar/lodestar.log --network.maxPeers=1000 --api.rest.port=9596 --eth1.enabled=true --eth1.providerUrl=http://192.168.0.2:8545 --eth1.depositContractDeployBlock 3085928`

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version: 20
 - Branch: Master
 - Commit hash: 2f184cf135b06cbf89b46f1bd276f4badb6457e1

**Comment by 3xtr4t3rr3str14l** [comment]
@SeaMonkey82 , i'm closing this issue since we are already tracking it in #1725 (with an upcoming fix in #1729 )
