### ISSUE TITLE
Failed unit test in CI

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1779]
**Describe the bug**
Sometimes this happens in CI:
```
@chainsafe/lodestar:   1 failing
@chainsafe/lodestar:   1) beacon state api utils
@chainsafe/lodestar:        getEpochBeaconCommittees
@chainsafe/lodestar:          old/new epoch with epoch context:
@chainsafe/lodestar:      AssertionError: expected undefined not to be undefined
@chainsafe/lodestar:       at Context.<anonymous> (test/unit/api/impl/beacon/state/utils.test.ts:148:44)
@chainsafe/lodestar:       at processImmediate (internal/timers.js:439:21)
@chainsafe/lodestar:       at process.topLevelDomainCallback (domain.js:130:23)
```
**Expected behavior**
Unit tests always pass.

**Comment by 3xtr4t3rr3str14l** [comment]
I think I saw this error locally yesterday too.  Forgot to make an issue for it.  Thanks for doing that!

**Comment by dapplion** [comment]
We should improve assertions to not get `AssertionError: expected undefined not to be undefined`

**Comment by dapplion** [comment]
Open a new issue if it happens again, too old
