### ISSUE TITLE
lodestar-spec-test-util happily skips missing tests

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1810]
Here as an example, spec tests pass with

```
Run yarn test:spec
yarn run v1.22.5
$ mocha --colors -r ts-node/register 'test/spec/**/*.test.ts'


  0 passing (2ms)

Done in 2.91s.
```

https://github.com/ChainSafe/bls/pull/56/checks?check_run_id=1478816690#step:9:11

If I debug that run, actually an error gets thrown in the spec tests util
```
Error: ENOENT: no such file or directory, lstat '/home/lion/Code/eth2.0/bls/node_modules/@chainsafe/eth2-spec-tests/tests/tests/general/phase0/bls/verify/small'
    at Object.lstatSync (fs.js:1007:3)
    at isDirectory (/home/lion/Code/eth2.0/bls/node_modules/@chainsafe/lodestar-spec-test-util/src/util.ts:5:13)
    at Object.describeDirectorySpecTest (/home/lion/Code/eth2.0/bls/node_modules/@chainsafe/lodestar-spec-test-util/src/single.ts:69:4)
    at /home/lion/Code/eth2.0/bls/test/spec/verify.test.ts:19:3
    at Suite.<anonymous> (/home/lion/Code/eth2.0/bls/test/switch.ts:34:7)
    at Object.create (/home/lion/Code/eth2.0/bls/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/home/lion/Code/eth2.0/bls/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at /home/lion/Code/eth2.0/bls/test/switch.ts:29:5
    at runForAllImplementations (/home/lion/Code/eth2.0/bls/test/switch.ts:23:5) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/home/lion/Code/eth2.0/bls/node_modules/@chainsafe/eth2-spec-tests/tests/tests/general/phase0/bls/verify/small'
}
```
The directory is not there because I haven't downloaded the tests yet. But this CI should be a failure not a success.

However, that error is swallowed by Mocha and nothing happens.  Anyone has a clue what's going on?

**Comment by dapplion** [comment]
Should be fixed already
