### ISSUE TITLE
ReferenceError: artifacts is not defined

### ISSUE THREAD

**Issue by hugo-dc** [ChainSafe/lodestar#19]
I've just cloned the repository, installed the dependencies and I'm getting this error when I run `npm test`:

```
[lodestar_chain](master)$ npm test

> lodestar-chain@0.1.0 test /home/hugo/workspace/Sharding/lodestar_chain
> mocha --recursive

/home/hugo/workspace/Sharding/lodestar_chain/test/test_validator_registration.js:1
(function (exports, require, module, __filename, __dirname) { var ValidatorRegistration = artifacts.require('ValidatorRegistration');
                                                                                                    ^

ReferenceError: artifacts is not defined
    at Object.<anonymous> (/home/hugo/workspace/Sharding/lodestar_chain/test/test_validator_registration.js:1:101)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /home/hugo/workspace/Sharding/lodestar_chain/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/hugo/workspace/Sharding/lodestar_chain/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/hugo/workspace/Sharding/lodestar_chain/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/home/hugo/workspace/Sharding/lodestar_chain/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
npm ERR! Test failed.  See above for more details. 
```

I couldn't find information about this error which is related to mocha, all the information I found is related to truffle.

**Comment by GregTheGreek** [comment]
@hugo-dc It looks like we're importing the `ValidatorRegistration.sol` contract incorrectly, thanks for finding this! I'll go and patch this right now!

**Comment by GregTheGreek** [comment]
@hugo-dc further investigation, `truffle test` is the actual test command. I'm actually fixing that right now. If you run `truffle test` you'll see a completely different output where the tests run (some are failing im trying to look into that now)
