### ISSUE TITLE
Manage cloud infrastructure

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#1923]
1. We need to increase memory for one of the servers as 2GB RAM is not enough to run Pyrmont
2. Need to increase disk space for server 01 to run mainnet as we got this error
```
2020-12-31 22:41:16 [SYNC]             info: Peer status activePeers=25, syncPeers=23, unknownRootPeers=23
2020-12-31 22:41:16 [CHORES]           info: Archive states completed finalizedEpoch=6415
2020-12-31 22:41:16 [CHORES]           info: Archive States epoch #6415  - duration=4602ms
2020-12-31 22:41:16 [CHAIN]           error: Error handling event event=block message=IO error: .mainnet/chain-db/084314.ldb: No space left on device
WriteError: IO error: .mainnet/chain-db/084314.ldb: No space left on device
    at /home/ubuntu/lodestar/node_modules/levelup/lib/batch.js:69:34
2020-12-31 22:41:16 [CHAIN]           error: Error handling event event=block message=IO error: .mainnet/chain-db/084314.ldb: No space left on device
WriteError: IO error: .mainnet/chain-db/084314.ldb: No space left on device
    at /home/ubuntu/lodestar/node_modules/levelup/lib/levelup.js:217:23
```

**Comment by wemeetagain** [comment]
server 01 and 02 upgraded to 4GB RAM + 80GB SSD (vs 2GB RAM + 60GB SSD)

**Comment by dapplion** [comment]
Contabo :tada:
