### ISSUE TITLE
Blocking error: headState does not exist

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#1960]
When restarting the beacon chain after stopping fast it throws on start-up with
```
2021-01-17 17:19:21 [DB]               info: Connected to LevelDB database name=/home/lion/.local/share/lodestar/mainnet/chain-db
2021-01-17 17:19:24 []                 info: Initializing beacon state from db slot=63008, epoch=1969, stateRoot=0x1129b844626e335464f4a56e9b3e23dbf016506cdbf1e161aff592d6e8957da1
2021-01-17 17:19:24 [DB]               info: Connected to LevelDB database name=/home/lion/.local/share/lodestar/mainnet/chain-db
2021-01-17 17:19:27 [API]              warn: Server listening at http://127.0.0.1:9596
2021-01-17 17:19:27 [API]              info: Started rest api server address=http://127.0.0.1:9596
2021-01-17 17:19:27 [METRICS]          info: Starting metrics HTTP server port=8008
 ✖ Error: headState does not exist
    at BeaconChain.getHeadStateContext (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/chain/chain.ts:143:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at BeaconChain.getHeadState (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/chain/chain.ts:148:13)
    at BeaconChain.getENRForkID (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/chain/chain.ts:250:19)
    at MetadataController.start (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/network/metadata/metadata.ts:41:78)
    at Libp2pNetwork.start (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/network/network.ts:89:5)
    at Function.init (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/node/nodejs.ts:200:5)
    at Object.beaconHandler [as handler] (/home/lion/Code/eth2.0/lodestar/packages/lodestar-cli/src/cmds/beacon/handler.ts:63:16)
```
The process stops there and is not recoverable. I have to whipe out the entire DB to continue. This seems a regression introduced with https://github.com/ChainSafe/lodestar/pull/1937

**Comment by twoeths** [comment]
Fixed by https://github.com/ChainSafe/lodestar/pull/1962
