### ISSUE TITLE
Error pruning forkchoice

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2010]
I got this error during Pyrmont sync

```
2021-01-29 17:57:24 [SYNC]             info: Sync progress 5485/16188 - 23 hours left - 4.12 slots/s
2021-01-29 17:57:24 [CHORES]          error: Error processing finalized checkpoint epoch=5484 code=PROTO_ARRAY_ERROR_FINALIZED_NODE_UNKNOWN, root=0xe1151e07babfe3b9612746e8ad5a40de8d0ada5523abe7b035916a6db336f9b0
Error: PROTO_ARRAY_ERROR_FINALIZED_NODE_UNKNOWN
    at ProtoArray.maybePrune (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar-fork-choice/src/protoArray/protoArray.ts:241:13)
    at LodestarForkChoice.prune (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar-fork-choice/src/forkChoice/forkChoice.ts:488:28)
    at ChainEventEmitter.<anonymous> (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/tasks/index.ts:108:29)
2021-01-29 17:57:24 [CHORES]          error: Error processing finalized checkpoint epoch=5483 code=PROTO_ARRAY_ERROR_FINALIZED_NODE_UNKNOWN, root=0x6998e5cf31a604a33c70164cdd48eb88d306758510ee9aaa4f10b00c8b8cca3a
Error: PROTO_ARRAY_ERROR_FINALIZED_NODE_UNKNOWN
    at ProtoArray.maybePrune (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar-fork-choice/src/protoArray/protoArray.ts:241:13)
    at LodestarForkChoice.prune (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar-fork-choice/src/forkChoice/forkChoice.ts:488:28)
    at ChainEventEmitter.<anonymous> (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/tasks/index.ts:108:29)
2021-01-29 17:57:42 [CHAIN]            info: Checkpoint justified epoch=5487, root=0xc2cf47ab6d038944a3759a3c778d1f8956d77a34246c8aaab2ceffec9eaaee63
```

**Comment by twoeths** [comment]
duplicated to #2015
