### ISSUE TITLE
Error processing finalized checkpoint

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2015]
I got this when syncing pyrmont locally:

```
2021-01-31 20:36:17 [SYNC]             info: Sync progress 1957/16662 - 1.1 days left - 5.08 slots/s
2021-01-31 20:36:18 [CHORES]          error: Error processing finalized checkpoint epoch=1953 code=PROTO_ARRAY_ERROR_FINALIZED_NODE_UNKNOWN, root=0x631413d98355f04a73d701e8c19c3428fc1ef6702f032dc125883fea65f1e814
Error: PROTO_ARRAY_ERROR_FINALIZED_NODE_UNKNOWN
    at ProtoArray.maybePrune (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar-fork-choice/src/protoArray/protoArray.ts:241:13)
    at LodestarForkChoice.prune (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar-fork-choice/src/forkChoice/forkChoice.ts:488:28)
    at ChainEventEmitter.<anonymous> (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/tasks/index.ts:108:29)
2021-01-31 20:36:32 [CHAIN]            info: Checkpoint justified epoch=1959, root=0x85a38819f760677973679cb24892959e521b46949a6acd54957cc5ce14636d1b
```

**Comment by dapplion** [comment]
I've seen it too!

**Comment by 3xtr4t3rr3str14l** [comment]
> I've seen it too!

ditto

**Comment by twoeths** [comment]
this is because we don't manage the order of archived tasks
+ archived task `n` runs and hasn't finished - maybe because it has to archive state
+ archived task `n+1` runs and finish - maybe because it doesn't have to archive state, it deletes all nodes all the way to its finalized node including the finalized node of task `n`
+ archived task reaches its last step which is `this.chain.forkChoice.prune(finalized.root);` and found that it's finalized root was deleted (by archived task `n+1`)

for this specific error, it causes no harm but we may have bigger issue after a big unfinalized period. To completely resolve this, I think we need to use `JobQueue` to order the execution of archived tasks.
