### ISSUE TITLE
validator client request timeouts

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#2017]
while running the validator client on pyrmont, things have been smooth, for the most part, but every now and then i'll see a timeout from one of the requests.  for example: 

```
2021-01-29 18:03:25 []              verbose: HttpClient POST error url=/beacon_committee_subscriptions message=timeout of 4000ms exceeded
    Error: timeout of 4000ms exceeded
        at createError (/home/seraph/work/ChainSafe/lodestar/node_modules/axios/lib/core/createError.js:16:15)
        at RedirectableRequest.handleRequestTimeout (/home/seraph/work/ChainSafe/lodestar/node_modules/axios/lib/adapters/http.js:280:16)
        at Object.onceWrapper (events.js:297:20)
        at RedirectableRequest.emit (events.js:209:13)
        at RedirectableRequest.EventEmitter.emit (domain.js:476:20)
        at Timeout._onTimeout (/home/seraph/work/ChainSafe/lodestar/node_modules/follow-redirects/index.js:166:13)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7)
```

I also see this same error in other areas of the code too, which will sometimes cause us to miss attestations:
```
2021-01-29 18:28:43 []              verbose: HttpClient GET error url=/aggregate_attestation?attestation_data_root=0xf85f73e0430207c7cd8009f6fd87b0d416df0ff98ec709b42b6368dc15354281&slot=522142 message=timeout of 4000ms exceeded
    Error: timeout of 4000ms exceeded
        at createError (/home/seraph/work/ChainSafe/lodestar/node_modules/axios/lib/core/createError.js:16:15)
        at RedirectableRequest.handleRequestTimeout (/home/seraph/work/ChainSafe/lodestar/node_modules/axios/lib/adapters/http.js:280:16)
        at Object.onceWrapper (events.js:297:20)
        at RedirectableRequest.emit (events.js:209:13)
        at RedirectableRequest.EventEmitter.emit (domain.js:476:20)
        at Timeout._onTimeout (/home/seraph/work/ChainSafe/lodestar/node_modules/follow-redirects/index.js:166:13)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7)
```

Either our timeout is too soon, or maybe something else is going on.

**Comment by dapplion** [comment]
4000ms is the max it can wait for the protocol, otherwise it misses the opportunity to aggregate. However, the node is known to be busy for over 3 seconds https://github.com/ChainSafe/lodestar/issues/1990

**Comment by 3xtr4t3rr3str14l** [comment]
closing in favor of #1990
