### ISSUE TITLE
Remove --ignore-optional flag in Dockerfile

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2113]
We don't have to use this flag anymore since the spec tests are not an NPM package. However, I tried to delete the flag and the node did not start crashing with:

```
lodestar_1    |  ✖ SyntaxError: Cannot convert undefined to a BigInt
lodestar_1    |     at BigInt (<anonymous>)
lodestar_1    |     at NumberUintType.fromJson (/usr/app/node_modules/@chainsafe/ssz/src/types/basic/uint.ts:87:18)
lodestar_1    |     at forEach (/usr/app/packages/lodestar-params/src/utils.ts:11:66)
lodestar_1    |     at Array.forEach (<anonymous>)
lodestar_1    |     at createIBeaconParams (/usr/app/packages/lodestar-params/src/utils.ts:9:39)
lodestar_1    |     at getBeaconParams (/usr/app/packages/lodestar-cli/src/config/beaconParams.ts:70:37)
lodestar_1    |     at getBeaconParamsFromArgs (/usr/app/packages/lodestar-cli/src/config/beaconParams.ts:37:10)
lodestar_1    |     at getBeaconConfigFromArgs (/usr/app/packages/lodestar-cli/src/config/beaconParams.ts:29:30)
lodestar_1    |     at initializeOptionsAndConfig (/usr/app/packages/lodestar-cli/src/cmds/init/handler.ts:52:18)
lodestar_1    |     at Object.beaconHandler [as handler] (/usr/app/packages/lodestar-cli/src/cmds/beacon/handler.ts:25:45)
```

What may be happening here?

**To recreate**

Remove flag from these two lines
https://github.com/ChainSafe/lodestar/blob/8c860b334a73ece8b310f86c58487104dd8976b3/Dockerfile#L7
https://github.com/ChainSafe/lodestar/blob/8c860b334a73ece8b310f86c58487104dd8976b3/Dockerfile#L10

```
docker-compose up --build
```

**Comment by dapplion** [comment]
I confirm this issue after:
1. cloning lodestar in fresh machine
2. docker-compose build -> :white_check_mark: 
3. Do only the change of removing `--ignore-optional` from Dockerfile
4. docker-compose build -> :heavy_multiplication_x:

**Comment by dapplion** [comment]
@wemeetagain Can you take a look? I can't find anything suspicious

**Comment by dapplion** [comment]
Root issue -> https://github.com/ChainSafe/lodestar/issues/2120
