### ISSUE TITLE
Cannot collect attestations before regular sync

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2166]
**Describe the bug**

When running node + validator right before genesis

```
2021-03-12 15:49:14 [VALI 8-15]       [31merror[39m: Failed to subscribe to committee subnet message=Cannot collect attestations before regular sync
Error: Cannot collect attestations before regular sync
    at BeaconSync.collectAttestations (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/sync/sync.ts:136:13)
    at ValidatorApi.prepareBeaconCommitteeSubnet (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/api/impl/validator/validator.ts:187:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at AttestationService.updateDuties (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar-validator/src/services/attestation.ts:145:9)
    at AttestationService.start (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar-validator/src/services/attestation.ts:55:5)
    at async Promise.all (index 1)
    at ApiClientOverInstance.<anonymous> (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar-validator/src/validator.ts:66:5)
```

**Expected behavior**

Node + validator should coordinate okay without errors

**Steps to Reproduce**

Run sim tests, or inspect the debug logs here https://github.com/ChainSafe/lodestar/issues/2081#issuecomment-797428629

**Comment by twoeths** [comment]
this is the 1st time nodes reaches Synced status:
```
2021-03-12 10:29:32 [NODE 2]           ^[[32minfo^[[39m: Synced - finalized: 0 0x0000…0000 - head: 3 0x003a…7702      - peers: 3
```

all of the errors happens before that time so it's expected.

**Comment by dapplion** [comment]
We can make some changes to prevent those errors:
- Beacon accepts subscriptions close but before genesis
- Beacon considers itself synced close but before genesis
- Validator waits for genesis + 1 second to request subscription

**Comment by 3xtr4t3rr3str14l** [comment]
has anyone seen this error recently?

**Comment by dapplion** [comment]
No, I think we can close it. Now the validator spams "Node is syncing" errors instead
