### ISSUE TITLE
Fix getDefaultGraffiti

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2220]
**Describe the bug**

This function 
https://github.com/ChainSafe/lodestar/blob/0bddc7ac75a0fab0356d29ebce6ea14f94a96458/packages/lodestar-cli/src/util/graffiti.ts#L20
when ran throws 

```
Error guessing lodestar version Error: No version in /root/lodestar/package.json     
  at guessVersion (/root/lodestar/packages/lodestar-cli/src/util/graffiti.ts:13:23)                                                                               
  at getDefaultGraffiti (/root/lodestar/packages/lodestar-cli/src/util/graffiti.ts:22:38)                                                                         
  at Object.validatorHandler [as handler] (/root/lodestar/packages/lodestar-cli/src/cmds/validator/handler.ts:22:37)                                                
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

- [ ] The root package.json does not contain a version. It can be found either at lerna.json or packages/lodestar/package.json
- [ ] Should not log to console.error errors
- [ ] Consider not using `read-pkg-up`, but `find-up`.

**Comment by dapplion** [comment]
Fixed
