### ISSUE TITLE
Prater logs - ATTESTATION_ERROR_PAST_EPOCH

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2242]
**Describe the bug**

On Prater genesis with our extremely overloaded beacon seems to process block 2 (late) from somewhere (db, gossip?) and when processing it's attestations throws `ATTESTATION_ERROR_PAST_EPOCH` 178 times (all of them + some other block? note MAX_ATTESTATIONS=128). Is this error expected?

```
2021-03-23 15:18:42 [CHAIN]         verbose: Clock slot slot=93
2021-03-23 15:18:42 [CHAIN]           debug: Block pools:  pendingBlocks=0, currentSlot=93
2021-03-23 15:18:42 [CHAIN]         verbose: Block processed slot=2, root=0x629bd2acd1af7e70c0bc8a53bf28a6c3ca869106c23a4217c5bb03cdd8292690
2021-03-23 15:18:42 [CHAIN]         verbose: New chain head headSlot=2, headRoot=0x629bd2acd1af7e70c0bc8a53bf28a6c3ca869106c23a4217c5bb03cdd8292690
...
2021-03-23 15:18:42 [CHAIN]           debug: Attestation error code=ATTESTATION_ERROR_PAST_EPOCH, attestationEpoch=0, currentEpoch=2
Error: ATTESTATION_ERROR_PAST_EPOCH
    at validateAttestation (/root/lodestar/packages/lodestar/src/chain/attestation/validate.ts:39:11)
    at processAttestationJob (/root/lodestar/packages/lodestar/src/chain/attestation/processor.ts:44:5)
    at AttestationProcessor.processAttestationJob (/root/lodestar/packages/lodestar/src/chain/attestation/processor.ts:28:11)
    at fn (/root/lodestar/packages/lodestar/src/chain/eventHandlers.ts:238:42)
    at CompositeListTreeHandler.readOnlyMap (/root/lodestar/node_modules/@chainsafe/ssz/src/backings/tree/array.ts:347:19)
    at readOnlyMap (/root/lodestar/node_modules/@chainsafe/ssz/src/backings/readOnlyIterate.ts:25:43)
    at BeaconChain.onBlock (/root/lodestar/packages/lodestar/src/chain/eventHandlers.ts:237:10)
    at ChainEventEmitter.<anonymous> (/root/lodestar/packages/lodestar/src/chain/eventHandlers.ts:37:7)
```

**Comment by dapplion** [comment]
Following the logs these errors keep happening. Should the node be able to drop all buffered attestations so it can processed the new ones? It seems to be stuck in a death spiral spending time validating old attestations that will error, and never getting to the newer attestations.

```
2021-03-23 15:22:47 [CHAIN]           debug: Attestation error code=ATTESTATION_ERROR_PAST_EPOCH, attestationEpoch=0, currentEpoch=3
2021-03-23 15:22:47 [CHAIN]           debug: Attestation error code=ATTESTATION_ERROR_PAST_EPOCH, attestationEpoch=0, currentEpoch=3
2021-03-23 15:22:47 [CHAIN]           debug: Attestation error code=ATTESTATION_ERROR_PAST_EPOCH, attestationEpoch=0, currentEpoch=3
2021-03-23 15:22:47 [CHAIN]           debug: Attestation error code=ATTESTATION_ERROR_PAST_EPOCH, attestationEpoch=0, currentEpoch=3
2021-03-23 15:22:47 [CHAIN]           debug: Attestation error code=ATTESTATION_ERROR_PAST_EPOCH, attestationEpoch=0, currentEpoch=3
```

**Comment by dapplion** [comment]
Attestation queues have been changed to LIFO and https://github.com/ChainSafe/lodestar/pull/2876 will drop them if too overloaded
