### ISSUE TITLE
Prater logs - Error: Peer ID doesn't match libp2p public key

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2243]
**Describe the bug**

During Prater genesis I see this log a bunch of times. Does this mean that the public key of another peer has changed between the last connection and now? 

```
2021-03-23 15:22:45 [NETWORK]         debug: Error dialing discovered peer peer=16Uiu2HAmR5sBraVshGyBayrYn6gMmT2B2aqYMcbm3mjB7LKGXR1B message=
    Error: connection error 172.17.0.1:9124: connect ECONNREFUSED 172.17.0.1:9124
    Error: connection error 127.0.0.1:9124: connect ECONNREFUSED 127.0.0.1:9124
    Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.
        at Noise.performXXHandshake (/root/lodestar/node_modules/libp2p-noise/src/noise.ts:211:13)
    Error: The operation was aborted
        at AbortSignal.onAbort (/root/lodestar/node_modules/libp2p-tcp/src/index.js:86:14)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
        at abortSignal (/root/lodestar/node_modules/abort-controller/src/abort-signal.ts:68:12)
        at AbortController.abort (/root/lodestar/node_modules/abort-controller/src/abort-controller.ts:26:9)
        at AbortSignal.onAbort (/root/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
        at abortSignal (/root/lodestar/node_modules/abort-controller/src/abort-signal.ts:68:12)
        at AbortController.abort (/root/lodestar/node_modules/abort-controller/src/abort-controller.ts:26:9)
        at AbortSignal.onAbort (/root/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
    Error: The operation was aborted
        at AbortSignal.onAbort (/root/lodestar/node_modules/libp2p-tcp/src/index.js:86:14)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
        at abortSignal (/root/lodestar/node_modules/abort-controller/src/abort-signal.ts:68:12)
        at AbortController.abort (/root/lodestar/node_modules/abort-controller/src/abort-controller.ts:26:9)
        at AbortSignal.onAbort (/root/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
        at abortSignal (/root/lodestar/node_modules/abort-controller/src/abort-signal.ts:68:12)
        at AbortController.abort (/root/lodestar/node_modules/abort-controller/src/abort-controller.ts:26:9)
        at AbortSignal.onAbort (/root/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
AggregateError: 
    Error: connection error 172.17.0.1:9124: connect ECONNREFUSED 172.17.0.1:9124
    Error: connection error 127.0.0.1:9124: connect ECONNREFUSED 127.0.0.1:9124
    Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.
        at Noise.performXXHandshake (/root/lodestar/node_modules/libp2p-noise/src/noise.ts:211:13)
    Error: The operation was aborted
        at AbortSignal.onAbort (/root/lodestar/node_modules/libp2p-tcp/src/index.js:86:14)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
        at abortSignal (/root/lodestar/node_modules/abort-controller/src/abort-signal.ts:68:12)
        at AbortController.abort (/root/lodestar/node_modules/abort-controller/src/abort-controller.ts:26:9)
        at AbortSignal.onAbort (/root/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
        at abortSignal (/root/lodestar/node_modules/abort-controller/src/abort-signal.ts:68:12)
        at AbortController.abort (/root/lodestar/node_modules/abort-controller/src/abort-controller.ts:26:9)
        at AbortSignal.onAbort (/root/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
    Error: The operation was aborted
        at AbortSignal.onAbort (/root/lodestar/node_modules/libp2p-tcp/src/index.js:86:14)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
        at abortSignal (/root/lodestar/node_modules/abort-controller/src/abort-signal.ts:68:12)
        at AbortController.abort (/root/lodestar/node_modules/abort-controller/src/abort-controller.ts:26:9)
        at AbortSignal.onAbort (/root/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
        at abortSignal (/root/lodestar/node_modules/abort-controller/src/abort-signal.ts:68:12)
        at AbortController.abort (/root/lodestar/node_modules/abort-controller/src/abort-controller.ts:26:9)
        at AbortSignal.onAbort (/root/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
    at maybeSettle (/root/lodestar/node_modules/p-some/index.js:31:11)
    at /root/lodestar/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processTimers (internal/timers.js:494:9)
```

**Comment by dapplion** [comment]
Other log latter
```
2021-03-23 15:24:05 [NETWORK]         debug: Error dialing discovered peer peer=16Uiu2HAmDng5UpRhZR5q7VzFjNmEBW9DSe92VKmhXvPZo4xEAciX message=
    Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.
        at Noise.performXXHandshake (/root/lodestar/node_modules/libp2p-noise/src/noise.ts:211:13)
        at runMicrotasks (<anonymous>)
    Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.
        at Noise.performXXHandshake (/root/lodestar/node_modules/libp2p-noise/src/noise.ts:211:13)
        at runMicrotasks (<anonymous>)
    Error: The operation was aborted
        at AbortSignal.onAbort (/root/lodestar/node_modules/libp2p-tcp/src/index.js:86:14)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
        at abortSignal (/root/lodestar/node_modules/abort-controller/src/abort-signal.ts:68:12)
        at AbortController.abort (/root/lodestar/node_modules/abort-controller/src/abort-controller.ts:26:9)
        at AbortSignal.onAbort (/root/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
        at abortSignal (/root/lodestar/node_modules/abort-controller/src/abort-signal.ts:68:12)
        at AbortController.abort (/root/lodestar/node_modules/abort-controller/src/abort-controller.ts:26:9)
        at AbortSignal.onAbort (/root/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
```

**Comment by dapplion** [comment]
@vasco-santos Can you review? Is this expected behaviour in a normal setting? Is it safe to ignore this error?

**Comment by vasco-santos** [comment]
`Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.` this should only happen if a peer is advertising addresses with addresses including a different PeerId.

Other more strange case I can think on top of my head is old PeerStore persisted data where IPs actually match for a different peer.

Making this an error test scenario is the best way to try to figure out a more concrete root reason / bug fix. Let me know if you can gather more data

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
