### ISSUE TITLE
Prater logs - dialing local IP

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2244]
**Describe the bug**

During Prater genesis I see some libp2p errors of failed dials to local IPs. Why does libp2p try to connect to local IPs for nodes? Do they advertise local IPs in their ENRs or ENRs contain multiple entries?

```
21-03-23 15:22:45 [NETWORK]         debug: Error dialing discovered peer peer=16Uiu2HAkw3emzXMPYuVoYM21DmRh832diFswxszxGdcv51F9HrtE message=
    Error: connection error 0.0.0.0:9137: connect ECONNREFUSED 0.0.0.0:9137
AggregateError: 
    Error: connection error 0.0.0.0:9137: connect ECONNREFUSED 0.0.0.0:9137
    at maybeSettle (/root/lodestar/node_modules/p-some/index.js:31:11)
    at /root/lodestar/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

To investigate:
- How often does libp2p try to connect to local IPs when dialing peers?
- What's the cost of doing so?

**Comment by dapplion** [comment]
Other log latter
```
2021-03-23 15:24:05 [NETWORK]         debug: Error dialing discovered peer peer=16Uiu2HAmBNaJnhXvy15fa5FCQNBVrN8fBvdkbeFWStvYJ7UPSELQ message=
    Error: connection error 127.0.0.1:9150: connect ECONNREFUSED 127.0.0.1:9150
    Error: connection error 172.17.0.1:9150: connect ECONNREFUSED 172.17.0.1:9150
    Error: connection error 66.85.74.26:9150: connect ECONNREFUSED 66.85.74.26:9150
    Error: The operation was aborted
        at AbortSignal.onAbort (/root/lodestar/node_modules/libp2p-tcp/src/index.js:86:14)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
        at abortSignal (/root/lodestar/node_modules/abort-controller/src/abort-signal.ts:68:12)
        at AbortController.abort (/root/lodestar/node_modules/abort-controller/src/abort-controller.ts:26:9)
        at AbortSignal.onAbort (/root/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
        at abortSignal (/root/lodestar/node_modules/abort-controller/src/abort-signal.ts:68:12)
        at AbortController.abort (/root/lodestar/node_modules/abort-controller/src/abort-controller.ts:26:9)
        at AbortSignal.onAbort (/root/lodestar/node_modules/any-signal/index.js:13:16)
        at AbortSignal.dispatchEvent (/root/lodestar/node_modules/event-target-shim/src/event-target.mjs:337:35)
```

**Comment by dapplion** [comment]
@vasco-santos Can you take a look? Should we escalate this to some libp2p module?

**Comment by vasco-santos** [comment]
> Why does libp2p try to connect to local IPs for nodes? 

If it tries, that is because they are advertised. Check the [announceFilters option](https://github.com/libp2p/js-libp2p/blob/master/doc/CONFIGURATION.md#customizing-libp2p)

> @vasco-santos Can you take a look? Should we escalate this to some libp2p module?

I think this might be a re-connect attempt from both sides, resulting in a connection to happen from one side and the other is aborted as the connection was already established. Did you see if you have a connection after the error?

**Comment by dapplion** [comment]
> > Why does libp2p try to connect to local IPs for nodes?
> 
> If it tries, that is because they are advertised. Check the [announceFilters option](https://github.com/libp2p/js-libp2p/blob/master/doc/CONFIGURATION.md#customizing-libp2p)
> 
> > @vasco-santos Can you take a look? Should we escalate this to some libp2p module?
> 
> I think this might be a re-connect attempt from both sides, resulting in a connection to happen from one side and the other is aborted as the connection was already established. Did you see if you have a connection after the error?

Hmm the node should not assume that a valuable peer is the same host, tho unlikely. Should we filter 0.0.0.0, 127.0.0.1 addresses out by default, providing a flag to undo that?

I will debug to see if the connection was established, would need more debugging to be sure

**Comment by dapplion** [comment]
Closing here

@wemeetagain @maschad do you think this issue is relevant in libp2p side?
