### ISSUE TITLE
Prater logs - FORKCHOICE_ERROR_INVALID_ATTESTATION

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2249]
**Describe the bug**

In Prater genesis running our Beacon node in very overloaded conditions this error appears multiple times only after the first log time shown below.

```
2021-03-23 15:22:46 [CHAIN]         verbose: Block processed slot=36, root=0x7a93e1f09d0c4c398cb70a4d965acb274b56e8ac75cf47cca1479b7383d595d5
2021-03-23 15:22:46 [CHAIN]         verbose: New chain head headSlot=36, headRoot=0x7a93e1f09d0c4c398cb70a4d965acb274b56e8ac75cf47cca1479b7383d595d5
2021-03-23 15:22:46 [CHAIN]           error: Non AttestationError received code=FORKCHOICE_ERROR_INVALID_ATTESTATION, err={"code":"PAST_EPOCH","attestationEpoch":1,"currentEpoch":3}
Error: FORKCHOICE_ERROR_INVALID_ATTESTATION
    at LodestarForkChoice.validateOnAttestation (/root/lodestar/packages/lodestar-fork-choice/src/forkChoice/forkChoice.ts:630:13)
    at LodestarForkChoice.onAttestation (/root/lodestar/packages/lodestar-fork-choice/src/forkChoice/forkChoice.ts:377:10)
    at processAttestation (/root/lodestar/packages/lodestar/src/chain/attestation/process.ts:59:14)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
    at processAttestationJob (/root/lodestar/packages/lodestar/src/chain/attestation/processor.ts:45:5)
    at AttestationProcessor.processAttestationJob (/root/lodestar/packages/lodestar/src/chain/attestation/processor.ts:28:5)
    at async Promise.all (index 88)
    at BeaconChain.onBlock (/root/lodestar/packages/lodestar/src/chain/eventHandlers.ts:235:5)

... 42 times more same error
```

- Why is the chain not expecting this error? `error: Non AttestationError received`
- Why did this attestation make it to the ForkChoice? Maybe it took so long to process that it was still in the same epoch on the chain and then not when it reached the ForkChoice.
- Seems that some validations are done twice in the Chain and ForkChoice, is that expected?

**Expected behavior**

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Version: 
- Branch: 
- Commit hash:

**Comment by twoeths** [comment]
what happened is we process slot 36 at `22:22:46` while the block itself was produced at `21:07` as in https://prater.beaconcha.in/block/7a93e1f09d0c4c398cb70a4d965acb274b56e8ac75cf47cca1479b7383d595d5#overview

due to clock drift issue #2240, the `PAST_EPOCH` condition passed when we validate attestations but right after that when they're passed to forkchoice, clock jumps to the correct slot and attestations failed to pass that same condition in forkchoice.

> Why is the chain not expecting this error? error: Non AttestationError received

Forkchoice throws `ForkChoiceError` with `INVALID_ATTESTATION` code, and lodestar only expects its own `AttestationError`. We need to map these errors so that lodestar handle them correctly

> Why did this attestation make it to the ForkChoice? Maybe it took so long to process that it was still in the same epoch on the chain and then not when it reached the ForkChoice.

this is due to the clock drift issue as explained above

> Seems that some validations are done twice in the Chain and ForkChoice, is that expected?

yeah there is a duplication (we do exactly the same thing as commented in the function header), maybe just remove the one in lodestar and keep the one in forkchoice. Then provide a map of forkchoice error to lodestar `AttestationError` and handle it in `eventHandler` finally.
