### ISSUE TITLE
Prater logs - ATTESTATION_ERROR_UNKNOWN_BEACON_BLOCK_ROOT

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2253]
**Describe the bug**

On Prater genesis with a overloaded beacon node this error appeared after the time of this log only

```
2021-03-23 15:31:09 [CHAIN]         verbose: Block processed slot=123, root=0x0cc7bcb5f3a6310aa51107513ab370bad218cb3af5c26ac7db408dd73fd1ae85
2021-03-23 15:31:09 [CHAIN]         verbose: New chain head headSlot=123, headRoot=0x0cc7bcb5f3a6310aa51107513ab370bad218cb3af5c26ac7db408dd73fd1ae85
2021-03-23 15:31:09 [NETWORK]       verbose: Resp done method=ping, encoding=ssz_snappy, peer=16Uiu2HAmSKqznRxyy3dbZbPd9mbExFJZHRZw255usxKsqNez5uTV, requestId=186
2021-03-23 15:31:09 [NETWORK]         debug: Req  dialing peer method=metadata, encoding=ssz_snappy, peer=16Uiu2HAmSKqznRxyy3dbZbPd9mbExFJZHRZw255usxKsqNez5uTV, requestId=496
2021-03-23 15:31:09 [CHAIN]           debug: Attestation error code=ATTESTATION_ERROR_UNKNOWN_BEACON_BLOCK_ROOT, beaconBlockRoot=0x5e9d5986d0c18e5440398badba11e727a3d74b83791a9b1ac66f69904d69d978
Error: ATTESTATION_ERROR_UNKNOWN_BEACON_BLOCK_ROOT
    at validateAttestation (/root/lodestar/packages/lodestar/src/chain/attestation/validate.ts:74:11)
    at processAttestationJob (/root/lodestar/packages/lodestar/src/chain/attestation/processor.ts:44:5)
    at AttestationProcessor.processAttestationJob (/root/lodestar/packages/lodestar/src/chain/attestation/processor.ts:28:11)
    at fn (/root/lodestar/packages/lodestar/src/chain/eventHandlers.ts:238:42)
    at forEach (/root/lodestar/node_modules/@chainsafe/ssz/src/backings/readOnlyIterate.ts:29:19)
    at Array.forEach (<anonymous>)
    at readOnlyMap (/root/lodestar/node_modules/@chainsafe/ssz/src/backings/readOnlyIterate.ts:28:29)
    at BeaconChain.onBlock (/root/lodestar/packages/lodestar/src/chain/eventHandlers.ts:237:10)
    at ChainEventEmitter.<anonymous> (/root/lodestar/packages/lodestar/src/chain/eventHandlers.ts:37:7)

... 32 times more
```

The root is of block 112 https://prater.beaconcha.in/block/5e9d5986d0c18e5440398badba11e727a3d74b83791a9b1ac66f69904d69d978
The node is at head 123 at that moment.

- Should we keep this attestations as "pending" and process them latter when we actually get that block?

**Comment by twoeths** [comment]
> Should we keep this attestations as "pending" and process them latter when we actually get that block?

yes, we're doing that at https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/chain/eventHandlers.ts#L291

then once we process a block, we process all pending attestations of that block https://github.com/ChainSafe/lodestar/blob/master/packages/lodestar/src/chain/eventHandlers.ts#L237
