### ISSUE TITLE
Eth1 module requests a range that's too big

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2288]
**Describe the bug**

```
2021-03-29 08:33:59 [ETH1]            error: Error updating eth1 chain cache message=JSON RPC error: query returned more than 10000 results, method=eth_getLogs, params=[{"fromBlock":"0x391f63","toBlock":"0x39234a","address":"0x8c5fecdc472e27bc447696f431e425d02dd46a8c","topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"]}]
Error: JSON RPC error: query returned more than 10000 results, method=eth_getLogs, params=[{"fromBlock":"0x391f63","toBlock":"0x39234a","address":"0x8c5fecdc472e27bc447696f431e425d02dd46a8c","topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"]}]
    at parseRpcResponse (/usr/app/packages/lodestar/src/eth1/jsonRpcHttpClient.ts:60:9)
    at JsonRpcHttpClient.fetch (/usr/app/packages/lodestar/src/eth1/jsonRpcHttpClient.ts:39:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Eth1Provider.getLogs (/usr/app/packages/lodestar/src/eth1/eth1JsonRpcClient.ts:104:21)
    at async Promise.all (index 0)
    at retry (/usr/app/packages/lodestar/src/util/retry.ts:27:14)
    at Eth1Provider.getDepositEvents (/usr/app/packages/lodestar/src/eth1/eth1Provider.ts:27:24)
    at Eth1ForBlockProduction.updateDepositCache (/usr/app/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:147:27)
    at Eth1ForBlockProduction.update (/usr/app/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:133:31)

```

**Expected behavior**

Should be able to correct the error and request a smaller range

**Comment by dapplion** [comment]
Code should already deal with this

**Comment by q9f** [comment]
same as #2680 / duplicate
