### ISSUE TITLE
No matching attestations found for attestationData

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2298]
**Describe the bug**

Running `multiNodeSingleThread.test.ts` with 128 validators per node and there are errors like this:
```
2021-03-30 17:57:28 [NODE 1 VALI 128-255] error: Failed to produce aggregate and proof message=No matching attestations found for attestationData
Error: No matching attestations found for attestationData
    at ValidatorApi.getAggregatedAttestation (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/api/impl/validator/validator.ts:123:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at AttestationService.aggregateAttestations (/Users/tuyennguyen/Projects/workshop/lodestar/packages/validator/src/services/attestation.ts:273:19)
    at Timeout._onTimeout (/Users/tuyennguyen/Projects/workshop/lodestar/packages/validator/src/services/attestation.ts:212:13)
```

**Expected behavior**

At least there should be 1 attestation coming from that same aggregator

**Steps to Reproduce**

`yarn test:sim:singleThreadMultiNode`

**Comment by dapplion** [comment]
@tuyennhv Could you upload the logFile in debug level? It would help see if the attestations are actually received from gossip

**Comment by twoeths** [comment]
This is the debug log:

[issue_2298_debug.log](https://github.com/ChainSafe/lodestar/files/6233433/issue_2298_debug.log)

**Comment by dapplion** [comment]
Our current validator client implementation does not guarantee that the aggregation step happens strictly after publishing the attestation

If this API call is significantly delayed
https://github.com/ChainSafe/lodestar/blob/ea5e141daebce417f92f58520f7ea5741ce9a4e0/packages/validator/src/services/attestation.ts#L220

The timeout wrapping this call will fire and may be executed before completing the above if the beacon node is overloaded
https://github.com/ChainSafe/lodestar/blob/ea5e141daebce417f92f58520f7ea5741ce9a4e0/packages/validator/src/services/attestation.ts#L212

----

Full relevant code

https://github.com/ChainSafe/lodestar/blob/ea5e141daebce417f92f58520f7ea5741ce9a4e0/packages/validator/src/services/attestation.ts#L199-L224

**Comment by dapplion** [comment]
Fixed with validator client refactor
