### ISSUE TITLE
Error when syncing chain: QUEUE_ERROR_QUEUE_MAX_LENGTH

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2337]
**Describe the bug**

I got this when syncing Prater:
```
Apr-07 04:31:01.477 [SYNC]            ^[[31merror^[[39m: Batch processingError startEpoch=3164, status=Processing code=BLOCK_ERROR_BEACON_CHAIN_ERROR, error={"code":"QUEUE_ERROR_QUEUE_MAX_LENGTH"}
Error: QUEUE_ERROR_QUEUE_MAX_LENGTH
    at JobQueue.push (/root/lodestar/packages/lodestar/src/util/queue/index.ts:66:13)
    at QueuedStateRegenerator.getPreState (/root/lodestar/packages/lodestar/src/chain/regen/queued.ts:47:32)
    at processChainSegment (/root/lodestar/packages/lodestar/src/chain/blocks/process.ts:126:34)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)
    at processChainSegmentJob (/root/lodestar/packages/lodestar/src/chain/blocks/processor.ts:163:3)
    at Object.job (/root/lodestar/packages/lodestar/src/chain/blocks/processor.ts:62:42)
    at wrapError (/root/lodestar/packages/lodestar/src/util/wrapError.ts:18:32)
Error: BLOCK_ERROR_BEACON_CHAIN_ERROR
    at processChainSegment (/root/lodestar/packages/lodestar/src/chain/blocks/process.ts:175:13)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)
Apr-07 04:31:24.025 []                 ^[[32minfo^[[39m: Syncing - 2.1 hours left - 0.428 slots/s - finalized: 3164 0x0b9b…e6f4 - head: 101312 0xd721…143c - currentSlot: 104557 - peers: 10
Apr-07 04:31:30.026 []                 ^[[32minfo^[[39m: Syncing - 1.6 hours left - 0.546 slots/s - finalized: 3164 0x0b9b…e6f4 - head: 101317 0xf560…182c - currentSlot: 104557 - peers: 10
```

**Expected behavior**

No error

**Comment by twoeths** [comment]
the current regen queue size is 256. At initial sync, the only consumer of regen module is the sync itself.
@dapplion is it possible that the Batches get executed with an unpredictable order? i.e Batch `128 - 192` is processed before batch `64 - 127`

**Comment by dapplion** [comment]
> the current regen queue size is 256. At initial sync, the only consumer of regen module is the sync itself.
> @dapplion is it possible that the Batches get executed with an unpredictable order? i.e Batch `128 - 192` is processed before batch `64 - 127`

That should never happen, something has gone really wrong there

**Comment by twoeths** [comment]
this is because we're processing attestation job at the time of initial sync and it keeps regen queue busy
<img width="1136" alt="Screen Shot 2021-04-12 at 18 09 01" src="https://user-images.githubusercontent.com/10568965/114385614-6b383480-9bba-11eb-831f-b8abc18d8419.png">
