### ISSUE TITLE
Add more logs to validator when there is no validator index

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2356]
**Is your feature request related to a problem? Please describe.**

I forgot to upload `deposit_data.json`, still able to start validators but got 
```
Apr-11 06:24:12.085 []                error: Failed to obtain attester duty epoch=4186, error=Request failed with response
status 400
Apr-11 06:24:14.195 []              verbose: HttpClient GET error url=/duties/proposer/4185 message=timeout of 4000ms exceeded
Error: timeout of 4000ms exceeded
    at createError (/root/lodestar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/root/lodestar/node_modules/axios/lib/adapters/http.js:280:16)
    at Object.onceWrapper (events.js:421:28)
    at RedirectableRequest.emit (events.js:315:20)
    at RedirectableRequest.EventEmitter.emit (domain.js:467:12)
    at Timeout._onTimeout (/root/lodestar/node_modules/follow-redirects/index.js:166:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

our node has a warn log:
```
Apr-11 04:24:12.072 [API]              warn: Request 20 failed validation. Reason: body should NOT have fewer than 1 items
```

the reason is there is no validator index in validator http request

**Describe the solution you'd like**

Validator should log a `warn` when there is no validator index.

**Comment by twoeths** [comment]
also we need to clean up validator logs a little bit, in prater and DEBUG mode, with 4 validators, the log file got to 500MB after  1 hour!
looks like this is because 
```
 Apr-13 11:24:48.077 []              ^[[36mverbose^[[39m: HttpClient GET url=/duties/proposer/4682, result={"dependent_r    oot":"0x5413a5fe268e7c850ccdf02e2ba4036bf24303b5158a7bebaa4f6117cc4ccf1f","data":[{"pubkey":"0x81293db1cd2c5c827b7803e0    6872d48fb16ef712a5ce8a2d01287c8b28cf81bd59853c75b8e3e020a4a5665ffd7e7374","validator_index":"192994","slot":"149824"},{    "pubkey":"0xaf4b21795323652c869c22bd51368a9f1d391aa52b835cee13f0895caae68258e197d1513792fad25b8ab9e772eaed4a","validato    r_index":"21698","slot":"149825"},{"pubkey":"0x91d288586febd619d2d3ab6f4a142c7c485206b3fdfdd621ed0756f0a13c4be05fd7deca    c599f16e2145a4bdd40abd3f","validator_index":"139180","slot":"149826"},{"pubkey":"0xa933e254bfbfdcddbec7c1a8ab9f281a1368    0420f4739700c2d8af194824c73659a8f07caf96c68ee71d2f5dc242db68","validator_index":"158055","slot":"149827"},{"pubkey":"0x    841ef57f03b3bbbb44cfb33d1c53f531288233bf27784b523b9865a4239996c10709caff71b3c0bdd552b197bdb8cdfe","validator_index":"72    626","slot":"149828"},{"pubkey":"0xa68656910e3b4fc0d2a251f0c66d7cf1579033c45ab605a64ec6c6825a651626ef73db26f6487a95b894    a8321077114e","validator_index":"17116","slot":"149829"},{"pubkey":"0x99100a5c00ccef0ea0d3a38a2a622afb5b2b1dd260c77c607    6186d8cc03aecbf2515e9c43d7cc4acf1da5ff87df15fd4","validator_index":"204600","slot":"149830"},{"pubkey":"0x8fecc786cbba7    35a876e1b4fbfbad89a4eeabc1dad929f44a226fb54ebab2784ab13c72af39bd7c014b304d0cab4a1d0","validator_index":"167398","slot":    "149831"},{"pubkey":"0xa44bb8d2d4090278e12ce97ab5335ac2a9f410f7974a775a36d39d9e67e0757c5b498b7471648625b391a704e6761147    ","validator_index":"198850","slot":"149832"},{"pubkey":"0x996383aee84b0bfbba38c572748401b233dfedd2efe012017281597d6986    0e68e7f7eb422f9699c89d82c4af730ea51d","validator_index":"73092","slot":"149833"},{"pubkey":"0xb5b1b542280df90ce4593385c    74202f9a501477b1596371b213b14d47c20d51d3fc08ba1ca7cb7319bc3745adac72921","validator_index":"77970","slot":"149834"},{"p    ubkey":"0x8f23173a5be4c5ee7a6f43b05a163b7b0cc0ced3e208ee89b757c3c1fbe9c8107363bc69da5c941f7572860009fc196d","validator_    index":"52347","slot":"149835"},{"pubkey":"0xb2247626c9aa03521ebd3fb2ef5e3d1951463ccaa522417d91f1cc85cffa0c42b869673c4b    3ccae70d7ffe4aa31f9cb9","validator_index":"115127","slot":"149836"},{"pubkey":"0xae47e9ecca46ef113904823f59e60acb63eaba    0021faea802f7381b11a095ab567be3b8dcdd6b5194296a91060590a65","validator_index":"122407","slot":"149837"},{"pubkey":"0xa4    c2fdf5f6907c4affe4a6e885b811b7784186c2820ce65cfb8b8865f45bd5f45fdf4a76f58f4fdeec56f19668a68a9d","validator_index":"3153    6","slot":"149838"},{"pubkey":"0x990583ed3af594bc63cecda4687f97d689ee06d258dbe9f84bdfa647eb754c60a5e2008dedd745fe385266    da85a59dbb","validator_index":"39657","slot":"149839"},{"pubkey":"0xab318f7578309e98ce25cab3584d03ec8920ff80e25dd1527d1    fc670f47a2d096b609abbfe5c004cbe094765ed449eda","validator_index":"204820","slot":"149840"},{"pubkey":"0xb896e821fef943b    bad6d782c48a00f496445403fc20659463ad5a5a8be4a17e7ecc7abfedb5536f321ccd9ec720e21c4","validator_index":"131986","slot":"1    49841"},{"pubkey":"0x8a27b62f2cd670ec901d1e84b2b53059e12a563e7b8778babc5efa238fa8bda57b6231dc97ee38b27896898b5931547d",    "validator_index":"93783","slot":"149842"},{"pubkey":"0xa25e78bf37bc6c3f3f3e59796cd073c014b551ee43147fa55691b10f02fa29d    419045c915e419c7e5b2603ca1fa98604","validator_index":"178085","slot":"149843"}
```
and
```
Apr-13 11:25:28.819 []              ^[[36mverbose^[[39m: HttpClient GET url=/states/head/validators?indices=0x811af134a    14e68b8b14102bd8c5339864faa592b977eab427b245cc4e602c91f245f51ffb1ca04d0b36eeeaceac3ca6a&indices=0x8c55b7ba8cb50a4fb3997    e3a5dd2a6c0381b0a4b6b5a763580805fe90357374c5f6460b8df51ef06273968e85977a5b5&indices=0xa2b3f8912622c4e393823dd050fe5fe91    15ac75b0a2d3de956ebaec3206123a3ab61cfbcd89b393a0dcb5ec425187622&indices=0xb795245dc2a46d0c007c1a1d5c355cf48f827616e38bb    aa6666c93cdd9221429c31c6843ea33b1387845e1c834b97159, result={"data":[{"index":"0","balance":"32111241621","status":"act    ive_ongoing","validator":{"pubkey":"0xb824b5ede33a7b05a378a84b183b4bc7e7db894ce48b659f150c97d359edca2f503081d6678d1200f    582ec7cafa9caf2","withdrawal_credentials":"0x0052fed27badbdb67d5cad6a5929ac44abd0346f76f0061002ab7df75548cf33","effecti    ve_balance":"32000000000","slashed":false,"activation_eligibility_epoch":"0","activation_epoch":"0","exit_epoch":"18446    744073709551615","withdrawable_epoch":"18446744073709551615"}},{"index":"1","balance":"32116224162","status":"active_on    going","validator":{"pubkey":"0xaffc434cf8138634a4cd0ef6cb815febd3db25760b1b6c522f9b4aa78e599b60336d7dd2e953192e45d4ac9    1f66f0723","withdrawal_credentials":"0x00fc40352b0a186d83267fc1342ec5da49dbb78e1099a4bd8db16d2c0d223594","effective_bal    ance":"32000000000","slashed":false,"activation_eligibility_epoch":"0","activation_epoch":"0","exit_epoch":"18446744073    709551615","withdrawable_epoch":"18446744073709551615"}},{"index":"2","balance":"32112044542","status":"active_ongoing"    ,"validator":{"pubkey":"0xad9a0951d00c0988d3b8e719b9e65d6bc3501c9c35392fb6f050fcbbcdd316836a887acee989730bdf093629448bb    731","withdrawal_credentials":"0x00472bc262a89d741a00806182cf90466d92ed498bb04d6a07620ebf798747db","effective_balance":    "32000000000","slashed":false,"activation_eligibility_epoch":"0","activation_epoch":"0","exit_epoch":"18446744073709551    615","withdrawable_epoch":"18446744073709551615"}},{"index":"3","balance":"32106540742","status":"active_ongoing","vali    dator":{"pubkey":"0xb319a5f89662c127718c0be02599dfd28f4983590bdd30a6f04ea900847d91a5dedf6ed780defa926d1fc7ed07a1c47d","    withdrawal_credentials":"0x00edb33e0856b163b1386ddd6fc0fb322e6e5a22cfd97eae71b4afbf70d39a94","effective_balance":"32000    000000","slashed":false,"activation_eligibility_epoch":"0","activation_epoch":"0","exit_epoch":"18446744073709551615","    withdrawable_epoch":"18446744073709551615"}},{"index":"4","balance":"32106405786","status":"active_ongoing","validator"    :{"pubkey":"0x92ec3cf2aec46c4cfed875d7390ba548ae5d7b6fda537e726033e742dfab9b70fc2a7aaf2e1ba6cc4e5a8edfd82c307a","withdr    awal_credentials":"0x0018439cbf43b48521a4555720bbcb50d3b66d34275215341fbf315344ca7cdd","effective_balance":"32000000000    ","slashed":false,"activation_eligibility_epoch":"0","activation_epoch":"0","exit_epoch":"18446744073709551615","withdr    awable_epoch":"18446744073709551615"}},{"index":"5","balance":"32106547898","status":"active_ongoing","validator":{"pub    key":"0x98b369fc9a96252c777b93018961b7853ca7be2f120ac0d0e03c670af63185f6b6fa32e8ed88f7327a7cdcd326789bbe","withdrawal_c    redentials":"0x00a19843ea04dd3682193a03a9b957c60498db10b449e0ce5c48fa8f46fc4b1b","effective_balance":"32000000000","sla    shed":false,"activation_eligibility_epoch":"0","activation_epoch":"0","exit_epoch":"18446744073709551615"
```

**Comment by dapplion** [comment]
Should be fixed with recent validator client refactor
