### ISSUE TITLE
Validator requests timed out

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2358]
**Describe the bug**

On prater, our node is too busy to response to validator:

```
Apr-11 09:04:14.632 []              verbose: HttpClient POST error url=/duties/attester/4211 message=timeout of 4000ms exceeded
Error: timeout of 4000ms exceeded
    at createError (/root/lodestar/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/root/lodestar/node_modules/axios/lib/adapters/http.js:280:16)
    at Object.onceWrapper (events.js:421:28)
    at RedirectableRequest.emit (events.js:315:20)
    at RedirectableRequest.EventEmitter.emit (domain.js:467:12)
    at Timeout._onTimeout (/root/lodestar/node_modules/follow-redirects/index.js:166:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```
We should investigate which operations take time there, probably the state transition.

**Comment by twoeths** [comment]
maybe we should do #1770

**Comment by twoeths** [comment]
the timeout issue happens even after node runs epoch transition. In the log below, we do receive `onHead` event with `epochTransition=true` but got timeout issue right after that:

```
Apr-15 04:47:50.263 []                 info: @@@ onHead slot slot=162239, epochTransition=false
Apr-15 04:48:04.017 []                error: Failed to obtain proposer duties message=timeout of 4000ms exceeded
Apr-15 04:48:04.603 []                error: Failed to obtain attester duty epoch=5071, error=timeout of 4000ms exceeded
Apr-15 04:48:09.921 []                 info: @@@ onHead slot slot=162240, epochTransition=true
Apr-15 04:48:09.922 []                 info: @@@ onHead calling updateDuties
Apr-15 04:48:13.928 []                error: Failed to obtain proposer duties message=timeout of 4000ms exceeded
Apr-15 04:48:13.929 []                error: Failed to obtain attester duty epoch=5070, error=timeout of 4000ms exceeded
Apr-15 04:48:13.929 []                 info: @@@ onHead done calling updateDuties
Apr-15 04:48:15.603 []                 info: @@@ onHead slot slot=162241, epochTransition=false
```

**Comment by dapplion** [comment]
Timeout was expanded to 1 slot, and we track optimizing the epoch transition in a separate issue
