### ISSUE TITLE
Cannot read property 'currentShuffling' of null

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2450]
**Describe the bug**

Running Prater after the node collapsing for a bit:

```
Apr-29 18:37:47.214 [CHAIN]           error: Block error slot=267424 code=BLOCK_ERROR_BEACON_CHAIN_ERROR, error={"message":"Cannot read property 'currentShuffling' of null"}
TypeError: Cannot read property 'currentShuffling' of null
    at getEffectiveBalances (/usr/app/packages/beacon-state-transition/src/util/balance.ts:55:41)
    at runStateTransition (/usr/app/packages/lodestar/src/chain/blocks/stateTransition.ts:149:25)
    at processBlock (/usr/app/packages/lodestar/src/chain/blocks/process.ts:60:11)
    at processBlockJob (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:80:5)
    at Object.job (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:59:42)
    at wrapError (/usr/app/packages/lodestar/src/util/wrapError.ts:18:32)
    at JobQueue.runJob (/usr/app/packages/lodestar/src/util/queue/index.ts:99:17)
```

this error is happening a lot

**Comment by dapplion** [comment]
This error won't happen after removing `!` operators in https://github.com/ChainSafe/lodestar/pull/2526.

The underlying cause is probably not fixed, but open another issue if it happens since it will have a better error.
