### ISSUE TITLE
Node gets stuck in Prater - critical

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2461]
**Describe the bug**

Our test node in Prater gets stuck sometimes and is not able to progress and go back to syncing.

![Screenshot from 2021-05-01 16-53-38](https://user-images.githubusercontent.com/35266934/116786298-19d6e300-aa9e-11eb-9652-516272c7a6c9.png)

- Investigate why the node gets so collapsed suddenly
- Investigate why the node does not go back to syncing state. I think our syncing algorithm does not allow to do that.

**Expected behavior**

If the node gets overloaded it should be able to sync to the head.

**Comment by dapplion** [comment]
It has happened again, the most telling metric about the incident is 
- gossip validation block processing time: it goes to about 5-10 min
- gossip validation block wait time, climbed to 1 hour

![Screenshot from 2021-05-02 09-26-49 (1)](https://user-images.githubusercontent.com/35266934/116805746-c9f12e00-ab28-11eb-91e2-61429a1bbc5b.png)

Seems that the node is extremely busy doing something because the scrape time maxes out. The event loop stays low so the node has the event loop full of tasks that may not be synchronously long but compound to long times.

![Screenshot from 2021-05-02 09-30-06](https://user-images.githubusercontent.com/35266934/116805827-44ba4900-ab29-11eb-8716-22737f596c90.png)

Memory spikes like crazy too. Maybe something in the regen pulling up states from disk and filling the cache?

![Screenshot from 2021-05-02 09-30-30](https://user-images.githubusercontent.com/35266934/116805834-556abf00-ab29-11eb-91fb-74d5ab25c239.png)

-----

**Logs**

Charts are in CEST time, so the big fuck-up happen at 22:30 UTC time. 

This one shows that the node's and validators clock are way off
```
May-01 22:16:29.576 [API]             error: Request 4093 /eth/v1/validator/duties/proposer/:epoch failed with unexpected error:  Error: Requesting beacon proposer for different epoch current shuffling: 8851 != 8852
    at Proxy.getBeaconProposer (/usr/app/packages/beacon-state-transition/src/fast/util/epochContext.ts:221:13)
    at ValidatorApi.getProposerDuties (/usr/app/packages/lodestar/src/api/impl/validator/validator.ts:124:40)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
    at Object.handler (/usr/app/packages/lodestar/src/api/rest/validator/duties/getProposerDuties.ts:9:19)
```
There are a many many `ATTESTATION_ERROR_TARGET_STATE_MISSING`. The regen should attach the full error here
```
Error: ATTESTATION_ERROR_TARGET_STATE_MISSING
    at processAttestation (/usr/app/packages/lodestar/src/chain/attestation/process.ts:33:11)
    at processAttestationJob (/usr/app/packages/lodestar/src/chain/attestation/processor.ts:51:5)
    at AttestationProcessor.processAttestationJob (/usr/app/packages/lodestar/src/chain/attestation/processor.ts:34:5)
```
Then the node tries to get more peers but everything is timing out, the dials, ping requests, etc.
