### ISSUE TITLE
Node is out of sync

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2498]
**Describe the bug**

On server contabo 3:
<img width="1644" alt="Screen Shot 2021-05-10 at 09 24 18" src="https://user-images.githubusercontent.com/10568965/117598210-86727180-b171-11eb-9e4c-9a62f56756a4.png">

Current prater slot: 342124

Logs
```
 wrapError (/usr/app/packages/lodestar/src/util/wrapError.ts:18:32)
    at Timeout._onTimeout (/usr/app/packages/lodestar/src/util/queue/index.ts:93:17)
May-08 11:38:13.165 [CHAIN]           error: Block error slot=330491 code=BLOCK_ERROR_PARENT_UNKNOWN, parentRoot=0xf3eb2c4234770d5f0136a20a9b608b9fac8a94bcee65fb5dc77e4bbe9821bf9e
Error: BLOCK_ERROR_PARENT_UNKNOWN
    at processBlock (/usr/app/packages/lodestar/src/chain/blocks/process.ts:31:11)
    at processBlockJob (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:80:11)
    at Object.job (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:59:48)
    at JobQueue.runJob (/usr/app/packages/lodestar/src/util/queue/index.ts:93:46)
    at Timeout._onTimeout (/usr/app/packages/lodestar/src/util/queue/index.ts:105:15)
May-08 11:38:18.024 []                 info: Synced - finalized: 10131 0x9f23…b859 - head: 324255 0xf4ba…5bbd - peers: 25
May-08 11:38:18.248 [CHAIN]           error: Block error slot=324256 code=BLOCK_ERROR_BEACON_CHAIN_ERROR, error={"message":"Cannot read property 'currentShuffling' of null"}
TypeError: Cannot read property 'currentShuffling' of null
    at getEffectiveBalances (/usr/app/packages/beacon-state-transition/src/util/balance.ts:55:41)
    at runStateTransition (/usr/app/packages/lodestar/src/chain/blocks/stateTransition.ts:149:25)
    at processBlock (/usr/app/packages/lodestar/src/chain/blocks/process.ts:60:11)
    at processBlockJob (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:80:5)
    at Object.job (/usr/app/packages/lodestar/src/chain/blocks/
```

**Expected behavior**

Node stays synced

**Comment by twoeths** [comment]
so the issue is `currentJustifiedCheckpoint` not in checkpoint state cache, I think we always add all checkpoint states to the cache, but after that we delete them through `prune`.

although there is no evidence in the log, I think when we regen a state, we don't want to emit any events (and then trigger the event handler which call `prune` per regen checkpoint), we just want to get a state to get back to the consumer.
