### ISSUE TITLE
Cannot sync Prater

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2504]
**Describe the bug**

From `0.21.0` we cannot sync Prater, it happens on the current master (`e886a23`) too:
```
May-11 13:36:06.830 []                 info: Syncing - ? left - 0.00 slots/s - finalized: 5 0x2811…5120 - head: 255 0x6c99…033b - clockSlot: 352680 - peers: 2
May-11 13:36:20.018 []                 info: Syncing - ? left - 0.00 slots/s - finalized: 5 0x2811…5120 - head: 255 0x6c99…033b - clockSlot: 352681 - peers: 2
May-11 13:36:31.236 []                 info: Syncing - ? left - 0.00 slots/s - finalized: 5 0x2811…5120 - head: 255 0x6c99…033b - clockSlot: 352682 - peers: 2
May-11 13:36:42.000 []                 info: Syncing - ? left - 0.00 slots/s - finalized: 5 0x2811…5120 - head: 255 0x6c99…033b - clockSlot: 352683 - peers: 4
May-11 13:36:55.319 []                 info: Searching for peers - peers: 2 - finalized: 5 0x2811…5120 - head: 255 0x6c99…033b - clockSlot: 352684
```

Note that it works fine with `0.20.0`

**Expected behavior**

We can sync Prater all the way to head.

**Comment by dapplion** [comment]
Do you have debug logs of the node?

**Comment by 3xtr4t3rr3str14l** [comment]
i'm seeing this in mainnet too (no debug logs for right now though, i'll try to collect some if i get a chance)

**Comment by dapplion** [comment]
> no debug logs for right now though

Please collect them with the --logFile option and drop the file here when possible

**Comment by 3xtr4t3rr3str14l** [comment]
here's a log file i just grabbed of me syncing from genesis on latest master

[beacon-debug-log-prater-sync-error.txt](https://github.com/ChainSafe/lodestar/files/6480089/log-today.txt)

**Comment by 3xtr4t3rr3str14l** [comment]
think i found part of the problem (from the log file above):

```
May-14 11:38:50.718 [SYNC]          verbose: Batch process error id=Finalized, startEpoch=7, status=Processing code=BLOCK_ERROR_BEACON_CHAIN_ERROR, error={"message":"Cannot read property 'currentShuffling' of null"}
TypeError: Cannot read property 'currentShuffling' of null
    at getEffectiveBalances (/home/seraph/work/ChainSafe/lodestar/packages/beacon-state-transition/src/util/balance.ts:55:41)
    at runStateTransition (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/src/chain/blocks/stateTransition.ts:97:25)
    at processChainSegment (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/src/chain/blocks/process.ts:136:26)
    at processChainSegmentJob (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/src/chain/blocks/processor.ts:159:3)
    at Object.job (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/src/chain/blocks/processor.ts:58:42)
    at JobQueue.runJob (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/src/util/queue/index.ts:106:22)
Error: BLOCK_ERROR_BEACON_CHAIN_ERROR
    at processChainSegment (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/src/chain/blocks/process.ts:164:13)
    at processChainSegmentJob (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/src/chain/blocks/processor.ts:159:3)
    at Object.job (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/src/chain/blocks/processor.ts:58:42)
    at JobQueue.runJob (/home/seraph/work/ChainSafe/lodestar/packages/lodestar/src/util/queue/index.ts:106:22)
```

this error keeps happening periodically towards the end of the log file, and looks like it's preventing us from processing blocks

**Comment by twoeths** [comment]
thanks @3xtr4t3rr3str14l for the finding, I debugged the issue with Prater sync:
+ the missing justified checkpoint is at epoch 7
+ we actually haven't added any checkpoint state contexts for epoch 7
+ start lot of epoch 7 (224) is a skipped slot https://prater.beaconcha.in/block/224

we want to emit checkpoint events for skipped slots
