### ISSUE TITLE
Error if enr exists

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#2561]
**Describe the bug**

If you already have enr, starting with beacon command fails with:
```
✖ Error: Invalid filetype
    at parse (/Users/nodefactory/Projects/lodestar/packages/cli/src/util/file.ts:47:13)
    at readFile (/Users/nodefactory/Projects/lodestar/packages/cli/src/util/file.ts:89:10)
    at readEnr (/Users/nodefactory/Projects/lodestar/packages/cli/src/config/enr.ts:28:24)
    at persistOptionsAndConfig (/Users/nodefactory/Projects/lodestar/packages/cli/src/cmds/init/handler.ts:85:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.beaconHandler [as handler] (/Users/nodefactory/Projects/lodestar/packages/cli/src/cmds/beacon/handler.ts:24:3)
```
because enr doesn't have extension.

**Expected behavior**
should work

**Steps to Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Version: 
- Branch: 
- Commit hash:

**Comment by g11tech** [comment]
assign it to me pls
