### ISSUE TITLE
sNaPpY a0dPeer has been rate limited

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2622]
**Describe the bug**

Found this when syncing oonoonba:
```
Jun-03 09:43:13.494 [NETWORK]       verbose: Req  error method=beacon_blocks_by_range, encoding=ssz_snappy, agentVersion=teku/teku/v21.5.0+59-ga3cc317/linux-x86_64/-redhatinc-openjdk64bitservervm-java-16, peer=16...EAGj7C, requestId=22 code=RESPONSE_STATUS_ERROR, status=1, errorMessage=sNaPpY a0dPeer has been rate limited
Error: RESPONSE_ERROR_INVALID_REQUEST: sNaPpY a0dPeer has been rate limited
    at /Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/network/reqresp/encoders/responseDecode.ts:56:15
    at runMicrotasks (<anonymous>)
    at process.chunk (internal/process/task_queues.js:93:5)
    at /Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/network/reqresp/utils/onChunk.ts:7:22
    at response (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/network/reqresp/request/responseTimeoutsHandler.ts:39:7)
    at /Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/network/reqresp/request/collectResponses.ts:25:22
    at withTimeout (/Users/tuyennguyen/Projects/workshop/lodestar/packages/utils/src/timeout.ts:20:12)
    at sendRequest (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/network/reqresp/request/index.ts:139:25)
    at ReqResp.sendRequest (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/network/reqresp/reqResp.ts:141:22)
    at ReqResp.beaconBlocksByRange (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/network/reqresp/reqResp.ts:107:20)
```

**Steps to Reproduce**

Sync with `--network oonoonba`

**Comment by dapplion** [comment]
I've seen that one too. Since this network has only two peers we ask them for blocks too often on failures. I'm not sure how to tackle this issue since we may have to do assumptions of our other peers rate limits parameters

**Comment by dapplion** [comment]
Still happening in merge-interop in Teku nodes

**Comment by dapplion** [comment]
We should encode and decode the error message correctly now
