### ISSUE TITLE
Goodbye ReqResp may not return response

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2635]
**Describe the bug**

We currently expect to receive a response from Goodbye requestes. We also expect our peer to receive our goodbye response. As far as I know Lighthouse and Teku do not do any of that and it's not spec-ed.

```
Jun-04 03:10:53.117 [NETWORK]       [36mverbose[39m: Req  error method=goodbye, encoding=ssz_snappy, agentVersion=teku/teku/v21.4.1/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11, peer=16...kCrRcF, requestId=483 code=REQUEST_ERROR_EMPTY_RESPONSE
Error: REQUEST_ERROR_EMPTY_RESPONSE
    at /usr/app/packages/lodestar/src/network/reqresp/request/collectResponses.ts:20:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at withTimeout (/usr/app/packages/utils/src/timeout.ts:20:12)
    at sendRequest (/usr/app/packages/lodestar/src/network/reqresp/request/index.ts:139:25)
    at ReqResp.sendRequest (/usr/app/packages/lodestar/src/network/reqresp/reqResp.ts:141:22)
    at ReqResp.goodbye (/usr/app/packages/lodestar/src/network/reqresp/reqResp.ts:90:5)
    at PeerManager.goodbyeAndDisconnect (/usr/app/packages/lodestar/src/network/peers/peerManager.ts:429:7)
Jun-04 03:10:53.119 [NETWORK]       [36mverbose[39m: Failed to send goodbye peer=16...kCrRcF method=goodbye, encoding=ssz_snappy, peer=16...kCrRcF, code=REQUEST_ERROR_EMPTY_RESPONSE
Error: REQUEST_ERROR_EMPTY_RESPONSE
    at sendRequest (/usr/app/packages/lodestar/src/network/reqresp/request/index.ts:176:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ReqResp.sendRequest (/usr/app/packages/lodestar/src/network/reqresp/reqResp.ts:141:22)
    at ReqResp.goodbye (/usr/app/packages/lodestar/src/network/reqresp/reqResp.ts:90:5)
    at PeerManager.goodbyeAndDisconnect (/usr/app/packages/lodestar/src/network/peers/peerManager.ts:429:7)
```

**Expected behavior**

 We should not expect that to happen, and not log it as errors.

**Comment by Alleysira** [comment]
Sorry to comment on a closed issue, but this inconsistency still exists.

We ran differential tests against all 6 CL clients on a fulu testnet and observed the following Goodbye response behavior:

| Client     | Response to incoming Goodbye               |
|------------|---------------------------------------------|
| Lodestar   | Responds with SUCCESS (echoes reason code)  |
| Teku       | Stream reset (no response body)             |
| Prysm      | Connection closed / EOF                     |
| Lighthouse | No response                                 |
| Nimbus     | No response                                 |
| Grandine   | No response                                 |

Lodestar is the only client that responds to an incoming Goodbye. The other 5 clients process it internally (disconnect, apply backoff) but do not write back to the stream.
