### ISSUE TITLE
Error lightclientUpdater.onFinalized

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2643]
**Describe the bug**

Got this while syncing `oonoonba` network:
```
Jun-07 10:33:48.782 [CHAIN]           error: Error lightclientUpdater.onFinalized epoch=515 message=REGEN_ERROR_BLOCK_NOT_IN_FORKCHOICE
Error: REGEN_ERROR_BLOCK_NOT_IN_FORKCHOICE
    at StateRegenerator.getBlockSlotState (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/regen/regen.ts:92:13)
    at StateRegenerator.getCheckpointState (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/regen/regen.ts:86:23)
    at Object.job (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/regen/queued.ts:91:66)
    at Timeout._onTimeout (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/util/queue/index.ts:106:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Expected behavior**

No error

**Comment by twoeths** [comment]
another error
```
Jun-07 12:43:21.502 [CHAIN]           error: Error lightclientUpdater.onFinalized epoch=488 message=No block found for checkpoint 488 : 0xad0da9ee63bf4aca2ebccf8f21525e31f6b65659de12cc0d35909ccd94a33b88
Error: No block found for checkpoint 488 : 0xad0da9ee63bf4aca2ebccf8f21525e31f6b65659de12cc0d35909ccd94a33b88
    at BeaconChain.onFinalized (/root/workspace/node/lodestar/packages/lodestar/src/chain/eventHandlers.ts:185:15)
    at ChainEventEmitter.<anonymous> (/root/workspace/node/lodestar/packages/lodestar/src/chain/eventHandlers.ts:33:7)
```

**Comment by twoeths** [comment]
maybe this is the root cause #2783

**Comment by twoeths** [comment]
the `onFinalized` handler try to get block by skipped slot
```
Jul-07 03:32:49.057 [CHAIN]           error: Error lightclientUpdater.onFinalized epoch=4475 message=No block found for checkpoint 4475 : 0xbfd44f561487162039156ddf83bf69379908881c6d6d0126abba287481202a5c
Error: No block found for checkpoint 4475 : 0xbfd44f561487162039156ddf83bf69379908881c6d6d0126abba287481202a5c
    at BeaconChain.onFinalized (/usr/app/packages/lodestar/src/chain/eventHandlers.ts:179:15)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
    at ChainEventEmitter.<anonymous> (/usr/app/packages/lodestar/src/chain/eventHandlers.ts:33:7)
```
start slot of epoch 4475 is slot 143200, it shows in the validator log that it's a skipped slot

```
Jul-07 03:20:04.040 []                error: Error on runSyncCommitteeTasks slot=143200 message=Error producing SyncCommitteeMessage - Not Found: No block found for id '143200'
Error: Error producing SyncCommitteeMessage - Not Found: No block found for id '143200'
    at HttpClient.request (/usr/app/packages/api/src/client/utils/httpClient.ts:85:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HttpClient.json (/usr/app/packages/api/src/client/utils/httpClient.ts:57:12)
    at Object.request [as getBlockRoot] (/usr/app/packages/api/src/client/utils/client.ts:71:19)
    at SyncCommitteeService.produceAndPublishSyncCommittees (/usr/app/packages/validator/src/services/syncCommittee.ts:93:29)
    at /usr/app/packages/validator/src/services/syncCommittee.ts:51:31
    at Clock.runAtMostEvery (/usr/app/packages/validator/src/util/clock.ts:68:7)
```

**Comment by twoeths** [comment]
also this checkpoint `onFinalized` is conflict to `forkChoiceFinalized` event and both seems to happen at the same time
```
Jul-07 11:43:16.660 [CHORES]           info: Start processing finalized checkpoint epoch=1080
Jul-07 11:43:16.666 [CHAIN]           error: Error lightclientUpdater.onFinalized epoch=1080 message=No block found for checkpoint 1080 : 0x14823228ba8041d0576bf07f3c6ac2233fd4363be6ab3aa79c2f30dd36654f28
Error: No block found for checkpoint 1080 : 0x14823228ba8041d0576bf07f3c6ac2233fd4363be6ab3aa79c2f30dd36654f28
    at BeaconChain.onFinalized (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/eventHandlers.ts:183:15)
    at ChainEventEmitter.<anonymous> (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/eventHandlers.ts:33:7)
Jul-07 11:43:16.764 [CHORES]           info: Finish processing finalized checkpoint epoch=1080
```
