### ISSUE TITLE
SYNC_COMMITTEE_INVALID_SIGNATURE in sim test

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2644]
**Describe the bug**

In `multiNodeSingleThread.test.ts` we only wait for justified event. If we wait for finalized event with
```
 {nodeCount: 4, validatorsPerNode: 8, event: ChainEvent.finalized, altairForkEpoch: 2},
```

then we'll see a couple of errors even the test still passed

```
Error: Multiple errors on publishContributionAndProofs
 447 Cannot read property 'jacobian' of undefined
 448 Cannot read property 'jacobian' of undefined
 449     at Object.publishContributionAndProofs (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/ap     i/impl/validator/index.ts:424:15)
 450     at SyncCommitteeService.produceAndPublishAggregates (/Users/tuyennguyen/Projects/workshop/lodestar/packages/va     lidator/src/services/syncCommittee.ts:169:9)
 451     at /Users/tuyennguyen/Projects/workshop/lodestar/packages/validator/src/services/syncCommittee.ts:64:9
 452     at async Promise.all (index 2)
 453     at /Users/tuyennguyen/Projects/workshop/lodestar/packages/validator/src/services/syncCommittee.ts:59:5
 454     at Clock.runAtMostEvery (/Users/tuyennguyen/Projects/workshop/lodestar/packages/validator/src/util/clock.ts:68     :7)
 455 Eph 3/0 2.069 [NODE 2 API]      ^[[31merror^[[39m: Error on publishContributionAndProofs [0] slot=24, subCommittee     Index=1 code=SYNC_COMMITTEE_INVALID_SIGNATURE
 456 Error: SYNC_COMMITTEE_INVALID_SIGNATURE
 457     at Object.validateSyncCommitteeGossipContributionAndProof (/Users/tuyennguyen/Projects/workshop/lodestar/packa     ges/lodestar/src/chain/validation/syncCommitteeContributionAndProof.ts:77:11)
 458     at /Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/api/impl/validator/index.ts:398:13
 459     at async Promise.all (index 0)
 460     at Object.publishContributionAndProofs (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/ap     i/impl/validator/index.ts:394:7)
 461     at SyncCommitteeService.produceAndPublishAggregates (/Users/tuyennguyen/Projects/workshop/lodestar/packages/va     lidator/src/services/syncCommittee.ts:169:9)
 462     at /Users/tuyennguyen/Projects/workshop/lodestar/packages/validator/src/services/syncCommittee.ts:64:9
 463     at async Promise.all (index 0)
 464     at /Users/tuyennguyen/Projects/workshop/lodestar/packages/validator/src/services/syncCommittee.ts:59:5
 465     at Clock.runAtMostEvery (/Users/tuyennguyen/Projects/workshop/lodestar/packages/validator/src/util/clock.ts:68     :7)
```

**Expected behavior**

No error

**Steps to Reproduce**

`yarn test:sim`

**Comment by twoeths** [comment]
I checked that we have same domain and signing root between validator side and node site.
Given this error, do you have any ideas @dapplion 

```
 Eph 3/0 2.057 [NODE 3 API]      ^[[31merror^[[39m: Error on publishContributionAndProofs [1] slot=24, subCommittee     Index=3 message=Cannot read property 'jacobian' of undefined
 427 TypeError: Cannot read property 'jacobian' of undefined
 428     at Object.aggregatePubkeys (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@chainsafe/blst/src/lib     .ts:195:36)
 429     at Function.aggregate (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/@chainsafe/bls/lib/blst/publ     icKey.js:32:25)
 430     at getAggregatedPubkey (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/bls/index.ts     :65:28)
 431     at /Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/bls/index.ts:50:20
 432     at Array.map (<anonymous>)
 433     at BlsVerifier.verifySignatureSets (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/     bls/index.ts:49:21)
 434     at Object.validateSyncCommitteeGossipContributionAndProof (/Users/tuyennguyen/Projects/workshop/lodestar/packa     ges/lodestar/src/chain/validation/syncCommitteeContributionAndProof.ts:76:25)
 435     at /Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/api/impl/validator/index.ts:398:19
 436     at Array.map (<anonymous>)
 437     at Object.publishContributionAndProofs (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/ap     i/impl/validator/index.ts:395:31)
```

**Comment by dapplion** [comment]
The `.jacobian` property is access on the BLS lib to do aggregation. Could you have incompatible versions of bls or blst-ts installed locally? Wipe out all node_modules, re-install and try again

**Comment by dapplion** [comment]
Closing for now, re-open if it happens again
