### ISSUE TITLE
Error updating eth1 chain cache 

### ISSUE THREAD

**Issue by KBryan** [ChainSafe/lodestar#2680]
This is the general error displayed when running the project

JSON RPC error: query returned more than 10000 results

On git cloning the lodestar project and installing the necessary dependencies. Running the project produced the following error,

Steps to reproduce

Download the project and install the necessary dependencies.
run the project

<img width="952" alt="Screen Shot 2021-06-10 at 5 58 19 PM" src="https://user-images.githubusercontent.com/681817/121602576-820dd280-ca15-11eb-9814-d0ad91a11b65.png">

**Comment by wemeetagain** [comment]
```
Jun-10 17:26:13.970 [ETH1]            error: Error updating eth1 chain cache message=JSON RPC error: query returned more than 10000 results, method=eth_getLogs, params=[{"fromBlock":"0x391f63","toBlock":"0x39234a","address":"0x8c5fecdc472e27bc447696f431e425d02dd46a8c","topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"]}]
Error: JSON RPC error: query returned more than 10000 results, method=eth_getLogs, params=[{"fromBlock":"0x391f63","toBlock":"0x39234a","address":"0x8c5fecdc472e27bc447696f431e425d02dd46a8c","topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"]}]    at parseRpcResponse (/home/cayman/Code/lodestar/packages/lodestar/src/eth1/jsonRpcHttpClient.ts:60:9)
    at JsonRpcHttpClient.fetch (/home/cayman/Code/lodestar/packages/lodestar/src/eth1/jsonRpcHttpClient.ts:39:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Eth1Provider.getLogs (/home/cayman/Code/lodestar/packages/lodestar/src/eth1/eth1JsonRpcClient.ts:104:21)
    at async Promise.all (index 0)
    at retry (/home/cayman/Code/lodestar/packages/lodestar/src/util/retry.ts:27:14)
    at Eth1Provider.getDepositEvents (/home/cayman/Code/lodestar/packages/lodestar/src/eth1/eth1Provider.ts:27:24)
    at Eth1ForBlockProduction.updateDepositCache (/home/cayman/Code/lodestar/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:148:27)
    at Eth1ForBlockProduction.update (/home/cayman/Code/lodestar/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:134:31)
    at Eth1ForBlockProduction.runAutoUpdate (/home/cayman/Code/lodestar/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:116:28)
```

**Comment by KBryan** [comment]
Here is also the original screenshot to support @wemeetagain findings.

![lodestar_error](https://user-images.githubusercontent.com/681817/121605356-43c6e200-ca1a-11eb-8934-080ac9318fb5.png)

**Comment by KBryan** [comment]
This seems to have been fixed in the latest release.

**Comment by q9f** [comment]
I'm still getting this with v0.28.0 on Pyrmont testnet.

```
Aug-12 11:46:41.280 []                 info: Lodestar version=0.28.0 master 2c010b25, network=pyrmont
Aug-12 11:46:41.396 [DB]               info: Connected to LevelDB database name=/srv/chain/lodestar/chain-db
Aug-12 11:46:45.294 []                 info: Initializing beacon state from anchor state slot=10240, epoch=320, stateRoot=0x2d5fc63377925d1f1a2378dc5277ebef4533cd8ae0b6a2e144fb008de9b59c9b
Aug-12 11:46:54.271 [METRICS]          info: Starting metrics HTTP server port=8008
(node:1301099) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
Aug-12 11:46:56.916 [NETWORK]          info: PeerId 16Uiu2HAmGWtTaoLRALWFUr5dFApu3mCiKUGdcGobF7VZseHZBtqA, Multiaddrs /ip4/127.0.0.1/tcp/9000,/ip4/135.181.182.52/tcp/9000
Aug-12 11:46:56.917 []                 warn: Low peer count peers=0
Aug-12 11:46:56.918 []                 info: Searching for peers - peers: 0 - finalized: 318 0xf918…f52c - head: 10239 0x198f…7f39 - clockSlot: 1921734
Aug-12 11:47:01.001 []                 info: Searching for peers - peers: 0 - finalized: 318 0xf918…f52c - head: 10239 0x198f…7f39 - clockSlot: 1921734
Aug-12 11:47:05.241 [ETH1]            error: Error updating eth1 chain cache message=JSON RPC error: query returned more than 10000 results, method=eth_getLogs, params=[{"fromBlock":"0x39234b","toBlock":"0x392444","address":"0x8c5fecdc472e27bc447696f431e425d02dd46a8c","topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"]}]
Error: JSON RPC error: query returned more than 10000 results, method=eth_getLogs, params=[{"fromBlock":"0x39234b","toBlock":"0x392444","address":"0x8c5fecdc472e27bc447696f431e425d02dd46a8c","topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"]}]
    at parseRpcResponse (/home/user/lodestar/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:139:9)
    at JsonRpcHttpClient.fetch (/home/user/lodestar/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:53:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Eth1Provider.getLogs (/home/user/lodestar/packages/lodestar/src/eth1/provider/eth1Provider.ts:158:21)
    at async Promise.all (index 0)
    at retry (/home/user/lodestar/packages/lodestar/src/util/retry.ts:33:14)
    at Eth1Provider.getDepositEvents (/home/user/lodestar/packages/lodestar/src/eth1/provider/eth1Provider.ts:67:24)
    at Eth1ForBlockProduction.updateDepositCache (/home/user/lodestar/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:164:27)
    at Eth1ForBlockProduction.update (/home/user/lodestar/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:150:31)
Aug-12 11:47:13.001 []                 info: Searching for peers - peers: 0 - finalized: 318 0xf918…f52c - head: 10239 0x198f…7f39 - clockSlot: 1921735
Aug-12 11:47:17.169 [ETH1]            error: Error updating eth1 chain cache message=JSON RPC error: query returned more than 10000 results, method=eth_getLogs, params=[{"fromBlock":"0x39234b","toBlock":"0x392444","address":"0x8c5fecdc472e27bc447696f431e425d02dd46a8c","topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"]}]
Error: JSON RPC error: query returned more than 10000 results, method=eth_getLogs, params=[{"fromBlock":"0x39234b","toBlock":"0x392444","address":"0x8c5fecdc472e27bc447696f431e425d02dd46a8c","topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"]}]
    at parseRpcResponse (/home/user/lodestar/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:139:9)
    at JsonRpcHttpClient.fetch (/home/user/lodestar/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:53:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Eth1Provider.getLogs (/home/user/lodestar/packages/lodestar/src/eth1/provider/eth1Provider.ts:158:21)
    at async Promise.all (index 0)
    at retry (/home/user/lodestar/packages/lodestar/src/util/retry.ts:33:14)
    at Eth1Provider.getDepositEvents (/home/user/lodestar/packages/lodestar/src/eth1/provider/eth1Provider.ts:67:24)
    at Eth1ForBlockProduction.updateDepositCache (/home/user/lodestar/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:164:27)
```
