### ISSUE TITLE
timeout in CI test - network / ReqResp

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/lodestar#2715]
see:

https://github.com/ChainSafe/lodestar/pull/2571/checks?check_run_id=2842324154#step:11:466

**Comment by dapplion** [comment]
```
@chainsafe/lodestar:   1) network / ReqResp
@chainsafe/lodestar:        should handle a server error:
@chainsafe/lodestar:      Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/lodestar/lodestar/packages/lodestar/test/e2e/network/reqresp.test.ts)
@chainsafe/lodestar:       at listOnTimeout (internal/timers.js:554:17)
@chainsafe/lodestar:       at processTimers (internal/timers.js:497:7)
```

**Comment by dapplion** [comment]
Still happens sometimes
