### ISSUE TITLE
Validator: attestation and sync committee services stop working

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2727]
**Describe the bug**

I synced oonoonba with 160 validators, got this right after I start validator:
```
Jun-20 10:56:46.448 []                 info: Verified node and validator have same config
Jun-20 10:56:46.546 []                error: Error on poll indices and attesters epoch=4118 message=Bad Request: Client Error
Error: Bad Request: Client Error
    at HttpClient.request (/usr/app/packages/api/src/client/utils/httpClient.ts:85:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HttpClient.json (/usr/app/packages/api/src/client/utils/httpClient.ts:57:12)
    at Object.request [as getStateValidators] (/usr/app/packages/api/src/client/utils/client.ts:71:19)
    at IndicesService.pollValidatorIndicesInternal (/usr/app/packages/validator/src/services/indices.ts:62:29)
Jun-20 10:56:46.574 []                error: Error on poll indices and SyncDuties epoch=4118 message=Bad Request: Client Error
Error: Bad Request: Client Error
    at HttpClient.request (/usr/app/packages/api/src/client/utils/httpClient.ts:85:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HttpClient.json (/usr/app/packages/api/src/client/utils/httpClient.ts:57:12)
    at Object.request [as getStateValidators] (/usr/app/packages/api/src/client/utils/client.ts:71:19)
    at IndicesService.pollValidatorIndicesInternal (/usr/app/packages/validator/src/services/indices.ts:62:29)
(node:1) UnhandledPromiseRejectionWarning: Error: Bad Request: Client Error
    at HttpClient.request (/usr/app/packages/api/src/client/utils/httpClient.ts:85:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HttpClient.json (/usr/app/packages/api/src/client/utils/httpClient.ts:57:12)
    at Object.request [as getStateValidators] (/usr/app/packages/api/src/client/utils/client.ts:71:19)
    at IndicesService.pollValidatorIndicesInternal (/usr/app/packages/validator/src/services/indices.ts:62:29)
(Use `node --trace-warnings ...` to show where the warning was created)
```

I don't see attestation + sync committee services' logs, only block proposal service continues after that
```
Jun-20 10:59:20.358 []                 info: Published block slot=131792, validator=0x91a4…f7e2, graffiti=chainsafe/lodestar-0.24.3
```

also, no error at node side

**Expected behavior**

No error

**Comment by twoeths** [comment]
script to import validator folder containing *.json and *.txt
```sh
#!/bin/bash

dirPath=/root/oonoonba_validators/tranch3
dirPathLen=${#dirPath}
echo "length=${dirPathLen}"


for file in "${dirPath}"/*.json;do
  json=${file:dirPathLen+1:98}
  pw=$( cat $dirPath/$json.txt )

  echo ${pw} | ./bin/lodestar account validator import --keystore ${dirPath}/${json}.json --network oonoonba
done
```
got
```
root@vmi512326:~/lodestar/packages/cli# ./bin/lodestar account validator list --network oonoonba | wc -l
400
```

**Comment by dapplion** [comment]
Nice script! I agree it's very annoying to import large amounts of validators. We should improve our CLI to make that job easier

Lighthouse uses a script in their docker entrypoint to help with that https://github.com/sigp/lighthouse-docker/blob/master/scripts/start-validator-client.sh
