### ISSUE TITLE
Error proposing block - REGEN_ERROR_SLOT_BEFORE_BLOCK_SLOT

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2731]
**Describe the bug**

Got this error at validator side
```
Jun-22 14:21:20.170 []                error: Error proposing block slot=147201, validator=0xb0c4…20e0 message=Failed to produce block - Internal Server Error: REGEN_ERROR_SLOT_BEFORE_BLOCK_SLOT
Error: Failed to produce block - Internal Server Error: REGEN_ERROR_SLOT_BEFORE_BLOCK_SLOT
    at HttpClient.request (/usr/app/packages/api/src/client/utils/httpClient.ts:85:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HttpClient.json (/usr/app/packages/api/src/client/utils/httpClient.ts:57:12)
    at Object.request [as produceBlock] (/usr/app/packages/api/src/client/utils/client.ts:71:19)
    at BlockProposingService.createAndPublishBlock (/usr/app/packages/validator/src/services/block.ts:65:21)
    at async Promise.all (index 0)
```
at node side
```
Jun-22 14:21:20.162 [API]             error: Req req-3eua produceBlock error message=REGEN_ERROR_SLOT_BEFORE_BLOCK_SLOT
Error: REGEN_ERROR_SLOT_BEFORE_BLOCK_SLOT
    at StateRegenerator.getBlockSlotState (/usr/app/packages/lodestar/src/chain/regen/regen.ts:99:13)
    at Object.job (/usr/app/packages/lodestar/src/chain/regen/queued.ts:95:66)
    at JobQueue.runJob (/usr/app/packages/lodestar/src/util/queue/index.ts:106:32)
    at Timeout._onTimeout (/usr/app/packages/lodestar/src/util/queue/index.ts:123:15)
```

**Expected behavior**

We should be able to produce a block

**Comment by twoeths** [comment]
same issue when producing attestation data:
```
Jun-23 00:55:20.124 [API]             error: Req req-45n6 produceAttestationData error message=REGEN_ERROR_SLOT_BEFORE_BLOCK_SLOT
Error: REGEN_ERROR_SLOT_BEFORE_BLOCK_SLOT
    at StateRegenerator.getBlockSlotState (/usr/app/packages/lodestar/src/chain/regen/regen.ts:99:13)
    at Object.job (/usr/app/packages/lodestar/src/chain/regen/queued.ts:95:66)
    at JobQueue.runJob (/usr/app/packages/lodestar/src/util/queue/index.ts:106:32)
    at Timeout._onTimeout (/usr/app/packages/lodestar/src/util/queue/index.ts:123:15)

```

**Comment by twoeths** [comment]
one validator tried to produce block 2 times, and the 2nd attempt failed.

+ 1st attempt
```
Jun-22 14:21:08.017 []                ^[[34mdebug^[[39m: Producing block slot=147201, validator=0xb0c4…20e0
Jun-22 14:21:08.240 []                ^[[34mdebug^[[39m: Downloaded proposer duties epoch=4600, dependentRoot=0xc239982cdbe60a8a810c8fcd5b683bf79423419307e13e0a64dd76620ab5632f, count=4
Jun-22 14:21:08.515 []                ^[[34mdebug^[[39m: Produced block slot=147201, validator=0xb0c4…20e0
Jun-22 14:21:08.561 []                 ^[[32minfo^[[39m: Published block slot=147201, validator=0xb0c4…20e0, graffiti=chainsafe/lodestar-0.24.3
```

+ 2nd attempt

```
Jun-22 14:21:20.002 []                ^[[34mdebug^[[39m: Producing block slot=147201, validator=0xb0c4…20e0
Jun-22 14:21:20.160 []                ^[[34mdebug^[[39m: Downloaded proposer duties epoch=4600, dependentRoot=0xc239982cdbe60a8a810c8fcd5b683bf79423419307e13e0a64dd76620ab5632f, count=4
Jun-22 14:21:20.170 []                ^[[31merror^[[39m: Error proposing block slot=147201, validator=0xb0c4…20e0 message=Failed to produce block - Internal Server Error: REGEN_ERROR_SLOT_BEFORE_BLOCK_SLOT
Error: Failed to produce block - Internal Server Error: REGEN_ERROR_SLOT_BEFORE_BLOCK_SLOT
    at HttpClient.request (/usr/app/packages/api/src/client/utils/httpClient.ts:85:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HttpClient.json (/usr/app/packages/api/src/client/utils/httpClient.ts:57:12)
    at Object.request [as produceBlock] (/usr/app/packages/api/src/client/utils/client.ts:71:19)
    at BlockProposingService.createAndPublishBlock (/usr/app/packages/validator/src/services/block.ts:65:21)
    at async Promise.all (index 0)
```

**Comment by twoeths** [comment]
this is an issue with the validator clock.

+ at node side

```
Jun-22 14:21:08.000 [CHAIN]         ^[[36mverbose^[[39m: Clock slot slot=147201
Jun-22 14:21:20.000 [CHAIN]         ^[[36mverbose^[[39m: Clock slot slot=147202
```

+ but at validator side

```
Jun-22 14:21:08.017 []                ^[[34mdebug^[[39m: Producing block slot=147201, validator=0xb0c4…20e0
Jun-22 14:21:20.002 []                ^[[34mdebug^[[39m: Producing block slot=147201, validator=0xb0c4…20e0
```
