### ISSUE TITLE
Error producing block - Block is not newer than latest block

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2734]
**Describe the bug**

Got this while running oonoonba:
```
Jun-23 00:51:32.175 [API]             error: Req req-45hq produceBlock error message=Block is not newer than latest block headerblockSlot=150352 latestBlockHeader.slot=150352
Error: Block is not newer than latest block headerblockSlot=150352 latestBlockHeader.slot=150352
    at processBlockHeader (/usr/app/packages/beacon-state-transition/src/allForks/block/processBlockHeader.ts:13:11)
    at Object.processBlock [as altair] (/usr/app/packages/beacon-state-transition/src/altair/block/index.ts:28:3)
    at Object.processBlock (/usr/app/packages/beacon-state-transition/src/allForks/stateTransition.ts:92:5)
    at computeNewStateRoot (/usr/app/packages/lodestar/src/chain/factory/block/index.ts:59:12)
    at assembleBlock (/usr/app/packages/lodestar/src/chain/factory/block/index.ts:42:21)
    at Object.produceBlock (/usr/app/packages/lodestar/src/api/impl/validator/index.ts:144:21)
    at Object.handler (/usr/app/packages/api/src/server/utils/server.ts:70:23)
```

**Expected behavior**

No error.

**Comment by twoeths** [comment]
looks like this is due to the validator clock issue which is fixed in #2731, will reopen if it's a separate issue
