### ISSUE TITLE
Error producing attestation data - REGEN_ERROR_SLOT_BEFORE_BLOCK_SLOT

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2735]
**Describe the bug**

Got this while running oonoonba:
```
Jun-23 00:55:20.124 [API]             error: Req req-45n6 produceAttestationData error message=REGEN_ERROR_SLOT_BEFORE_BLOCK_SLOT
Error: REGEN_ERROR_SLOT_BEFORE_BLOCK_SLOT
    at StateRegenerator.getBlockSlotState (/usr/app/packages/lodestar/src/chain/regen/regen.ts:99:13)
    at Object.job (/usr/app/packages/lodestar/src/chain/regen/queued.ts:95:66)
    at JobQueue.runJob (/usr/app/packages/lodestar/src/util/queue/index.ts:106:32)
    at Timeout._onTimeout (/usr/app/packages/lodestar/src/util/queue/index.ts:123:15)
```

**Expected behavior**

No error

**Comment by twoeths** [comment]
duplicate to #2731
