### ISSUE TITLE
Unable to archive states

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2740]
**Describe the bug**

In our Prater node 100,000 slots of sync progress were lost after a node restart.

![Screenshot from 2021-06-23 12-01-00](https://user-images.githubusercontent.com/35266934/123077947-cb4d2180-d41a-11eb-80c8-5afdbd5f5aa1.png)

**Expected behavior**

States should be persisted more regularly and just a few epochs would have to be re-processed

**Steps to Reproduce**

?

**Screenshots**

**Comment by dapplion** [comment]
It happened again. Seems that for two weeks the node hasn't persisted anything to disk

![Screenshot from 2021-06-30 12-24-17](https://user-images.githubusercontent.com/35266934/123945179-2abcab80-d99e-11eb-84f7-12ea8b4de197.png)

**Comment by dapplion** [comment]
Looking at the logs:
```
Jun-30 10:25:02.161 [CHORES]          error: Error processing finalized checkpoint epoch=17537 message=No block found for root 0x37487efdbfbeeb82d7d35c6eb96438c4576f645b0f4c0386184592abab4b1736
Error: No block found for root 0x37487efdbfbeeb82d7d35c6eb96438c4576f645b0f4c0386184592abab4b1736
    at /usr/app/packages/lodestar/src/tasks/tasks/archiveBlocks.ts:75:19
    at async Promise.all (index 183)
    at ArchiveBlocksTask.processCanonicalBlocks (/usr/app/packages/lodestar/src/tasks/tasks/archiveBlocks.ts:71:7)
    at ArchiveBlocksTask.run (/usr/app/packages/lodestar/src/tasks/tasks/archiveBlocks.ts:52:7)
    at TasksService.processFinalizedCheckpoint (/usr/app/packages/lodestar/src/tasks/index.ts:79:7)
    at Object.job (/usr/app/packages/lodestar/src/tasks/index.ts:74:43)
    at Timeout._onTimeout (/usr/app/packages/lodestar/src/util/queue/index.ts:106:22)

Jun-30 10:25:15.780 [CHORES]          error: Error processing finalized checkpoint epoch=17538 message=No block found for root 0x37487efdbfbeeb82d7d35c6eb96438c4576f645b0f4c0386184592abab4b1736
Error: No block found for root 0x37487efdbfbeeb82d7d35c6eb96438c4576f645b0f4c0386184592abab4b1736
    at /usr/app/packages/lodestar/src/tasks/tasks/archiveBlocks.ts:75:19
    at async Promise.all (index 214)
    at ArchiveBlocksTask.processCanonicalBlocks (/usr/app/packages/lodestar/src/tasks/tasks/archiveBlocks.ts:71:7)
    at ArchiveBlocksTask.run (/usr/app/packages/lodestar/src/tasks/tasks/archiveBlocks.ts:52:7)
    at TasksService.processFinalizedCheckpoint (/usr/app/packages/lodestar/src/tasks/index.ts:79:7)
    at Object.job (/usr/app/packages/lodestar/src/tasks/index.ts:74:43)
    at Timeout._onTimeout (/usr/app/packages/lodestar/src/util/queue/index.ts:106:22)

```

The block is complaining about is this one from 20 days ago. 
```
Slot: 560991
Time: Jun 9, 2021, 1:58 PM (20 days ago)
```
https://prater.beaconcha.in/block/37487efdbfbeeb82d7d35c6eb96438c4576f645b0f4c0386184592abab4b1736

It lines up well with the slot the node reverts to after crashing

**Comment by dapplion** [comment]
I synced the node to the head with a weak subjectivity state and it still was unable to archive

```
Jun-30 13:14:10.920 [CHORES]          error: Error processing finalized checkpoint epoch=22265 message=No block found for root 0x1654d3d939ac98216be951c65cfb497716ccfa236192b56c66886e1a43196a23
Error: No block found for root 0x1654d3d939ac98216be951c65cfb497716ccfa236192b56c66886e1a43196a23
    at /usr/app/packages/lodestar/src/tasks/tasks/archiveBlocks.ts:75:19
    at async Promise.all (index 29)
    at ArchiveBlocksTask.processCanonicalBlocks (/usr/app/packages/lodestar/src/tasks/tasks/archiveBlocks.ts:71:7)
    at ArchiveBlocksTask.run (/usr/app/packages/lodestar/src/tasks/tasks/archiveBlocks.ts:52:7)
    at TasksService.processFinalizedCheckpoint (/usr/app/packages/lodestar/src/tasks/index.ts:79:7)
    at Object.job (/usr/app/packages/lodestar/src/tasks/index.ts:74:43)
    at Timeout._onTimeout (/usr/app/packages/lodestar/src/util/queue/index.ts:106:22)
```

**Comment by twoeths** [comment]
When we start from a weak subjectivity checkpoint, we don't have the respective block in `block` db so the issue happens consistently.
I think we have same issue somewhere, but it does not always happen.

**Comment by twoeths** [comment]
## Explanation
So I traced the issue to the beginning of the log file in `contabo-5`, the `archiveBlock` task really failed from the beginning
```
Jun-30 09:02:02.660 []                 ^[[32minfo^[[39m: Initializing beacon state slot=549120, epoch=17160, stateRoot=0xb021a96da54dd89dfafc0e8817e23fe708f5746e924855f49b3f978133c3ac6a
```
```
7027 Jun-30 09:07:38.550 [CHORES]          ^[[31merror^[[39m: Error processing finalized checkpoint epoch=17161 message=No block found for root 0x85d7534b470b817c5b1a65e9eeec8dc712a1f11014232ebf01970444d75ddcf7
```
`0x85d7534b470b817c5b1a65e9eeec8dc712a1f11014232ebf01970444d75ddcf7` is the root of block slot 549120

once we fail to process a run, it keeps failing for all next run because some blocks are moved to`blockArchive` db but forkchoice still retain them.

## Root cause
Currently, we try to make `block` db to be synchronized to forkchoice and it works fine until we restart the node.

When we restart from an anchor state, if we have the finalized block in db then issue does not happen, otherwise the issue happens.

## Solution
Make `block` db to be synchronized to `stateArchived` db instead of the forkchoice. Although forkchoice contains the old finalized block, ArchiveBlock should not process it, it should process that in the previous run.

When we restart, ArchiveBlock should not work on the finalized block of the anchor state since that block is finalized already.
