### ISSUE TITLE
Randomly failing tests

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2773]
**Describe the bug**

Compile randomly failing tests in CI

https://github.com/ChainSafe/lodestar/pull/2772/checks?check_run_id=2940611026
```
@chainsafe/lodestar-api:   1) debug
@chainsafe/lodestar-api:        get SSZ response
@chainsafe/lodestar-api:          getState:
@chainsafe/lodestar-api:      Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/lodestar/lodestar/packages/api/test/unit/debug.test.ts)
@chainsafe/lodestar-api:       at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Expected behavior**

Don't fail

**Comment by dapplion** [comment]
Happened again

https://github.com/ChainSafe/lodestar/runs/2997682414

```
@chainsafe/lodestar-api:   1) debug
@chainsafe/lodestar-api:        get SSZ response
@chainsafe/lodestar-api:          getState:
@chainsafe/lodestar-api:      Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/lodestar/lodestar/packages/api/test/unit/debug.test.ts)
@chainsafe/lodestar-api:       at processTicksAndRejections (internal/process/task_queues.js:93:5)
@chainsafe/lodestar-api: 
@chainsafe/lodestar-api: error Command failed with exit code 1.
@chainsafe/lodestar-api: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@chainsafe/lodestar-fork-choice: $ mocha --colors -r ts-node/register 'test/unit/**/*.test.ts'
```

**Comment by dapplion** [comment]
Should be fixed now
