### ISSUE TITLE
Reduce verbosity in vc when Node is syncing

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2790]
Along those lines, changing Lodestar so it does not worry the user with error messages while consensus client is still syncing would be excellent.

```
consensus_1             | Jul-02 08:55:08.118 [API]             error: Req req-3 getProposerDuties error message=Node is syncing, headSlot 7040 currentSlot 726875
consensus_1             | Error: Node is syncing, headSlot 7040 currentSlot 726875
consensus_1             |     at notWhileSyncing (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:124:17)
consensus_1             |     at Object.getProposerDuties (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:182:7)
consensus_1             |     at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:70:29)
consensus_1             |     at preHandlerCallback (/usr/app/node_modules/fastify/lib/handleRequest.js:124:28)
consensus_1             |     at preValidationCallback (/usr/app/node_modules/fastify/lib/handleRequest.js:107:5)
consensus_1             |     at handler (/usr/app/node_modules/fastify/lib/handleRequest.js:70:7)
consensus_1             |     at handleRequest (/usr/app/node_modules/fastify/lib/handleRequest.js:18:5)
consensus_1             |     at runPreParsing (/usr/app/node_modules/fastify/lib/route.js:422:5)
consensus_1             |     at next (/usr/app/node_modules/fastify/lib/hooks.js:158:7)
consensus_1             |     at handleResolve (/usr/app/node_modules/fastify/lib/hooks.js:175:5)
```

_Originally posted by @yorickdowne in https://github.com/ChainSafe/lodestar/issues/1492#issuecomment-872977281_

**Comment by yorickdowne** [comment]
To be clear, these error messages are from the consensus client (beacon), not the validator client.

The validator client shows similar error messages. Reducing verbosity in both would be awesome.

From the vc:

```
validator_1             | Jul-02 12:04:13.148 []                error: Error on pollBeaconProposers message=Error on getProposerDuties - Service Unavailable: Node is syncing, headSlot 52544 currentSlot 727821
validator_1             | Error: Error on getProposerDuties - Service Unavailable: Node is syncing, headSlot 52544 currentSlot 727821
validator_1             |     at HttpClient.request (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:85:15)
validator_1             |     at runMicrotasks (<anonymous>)
validator_1             |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
validator_1             |     at HttpClient.json (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:57:12)
validator_1             |     at Object.request [as getProposerDuties] (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/client.ts:71:19)
validator_1             |     at BlockDutiesService.pollBeaconProposers (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/blockDuties.ts:141:28)
validator_1             |     at BlockDutiesService.pollBeaconProposersAndNotify (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/blockDuties.ts:115:5)
validator_1             |     at /usr/app/node_modules/@chainsafe/lodestar-validator/src/services/blockDuties.ts:74:7
validator_1             |     at Clock.runAtMostEvery (/usr/app/node_modules/@chainsafe/lodestar-validator/src/util/clock.ts:68:7)
```

**Comment by twoeths** [comment]
an example response from https://ethereum.github.io/eth2.0-APIs/#/Validator/produceBlockV2
```
{
  "code": 503,
  "message": "Beacon node is currently syncing and not serving request on that endpoint"
}
```
