### ISSUE TITLE
Error publishing SyncCommitteeContribution SYNC_COMMITTEE_INVALID_SIGNATURE

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2799]
**Describe the bug**

Got this when running a validator on `yeerongpilly` network
```
Jul-05 08:42:32.081 []                error: Error publishing SyncCommitteeContribution slot=130412, index=1 message=Internal Server Error: Multiple errors on publishContributionAndProofs
SYNC_COMMITTEE_INVALID_SIGNATURE
SYNC_COMMITTEE_INVALID_SIGNATURE
Error: Internal Server Error: Multiple errors on publishContributionAndProofs
SYNC_COMMITTEE_INVALID_SIGNATURE
SYNC_COMMITTEE_INVALID_SIGNATURE
    at HttpClient.request (/usr/app/packages/api/src/client/utils/httpClient.ts:85:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HttpClient.json (/usr/app/packages/api/src/client/utils/httpClient.ts:57:12)
    at Object.request [as publishContributionAndProofs] (/usr/app/packages/api/src/client/utils/client.ts:71:19)
    at SyncCommitteeService.produceAndPublishAggregates (/usr/app/packages/validator/src/services/syncCommittee.ts:173:9)
    at /usr/app/packages/validator/src/services/syncCommittee.ts:65:11
    at async Promise.all (index 3)
    at /usr/app/packages/validator/src/services/syncCommittee.ts:60:7
    at Clock.runAtMostEvery (/usr/app/packages/validator/src/util/clock.ts:68:7)
```

Other messages are fine
```
Jul-05 08:50:56.143 []                 info: Published aggregateAndProofs slot=130454, index=0, count=2
Jul-05 08:51:04.280 []                 info: Published attestations slot=130455, index=0, count=9
Jul-05 08:51:04.697 []                 info: Published SyncCommitteeMessage slot=130455, count=87
```

this did not happen with `oonoonba` network

**Expected behavior**

No error

**Comment by twoeths** [comment]
not able to reproduce with #2798 as SyncCommitteeContribution is working fine with that branch/PR

```
Jul-06 03:31:08.056 []                 info: Published SyncCommitteeContribution slot=136055, index=2, count=2
Jul-06 03:31:08.057 []                 info: Published SyncCommitteeContribution slot=136055, index=1, count=1
```

**Comment by twoeths** [comment]
not able to reproduce after we merge #2803
