### ISSUE TITLE
Yeerongpilly: error publishing AggregateAndProofs

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2805]
**Describe the bug**

Got this while running yeerongpilly

```
Jul-06 03:32:56.047 [API]             error: Error on publishAggregateAndProofs [0] slot=136064, index=0 code=ATTESTATION_ERROR_AGGREGATOR_NOT_IN_COMMITTEE
Error: ATTESTATION_ERROR_AGGREGATOR_NOT_IN_COMMITTEE
    at validateGossipAggregateAndProof (/usr/app/packages/lodestar/src/chain/validation/aggregateAndProof.ts:88:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /usr/app/packages/lodestar/src/api/impl/validator/index.ts:323:32
    at async Promise.all (index 0)
    at Object.publishAggregateAndProofs (/usr/app/packages/lodestar/src/api/impl/validator/index.ts:319:7)
    at Object.handler (/usr/app/packages/api/src/server/utils/server.ts:70:23)
```

I notice that it works most of the time
```
Jul-06 03:41:20.075 []                 info: Published aggregateAndProofs slot=136106, index=0, count=2
```

**Expected behavior**

No error

**Comment by dapplion** [comment]
Should we validate the full aggregateAndProof object in the API, or just check the signature?

**Comment by dapplion** [comment]
Fixed, cause = https://github.com/ChainSafe/lodestar/issues/3063#issuecomment-911906811
