### ISSUE TITLE
Yeerongpilly: error proposing block ERR_INVALID_BLOCK_SLOT_LESS_THAN_LOWER_BOUND

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2806]
**Describe the bug**

Got this error at validator side while running yeerongpilly:
```
Jul-06 03:31:24.268 []                error: Error proposing block slot=136057, validator=0xa757…81c9 code=ERR_INVALID_BLOCK_SLOT_LESS_THAN_LOWER_BOUND, slot=136057, minSlot=148047
Error: ERR_INVALID_BLOCK_SLOT_LESS_THAN_LOWER_BOUND
    at SlashingProtectionBlockService.checkBlockProposal (/usr/app/packages/validator/src/slashingProtection/block/service.ts:56:13)
    at SlashingProtectionBlockService.checkAndInsertBlockProposal (/usr/app/packages/validator/src/slashingProtection/block/service.ts:23:24)
    at SlashingProtection.checkAndInsertBlockProposal (/usr/app/packages/validator/src/slashingProtection/index.ts:50:5)
    at ValidatorStore.signBlock (/usr/app/packages/validator/src/services/validatorStore.ts:84:5)
    at BlockProposingService.createAndPublishBlock (/usr/app/packages/validator/src/services/block.ts:70:27)
    at async Promise.all (index 0)
```

**Expected behavior**

No error

**Comment by twoeths** [comment]
`minSlot` is incorrect as clock slot is 136xxx at the time of error

**Comment by twoeths** [comment]
seems like it's because of the shared validator db used for oonoonba, cleaned up and it worked fine
```
Jul-06 06:25:37.927 []                 info: Published block slot=136928, validator=0x848d…2703, graffiti=chainsafe/lodestar-0.25.1
```
