### ISSUE TITLE
Yeerongpilly: error signing attestation - ERR_INVALID_ATTESTATION_DOUBLE_VOTE

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2807]
**Describe the bug**

Got this at validator side while running yeerongpilly

```
Jul-06 03:34:40.160 []                error: Error signing attestation slot=136073, index=0, validator=0xa4b5…9025 code=ERR_INVALID_ATTESTATION_DOUBLE_VOTE, att={"sourceEpoch":4252,"targetEpoch":4252,"signingRoot":"0x31bbcc70a03cf24c3b72c71bae9be78f3465e4c1ca921ec288fb0b20dc2c8dc6"}, prev={"sourceEpoch":4252,"targetEpoch":4252,"signingRoot":"0xf4e3bc7fa5504b7a63d10068cd7d27250e576bcf6cdde71fc8b694a79e7d3dac"}
Error: ERR_INVALID_ATTESTATION_DOUBLE_VOTE
    at SlashingProtectionAttestationService.checkAttestation (/usr/app/packages/validator/src/slashingProtection/attestation/service.ts:60:15)
    at SlashingProtectionAttestationService.checkAndInsertAttestation (/usr/app/packages/validator/src/slashingProtection/attestation/service.ts:33:24)
    at SlashingProtection.checkAndInsertAttestation (/usr/app/packages/validator/src/slashingProtection/index.ts:54:5)
    at ValidatorStore.signAttestation (/usr/app/packages/validator/src/services/validatorStore.ts:118:5)
    at AttestationService.produceAndPublishAttestations (/usr/app/packages/validator/src/services/attestation.ts:99:33)
    at AttestationService.publishAttestationsAndAggregates (/usr/app/packages/validator/src/services/attestation.ts:59:25)
    at /usr/app/packages/validator/src/services/attestation.ts:45:9
    at async Promise.all (index 0)
    at /usr/app/packages/validator/src/services/attestation.ts:42:5
    at Clock.runAtMostEvery (/usr/app/packages/validator/src/util/clock.ts:68:7)
```

This does not always happen, a lot of times it's a success

```
Jul-06 03:34:40.276 []                 info: Published attestations slot=136073, index=0, count=13
Jul-06 03:34:44.096 []                 info: Published aggregateAndProofs slot=136073, index=0, count=4
```

**Expected behavior**

No error

**Comment by twoeths** [comment]
seems like it's because of the shared validator db used for oonoonba, cleaned up and it worked fine
```
Jul-06 06:28:38.547 []                 info: Published attestations slot=136942, index=0, count=13
Jul-06 06:28:38.619 []                 info: Published aggregateAndProofs slot=136942, index=0, count=5
```
