### ISSUE TITLE
OP_POOL_ERROR_SLOT_TOO_LOW error

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2826]
**Describe the bug**

On a prater node with full attestation subnet subscriptions, this error happens repeatedly:

```
Jul-09 17:58:46.696 []                error: Error adding attestation to pool subnet=46 code=OP_POOL_ERROR_SLOT_TOO_LOW, slot=776681, lowestPermissibleSlot=776690
Error: OP_POOL_ERROR_SLOT_TOO_LOW
    at AttestationPool.add (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/opPools/attestationPool.ts:86:13)
    at beacon_attestation (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/network/gossip/handlers/index.ts:119:31)
    at /Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/network/gossip/validation/index.ts:83:7
    at JobQueue.runJob (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/util/queue/index.ts:106:22)
```

**Expected behavior**

Investigate if we have any performance issue there that make the attestation comes to the pool so late

**Comment by dapplion** [comment]
The pool is more restrictive than gossip validation. For attestations it only accepts 3 slots old. Maybe we should just ignore this error in the handler caller

https://github.com/ChainSafe/lodestar/blob/a75ef9b0c28cce5a58cc243b6ee10010b15fcce8/packages/lodestar/src/chain/opPools/attestationPool.ts#L15

**Comment by twoeths** [comment]
with the latest master, we ignored this error. Closing the issue.
