### ISSUE TITLE
altair-devnet-2 issues

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2905]
Compilation of issues during altair-devnet-2

**Comment by dapplion** [comment]
Block at slot 337 was missed, but our validator did propose it

```
validator3_1   | Jul-29 13:07:24.092 []                 info: Published block slot=337, validator=0x8b75…4060, graffiti=chainsafe/lodestar-0.27.1-dev.26
```

Missed block from explorer https://altair-devnet-2-explorer.ethdevops.io/block/337

The beacon_node acknowledged the block and inserted it as head
```
Jul-29 13:07:24.092 [API]             debug: Res req-6p3 publishBlock - 200
Jul-29 13:07:24.135 [CHAIN]         verbose: New chain head headSlot=337, headRoot=0x9830ba2d7e0a16a14b27f5e7ad61caeffe4c09ff7be93b2d8271d174cb75ec08
```

Latter we processed the next block (which orphans us, and eventually became the head)

```
Jul-29 13:07:36.143 [NETWORK]       verbose: Received gossip block slot=338, root=0x4729…de1b
Jul-29 13:07:36.152 [NETWORK]         debug: gossip - beacon_block - accept slot=338, root=0x4729de2600d1568295bf659934a85ff6067076882c85a855cefa32a01edade1b
Jul-29 13:07:36.203 [CHAIN]         verbose: Block processed slot=338, root=0x4729de2600d1568295bf659934a85ff6067076882c85a855cefa32a01edade1b
```

We eventually re-org at block 340

```
Jul-29 13:08:00.144 [NETWORK]         debug: gossip - beacon_block - accept slot=340, root=0xc1e86c51c1b4cf27714623482f0d73f3e8703f7c7ba1485e712b6a2e9b736bb3
Jul-29 13:08:00.184 [CHAIN]         verbose: Block processed slot=340, root=0xc1e86c51c1b4cf27714623482f0d73f3e8703f7c7ba1485e712b6a2e9b736bb3
Jul-29 13:08:00.191 [CHAIN]         verbose: Chain reorg depth=0
Jul-29 13:08:00.191 [CHAIN]         verbose: New chain head headSlot=340, headRoot=0xc1e86c51c1b4cf27714623482f0d73f3e8703f7c7ba1485e712b6a2e9b736bb3
```

**Comment by twoeths** [comment]
Lodestar included attestations for a missed block https://altair-devnet-2-explorer.ethdevops.io/block/407#attestations (391 is a missed block)

**Edit**: tracked in #2909

**Comment by twoeths** [comment]
From Teku

At the same time I got the following invalid signed aggregate and proof (which I think comes from a lodestar validator): 
```
0x64000000b80c5d8233733f9684fef1edee56603df7cf4700d13e9532c338fac1fcbe2886209c94490e09082430a94d0bdaf04ad11827be97358d114dece6b81c298ff427294d64d7efab8b19eaacb6a77916931770aaed3eeafa4d6b93573c271e4377e86e290000000000006c00000093a901006eaf8c2e5d8ea94939d631247984180c4faad3e3646ca112c467e419a2f7308fc5abc79ba99a07999362b1c30ec28bccbfd7bd0a60f58a2fab272edb0256309219eff2493e7ea52b7d73ce2dc0bbac27120d7997d9a6944e3a1e4255e40000004001000000000000020000000000000039998ed61f601fed3e21059e7f99dfc31a5ee8ecb34e22e2790f09095397997d0900000000000000b523c2bc822f304369018e505920e3f5451b0616fb2b6750eaeb5273f76f72050a0000000000000039998ed61f601fed3e21059e7f99dfc31a5ee8ecb34e22e2790f09095397997db945ebbf87891cd5c47df4c7110282948b129bb56fb73d570ce3c05cad7db58592f477669996d086e73d73ebf7c850c10828071f3b54a7e24a9868072197df6bd90c59fa0322b718d055044ed4d91cff5756f328430e70dca1d6824bb4df5f2730000122c07600a040604000420000700001
```
Teku rejected it for a bad signature.

Tracked in #2908

------

**Update: ignore the below**

From Proto:

That decodes too:
```
{
    "sync_committee_bits": "0x64000000b80c5d8233733f9684fef1edee56603df7cf4700d13e9532c338fac1fcbe2886209c94490e09082430a94d0bdaf04ad11827be97358d114dece6b81c",
    "sync_committee_signature": "0x298ff427294d64d7efab8b19eaacb6a77916931770aaed3eeafa4d6b93573c271e4377e86e290000000000006c00000093a901006eaf8c2e5d8ea94939d631247984180c4faad3e3646ca112c467e419a2f7308fc5abc79ba99a07999362b1c3"
  }
```
That 64000000 is very suspicious: it's the first 4 bytes, like a SSZ offset. But the fields are all fixed-size (bitvector for sync committee bits, not bitlist). Also, 0x64 = 100 = 4 + 96 (matches offset size + signature size). So either Lodestar or Teku (or whomever encoded that message) has implemented the SyncAggregate wrong and isn't running the new SSZ tests

**Comment by dapplion** [comment]
Review this `ATTESTATION_ERROR_FUTURE_SLOT` errors. Is our clock logic right? We seem to reject some, accept some.

```
Jul-29 13:07:36.426 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.426 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.431 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.434 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.438 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.446 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.446 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.451 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.455 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.458 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.458 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.464 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.466 [NETWORK]         debug: gossip - sync_committee - accept slot=337, subnet=3
Jul-29 13:07:36.468 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.477 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.488 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.492 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.499 [NETWORK]         debug: gossip - beacon_attestation - ignore code=ATTESTATION_ERROR_FUTURE_SLOT, latestPermissibleSlot=337, attestationSlot=338
Jul-29 13:07:36.584 [NETWORK]         debug: gossip - beacon_attestation - accept slot=338, subnet=56, index=2
Jul-29 13:07:36.584 [NETWORK]         debug: gossip - beacon_attestation - accept slot=338, subnet=54, index=0
Jul-29 13:07:36.585 [NETWORK]         debug: gossip - beacon_attestation - accept slot=338, subnet=56, index=2
Jul-29 13:07:36.585 [NETWORK]         debug: gossip - beacon_attestation - accept slot=338, subnet=56, index=2
Jul-29 13:07:36.585 [NETWORK]         debug: gossip - beacon_attestation - accept slot=338, subnet=56, index=2
Jul-29 13:07:36.585 [NETWORK]         debug: gossip - beacon_attestation - accept slot=338, subnet=56, index=2
Jul-29 13:07:36.585 [NETWORK]         debug: gossip - beacon_attestation - accept slot=338, subnet=56, index=2
Jul-29 13:07:36.585 [NETWORK]         debug: gossip - beacon_attestation - accept slot=338, subnet=55, index=1
```

**Comment by twoeths** [comment]
Found this in validator log
```
Jul-29 13:36:08.038 []                error: Error publishing aggregateAndProofs slot=480, index=1 message=Internal Server Error: ATTESTATION_ERROR_AGGREGATOR_NOT_IN_COMMITTEE
Error: Internal Server Error: ATTESTATION_ERROR_AGGREGATOR_NOT_IN_COMMITTEE
    at HttpClient.request (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:85:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at HttpClient.json (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:57:12)
    at Object.request [as publishAggregateAndProofs] (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/client.ts:71:19)
    at AttestationService.produceAndPublishAggregates (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:167:9)
    at AttestationService.publishAttestationsAndAggregates (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:66:5)
    at /usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:43:9
    at async Promise.all (index 1)
    at /usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:40:5
```

=> maybe related to https://github.com/ChainSafe/lodestar/issues/3063

**Comment by twoeths** [comment]
Is this a configuration error?
```
Jul-29 13:36:52.032 []                error: Error signing attestation slot=484, index=2, head=0x93ca…b07d, validator=0xaa1d…8b89 code=ERR_INVALID_ATTESTATION_DOUBLE_VOTE, attestation={"sourceEpoch":14,"targetEpoch":15,"signingRoot":"0xa8ae45ee7343e0463fe6de0c7471c1a462709e9bce565c2f3e7e05668437abbf"}, prev={"sourceEpoch":14,"targetEpoch":15,"signingRoot":"0x4be16167539baf4f3b2c0df064fd351f464ebb32eafc7be64b3222df0df905c1"}
Error: ERR_INVALID_ATTESTATION_DOUBLE_VOTE
    at SlashingProtectionAttestationService.checkAttestation (/usr/app/node_modules/@chainsafe/lodestar-validator/src/slashingProtection/attestation/index.ts:67:15)
    at SlashingProtectionAttestationService.checkAndInsertAttestation (/usr/app/node_modules/@chainsafe/lodestar-validator/src/slashingProtection/attestation/index.ts:40:24)
    at SlashingProtection.checkAndInsertAttestation (/usr/app/node_modules/@chainsafe/lodestar-validator/src/slashingProtection/index.ts:55:5)
    at ValidatorStore.signAttestation (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/validatorStore.ts:106:5)
    at AttestationService.produceAndPublishAttestations (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:101:33)
    at AttestationService.publishAttestationsAndAggregates (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:57:25)
    at /usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:43:9
    at async Promise.all (index 2)
    at /usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:40:5
    at Clock.runAtMostEvery (/usr/app/node_modules/@chainsafe/lodestar-validator/src/util/clock.ts:71:7)
```

=> maybe due to same root cause to https://github.com/ChainSafe/lodestar/issues/3063

**Comment by twoeths** [comment]
Error submitting attestations to pool
```
Jul-29 13:36:05.551 [API]             error: Error on submitPoolAttestations [1] slot=480, index=0 code=ATTESTATION_ERROR_INVALID_SIGNATURE
Error: ATTESTATION_ERROR_INVALID_SIGNATURE
    at validateGossipAttestation (/usr/app/node_modules/@chainsafe/lodestar/src/chain/validation/attestation.ts:143:11)
    at /usr/app/node_modules/@chainsafe/lodestar/src/api/impl/beacon/pool/index.ts:52:50
    at async Promise.all (index 1)
    at Object.submitPoolAttestations (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/beacon/pool/index.ts:49:7)
    at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:70:23)
```

=> closed via https://github.com/ChainSafe/lodestar/issues/3063

**Comment by dapplion** [comment]
TODO:
- Persist invalid objects to disk for latter debugging (behind a flag). Help us debug this testnets better, also CI
- Investigate ERR_INVALID_ATTESTATION_DOUBLE_VOTE errors, and what can we do to debug them once they happen.

**Comment by dapplion** [comment]
All items are either resolved or tracked in other issues :+1:
