### ISSUE TITLE
Invalid attestations included in blocks

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2909]
**Describe the bug**

Lodestar blocks include attestations voted for orphaned head, for example https://altair-devnet-2-explorer.ethdevops.io/block/351#attestations and https://altair-devnet-2-explorer.ethdevops.io/block/407#attestations

**Expected behavior**

We should only include attestations with correct source, target and head.

**Steps to Reproduce**

Join `altair-devnet-2`

**Comment by dapplion** [comment]
:+1: Time to add those attestations checks on inclusion

**Comment by twoeths** [comment]
we don't have to validate attestation head and target but source, this is already an issue that caused us having a missed slot at 35500
```
Aug-03 10:20:00.089 []                ^[[31merror^[[39m: Error proposing block slot=35500, validator=0x8a7e…91ea message=Failed to produce block - Internal Server Error: Attestation source does not equal justified checkpoint: source={"epoch":"1107","root":"0x21ce5deed38b1965e59180f75fe414f85eaaf203e1e10e0b67699a3bca7eb158"} justifiedCheckpoint={"epoch":"1108","root":"0x822fe00309a976bf69cfd4fb6289c8f45f0e6912534b2c10d4c0f80406a18b4f"}
Error: Failed to produce block - Internal Server Error: Attestation source does not equal justified checkpoint: source={"epoch":"1107","root":"0x21ce5deed38b1965e59180f75fe414f85eaaf203e1e10e0b67699a3bca7eb158"} justifiedCheckpoint={"epoch":"1108","root":"0x822fe00309a976bf69cfd4fb6289c8f45f0e6912534b2c10d4c0f80406a18b4f"}
    at HttpClient.request (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:85:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at HttpClient.json (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:57:12)
    at Object.request [as produceBlock] (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/client.ts:71:19)
    at BlockProposingService.createAndPublishBlock (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/block.ts:55:21)
    at async Promise.all (index 0)
```

**Comment by twoeths** [comment]
same issues for a couple of blocks:
```
validator1-2021-08-03.log:62648:Aug-03 10:18:24.146 []                error: Error proposing block slot=35492, validator=0xa2fa…6f93 message=Failed to produce block - Internal Server Error: Attestation source does not equal justified checkpoint: source={"epoch":"1107","root":"0x21ce5deed38b1965e59180f75fe414f85eaaf203e1e10e0b67699a3bca7eb158"} justifiedCheckpoint={"epoch":"1108","root":"0x822fe00309a976bf69cfd4fb6289c8f45f0e6912534b2c10d4c0f80406a18b4f"}
validator2-2021-08-03.log:41871:Aug-03 10:21:12.155 []                error: Error proposing block slot=35506, validator=0xad45…c002 message=Failed to produce block - Internal Server Error: Attestation source does not equal justified checkpoint: source={"epoch":"1107","root":"0x21ce5deed38b1965e59180f75fe414f85eaaf203e1e10e0b67699a3bca7eb158"} justifiedCheckpoint={"epoch":"1108","root":"0x822fe00309a976bf69cfd4fb6289c8f45f0e6912534b2c10d4c0f80406a18b4f"}
validator3-2021-08-03.log:58292:Aug-03 10:23:12.115 []                error: Error proposing block slot=35516, validator=0x8859…feb5 message=Failed to produce block - Internal Server Error: Attestation source does not equal justified checkpoint: source={"epoch":"1107","root":"0x21ce5deed38b1965e59180f75fe414f85eaaf203e1e10e0b67699a3bca7eb158"} justifiedCheckpoint={"epoch":"1108","root":"0x822fe00309a976bf69cfd4fb6289c8f45f0e6912534b2c10d4c0f80406a18b4f"}
validator4-2021-08-03.log:52744:Aug-03 10:20:00.089 []                error: Error proposing block slot=35500, validator=0x8a7e…91ea message=Failed to produce block - Internal Server Error: Attestation source does not equal justified checkpoint: source={"epoch":"1107","root":"0x21ce5deed38b1965e59180f75fe414f85eaaf203e1e10e0b67699a3bca7eb158"} justifiedCheckpoint={"epoch":"1108","root":"0x822fe00309a976bf69cfd4fb6289c8f45f0e6912534b2c10d4c0f80406a18b4f"}
validator4-2021-08-03.log:52945:Aug-03 10:22:12.101 []                error: Error proposing block slot=35511, validator=0x941e…dab9 message=Failed to produce block - Internal Server Error: Attestation source does not equal justified checkpoint: source={"epoch":"1107","root":"0x21ce5deed38b1965e59180f75fe414f85eaaf203e1e10e0b67699a3bca7eb158"} justifiedCheckpoint={"epoch":"1108","root":"0x822fe00309a976bf69cfd4fb6289c8f45f0e6912534b2c10d4c0f80406a18b4f"}
```
