### ISSUE TITLE
altair-devnet-3: invalid signature attestation submitted by lodestar

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2951]
**Describe the bug**

Found this error in our node:
```
Aug-12 04:04:53.124 [API]             ^[[31merror^[[39m: Req req-33uk submitPoolAttestations error code=ATTESTATION_ERROR_INVALID_SIGNATURE
Error: ATTESTATION_ERROR_INVALID_SIGNATURE
    at Object.validateGossipAttestation (/usr/app/node_modules/@chainsafe/lodestar/lib/chain/validation/attestation.js:117:15)
    at /usr/app/node_modules/@chainsafe/lodestar/lib/api/impl/beacon/pool/index.js:36:60
    at async Promise.all (index 0)
    at Object.submitPoolAttestations (/usr/app/node_modules/@chainsafe/lodestar/lib/api/impl/beacon/pool/index.js:34:13)
    at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/lib/server/utils/server.js:20:31)
Aug-12 04:04:53.124 [API]             ^[[31merror^[[39m: Req req-33ul submitPoolAttestations error code=ATTESTATION_ERROR_INVALID_SIGNATURE
Error: ATTESTATION_ERROR_INVALID_SIGNATURE
    at Object.validateGossipAttestation (/usr/app/node_modules/@chainsafe/lodestar/lib/chain/validation/attestation.js:117:15)
    at /usr/app/node_modules/@chainsafe/lodestar/lib/api/impl/beacon/pool/index.js:36:60
    at async Promise.all (index 0)
    at Object.submitPoolAttestations (/usr/app/node_modules/@chainsafe/lodestar/lib/api/impl/beacon/pool/index.js:34:13)
    at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/lib/server/utils/server.js:20:31)
Aug-12 04:04:53.130 [API]             ^[[34mdebug^[[39m: Res req-33uk submitPoolAttestations - 500
```

**Expected behavior**

No error

**Comment by twoeths** [comment]
I have no idea how can this happen but #2955 may be one of the causes. If we have wrong active validator indices, we'll get wrong committee and the aggregated signature verification may be failed due to that.

The issue does not happen in the mean time though. Perhaps the only way we can do with this is to log out the whole attestation hash so that we can recreate its struct data when we investigate (this is what Teku does).

**Comment by dapplion** [comment]
Closing since it was likely to wrong duties
