### ISSUE TITLE
altair-devnet-3: Time out producing attestation

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2952]
**Describe the bug**

From validator log:
```
Aug-12 10:07:40.012 []                error: Error on attestations routine slot=6037, committeeIndex=0 message=Error producing attestation - Timeout request
Error: Error producing attestation - Timeout request
    at HttpClient.request (/usr/app/node_modules/@chainsafe/lodestar-api/lib/client/utils/httpClient.js:60:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at listOnTimeout (internal/timers.js:526:9)
    at processTimers (internal/timers.js:500:7)
    at HttpClient.json (/usr/app/node_modules/@chainsafe/lodestar-api/lib/client/utils/httpClient.js:28:16)
    at Object.request [as produceAttestationData] (/usr/app/node_modules/@chainsafe/lodestar-api/lib/client/utils/client.js:43:25)
    at AttestationService.produceAndPublishAttestations (/usr/app/node_modules/@chainsafe/lodestar-validator/lib/services/attestation.js:61:32)
    at AttestationService.publishAttestationsAndAggregates (/usr/app/node_modules/@chainsafe/lodestar-validator/lib/services/attestation.js:40:29)
```
Our node shows that it may takes up to 8s to produce attestations
<img width="841" alt="Screen Shot 2021-08-12 at 17 12 11" src="https://user-images.githubusercontent.com/10568965/129179851-5560c3f8-cb8f-4d93-89a2-6fa0c4924efc.png">

It looks like our node is very busy.

**Expected behavior**

No error

**Comment by dapplion** [comment]
We need a metric to track how "busy" our node is.

A potential approach would be to track async event loop lag:

```ts
setInterval(async () => {
  const startTime = Date.now();
  await sleep(0);
  const asyncEventLoopLag = Date.now() - startTime;
}, 1000)

```
