### ISSUE TITLE
Cannot read property 'map' of null

### ISSUE THREAD

**Issue by q9f** [ChainSafe/lodestar#2953]
**Describe the bug**

Similar to #2680 I guess.

`[ETH1]            error: Error updating eth1 chain cache message=Cannot read property 'map' of null`

**Expected behavior**

No.

**Steps to Reproduce**

```
NODE_OPTIONS="--max_old_space_size=8192" lodestar beacon \
  --metrics.enabled \
  --eth1.providerUrl https://goerli.infura.io/v3/**SNAP** \
  --rootDir /srv/chain/lodestar \
  --network "pyrmont"
```

**Screenshots**

```
Aug-12 12:01:13.000 []                 info: Syncing - ? left - 0.00 slots/s - finalized: 320 0x198f…7f39 - head: 10334 0x20b0…52cc - clockSlot: 1921805 - peers: 29
Aug-12 12:01:25.001 []                 info: Syncing - ? left - 0.00 slots/s - finalized: 320 0x198f…7f39 - head: 10334 0x20b0…52cc - clockSlot: 1921806 - peers: 27
Aug-12 12:01:26.242 [ETH1]            error: Error updating eth1 chain cache message=Cannot read property 'map' of null
TypeError: Cannot read property 'map' of null
    at Eth1Provider.getLogs (/home/user/lodestar/packages/lodestar/src/eth1/provider/eth1Provider.ts:159:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 1)
    at retry (/home/user/lodestar/packages/lodestar/src/util/retry.ts:33:14)
    at Eth1Provider.getDepositEvents (/home/user/lodestar/packages/lodestar/src/eth1/provider/eth1Provider.ts:67:24)
    at Eth1ForBlockProduction.updateDepositCache (/home/user/lodestar/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:164:27)
    at Eth1ForBlockProduction.update (/home/user/lodestar/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:150:31)
    at Eth1ForBlockProduction.runAutoUpdate (/home/user/lodestar/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:124:30)
Aug-12 12:01:35.693 [NETWORK]         error: Unexpected error in assertPeerRelevance peer=16...hM2vJH message=Cannot get block root from slot more than 8192 in the past: 10334 <= 10240
Error: Cannot get block root from slot more than 8192 in the past: 10334 <= 10240
    at Object.lte (/home/user/lodestar/packages/utils/src/assert.ts:31:13)
    at getBlockRootAtSlot (/home/user/lodestar/packages/beacon-state-transition/src/util/blockRoot.ts:18:10)
    at getRootAtHistoricalEpoch (/home/user/lodestar/packages/lodestar/src/network/peers/utils/assertPeerRelevance.ts:98:10)
    at assertPeerRelevance (/home/user/lodestar/packages/lodestar/src/network/peers/utils/assertPeerRelevance.ts:72:11)
    at PeerManager.onStatus (/home/user/lodestar/packages/lodestar/src/network/peers/peerManager.ts:236:7)
    at NetworkEventBus.<anonymous> (/home/user/lodestar/packages/lodestar/src/network/peers/peerManager.ts:185:23)
    at NetworkEventBus.emit (events.js:400:28)
    at NetworkEventBus.emit (domain.js:470:12)
    at Timeout._onTimeout (/home/user/lodestar/packages/lodestar/src/network/reqresp/reqResp.ts:245:43)
    at listOnTimeout (internal/timers.js:557:17)
```

**Desktop (please complete the following information):**

- OS: Archlinux `kernel 5.10.11-arch1-1 #1 SMP PREEMPT Wed, 27 Jan 2021 13:53:16 +0000 x86_64 GNU/Linux`
- Version: `v0.28.0`
- Branch: `master`
- Commit hash: 2c010b25
- Node: `nvm use lts/fermium` / `Now using node v14.17.4 (npm v7.20.5)`

**Comment by q9f** [comment]
Also that one: 

```
Aug-12 12:19:45.632 [ETH1]            error: Error updating eth1 chain cache message=Gateway Time-out: <html>                                                                                                                                                                                                                                                                                                                  [6/1896]
<head><title>504 Gateway Time-out</title></head>                                                         
<body>                                                                                                                                                                                                             
<center><h1>504 Gateway Time-out</h1></center>                                                                                                                                                                     
</body>                                                                                                                                                                                                            
</html>                                                                                                                                                                                                            
                                                                                                                                                                                                                   
Error: Gateway Time-out: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

    at JsonRpcHttpClient.fetchJsonOneUrl (/home/user/lodestar/packages/lodestar/lib/eth1/provider/jsonRpcHttpClient.js:105:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at JsonRpcHttpClient.fetchJson (/home/user/lodestar/packages/lodestar/lib/eth1/provider/jsonRpcHttpClient.js:53:24)
    at JsonRpcHttpClient.fetch (/home/user/lodestar/packages/lodestar/lib/eth1/provider/jsonRpcHttpClient.js:35:21)
    at Eth1Provider.getLogs (/home/user/lodestar/packages/lodestar/lib/eth1/provider/eth1Provider.js:96:25)
    at async Promise.all (index 0)
    at Object.retry (/home/user/lodestar/packages/lodestar/lib/util/retry.js:17:20)
```

🤣

**Comment by dapplion** [comment]
Thanks for reporting! Seems that our eth1 consumer doesn't do enough data validation.

The error `error: Error updating eth1 chain cache message=Cannot read property 'map' of null
TypeError: Cannot read property 'map' of null` seems to be caused by an response that does not follow the RPC format. We should add schema validation for all the fields that we expect to exist
