### ISSUE TITLE
altair-devnet-3: Invalid state root

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2960]
**Describe the bug**

Sync altair-devnet-3 and got:
```
Aug-14 12:29:02.562 [CHAIN]         ^[[36mverbose^[[39m: Checkpoint processed epoch=538, root=0x95acd717e8b9be1a497f270a4dc2d49c12c4c61a52a475476901fd9086664e8c
230398 Aug-14 12:29:02.563 [CHAIN]         ^[[36mverbose^[[39m: Checkpoint justified epoch=537, root=0x42b55ff5ce924376fc933b35a88d78928f1ed7b39937a81fcc3101260636e2f7
230399 Aug-14 12:29:02.563 [CHAIN]         ^[[36mverbose^[[39m: Checkpoint finalized epoch=536, root=0x9ddeb629a8666964902608a16ee11778bc0ce15d576986798755f42be5c6419b
230400 Aug-14 12:29:04.368 [SYNC]          ^[[36mverbose^[[39m: Batch process error id=Finalized, startEpoch=536, status=Processing code=BLOCK_ERROR_BEACON_CHAIN_ERROR, error={"mess       age":"Invalid state root"}
230401 Error: Invalid state root
230402     at Object.stateTransition (/root/lodestar/packages/beacon-state-transition/src/allForks/stateTransition.ts:66:13)
230403     at Object.runStateTransition (/root/lodestar/packages/lodestar/src/chain/blocks/stateTransition.ts:83:30)
230404     at processBlocksInEpoch (/root/lodestar/packages/lodestar/src/chain/blocks/process.ts:108:24)
230405     at runMicrotasks (<anonymous>)
230406     at runNextTicks (node:internal/process/task_queues:61:5)
230407     at processTimers (node:internal/timers:497:9)
230408     at Object.processChainSegment (/root/lodestar/packages/lodestar/src/chain/blocks/process.ts:77:7)
230409     at processChainSegmentJob (/root/lodestar/packages/lodestar/src/chain/blocks/processor.ts:151:3)
230410     at JobItemQueue.runJob (/root/lodestar/packages/lodestar/src/util/queue/itemQueue.ts:85:22)
230411 Error: BLOCK_ERROR_BEACON_CHAIN_ERROR
230412     at Object.processChainSegment (/root/lodestar/packages/lodestar/src/chain/blocks/process.ts:80:15)
230413     at runMicrotasks (<anonymous>)
230414     at runNextTicks (node:internal/process/task_queues:61:5)
230415     at processTimers (node:internal/timers:497:9)
230416     at processChainSegmentJob (/root/lodestar/packages/lodestar/src/chain/blocks/processor.ts:151:3)
230417     at JobItemQueue.runJob (/root/lodestar/packages/lodestar/src/util/queue/itemQueue.ts:85:22)
230418 Aug-14 12:29:04.369 [NETWORK]         ^[[34mdebug^[[39m: Req  dialing peer method=beacon_blocks_by_range, encoding=ssz_snappy, agentVersion=N/A, peer=16...jga78X, requestId=8       766
230419 Aug-14 12:29:04.366 [CHAIN]         ^[[36mverbose^[[39m: Checkpoint processed epoch=638, root=0x90286aa211b74d5ee2be12e87834bfa5885993bed463a38013f71f1ce4c9871a
```

**Expected behavior**

No error

**Comment by twoeths** [comment]
meanwhile the block explorer stops working at epoch 535
<img width="1517" alt="Screen Shot 2021-08-14 at 17 50 21" src="https://user-images.githubusercontent.com/10568965/129444033-74c34440-c761-4086-b745-75eb256a1097.png">

**Comment by twoeths** [comment]
not a lodestar issue, I was able to sync to head from genesis.
