### ISSUE TITLE
query returned more than 10000 results

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#2977]
**Describe the bug**

This issue is showing up again

```
Aug-19 12:16:27.578 [ETH1]            error: Error updating eth1 chain cache message=JSON RPC error: query returned more than 10000 results, method=eth_getLogs, params=[{"fromBlock":"0x392445","toBlock":"0x39253e","address":"0x8c5fecdc472e27bc447696f431e425d02dd46a8c","topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"]}]
Error: JSON RPC error: query returned more than 10000 results, method=eth_getLogs, params=[{"fromBlock":"0x392445","toBlock":"0x39253e","address":"0x8c5fecdc472e27bc447696f431e425d02dd46a8c","topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"]}]
    at parseRpcResponse (/usr/app/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:139:9)
    at JsonRpcHttpClient.fetch (/usr/app/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:53:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Eth1Provider.getLogs (/usr/app/packages/lodestar/src/eth1/provider/eth1Provider.ts:158:21)
    at async Promise.all (index 1)
    at Object.retry (/usr/app/packages/lodestar/src/util/retry.ts:33:14)
    at Eth1Provider.getDepositEvents (/usr/app/packages/lodestar/src/eth1/provider/eth1Provider.ts:67:24)
    at Eth1ForBlockProduction.updateDepositCache (/usr/app/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:164:27)
    at Eth1ForBlockProduction.update (/usr/app/packages/lodestar/src/eth1/eth1ForBlockProduction.ts:150:31)
```

Happens every slot

**Expected behavior**

No error level log

**Comment by q9f** [comment]
similar to #2680 #2953

**Comment by dapplion** [comment]
Lodestar should split failed requests into smaller request to prevent this issue from happening

https://github.com/ChainSafe/lodestar/blob/2ed2e03d0ca3e2d6e04e503d4e1beb2deedd47a7/packages/lodestar/src/eth1/provider/eth1Provider.ts#L75-L79
