### ISSUE TITLE
uncaughtException: cb is not a function

### ISSUE THREAD

**Issue by q9f** [ChainSafe/lodestar#2996]
**Describe the bug**

Mainnet sync throws:

```
Aug-23 12:48:21.949 []                error: uncaughtException: cb is not a function
TypeError: cb is not a function
```

It does continue to sync though.

**Expected behavior**

Handle that exception.

**Screenshots**

```
Aug-23 12:47:41.076 []                 info: Syncing - 15 hours left - 31.3 slots/s - head: 204255 0x5f5a…c92c - finalized: 204160 0x1356…5be6 (6380) - clockSlot: 1907636 - peers: 21
Aug-23 12:47:53.004 []                 info: Syncing - 15 hours left - 31.7 slots/s - head: 204680 0x277e…1cd0 - finalized: 204608 0x9706…d434 (6394) - clockSlot: 1907637 - peers: 21
Aug-23 12:48:05.000 []                 info: Syncing - 15 hours left - 30.6 slots/s - head: 205056 0x9599…f296 - finalized: 204992 0x799d…5871 (6406) - clockSlot: 1907638 - peers: 22
Aug-23 12:48:17.002 []                 info: Syncing - 17 hours left - 28.2 slots/s - head: 205056 0x9599…f296 - finalized: 204992 0x799d…5871 (6406) - clockSlot: 1907639 - peers: 21
Aug-23 12:48:21.949 []                error: uncaughtException: cb is not a function
TypeError: cb is not a function
    at /home/user/.opt/chainsafe/lodestar/node_modules/@motrix/nat-api/index.js:336:7
    at /home/user/.opt/chainsafe/lodestar/node_modules/@motrix/nat-api/lib/upnp/device.js:61:11
    at Parser.<anonymous> (/home/user/.opt/chainsafe/lodestar/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:400:28)
    at Parser.emit (domain.js:470:12)
    at SAXParser.onclosetag (/home/user/.opt/chainsafe/lodestar/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/home/user/.opt/chainsafe/lodestar/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/user/.opt/chainsafe/lodestar/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/user/.opt/chainsafe/lodestar/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/user/.opt/chainsafe/lodestar/node_modules/sax/lib/sax.js:1436:13) message=cb is not a function
TypeError: cb is not a function
    at /home/user/.opt/chainsafe/lodestar/node_modules/@motrix/nat-api/index.js:336:7
    at /home/user/.opt/chainsafe/lodestar/node_modules/@motrix/nat-api/lib/upnp/device.js:61:11
    at Parser.<anonymous> (/home/user/.opt/chainsafe/lodestar/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:400:28)
    at Parser.emit (domain.js:470:12)
    at SAXParser.onclosetag (/home/user/.opt/chainsafe/lodestar/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/home/user/.opt/chainsafe/lodestar/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/user/.opt/chainsafe/lodestar/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/user/.opt/chainsafe/lodestar/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/user/.opt/chainsafe/lodestar/node_modules/sax/lib/sax.js:1436:13)
```

**Desktop (please complete the following information):**

- OS: Archlinux
- Version: 0.29.0 (tag)

**Comment by dapplion** [comment]
That's so strange, what code can be parsing xml with `xml2js`?

**Comment by twopercent** [comment]
My node was syncing (```lodestar beacon --eth1.enabled false```) for a few days, but now I see this error ```error: uncaughtException: cb is not a function``` as far back as I can scroll. It ended with a core dump:
```
TypeError: cb is not a function
    at /home/chris/.nvm/versions/node/v16.14.0/lib/node_modules/@chainsafe/lodestar-cli/node_modules/@motrix/nat-api/index.js:324:16
    at Request._callback (/home/chris/.nvm/versions/node/v16.14.0/lib/node_modules/@chainsafe/lodestar-cli/node_modules/@motrix/nat-api/lib/upnp/device.js:46:25)
    at self.callback (/home/chris/.nvm/versions/node/v16.14.0/lib/node_modules/@chainsafe/lodestar-cli/node_modules/request/request.js:185:22)
    at Request.emit (node:events:520:28)
    at Request.emit (node:domain:475:12)
    at Request.onRequestError (/home/chris/.nvm/versions/node/v16.14.0/lib/node_modules/@chainsafe/lodestar-cli/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:520:28)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:442:9)
    at Socket.emit (node:events:520:28) message=cb is not a function
TypeError: cb is not a function
    at /home/chris/.nvm/versions/node/v16.14.0/lib/node_modules/@chainsafe/lodestar-cli/node_modules/@motrix/nat-api/index.js:324:16
    at Request._callback (/home/chris/.nvm/versions/node/v16.14.0/lib/node_modules/@chainsafe/lodestar-cli/node_modules/@motrix/nat-api/lib/upnp/device.js:46:25)
    at self.callback (/home/chris/.nvm/versions/node/v16.14.0/lib/node_modules/@chainsafe/lodestar-cli/node_modules/request/request.js:185:22)
    at Request.emit (node:events:520:28)
    at Request.emit (node:domain:475:12)
    at Request.onRequestError (/home/chris/.nvm/versions/node/v16.14.0/lib/node_modules/@chainsafe/lodestar-cli/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:520:28)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:442:9)
    at Socket.emit (node:events:520:28)

<--- Last few GCs --->

[12946:0x4e338e0] 125790461 ms: Mark-sweep 2022.8 (2090.5) -> 2009.8 (2093.5) MB, 2059.7 / 3.9 ms  (average mu = 0.830, current mu = 0.405) allocation failure scavenge might not succeed
[12946:0x4e338e0] 125794865 ms: Mark-sweep 2026.0 (2093.8) -> 2013.0 (2096.3) MB, 3014.4 / 3.4 ms  (average mu = 0.674, current mu = 0.316) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09980 node::Abort() [node]
 2: 0xa1c235 node::FatalError(char const*, char const*) [node]
 3: 0xcf77be v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcf7b37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xeaf3d5  [node]
 6: 0xebf09d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xec1d9e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xe832da v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
 9: 0x11fc026 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
10: 0x15f0a99  [node]
Aborted (core dumped)
```

**OS:** Ubuntu 20.04.3 LTS
**node:** v16.14.0

**Comment by dapplion** [comment]
Hi @twopercent thanks for reporting! Are you running your node in a cloud instance or local machine? Could you provide more details about your host machine and network it's connected to?
