### ISSUE TITLE
Lodestar CLI is not working with 3rd party beacon nodes

### ISSUE THREAD

**Issue by BeroBurny** [ChainSafe/lodestar#3018]
**Describe the bug**
running validator with 3rd party beacon node should run it

**Expected behavior**

To run and do work

**Steps to Reproduce**

version build from source

```
bernard:~/lodestar$ ./lodestar validator --network pyrmont --server https://1wDQcYYEukhUVgfL4QSgW52I5Qf:cf7444934146776605812bc78292f4d1@eth2-beacon-pyrmont.infura.io
Aug-25 15:02:02.704 []                 info: Lodestar version=v0.29.0/master/+13/3b36d7f9 (git), network=pyrmont
Aug-25 15:02:08.107 []                 info: Decrypted 1 validator keystores
Aug-25 15:02:08.766 []                 info: Genesis available
 ✖ Error: Invalid JSON container field: expected field max_committees_per_slot is undefined
    at ContainerType.struct_convertFromJson (/home/bernard/lodestar/node_modules/@chainsafe/ssz/src/types/composite/container.ts:223:15)
    at ContainerType.fromJson (/home/bernard/lodestar/node_modules/@chainsafe/ssz/src/types/composite/abstract.ts:377:17)
    at ContainerType.struct_convertFromJson (/home/bernard/lodestar/node_modules/@chainsafe/ssz/src/types/composite/container.ts:225:47)
    at ContainerType.fromJson (/home/bernard/lodestar/node_modules/@chainsafe/ssz/src/types/composite/abstract.ts:377:17)
    at Object.request (/home/bernard/lodestar/packages/api/src/client/utils/client.ts:75:27)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at Function.initializeFromBeaconNode (/home/bernard/lodestar/packages/validator/src/validator.ts:91:32)
    at Object.validatorHandler [as handler] (/home/bernard/lodestar/packages/cli/src/cmds/validator/handler.ts:53:21)

bernard:~/lodestar$ ./lodestar validator --network pyrmont --server http://localhost:5062/
Aug-25 15:02:14.201 []                 info: Lodestar version=v0.29.0/master/+13/3b36d7f9 (git), network=pyrmont
Aug-25 15:02:19.676 []                 info: Decrypted 1 validator keystores
Aug-25 15:02:19.710 []                 info: Genesis available
 ✖ Error: Invalid JSON container field: expected field max_committees_per_slot is undefined
    at ContainerType.struct_convertFromJson (/home/bernard/lodestar/node_modules/@chainsafe/ssz/src/types/composite/container.ts:223:15)
    at ContainerType.fromJson (/home/bernard/lodestar/node_modules/@chainsafe/ssz/src/types/composite/abstract.ts:377:17)
    at ContainerType.struct_convertFromJson (/home/bernard/lodestar/node_modules/@chainsafe/ssz/src/types/composite/container.ts:225:47)
    at ContainerType.fromJson (/home/bernard/lodestar/node_modules/@chainsafe/ssz/src/types/composite/abstract.ts:377:17)
    at Object.request (/home/bernard/lodestar/packages/api/src/client/utils/client.ts:75:27)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at Function.initializeFromBeaconNode (/home/bernard/lodestar/packages/validator/src/validator.ts:91:32)
    at Object.validatorHandler [as handler] (/home/bernard/lodestar/packages/cli/src/cmds/validator/handler.ts:53:21)

bernard:~/lodestar$ 
```

**Comment by dapplion** [comment]
Maybe related https://github.com/ChainSafe/ssz/issues/166 our casing transformation might be wrong

**Comment by g11tech** [comment]
yup @dapplion  this looks to be case related, for e.g. the current response received from lighthouse beacon was in UPPER_CASE/CONSTANT_CASE while we are expecting snake_case (most probably for network params fetch)
![image](https://user-images.githubusercontent.com/76567250/131509626-521849f7-e03a-4b7a-a102-b166463732a7.png) 

while other we are receiving in snake, and hence parsing correctly, though all api calls yet need to be inspected

![image](https://user-images.githubusercontent.com/76567250/131510173-52dc1caf-af65-47a2-9fad-06336c7d2c5e.png)

**Comment by g11tech** [comment]
@BeroBurny , could you try the latest master and let know if it works. any missing config parametern not yet operational (for e.g. merge related config params), if reported by the config api error can be filled locally (and appropriately) on validator side with `--paramsFile`
