### ISSUE TITLE
Error starting docker

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3056]
**Describe the bug**

This happens when I start our node on an dockerized environment:
```
Sep-02 03:31:34.171 []                 info: Initializing beacon state from anchor state slot=88672, epoch=2771, stateRoot=0xeeec0ade1a2d36aa802c069c165d9ab5cf7fa210c9df17f8228dfbb9cc5d9cee
 ✖ TypeError: uint8ArrayFromString is not a function
    at new IdentifyService (/usr/app/node_modules/libp2p/src/identify/index.js:62:66)
    at new Libp2p (/usr/app/node_modules/libp2p/src/index.js:291:30)
    at new NodejsNode (/usr/app/node_modules/@chainsafe/lodestar/src/network/nodejs/bundle.ts:93:5)
    at Object.createNodeJsLibp2p (/usr/app/node_modules/@chainsafe/lodestar/src/network/nodejs/util.ts:62:10)
    at Object.beaconHandler [as handler] (/usr/app/node_modules/@chainsafe/lodestar-cli/src/cmds/beacon/handler.ts:79:15)
```

**Expected behavior**
No error
**Desktop (please complete the following information):**

- Commit hash: 1f44e0

**Comment by twoeths** [comment]
got this error when I run from command line or run docker with `--build` option:

```
Sep-02 06:07:12.131 []                 info: Initializing beacon state from anchor state slot=2071167, epoch=64723, stateRoot=0x6ffde0580e2dff1b256b1fdf0956744667fa59a3ce57c628759d8aeb4a870fdf
 ✖ TypeError: Cannot read property 'iterator' of undefined
    at LevelDatastore._query (/root/lodestar/node_modules/datastore-level/src/index.js:248:44)
    at LevelDatastore.query (/root/lodestar/node_modules/datastore-level/src/index.js:168:19)
    at PersistentPeerStore.start (/root/lodestar/node_modules/libp2p/src/peer-store/persistent/index.js:85:47)
    at NodejsNode._onStarting (/root/lodestar/node_modules/libp2p/src/index.js:620:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at NodejsNode.start (/root/lodestar/node_modules/libp2p/src/index.js:364:7)
    at Network.start (/root/lodestar/packages/lodestar/src/network/network.ts:133:5)
    at Function.init (/root/lodestar/packages/lodestar/src/node/nodejs.ts:205:5)
    at Object.beaconHandler [as handler] (/root/lodestar/packages/cli/src/cmds/beacon/handler.ts:74:18)
```

this does not happen if I revert https://github.com/ChainSafe/lodestar/pull/3042

**Comment by dapplion** [comment]
I'm able to up the latest :next build in our deploys :+1:
