### ISSUE TITLE
Error proposing blocks Cannot get tree for index: 7865

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3060]
**Describe the bug**

Running Prater after fork

```
validator3_1   | Sep-02 12:15:49.717 []                error: Error proposing block slot=1173079, validator=0x9897…ef30 message=Failed to produce block - Internal Server Error: Cannot get tree for index: 7865, maxIndex: 1
validator3_1   | Error: Failed to produce block - Internal Server Error: Cannot get tree for index: 7865, maxIndex: 1
validator3_1   |     at HttpClient.request (/usr/app/packages/api/src/client/utils/httpClient.ts:91:15)
validator3_1   |     at runMicrotasks (<anonymous>)
validator3_1   |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
validator3_1   |     at HttpClient.json (/usr/app/packages/api/src/client/utils/httpClient.ts:58:12)
validator3_1   |     at Object.request [as produceBlock] (/usr/app/packages/api/src/client/utils/client.ts:72:19)
validator2_1   |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
validator2_1   |     at runNextTicks (internal/process/task_queues.js:64:3)
validator2_1   |     at listOnTimeout (internal/timers.js:526:9)
validator2_1   |     at processTimers (internal/timers.js:500:7)
validator2_1   |     at HttpClient.json (/usr/app/packages/api/src/client/utils/httpClient.ts:58:12)
validator2_1   |     at Object.request [as produceAttestationData] (/usr/app/packages/api/src/client/utils/client.ts:72:19)
validator2_1   |     at AttestationService.produceAndPublishAttestations (/usr/app/packages/validator/src/services/attestation.ts:86:28)
validator2_1   |     at AttestationService.publishAttestationsAndAggregates (/usr/app/packages/validator/src/services/attestation.ts:57:25)
validator2_1   |     at /usr/app/packages/validator/src/services/attestation.ts:43:9
```

**Expected behavior**

Don't break proposing blocks

**Comment by philknows** [comment]
Hasn't been seen recently.

**Comment by dapplion** [comment]
> Hasn't been seen recently.

This didn't age well, seen again in https://github.com/ChainSafe/lodestar/issues/3700
