### ISSUE TITLE
Chain logs "expected" errors

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3062]
**Describe the bug**

In Prater fork many blocks were missed, causing many errors for the chain processor. However this errors are expected in such network conditions and should not be logged as full errors, maybe warning or just info.

```
beacon_node_1  | Sep-02 12:40:40.494 [CHAIN]           error: Block error slot=1173203 code=BLOCK_ERROR_PARENT_UNKNOWN, parentRoot=0x520990c851ba76fec4bfdbe08a06ade7da6cce87d233c72a237be4cec0da7c05
beacon_node_1  | Error: BLOCK_ERROR_PARENT_UNKNOWN
beacon_node_1  |     at Object.processBlock (/usr/app/packages/lodestar/src/chain/blocks/process.ts:36:11)
beacon_node_1  |     at processBlockJob (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:66:11)
beacon_node_1  |     at JobItemQueue.BlockProcessor.jobQueue.queue_1.JobItemQueue.maxLength.maxLength [as itemProcessor] (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:34:18)
beacon_node_1  |     at Timeout.JobItemQueue.runJob [as _onTimeout] (/usr/app/packages/lodestar/src/util/queue/itemQueue.ts:85:33)
beacon_node_1  |     at listOnTimeout (internal/timers.js:554:17)
beacon_node_1  |     at processTimers (internal/timers.js:497:7)
beacon_node_1  | Sep-02 12:40:40.854 [CHAIN]           error: Block error slot=1173202 code=BLOCK_ERROR_PARENT_UNKNOWN, parentRoot=0x9c583b08f4f000776b74934ddf8ab4e11c0e17e933f0f6133844c35b97115f52
beacon_node_1  | Error: BLOCK_ERROR_PARENT_UNKNOWN
beacon_node_1  |     at Object.processBlock (/usr/app/packages/lodestar/src/chain/blocks/process.ts:36:11)
beacon_node_1  |     at processBlockJob (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:66:11)
beacon_node_1  |     at JobItemQueue.BlockProcessor.jobQueue.queue_1.JobItemQueue.maxLength.maxLength [as itemProcessor] (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:34:18)
beacon_node_1  |     at Timeout.JobItemQueue.runJob [as _onTimeout] (/usr/app/packages/lodestar/src/util/queue/itemQueue.ts:85:33)
beacon_node_1  |     at listOnTimeout (internal/timers.js:554:17)
beacon_node_1  |     at processTimers (internal/timers.js:497:7)
beacon_node_1  | Sep-02 12:40:41.295 [CHAIN]           error: Block error slot=1173200 code=BLOCK_ERROR_PARENT_UNKNOWN, parentRoot=0x33ffd09b9a984de9301c9a910b5194b5b2eed7a0ce0de7ac8dd26493f6d6f58d
beacon_node_1  | Error: BLOCK_ERROR_PARENT_UNKNOWN
beacon_node_1  |     at Object.processBlock (/usr/app/packages/lodestar/src/chain/blocks/process.ts:36:11)
beacon_node_1  |     at processBlockJob (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:66:11)
beacon_node_1  |     at JobItemQueue.BlockProcessor.jobQueue.queue_1.JobItemQueue.maxLength.maxLength [as itemProcessor] (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:34:18)
beacon_node_1  |     at Timeout.JobItemQueue.runJob [as _onTimeout] (/usr/app/packages/lodestar/src/util/queue/itemQueue.ts:85:33)
beacon_node_1  |     at listOnTimeout (internal/timers.js:554:17)
beacon_node_1  |     at processTimers (internal/timers.js:497:7)
beacon_node_1  | Sep-02 12:40:41.536 [CHAIN]           error: Block error slot=1173197 code=BLOCK_ERROR_PARENT_UNKNOWN, parentRoot=0xbb2f42559ec348347e1e83bd52caa5765768ecb5a99654c7cc6d6ea53bd2e78b
beacon_node_1  | Error: BLOCK_ERROR_PARENT_UNKNOWN
beacon_node_1  |     at Object.processBlock (/usr/app/packages/lodestar/src/chain/blocks/process.ts:36:11)
beacon_node_1  |     at processBlockJob (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:66:11)
beacon_node_1  |     at JobItemQueue.BlockProcessor.jobQueue.queue_1.JobItemQueue.maxLength.maxLength [as itemProcessor] (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:34:18)
beacon_node_1  |     at Timeout.JobItemQueue.runJob [as _onTimeout] (/usr/app/packages/lodestar/src/util/queue/itemQueue.ts:85:33)
beacon_node_1  |     at listOnTimeout (internal/timers.js:554:17)
beacon_node_1  |     at processTimers (internal/timers.js:497:7)
```

**Expected behavior**

Log as errors bad unexpected things

**Comment by come-maiz** [comment]
I'm testing in kiln with nethermind, and I got:

```
Aug-11 01:02:08.901[CHAIN]           error: Block error slot=5760, errCode=BLOCK_ERROR_PARENT_UNKNOWN BLOCK_ERROR_PARENT_UNKNOWN
Error: BLOCK_ERROR_PARENT_UNKNOWN
    at verifyBlocksSanityChecks (file:///mnt/data/workspace/lodestar/packages/beacon-node/src/chain/blocks/verifyBlocksSanityChecks.ts:68:15)
    at BeaconChain.processBlocks (file:///mnt/data/workspace/lodestar/packages/beacon-node/src/chain/blocks/index.ts:61:56)
    at JobItemQueue.BlockProcessor.jobQueue.JobItemQueue.maxLength [as itemProcessor] (file:///mnt/data/workspace/lodestar/packages/beacon-node/src/chain/blocks/index.ts:27
:30)
    at Timeout.JobItemQueue.runJob [as _onTimeout] (file:///mnt/data/workspace/lodestar/packages/beacon-node/src/util/queue/itemQueue.ts:92:33)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

Same for slots 5824, 5857, 5952, 6080, 6305.

Is this the same problem reported here?

**Comment by g11tech** [comment]
> I'm testing in kiln with nethermind, and I got:
> 
> ```
> Aug-11 01:02:08.901[CHAIN]           error: Block error slot=5760, errCode=BLOCK_ERROR_PARENT_UNKNOWN BLOCK_ERROR_PARENT_UNKNOWN
> Error: BLOCK_ERROR_PARENT_UNKNOWN
>     at verifyBlocksSanityChecks (file:///mnt/data/workspace/lodestar/packages/beacon-node/src/chain/blocks/verifyBlocksSanityChecks.ts:68:15)
>     at BeaconChain.processBlocks (file:///mnt/data/workspace/lodestar/packages/beacon-node/src/chain/blocks/index.ts:61:56)
>     at JobItemQueue.BlockProcessor.jobQueue.JobItemQueue.maxLength [as itemProcessor] (file:///mnt/data/workspace/lodestar/packages/beacon-node/src/chain/blocks/index.ts:27
> :30)
>     at Timeout.JobItemQueue.runJob [as _onTimeout] (file:///mnt/data/workspace/lodestar/packages/beacon-node/src/util/queue/itemQueue.ts:92:33)
>     at listOnTimeout (node:internal/timers:559:17)
>     at processTimers (node:internal/timers:502:7)
> ```
> 
> Same for slots 5824, 5857, 5952, 6080, 6305.
> 
> Is this the same problem reported here?

its possible for lodestar to receive block segments from peers such that there are few missing blocks in front and can't connect to the chain. this is when such an error throw happens and is self recoverable. It becomes serious if its not recoverable and sync doesn't proceed, so the main issue here now is to modify the lodestar error UX.

**Comment by nazarhussain** [comment]
@dapplion Currently we are logging such block processing errors at `DEBUG` level. I think that's fine to do so and we can close this issue. What do you suggest? 

https://github.com/ChainSafe/lodestar/blob/6ac8c07023bc72c7ef54a6ea66884790793eda21/packages/beacon-node/src/chain/blocks/index.ts#L126
