### ISSUE TITLE
Prater altair fork: ATTESTATION_ERROR_INVALID_SIGNATURE

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3063]
**Describe the bug**

A single beacon node with one validator errors sometimes with

```
beacon_node_1  | Sep-02 12:43:16.941 [API]             error: Error on submitPoolAttestations [0] slot=1173216, index=50 code=ATTESTATION_ERROR_INVALID_SIGNATURE
beacon_node_1  | Error: ATTESTATION_ERROR_INVALID_SIGNATURE
beacon_node_1  |     at Object.validateGossipAttestation (/usr/app/packages/lodestar/src/chain/validation/attestation.ts:146:11)
beacon_node_1  |     at /usr/app/packages/lodestar/src/api/impl/beacon/pool/index.ts:52:50
beacon_node_1  |     at async Promise.all (index 0)
beacon_node_1  |     at Object.submitPoolAttestations (/usr/app/packages/lodestar/src/api/impl/beacon/pool/index.ts:49:7)
beacon_node_1  |     at Object.handler (/usr/app/packages/api/src/server/utils/server.ts:70:23)
beacon_node_1  | Sep-02 12:43:17.034 [API]             error: Req req-4e submitPoolAttestations error code=ATTESTATION_ERROR_INVALID_SIGNATURE
beacon_node_1  | Error: ATTESTATION_ERROR_INVALID_SIGNATURE
beacon_node_1  |     at Object.validateGossipAttestation (/usr/app/packages/lodestar/src/chain/validation/attestation.ts:146:11)
beacon_node_1  |     at /usr/app/packages/lodestar/src/api/impl/beacon/pool/index.ts:52:50
beacon_node_1  |     at async Promise.all (index 0)
beacon_node_1  |     at Object.submitPoolAttestations (/usr/app/packages/lodestar/src/api/impl/beacon/pool/index.ts:49:7)
beacon_node_1  |     at Object.handler (/usr/app/packages/api/src/server/utils/server.ts:70:23)
validator_1    | Sep-02 12:43:17.042 []                error: Error publishing attestations slot=1173216, index=50 message=Internal Server Error: ATTESTATION_ERROR_INVALID_SIGNATURE
validator_1    | Error: Internal Server Error: ATTESTATION_ERROR_INVALID_SIGNATURE
validator_1    |     at HttpClient.request (/usr/app/packages/api/src/client/utils/httpClient.ts:91:15)
validator_1    |     at runMicrotasks (<anonymous>)
validator_1    |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
validator_1    |     at HttpClient.json (/usr/app/packages/api/src/client/utils/httpClient.ts:58:12)
validator_1    |     at Object.request [as submitPoolAttestations] (/usr/app/packages/api/src/client/utils/client.ts:72:19)
validator_1    |     at AttestationService.produceAndPublishAttestations (/usr/app/packages/validator/src/services/attestation.ts:110:9)
validator_1    |     at AttestationService.publishAttestationsAndAggregates (/usr/app/packages/validator/src/services/attestation.ts:57:25)
validator_1    |     at /usr/app/packages/validator/src/services/attestation.ts:43:9
validator_1    |     at async Promise.all (index 0)
validator_1    |     at AttestationService.runAttestationTasks (/usr/app/packages/validator/src/services/attestation.ts:40:5)
```

CPU is not too high, < 80%

**Expected behavior**

Validator should agree with beacon node on correct signature

**Comment by dapplion** [comment]
Happened again right after restarting the node

```

beacon_node_1  | Sep-02 13:21:42.453 [API]             error: Error on submitPoolAttestations [0] slot=1173408, index=25 code=ATTESTATION_ERROR_INVALID_SIGNATURE
beacon_node_1  | Error: ATTESTATION_ERROR_INVALID_SIGNATURE
beacon_node_1  |     at Object.validateGossipAttestation (/usr/app/packages/lodestar/src/chain/validation/attestation.ts:146:11)
beacon_node_1  |     at /usr/app/packages/lodestar/src/api/impl/beacon/pool/index.ts:52:50
beacon_node_1  |     at async Promise.all (index 0)
beacon_node_1  |     at Object.submitPoolAttestations (/usr/app/packages/lodestar/src/api/impl/beacon/pool/index.ts:49:7)
beacon_node_1  |     at Object.handler (/usr/app/packages/api/src/server/utils/server.ts:70:23)
beacon_node_1  | Sep-02 13:21:42.466 [API]             error: Req req-o submitPoolAttestations error code=ATTESTATION_ERROR_INVALID_SIGNATURE
beacon_node_1  | Error: ATTESTATION_ERROR_INVALID_SIGNATURE
beacon_node_1  |     at Object.validateGossipAttestation (/usr/app/packages/lodestar/src/chain/validation/attestation.ts:146:11)
beacon_node_1  |     at /usr/app/packages/lodestar/src/api/impl/beacon/pool/index.ts:52:50
beacon_node_1  |     at async Promise.all (index 0)
beacon_node_1  |     at Object.submitPoolAttestations (/usr/app/packages/lodestar/src/api/impl/beacon/pool/index.ts:49:7)
beacon_node_1  |     at Object.handler (/usr/app/packages/api/src/server/utils/server.ts:70:23)
validator_1    | Sep-02 13:21:42.470 []                error: Error publishing attestations slot=1173408, index=25 message=Internal Server Error: ATTESTATION_ERROR_INVALID_SIGNATURE
validator_1    | Error: Internal Server Error: ATTESTATION_ERROR_INVALID_SIGNATURE
validator_1    |     at HttpClient.request (/usr/app/packages/api/src/client/utils/httpClient.ts:91:15)
validator_1    |     at runMicrotasks (<anonymous>)
validator_1    |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
validator_1    |     at HttpClient.json (/usr/app/packages/api/src/client/utils/httpClient.ts:58:12)
validator_1    |     at Object.request [as submitPoolAttestations] (/usr/app/packages/api/src/client/utils/client.ts:72:19)
validator_1    |     at AttestationService.produceAndPublishAttestations (/usr/app/packages/validator/src/services/attestation.ts:110:9)
validator_1    |     at AttestationService.publishAttestationsAndAggregates (/usr/app/packages/validator/src/services/attestation.ts:57:25)
validator_1    |     at /usr/app/packages/validator/src/services/attestation.ts:43:9
validator_1    |     at async Promise.all (index 0)
validator_1    |     at AttestationService.runAttestationTasks (/usr/app/packages/validator/src/services/attestation.ts:40:5)
```

**Comment by dapplion** [comment]
@tuyennhv  I've tracked the issue to incorrect ordering of attestation duties. The problem is that getCommitteeAssignments() returns un-ordered duties while the api impl code assumes it does. This makes the validator client apply duties to wrong validator and sign with a different key

The issue is fixed with this commit https://github.com/ChainSafe/lodestar/pull/3046/commits/e53647ea4e053f0c98a7c2506b79a61e4c831b9d
