### ISSUE TITLE
Invalid state root

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3066]
**Describe the bug**

Got this on contabo-0 running Prater
```
Sep-03 03:01:58.707 [CHAIN]           error: Block error slot=1177408 code=BLOCK_ERROR_BEACON_CHAIN_ERROR, error={"message":"Invalid state root at slot 1177408, expected=0xc7db41ea510dae0fbf32caae531c9e29e95b0318b4c4c6ff192654146f295a66, actual=0x17eb9ac943f2a3aa5b2a53640cd7c48088ef086eae7f825cda97dd9d6bd73ffb"}
Error: Invalid state root at slot 1177408, expected=0xc7db41ea510dae0fbf32caae531c9e29e95b0318b4c4c6ff192654146f295a66, actual=0x17eb9ac943f2a3aa5b2a53640cd7c48088ef086eae7f825cda97dd9d6bd73ffb
    at Object.stateTransition (/usr/app/packages/beacon-state-transition/src/allForks/stateTransition.ts:67:13)
    at Object.runStateTransition (/usr/app/packages/lodestar/src/chain/blocks/stateTransition.ts:83:30)
    at processBlocksInEpoch (/usr/app/packages/lodestar/src/chain/blocks/process.ts:108:24)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:60:5)
    at processTimers (internal/timers.js:497:9)
    at Object.processBlock (/usr/app/packages/lodestar/src/chain/blocks/process.ts:42:3)
    at processBlockJob (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:66:5)
    at Timeout.JobItemQueue.runJob [as _onTimeout] (/usr/app/packages/lodestar/src/util/queue/itemQueue.ts:85:22)
Error: BLOCK_ERROR_BEACON_CHAIN_ERROR
    at processBlocksInEpoch (/usr/app/packages/lodestar/src/chain/blocks/process.ts:149:11)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:60:5)
    at processTimers (internal/timers.js:497:9)
    at Object.processBlock (/usr/app/packages/lodestar/src/chain/blocks/process.ts:42:3)
    at processBlockJob (/usr/app/packages/lodestar/src/chain/blocks/processor.ts:66:5)
    at Timeout.JobItemQueue.runJob [as _onTimeout] (/usr/app/packages/lodestar/src/util/queue/itemQueue.ts:85:22)
```

after this, node stays out of synced

**Expected behavior**
No error

**Comment by twoeths** [comment]
~~another error when I deserialize weak subjectivity state:~~

```
Sep-03 16:52:44.535 []                 info: Fetching weak subjectivity state from https://eth2-beacon-prater.infura.io/eth/v1/debug/beacon/states/finalized
 ✖ Error: Unable to deserialize weak subjectivity state at archivePath /Users/tuyennguyen/.local/share/lodestar/prater/archive/2021-09-03/state_invalid_weak_subjectivity_1630662789679.ssz Offset out of bounds
    at Object.fetchWeakSubjectivityState (/Users/tuyennguyen/Projects/workshop/lodestar/packages/cli/src/networks/index.ts:125:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.initBeaconState (/Users/tuyennguyen/Projects/workshop/lodestar/packages/cli/src/cmds/beacon/initBeaconState.ts:107:21)
    at Object.beaconHandler [as handler] (/Users/tuyennguyen/Projects/workshop/lodestar/packages/cli/src/cmds/beacon/handler.ts:74:25)
```
Update: this is not an error, it's an issue of my environment having the old config file.

**Comment by twoeths** [comment]
attaching preState 1177407, signed block 1177408 and wrong postState 1177408 

[state_1177407_invalid_root_0x17eb9ac943f2a3aa5b2a53640cd7c48088ef086eae7f825cda97dd9d6bd73ffb_pre_1630729091819.ssz.zip](https://github.com/ChainSafe/lodestar/files/7109193/state_1177407_invalid_root_0x17eb9ac943f2a3aa5b2a53640cd7c48088ef086eae7f825cda97dd9d6bd73ffb_pre_1630729091819.ssz.zip)

[state_1177408_invalid_root_0x17eb9ac943f2a3aa5b2a53640cd7c48088ef086eae7f825cda97dd9d6bd73ffb_post_1630729122249.ssz.zip](https://github.com/ChainSafe/lodestar/files/7109195/state_1177408_invalid_root_0x17eb9ac943f2a3aa5b2a53640cd7c48088ef086eae7f825cda97dd9d6bd73ffb_post_1630729122249.ssz.zip)


[signedBlock_1177408_invalid_root_0x17eb9ac943f2a3aa5b2a53640cd7c48088ef086eae7f825cda97dd9d6bd73ffb_1630729091892.ssz.zip](https://github.com/ChainSafe/lodestar/files/7109200/signedBlock_1177408_invalid_root_0x17eb9ac943f2a3aa5b2a53640cd7c48088ef086eae7f825cda97dd9d6bd73ffb_1630729091892.ssz.zip)
