### ISSUE TITLE
ATTESTATION_ERROR_INVALID_SIGNATURE

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3233]
**Describe the bug**

Found this in validator log
```
Sep-22 22:12:55.859 []                ^[[31merror^[[39m: Error publishing attestations slot=1320064, index=50 message=Intern      al Server Error: ATTESTATION_ERROR_INVALID_SIGNATURE
61993 Error: Internal Server Error: ATTESTATION_ERROR_INVALID_SIGNATURE
61994     at HttpClient.request (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:91:15)
61995     at runMicrotasks (<anonymous>)
61996     at processTicksAndRejections (internal/process/task_queues.js:95:5)
61997     at HttpClient.json (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:58:12)
61998     at Object.request [as submitPoolAttestations] (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/client.ts:      72:19)
61999     at AttestationService.produceAndPublishAttestations (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/at      testation.ts:110:9)
62000     at AttestationService.publishAttestationsAndAggregates (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services      /attestation.ts:57:25)
62001     at /usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:43:9
62002     at async Promise.all (index 0)
62003     at AttestationService.runAttestationTasks (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.      ts:40:5)
```

**Expected behavior**

No error

**Comment by twoeths** [comment]
closing as it's part of #3211
