### ISSUE TITLE
BLOCK_ERROR_PRESTATE_MISSING

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3234]
**Describe the bug**

Error while syncing finalized
```
Sep-23 01:31:04.523 [SYNC]          ^[[36mverbose^[[39m: Batch process error id=Finalized, startEpoch=41251, status=Processing code=BLOCK_ERROR_PRESTATE_MISSING, error={"message":"REGEN_ERROR_NO_SEED_STATE"}
Error: REGEN_ERROR_NO_SEED_STATE
    at StateRegenerator.getState (/usr/app/node_modules/@chainsafe/lodestar/src/chain/regen/regen.ts:154:13)
    at StateRegenerator.getPreState (/usr/app/node_modules/@chainsafe/lodestar/src/chain/regen/regen.ts:65:23)
    at JobItemQueue.QueuedStateRegenerator.jobQueueProcessor [as itemProcessor] (/usr/app/node_modules/@chainsafe/lodestar/src/chain/regen/queued.ts:142:35)
    at Timeout.JobItemQueue.runJob [as _onTimeout] (/usr/app/node_modules/@chainsafe/lodestar/src/util/queue/itemQueue.ts:85:33)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
Error: BLOCK_ERROR_PRESTATE_MISSING
    at /usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/verifyBlock.ts:106:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at listOnTimeout (internal/timers.js:526:9)
    at processTimers (internal/timers.js:500:7)
    at verifyBlockStateTransition (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/verifyBlock.ts:105:20)
    at verifyBlock (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/verifyBlock.ts:33:10)
    at processChainSegment (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/index.ts:91:34)
    at JobItemQueue.runJob (/usr/app/node_modules/@chainsafe/lodestar/src/util/queue/itemQueue.ts:85:22)
```

this happens on server contabo-7 and node is not able to sync to head, maybe this is due to #3221 and related PR

**Expected behavior**

no error

**Comment by twoeths** [comment]
it may not be an issue anymore as I can sync to head with contabo-0 and latest image, @dapplion could you confirm you fixed this in one of your PRs?

**Comment by twoeths** [comment]
some more logs I found
+ this is the last finalized checkpoint we have
```
11695871 Sep-22 22:08:12.543 [CHAIN]         ^[[36mverbose^[[39m: Finish processing finalized checkpoint epoch=41249
```

+ the issue happened at slot 1320035
```
Sep-22 22:19:15.320 [CHAIN]           ^[[31merror^[[39m: Block error slot=1320035, errCode=BLOCK_ERROR_PRESTATE_MISSING code=BLOCK_ERROR_PRESTATE_MISSING, error={"message":"REGEN_ERROR_NO_S         EED_STATE"}
12133833 Error: REGEN_ERROR_NO_SEED_STATE
```

I suppose this issue is due to #3236 where a lot of gossip blocks being held as pending blocks hence our state cache can't store all of them https://github.com/ChainSafe/lodestar/blob/17291db2e39484f833e9bb8de3528654249f21e9/packages/lodestar/src/chain/regen/regen.ts#L155

**Comment by dapplion** [comment]
@tuyennhv There is a metric to track the number of pending blocks, can you check the metrics to corroborate this theory?

https://github.com/ChainSafe/lodestar/blob/4e8e969fa4223749ce760a02563913f3dbb44a94/packages/lodestar/src/metrics/metrics/lodestar.ts#L265

Also, regen should be able to get the state anyway even if it's expensive right?

**Comment by twoeths** [comment]
> Also, regen should be able to get the state anyway even if it's expensive right?

no, if regen traces back the forkchoice without finding a state in the state cache respective to the stateRoot in forkchoice then it'd throw this error

**Comment by twoeths** [comment]
> @tuyennhv There is a metric to track the number of pending blocks, can you check the metrics to corroborate this theory?

![Screen Shot 2021-09-24 at 08 04 43](https://user-images.githubusercontent.com/10568965/134603011-4199e3de-0429-4009-b6f6-5a6a1c66ed96.png)

@dapplion yeah the metric does show that pendingBlock used to be up to 100 in contabo-7, now it's fine

**Comment by twoeths** [comment]
it happens again in contabo-0, looks like the root cause of this time is the #3243 

```
Sep-27 01:57:42.566 [CHAIN]           ^[[31merror^[[39m: Block error slot=1324832, errCode=BLOCK_ERROR_BEACON_CHA       IN_ERROR code=BLOCK_ERROR_BEACON_CHAIN_ERROR, error={"message":"slot less than finalized block"}
176513 Error: slot less than finalized block
```
then the state is not added to cache, then the next block slot failed to get state
```
Sep-27 01:57:45.670 [CHAIN]           ^[[31merror^[[39m: Block error slot=1324833, errCode=BLOCK_ERROR_PRESTATE_M       ISSING code=BLOCK_ERROR_PRESTATE_MISSING, error={"message":"REGEN_ERROR_NO_SEED_STATE"}
176982 Error: REGEN_ERROR_NO_SEED_STATE
176983     at StateRegenerator.getState (/usr/app/node_modules/@chainsafe/lodestar/src/chain/regen/regen.ts:154:13)
```

**Comment by dapplion** [comment]
Closing for now
