### ISSUE TITLE
headState does not exist

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3237]
**Describe the bug**

We're not able to validate sync_committee message

```
Sep-22 22:19:25.645 [NETWORK]         ^[[31merror^[[39m: Gossip validation sync_committee threw a non-GossipActionError m         essage=headState does not exist
12144156 Error: headState does not exist
12144157     at BeaconChain.getHeadState (/usr/app/node_modules/@chainsafe/lodestar/src/chain/chain.ts:192:27)
12144158     at validateGossipSyncCommittee (/usr/app/node_modules/@chainsafe/lodestar/src/chain/validation/syncCommittee.ts:20:27         )
12144159     at sync_committee (/usr/app/node_modules/@chainsafe/lodestar/src/network/gossip/handlers/index.ts:262:65)
12144160     at gossipValidatorFn (/usr/app/node_modules/@chainsafe/lodestar/src/network/gossip/validation/index.ts:99:14)
12144161     at JobItemQueue.queue_1.JobItemQueue.signal.signal [as itemProcessor] (/usr/app/node_modules/@chainsafe/lodestar/src/         network/gossip/validation/queue.ts:47:45)
12144162     at JobItemQueue.runJob (/usr/app/node_modules/@chainsafe/lodestar/src/util/queue/itemQueue.ts:85:33)
12144163     at JobItemQueue.runJob (/usr/app/node_modules/@chainsafe/lodestar/src/util/queue/itemQueue.ts:102:15)
12144164     at runMicrotasks (<anonymous>)
12144165     at processTicksAndRejections (internal/process/task_queues.js:95:5)
12144166     at runNextTicks (internal/process/task_queues.js:64:3)
12144167 Sep-22 22:19:25.695 [NETWORK]       ^[[36mverbose^[[39m: Received gossip block slot=1320097, root=0xdd6c…9783, curentSlot         =1320097
12144168 Sep-22 22:19:25.696 [NETWORK]         ^[[34mdebug^[[39m: Gossip block has error slot=1320097, root=0xdd6c…9783, code=BLOC         K_ERROR_PARENT_UNKNOWN
```

**Expected behavior**

No error

**Comment by twoeths** [comment]
looks like the root cause is #3243 where we're able to add a block to forkchoice but state is not added to the cache

**Comment by dapplion** [comment]
Closing for now
