### ISSUE TITLE
RangeSync should handle PARENT_UNKNOWN errors

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3240]
**Describe the bug**

From this comment in the block processor, if the sync ignores WOULD_REVERT_FINALIZED_SLOT the sync must also be able to recover. 

https://github.com/ChainSafe/lodestar/blob/4e8e969fa4223749ce760a02563913f3dbb44a94/packages/lodestar/src/chain/blocks/index.ts#L104-L117

**Comment by twoeths** [comment]
the issue could be reproduced with "--weakSubjectivitySyncLatest` flag

```
Sep-24 13:38:15.294 [CHAIN]           error: Block error slot=1329602, errCode=BLOCK_ERROR_PARENT_UNKNOWN code=BLOCK_ERROR_PARENT_UNKNOWN, parentRoot=0xb58db597b73b564299825326035c05706203e15755e887a9450898de92358a30
Error: BLOCK_ERROR_PARENT_UNKNOWN
    at verifyBlockSanityChecks (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/blocks/verifyBlock.ts:58:11)
    at verifyBlock (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/blocks/verifyBlock.ts:32:3)
    at processChainSegment (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/blocks/index.ts:101:51)
    at JobItemQueue.BlockProcessor.jobQueue.queue_1.JobItemQueue.maxLength [as itemProcessor] (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/chain/blocks/index.ts:31:18)
    at Timeout.JobItemQueue.runJob [as _onTimeout] (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/util/queue/itemQueue.ts:85:33)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```
