### ISSUE TITLE
[bug] running the dev commands for setting a local network throws error

### ISSUE THREAD

**Issue by filipesmedeiros** [ChainSafe/lodestar#3342]
**Describe the bug**

running the "default" local dev ([the one from the tutorial in the docs](https://chainsafe.github.io/lodestar/usage/local/)) setup is throwing an error (too hard for me to investigate on my own ahah)

**Expected behavior**

the tutorial should lead to a working local setup

**Steps to Reproduce**

1. clone the repo
2. (stay on master and / of the repo)
3. run `yarn`
4. run `yarn build`
5. run `./lodestar dev --genesisValidators 8 -r`

**Screenshots**

```zsh
✖ Error: aggregatorsPerslot === 0
    at getAllTopicsScoreParams (/Users/filipesmedeiros/eth/lodestar/packages/lodestar/src/network/gossip/scoringParameters.ts:179:41)
    at computeGossipPeerScoreParams (/Users/filipesmedeiros/eth/lodestar/packages/lodestar/src/network/gossip/scoringParameters.ts:89:13)
    at new Eth2Gossipsub (/Users/filipesmedeiros/eth/lodestar/packages/lodestar/src/network/gossip/gossipsub.ts:94:48)
    at new Network (/Users/filipesmedeiros/eth/lodestar/packages/lodestar/src/network/network.ts:91:19)
    at Function.init (/Users/filipesmedeiros/eth/lodestar/packages/lodestar/src/node/nodejs.ts:146:21)
    at Object.devHandler [as handler] (/Users/filipesmedeiros/eth/lodestar/packages/cli/src/cmds/dev/handler.ts:95:16)

../src/bcrypto.c:13245: Assertion `napi_create_function(env, name, NAPI_AUTO_LENGTH, callback, NULL, &fn) == napi_ok' failed.
./lodestar: line 7: 63573 Abort trap: 6           node --trace-deprecation --max-old-space-size=6144 ./packages/cli/bin/lodestar "$@"
```

**Desktop (please complete the following information):**

- OS: macos
- Version: 11.6 big sur
- Branch: master
- Commit hash: bda8f2add1eeafd14275ade7a33733cbbd404710

**Comment by dapplion** [comment]
Oh yes this has affected us significantly in the merge-interop. Please @tuyennhv could you tweak the params calculations such that they **never** error?
