### ISSUE TITLE
BLOCK_ERROR_PARENT_UNKNOWN

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3359]
**Describe the bug**

Got this error while the node is syncing

```
Oct-13 06:22:40.324 [CHAIN]           error: Block error slot=14502, errCode=BLOCK_ERROR_PARENT_UNKNOWN code=BLOCK_ERROR_PARENT_UNKNOWN, parentRoot=0xca3a9de0c198e1f43e5f5fa9961a8b68f4c0b44209e8c56edc218decd87796d2
Error: BLOCK_ERROR_PARENT_UNKNOWN
    at verifyBlockSanityChecks (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/verifyBlock.ts:74:11)
    at verifyBlock (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/verifyBlock.ts:37:3)
    at processChainSegment (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/index.ts:101:51)
    at JobItemQueue.BlockProcessor.jobQueue.queue_1.JobItemQueue.maxLength [as itemProcessor] (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/index.ts:31:18)
    at JobItemQueue.runJob (/usr/app/node_modules/@chainsafe/lodestar/src/util/queue/itemQueue.ts:85:33)
    at JobItemQueue.runJob (/usr/app/node_modules/@chainsafe/lodestar/src/util/queue/itemQueue.ts:102:15)
```

The node can sync even this error exists

**Expected behavior**

No error

**Comment by twoeths** [comment]
There are 2 causes for the issue:
+ some peers send us orphaned block
+ the error happens at the 1st block of a batch because the previous batch hasn't finished

this works as designed
