### ISSUE TITLE
Error lightclientUpdater.onFinalized

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3360]
**Describe the bug**

Got this error while syncing lodestar:
```
Oct-13 06:16:45.755 [CHAIN]           error: Error lightclientUpdater.onFinalized epoch=1056 message=No block found for checkpoint 1056 : 0xc384ee5dda94f049e564dfcb7e120234e8575b51448f9e21f3343258f3644ce5
Error: No block found for checkpoint 1056 : 0xc384ee5dda94f049e564dfcb7e120234e8575b51448f9e21f3343258f3644ce5
    at BeaconChain.onForkChoiceFinalized (/usr/app/node_modules/@chainsafe/lodestar/src/chain/eventHandlers.ts:165:15)
    at ChainEventEmitter.<anonymous> (/usr/app/node_modules/@chainsafe/lodestar/src/chain/eventHandlers.ts:30:7)
```

**Expected behavior**
No error

**Comment by twoeths** [comment]
this is because we handle `forkchoiceFinalized` event at 2 different places and they are not synchronized

```
Oct-13 07:47:45.759 [CHAIN]         ^[[36mverbose^[[39m: Checkpoint finalized epoch=5228, root=0x8fff13cdd4b73614c3527ff0bed31b3c41f308e5592d95d12abd37c5d9ffa305
Oct-13 07:47:45.759 [CHAIN]         ^[[36mverbose^[[39m: New chain head headSlot=41856, headRoot=0xdf7f6a33e4e7dd08f3f2710a54a08fae6b8ff87dd33f25c4bf594de457773c2c
Oct-13 07:47:45.792 [CHAIN]         ^[[36mverbose^[[39m: Archive Blocks: processed chunk lowerBound=0, upperBound=10, size=10
Oct-13 07:47:45.793 [CHAIN]         ^[[36mverbose^[[39m: Archiving of finalized blocks complete totalArchived=10, finalizedEpoch=5228
Oct-13 07:47:45.793 [CHAIN]           ^[[31merror^[[39m: Error lightclientUpdater.onFinalized epoch=5228 message=No block found for checkpoint 5228 : 0x8fff13cdd4b73614c3527ff0bed31b3c41f308e5592d95d12abd37c5d9ffa305
Error: No block found for checkpoint 5228 : 0x8fff13cdd4b73614c3527ff0bed31b3c41f308e5592d95d12abd37c5d9ffa305
    at BeaconChain.onForkChoiceFinalized (/usr/app/node_modules/@chainsafe/lodestar/src/chain/eventHandlers.ts:165:15)
    at ChainEventEmitter.<anonymous> (/usr/app/node_modules/@chainsafe/lodestar/src/chain/eventHandlers.ts:30:7)
Oct-13 07:47:45.812 [CHAIN]         ^[[36mverbose^[[39m: Finish processing finalized checkpoint epoch=5228
```

While we handle `forkChoiceFinalized` event in EventHandler, Archiver was working on moving blocks from `block` db to `archiveBlock` db
