### ISSUE TITLE
Not able to sync from a skipped slot checkpoint

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3380]
**Describe the bug**

Sync prater with `weakSubjectivitySyncLatest` and it returns a skipped slot checkpoint

```
Oct-19 07:26:51.687 []                 ^[[32minfo^[[39m: Initializing beacon state from anchor state slot=1509951, epoc      h=47185, stateRoot=0xb4eda17df38f9f0e46d82d04a585eb5965c7b7051949b200f7face4a9f6142e5
```

got error
```
3942 Oct-19 07:30:23.428 [CHAIN]           ^[[31merror^[[39m: Block error slot=1509922, errCode=BLOCK_ERROR_PARENT_UNKNOWN c      ode=BLOCK_ERROR_PARENT_UNKNOWN, parentRoot=0x85a07dcd64dff27435c88350299a4ce1aab4a0bf5c553fd278f2a6e92c654248
 3943 Error: BLOCK_ERROR_PARENT_UNKNOWN
 3944     at verifyBlockSanityChecks (/usr/app/packages/lodestar/src/chain/blocks/verifyBlock.ts:74:11)
 3945     at verifyBlock (/usr/app/packages/lodestar/src/chain/blocks/verifyBlock.ts:37:3)
 3946     at processChainSegment (/usr/app/packages/lodestar/src/chain/blocks/index.ts:101:51)
 3947     at JobItemQueue.BlockProcessor.jobQueue.queue_1.JobItemQueue.maxLength [as itemProcessor] (/usr/app/packages/lodest      ar/src/chain/blocks/index.ts:31:18)
 3948     at Timeout.JobItemQueue.runJob [as _onTimeout] (/usr/app/packages/lodestar/src/util/queue/itemQueue.ts:85:33)
 3949     at listOnTimeout (internal/timers.js:554:17)
 3950     at processTimers (internal/timers.js:497:7)
 3951 Oct-19 07:30:23.433 [SYNC]          ^[[36mverbose^[[39m: Batch process error id=Finalized, startEpoch=47185, status=Pro      cessing code=BLOCK_ERROR_PARENT_UNKNOWN, parentRoot=0x85a07dcd64dff27435c88350299a4ce1aab4a0bf5c553fd278f2a6e92c654248
 3952 Error: BLOCK_ERROR_PARENT_UNKNOWN
 3953     at verifyBlockSanityChecks (/usr/app/packages/lodestar/src/chain/blocks/verifyBlock.ts:74:11)
 3954     at verifyBlock (/usr/app/packages/lodestar/src/chain/blocks/verifyBlock.ts:37:3)
 3955     at processChainSegment (/usr/app/packages/lodestar/src/chain/blocks/index.ts:101:51)
```

and we're not able to catch up to head. Notice that we start the sync from incorrect slot 1509922 while our state slot is bigger 1509951, that's why we got `BLOCK_ERROR_PARENT_UNKNOWN` error

**Expected behavior**

No error, sync should start from a slot later than 1509951. An example below shows that anchor state slot=1510112 and startSlot to download blocks = 1510113
```
Oct-19 15:00:26.357 []                 info: Initializing beacon state from anchor state slot=1510112, epoch=47191, stateRoot=0x078147d434574f21423399de86f16dd38baf81e8593f4753690ed10ad7248ffa
```
```
Oct-19 15:02:19.024 [NETWORK]         ^[[34mdebug^[[39m: Req  sending request method=beacon_blocks_by_range, encoding=ssz_snappy     , agentVersion=Lighthouse/v2.0.0-7c88f58+/x86_64-linux, peer=16...b11aav, requestId=83, requestBody={"startSlot":1510113,"count"     :64,"step":1}
```
[beacon-2021-10-19.log](https://github.com/ChainSafe/lodestar/files/7371501/beacon-2021-10-19.log)

**Steps to Reproduce**

+ if I specify with `--weakSubjectivitySyncLatest --weakSubjectivityCheckpoint 0x801fe3e5bdf5b47454def25c6b5dd000511098ad96da35933e6ff3adca8bda99:47186` it got the correct state of 1509952 (which is a skipped slot) and the issue does not happen
+ probably download with state 1509951 and use `weakSubjectivityStateFile` arg

**Comment by twoeths** [comment]
[state_1509951.ssz.zip](https://github.com/ChainSafe/lodestar/files/7372229/state_1509951.ssz.zip)

I can reproduce with `weakSubjectivityStateFile` flag and the attached state
