### ISSUE TITLE
Lodestar-besu error - BLOCK_ERROR_EXECUTION_PAYLOAD_NOT_VALID

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3388]
**Describe the bug**

Node is out of synced:
```
Oct-25 01:33:19.037 [CHAIN]           error: Block error slot=60943, errCode=BLOCK_ERROR_EXECUTION_PAYLOAD_NOT_VALID code=BLOCK_ERROR_EXECUTION_PAYLOAD_NOT_VALID
Error: BLOCK_ERROR_EXECUTION_PAYLOAD_NOT_VALID
    at verifyBlockStateTransition (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/verifyBlock.ts:167:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at verifyBlock (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/verifyBlock.ts:38:10)
    at processChainSegment (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/index.ts:101:34)
    at JobItemQueue.runJob (/usr/app/node_modules/@chainsafe/lodestar/src/util/queue/itemQueue.ts:85:22)
Oct-25 01:33:28.243 [CHAIN]           error: Block error slot=60943, errCode=BLOCK_ERROR_EXECUTION_PAYLOAD_NOT_VALID code=BLOCK_ERROR_EXECUTION_PAYLOAD_NOT_VALID
Error: BLOCK_ERROR_EXECUTION_PAYLOAD_NOT_VALID
    at verifyBlockStateTransition (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/verifyBlock.ts:167:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at verifyBlock (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/verifyBlock.ts:38:10)
    at processChainSegment (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/index.ts:101:34)
    at JobItemQueue.runJob (/usr/app/node_modules/@chainsafe/lodestar/src/util/queue/itemQueue.ts:85:22)
Oct-25 01:33:32.337 []                 info: Syncing - 44000000 days left - 3.99e-9 slots/s - slot: 76042 (skipped 15101) - head: 60941 0x6d96…16b9 - finalized: 0x5072…6107:1902 - peers: 13
```

**Expected behavior**

No error

**Steps to Reproduce**

Sync pithos with lodestar - besu

**Comment by twoeths** [comment]
More logs:
```
Oct-22 23:13:34.423 [CHAIN]         ^[[36mverbose^[[39m: Block processed slot=60942, root=0x6ca1a0c068f1bbbd4f5290f3e1d6628761242fa4d960876707d210c0dbe6d4ee
```

note that 60942 is a missed block https://pithos-explorer.ethdevops.io/block/60942

then

```
Oct-22 23:13:36.546 [NETWORK]       ^[[36mverbose^[[39m: Received gossip block slot=60943, root=0xce3f�~@�1510, curentSlot=60943

Oct-22 23:13:39.784 [NETWORK]         ^[[34mdebug^[[39m: gossip - sync_committee - accept slot=60943, subnet=1
Oct-22 23:13:39.825 [CHAIN]           ^[[31merror^[[39m: Block error slot=60943, errCode=BLOCK_ERROR_EXECUTION_PAYLOAD_NOT_VALID code=BLOCK_ERROR_EXECUTION_PAYLOAD_NOT_VALID
Error: BLOCK_ERROR_EXECUTION_PAYLOAD_NOT_VALID
    at verifyBlockStateTransition (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/verifyBlock.ts:167:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at verifyBlock (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/verifyBlock.ts:38:10)
    at processBlock (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/index.ts:64:32)
    at Timeout.JobItemQueue.runJob [as _onTimeout] (/usr/app/node_modules/@chainsafe/lodestar/src/util/queue/itemQueue.ts:85:22)
Oct-22 23:13:39.826 [NETWORK]         ^[[31merror^[[39m: Error receiving block slot=60943, peer=16Uiu2HAmVE3SgQq6D2WpNMgzLBaHDUW9TG8yT1MM34ZuCEVj2Ge1 code=BLOCK_ERROR_EXECUTION_PAYLOAD_NOT_VALID
Error: BLOCK_ERROR_EXECUTION_PAYLOAD_NOT_VALID
    at verifyBlockStateTransition (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/verifyBlock.ts:167:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at verifyBlock (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/verifyBlock.ts:38:10)
    at processBlock (/usr/app/node_modules/@chainsafe/lodestar/src/chain/blocks/index.ts:64:32)
    at Timeout.JobItemQueue.runJob [as _onTimeout] (/usr/app/node_modules/@chainsafe/lodestar/src/util/queue/itemQueue.ts:85:22)
```

note that all block roots are correct as found in lodestar-geth:
```
Oct-22 23:13:35.197 [CHAIN]         ^[[36mverbose^[[39m: Block processed slot=60942, root=0x6ca1a0c068f1bbbd4f5290f3e1d6628761242fa4d960876707d210c0dbe6d4ee
Oct-22 23:13:36.919 [NETWORK]       ^[[36mverbose^[[39m: Received gossip block slot=60943, root=0xce3f�~@�1510, curentSlot=60943
Oct-22 23:13:38.384 [CHAIN]         ^[[36mverbose^[[39m: Block processed slot=60943, root=0xce3f6417e64bd8c6c3ee1dc1f3b31adb8c6b9e8802c4f786b3688a32fe191510
```

**Comment by twoeths** [comment]
found this from besu docker log

```
2021-10-25 02:18:51.123+00:00 | vert.x-worker-thread-0 | ERROR | MainnetBlockValidator | Attempted to import block 52223 with hash 0x6d5744a9f813f81bdd90e517c85bc4e273e758eda93cbdcca525a91d684cc518 but parent block 0x19f2b43ef5572883499a7560f68ed718ce7095bc83d3b1fee3e425ce9b93e191 was not present
```

`0x6d5744a9f813f81bdd90e517c85bc4e273e758eda93cbdcca525a91d684cc518` is eth1 block hash of block 60943 and `0x19f2b43ef5572883499a7560f68ed718ce7095bc83d3b1fee3e425ce9b93e191` is eth1 block of block 60941

Block 60941 was processed successfully in lodestar 
```
Oct-22 23:13:30.586 [CHAIN]         ^[[36mverbose^[[39m: Block processed slot=60941, root=0x6d964c2b6f6ccef1125e89e7e5fc0d5490aa13c53db9af585acd974eba1816b9
```

need to investigate why execution layer could not process the payload of block slot 60941

**Comment by twoeths** [comment]
this log shows that `0x19f2b43ef5572883499a7560f68ed718ce7095bc83d3b1fee3e425ce9b93e191` was really imported to the execution layer, however it was not found later

```
devops@pithos-lodestar-besu-1 ➜  ~ docker logs a1454e465b6c | grep 0x19f2b43ef5572883499a7560f68ed718ce7095bc83d3b1fee3e425ce9b93e191 | head -n 10
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/besu/lib/log4j-slf4j-impl-2.14.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/besu/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2021-10-22 23:13:30.660+00:00 | vert.x-worker-thread-0 | INFO  | EngineForkchoiceUpdated | Consensus fork-choice-update: head: 0x19f2b43ef5572883499a7560f68ed718ce7095bc83d3b1fee3e425ce9b93e191, finalized: 0x926181c832f182f7b0442ee9f26e40824e644167c71fb16b793cf62e41c63940
2021-10-22 23:13:39.685+00:00 | vert.x-worker-thread-0 | ERROR | MainnetBlockValidator | Attempted to import block 52223 with hash 0x6d5744a9f813f81bdd90e517c85bc4e273e758eda93cbdcca525a91d684cc518 but parent block 0x19f2b43ef5572883499a7560f68ed718ce7095bc83d3b1fee3e425ce9b93e191 was not present
```

**Comment by dapplion** [comment]
Old devnet, open new issue if it happens again
