### ISSUE TITLE
Canot start validator due to INACTIVITY_PENALTY_QUOTIENT_MERGE being undefined

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3437]
**Describe the bug**

Got this error when starting validator
```
Nov-17 09:38:54.318 []                 info: Genesis available
 ✖ Error: Invalid JSON container field: expected field INACTIVITY_PENALTY_QUOTIENT_MERGE is undefined
    at ContainerType.struct_convertFromJson (/usr/app/node_modules/@chainsafe/ssz/src/types/composite/container.ts:260:15)
    at ContainerType.fromJson (/usr/app/node_modules/@chainsafe/ssz/src/types/composite/abstract.ts:387:17)
    at Object.fromJson (/usr/app/node_modules/@chainsafe/lodestar-api/src/routes/config.ts:69:64)
    at Object.request (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/client.ts:75:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Function.initializeFromBeaconNode (/usr/app/node_modules/@chainsafe/lodestar-validator/src/validator.ts:98:32)
    at Object.validatorHandler [as handler] (/usr/app/node_modules/@chainsafe/lodestar-cli/src/cmds/validator/handler.ts:54:21)
```

**Expected behavior**

No error

**Comment by g11tech** [comment]
@tuyennhv on cb6 the beacon is not on chainsafe/lodestar:**next**, but validator is on chainsafe/lodestar:next
![image](https://user-images.githubusercontent.com/76567250/142193025-b25c11a9-9a09-4a22-982f-7ade59ec4663.png)

while on cb7, both are on the same version and cb7's api seems to be returning the merge preset fields.
I think migrating the beacon on :next will resolve the issue.

**Comment by dapplion** [comment]
Bumped the beacon node to `chainsafe/lodestar:next` and now it works well :+1:

However we should review the parsing of the config because that field is never used by the validator so it shouldn't have to crash for it not being available. Otherwise it would be impossible to interop with any client when we keep extending the config.

**Comment by g11tech** [comment]
@dapplion  this PR was done exactly for this reason: https://github.com/ChainSafe/lodestar/pull/3379
one can provide missing fields through `--paramsFile` option for the validator, so that appropriate values can be filled for the missing. 🙂

**Comment by dapplion** [comment]
> @dapplion this PR was done exactly for this reason: #3379 one can provide missing fields through `--paramsFile` option for the validator, so that appropriate values can be filled for the missing. slightly_smiling_face

But that's bad UX and very problematic like we found now. The field `INACTIVITY_PENALTY_QUOTIENT_MERGE` is not mandatory for the altair fork however our client crashes if the beacon node hasn't define it. That's not ok

**Comment by g11tech** [comment]
ok will think of what else can be done
