### ISSUE TITLE
[Kintsugi] Error producing block

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3563]
**Describe the bug**

This happens in kinsugi
```
Jan-03 16:21:36.066 []                error: Error proposing block slot=132083, validator=0x99b0…d6a3 message=Failed to produce block - Internal Server Error: Cannot get tree for index: 389, maxIndex: 8
Error: Failed to produce block - Internal Server Error: Cannot get tree for index: 389, maxIndex: 8
    at HttpClient.request (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/api/src/client/utils/httpClient.ts:91:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HttpClient.json (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/api/src/client/utils/httpClient.ts:58:12)
    at Object.request [as produceBlockV2] (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/api/src/client/utils/client.ts:72:19)
    at BlockProposingService.createAndPublishBlock (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/validator/src/services/block.ts:59:21)
```

**Expected behavior**

No error

**Steps to Reproduce**

curl `/eth/v2/validator/blocks/:slot`

**Comment by philknows** [comment]
Is this still happening @tuyennhv ? cc: @g11tech

**Comment by SeaMonkey82** [comment]
Yes.  Currently on v0.32.0/master/+105/a00ec5c0

```
Error: Failed to produce block - Internal Server Error: Cannot get tree for index: 477, maxIndex: 0
    at HttpClient.request (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/api/src/client/utils/httpClient.ts:91:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HttpClient.json (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/api/src/client/utils/httpClient.ts:58:12)
    at Object.request [as produceBlockV2] (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/api/src/client/utils/client.ts:72:19)
    at BlockProposingService.createAndPublishBlock (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/validator/src/services/block.ts:59:21)
    at async Promise.all (index 0)
```

I have yet to propose blocks with lodestar using geth, nethermind, or besu.
[lodestar-geth](https://beaconchain.kintsugi.themerge.dev/dashboard?validators=72438,72439,72440,72441,72442,72443,72444,72445)
[lodestar-nethermind](https://beaconchain.kintsugi.themerge.dev/dashboard?validators=72448,72449,72450,72451,72452,72453,72454,72455)
[lodestar-besu](https://beaconchain.kintsugi.themerge.dev/dashboard?validators=72526,72527,72528,72529,72530,72531,72532,72533)

**Comment by g11tech** [comment]
@philknows @SeaMonkey82 thanks for update, will look into it.

**Comment by g11tech** [comment]
@SeaMonkey82 @tuyennhv  Is this still coming? 
I can see @SeaMonkey82's nodes producing blocks in kintsugi with lodestar as well: https://beaconchain.kintsugi.themerge.dev/blocks?q=seam

 I think this was linked to the deposit tracker issue, which should have been resolved by using the new configuration out of the box via `--network kintsugi`

**Comment by SeaMonkey82** [comment]
> @SeaMonkey82 @tuyennhv Is this still coming? I can see @SeaMonkey82's nodes producing blocks in kintsugi with lodestar as well: https://beaconchain.kintsugi.themerge.dev/blocks?q=seam
> 
> I think this was linked to the deposit tracker issue, which should have been resolved by using the new configuration out of the box via `--network kintsugi`

Yes, this is correct.  Adding `--network kintsugi` allowed me to start proposing blocks, and I haven't noticed the error since.
