### ISSUE TITLE
[Kintsugi] Error on publishContributionAndProofs

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3572]
**Describe the bug**

There are a lot of errors like below in lodestar<>geth node

```
Jan-04 16:11:20.245 [API]             ^[[31merror^[[39m: Error on publishContributionAndProofs [0] slot=137731        , subCommitteeIndex=2 code=SYNC_COMMITTEE_ERROR_VALIDATOR_NOT_IN_SYNC_COMMITTEE, validatorIndex=56062
2213092 Error: SYNC_COMMITTEE_ERROR_VALIDATOR_NOT_IN_SYNC_COMMITTEE
2213093     at validateGossipSyncCommitteeExceptSig (/usr/app/node_modules/@chainsafe/lodestar/src/chain/validation/sy        ncCommittee.ts:100:11)
2213094     at validateSyncCommitteeGossipContributionAndProof (/usr/app/node_modules/@chainsafe/lodestar/src/chain/va        lidation/syncCommitteeContributionAndProof.ts:25:39)
2213095     at /usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:504:66
2213096     at Array.map (<anonymous>)
2213097     at Object.publishContributionAndProofs (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/i        ndex.ts:501:31)
2213098     at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:70:42)
2213099     at preHandlerCallback (/usr/app/node_modules/fastify/lib/handleRequest.js:124:28)
2213100     at preValidationCallback (/usr/app/node_modules/fastify/lib/handleRequest.js:107:5)
2213101     at handler (/usr/app/node_modules/fastify/lib/handleRequest.js:70:7)
2213102     at done (/usr/app/node_modules/fastify/lib/contentTypeParser.js:151:7)
```

**Expected behavior**
No error

**Comment by twoeths** [comment]
I took a look at slot 142749, we published 12 SyncCommitteeMessage:

```
Jan-05 08:54:52.002 []                ^[[34mdebug^[[39m: Signed SyncCommitteeMessage slot=142749, validatorIndex=56062
Jan-05 08:54:52.004 []                ^[[34mdebug^[[39m: Signed SyncCommitteeMessage slot=142749, validatorIndex=56548
Jan-05 08:54:52.005 []                ^[[34mdebug^[[39m: Signed SyncCommitteeMessage slot=142749, validatorIndex=56364
Jan-05 08:54:52.006 []                ^[[34mdebug^[[39m: Signed SyncCommitteeMessage slot=142749, validatorIndex=56411
Jan-05 08:54:52.007 []                ^[[34mdebug^[[39m: Signed SyncCommitteeMessage slot=142749, validatorIndex=56423
Jan-05 08:54:52.008 []                ^[[34mdebug^[[39m: Signed SyncCommitteeMessage slot=142749, validatorIndex=56071
Jan-05 08:54:52.009 []                ^[[34mdebug^[[39m: Signed SyncCommitteeMessage slot=142749, validatorIndex=56550
Jan-05 08:54:52.010 []                ^[[34mdebug^[[39m: Signed SyncCommitteeMessage slot=142749, validatorIndex=56918
Jan-05 08:54:52.011 []                ^[[34mdebug^[[39m: Signed SyncCommitteeMessage slot=142749, validatorIndex=56852
Jan-05 08:54:52.012 []                ^[[34mdebug^[[39m: Signed SyncCommitteeMessage slot=142749, validatorIndex=56690
Jan-05 08:54:52.013 []                ^[[34mdebug^[[39m: Signed SyncCommitteeMessage slot=142749, validatorIndex=56506
Jan-05 08:54:52.014 []                ^[[34mdebug^[[39m: Signed SyncCommitteeMessage slot=142749, validatorIndex=56333
Jan-05 08:54:52.265 []                 ^[[32minfo^[[39m: Published SyncCommitteeMessage slot=142749, count=12
```

as confirmed in https://beaconchain.kintsugi.themerge.dev/block/142749 , only the first 3 validators stay in sync committee, others are redundant, this log confirms that:

```
Jan-05 08:49:00.026 []                ^[[34mdebug^[[39m: Downloaded SyncDuties epoch=4460, dependentRoot=0x0000000000000000000000000000000000000000000000000000000000000000, count=3
```

it looks like there's a reorg and we keep merging different sync committee duties per epochs in same period https://github.com/ChainSafe/lodestar/blob/659e3e105aa934b4b638071a9e252ea0a4444c7d/packages/validator/src/services/syncCommitteeDuties.ts#L214 and it made a lot of redundant/wrong duties

we need to handle sync committee duties reorg anyway

**Comment by dapplion** [comment]
> it looks like there's a reorg and we keep merging different sync committee duties per epochs in same period 

Makes sense! Thanks for looking into this :pray:

**Comment by twoeths** [comment]
+ dependentRoot is not part of api spec and other clients (at least lighthouse) did not implement it. I think it's not likely the long reorg could happen over 256 epochs, it's not the same situation to attestation duties
+ for each epoch, we query duties for next sync period as well so maybe the reorg comes for these next period duties query. And when next period becomes current period, our duties could contain some redundant ones (since we keep merging to the period map).
