### ISSUE TITLE
Not all variable bytes consumed (kintsugi)

### ISSUE THREAD

**Issue by SeaMonkey82** [ChainSafe/lodestar#3627]
**Describe the bug**

beacon process fails to launch with error `Not all variable bytes consumed`

**Expected behavior**

Sync without error

**Steps to Reproduce**

Start beacon process.

**~~Screenshots~~ Output**

```
Jan-14 15:30:19.897 [SYNC]             info: BackfillSync - initializing from Checkpoint root=0x1bb18abd64584c21255111a221f83a31f276e39e0b53c2f877a5a381d50f8746, epoch=6585, slot=210720
 ✖ Error: message.body: Not all variable bytes consumed
    at ContainerType.struct_deserializeFromBytes (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/node_modules/@chainsafe/ssz/src/types/composite/container.ts:202:15)
    at ContainerType.fromBytes (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/node_modules/@chainsafe/ssz/src/types/composite/abstract.ts:335:17)
    at ContainerType.deserialize (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/node_modules/@chainsafe/ssz/src/types/composite/abstract.ts:342:17)
    at BlockArchiveRepository.decodeValue (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/lodestar/src/db/repositories/blockArchive.ts:37:59)
    at BlockArchiveRepository.valuesStream (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/db/src/abstractRepository.ts:168:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BlockArchiveRepository.valuesStream (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/lodestar/src/db/repositories/blockArchive.ts:109:22)
    at all (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/node_modules/it-all/index.js:6:20)
    at extractPreviousFinOrWsCheckpoint (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/lodestar/src/sync/backfill/backfill.ts:841:5)
    at Function.init (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/lodestar/src/sync/backfill/backfill.ts:257:42)
```

**Desktop (please complete the following information):**

- OS: Linux Mint
- Version: 20.3
- Branch: master
- Commit hash: 1bd730a0abdbb34bfc02a5e586c2256a287c3fcc

**Comment by SeaMonkey82** [comment]
Wiping the chain-db folder resolved this issue.

**Comment by g11tech** [comment]
@SeaMonkey82 did this ever come again?

**Comment by SeaMonkey82** [comment]
Not that I recall.
