### ISSUE TITLE
Unexpected BackfillSync log

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3640]
**Describe the bug**

Got this in one of the node, latest master:

```
Jan-20 03:15:45.273 [SYNC]            error: BackfillSync processor error message=InvalidWsCheckpoint root=0,51,39,237,194,129,170,240,73,236,184,19,226,209,225,219,98,249,131,9,236,59,86,81,14,151,236,6,176,118,110,132, epoch=68061, found at epoch=68061
Error: InvalidWsCheckpoint root=0,51,39,237,194,129,170,240,73,236,184,19,226,209,225,219,98,249,131,9,236,59,86,81,14,151,236,6,176,118,110,132, epoch=68061, found at epoch=68061
    at BackfillSync.checkIfCheckpointSyncedAndValidate (/root/lodestar/packages/lodestar/src/sync/backfill/backfill.ts:524:15)
    at BackfillSync.sync (/root/lodestar/packages/lodestar/src/sync/backfill/backfill.ts:386:11)
```

**Expected behavior**

Should log root hex instead

**Steps to Reproduce**

Run node with prater network

**Desktop (please complete the following information):**

- Branch: master
- Commit hash: 9be6d13

**Comment by dapplion** [comment]
Closing until refactoring backfill sync
