### ISSUE TITLE
Kurtosis [Merge testnet] runs: lodestar nodes downscores and loose each other incase ELs don't sync up

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3644]
### Scenario
Sometimes in the mergenet runs, on the `bellatrix` epoch when the execution payload starts to come in, the respective EL are generally at diffierent TTD blocks, and hence respond with `SYNCING` status.
Because as per optimistic spec, we can't accept block with SYNCING staus at the merge transition, and the EL's are supposed to sync up, so that one of the EL stops giving syncing status.

However, if the ELs don't sync up fast enought, the each other nodes start rejecting each other blocks, resulting into the each banning the other and loosing the peers.

Expected:
The CLs should not loose each other and at some point resolve the chain in the favor of one or the other.
 
Example log:
Node 0:
at bellatrix(merge epoch):
```
Jan-20 09:18:38.501 []                 info: Synced - slot: 63 - head: 63 0x7ad7…35db - finalized: 0x0000…0000:0 - peers: 1
Jan-20 09:18:41.509 []                 info: Synced - slot: 64 - head: 64 0xc54e…2598 - execution: valid(0x3e0d…22c0) - finalized: 0x0000…0000:0 - peers: 1
Jan-20 09:18:43.432 [CHAIN]           error: Block error slot=65, errCode=BLOCK_ERROR_EXECUTION_ERROR code=BLOCK_ERROR_EXECUTION_ERROR, errorMessage=not safe to import SYNCING payload within 128 of currentSlot
Error: BLOCK_ERROR_EXECUTION_ERROR
    at verifyBlockStateTransition (/usr/app/packages/lodestar/src/chain/blocks/verifyBlock.ts:231:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at verifyBlock (/usr/app/packages/lodestar/src/chain/blocks/verifyBlock.ts:46:40)
    at processBlock (/usr/app/packages/lodestar/src/chain/blocks/index.ts:64:32)
    at Timeout.JobItemQueue.runJob [as _onTimeout] (/usr/app/packages/lodestar/src/util/queue/itemQueue.ts:85:22)
Jan-20 09:18:43.433 [NETWORK] 
```
after couple of such errors:
```
Jan-20 09:18:55.353 [CHAIN]           error: Block error slot=65, errCode=BLOCK_ERROR_EXECUTION_ERROR code=BLOCK_ERROR_EXECUTION_ERROR, errorMessage=not safe to import SYNCING payload within 128 of currentSlot
Error: BLOCK_ERROR_EXECUTION_ERROR
    at verifyBlockStateTransition (/usr/app/packages/lodestar/src/chain/blocks/verifyBlock.ts:231:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at verifyBlock (/usr/app/packages/lodestar/src/chain/blocks/verifyBlock.ts:46:40)
    at processBlock (/usr/app/packages/lodestar/src/chain/blocks/index.ts:64:32)
    at Timeout.JobItemQueue.runJob [as _onTimeout] (/usr/app/packages/lodestar/src/util/queue/itemQueue.ts:85:22)
Jan-20 09:18:55.354 [SYNC]            error: Removing unknown parent block root=0xce1916f623fa7d1c2596dcbce5a2706517afaf0352d689b2123c6d4d13cde13b, slot=65
Jan-20 09:18:55.354 [SYNC]            error: Removing unknown parent block root=0x32824e30ec8dcd9c9c9098316e16eda429e9b34d0d23a3c4e898b45835a8e452, slot=68
Jan-20 09:18:55.354 [SYNC]            error: Removing unknown parent block root=0xe265516d08bdba89a9f63b14c8e1981e87cc5675987e01559125748ffd184681, slot=69
```
finally loses the peer:
```
48183, slot=77
Jan-20 09:19:34.475 [SYNC]            error: Removing unknown parent block root=0x9032f60ca13587c81ad8c87ca42be5ccab0b25852a20ce7cee55c2e3c77db0f6, slot=82
Jan-20 09:19:35.505 []                 info: Synced - slot: 82 (skipped 1) - head: 81 0x5dc6…3b63 - execution: valid(0x66e8…b42a) - finalized: 0x0000…0000:0 - peers: 1
Jan-20 09:19:38.502 []                 info: Synced - slot: 83 - head: 83 0xb609…405a - execution: valid(0x2087…7b4d) - finalized: 0x0000…0000:0 - peers: 1
Jan-20 09:19:41.501 []                 info: Searching peers - peers: 0 - slot: 84 (skipped 1) - head: 83 0xb609…405a - execution: valid(0x2087…7b4d) - finalized: 0x0000…0000:0
Jan-20 09:19:44.501 []                 info: Searching peers - peers: 0 - slot: 85 (skipped 2) - head: 83 0xb609…405a - execution: valid(0x2087…7b4d) - finalized: 0x0000…0000:0
Jan-20 09:19:47.501 []                 info: Searching peers - peers: 0 - slot: 86 (skipped 3) - head: 83 0xb609…405a - execution: valid(0x2087…7b4d) - finalized: 0x0000…0000:0
Jan-20
```

**Comment by g11tech** [comment]
stale
