### ISSUE TITLE
Error pushing notifyForkchoiceUpdate (kintsugi-lodestar-besu)

### ISSUE THREAD

**Issue by SeaMonkey82** [ChainSafe/lodestar#3647]
**Describe the bug**

Restarting the lodestar beacon results in a flood of `error: Error pushing notifyForkchoiceUpdate()`.  Sync appears to resume correctly once the head of the chain is reached.

**Expected behavior**

Sync without error

**Steps to Reproduce**

1. Start besu
2. Sync lodestar beacon
3. Stop lodestar beacon
4. Start lodestar beacon

**~~Screenshots~~ Output**

```
Jan-20 20:35:11.819 [CHAIN]           error: Error pushing notifyForkchoiceUpdate() headBlockHash=0x70dc2cf7b44b0d198dfc3eda2f9d5e4ca70cd8525999c2303635e27f02e8c42e, finalizedBlockHash=0x7ad668983cd80d380a9053b5bd31427096e7b6499f2baf8d0bb7f281b5e1efe9 message=Bad Request: {
  "jsonrpc" : "2.0",
  "id" : 1179,
  "error" : {
    "code" : -32600,
    "message" : "Invalid Request"
  }
}
Error: Bad Request: {
  "jsonrpc" : "2.0",
  "id" : 1179,
  "error" : {
    "code" : -32600,
    "message" : "Invalid Request"
  }
}
    at JsonRpcHttpClient.fetchJsonOneUrl (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:138:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at JsonRpcHttpClient.fetchJson (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:82:16)
    at JsonRpcHttpClient.fetch (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:59:34)
Jan-20 20:35:11.856 [CHAIN]           error: Error pushing notifyForkchoiceUpdate() headBlockHash=0x2d43a23523cb5995fba157472d84f59e6e8a408f7a792ed1d574776b0d23fd5e, finalizedBlockHash=0x7ad668983cd80d380a9053b5bd31427096e7b6499f2baf8d0bb7f281b5e1efe9 message=Bad Request: {
  "jsonrpc" : "2.0",
  "id" : 1181,
  "error" : {
    "code" : -32600,
    "message" : "Invalid Request"
  }
}
Error: Bad Request: {
  "jsonrpc" : "2.0",
  "id" : 1181,
  "error" : {
    "code" : -32600,
    "message" : "Invalid Request"
  }
}
    at JsonRpcHttpClient.fetchJsonOneUrl (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:138:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at JsonRpcHttpClient.fetchJson (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:82:16)
    at JsonRpcHttpClient.fetch (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:59:34)
Jan-20 20:35:18.340 []                 info: Searching peers - peers: 0 - slot: 255751 (skipped 41) - head: 255710 0x39c7…e9c9 - execution: valid(0x2d43…fd5e) - finalized: 0xa198…2e63:7988
Jan-20 20:35:18.362 [CHAIN]           error: Error pushing notifyForkchoiceUpdate() headBlockHash=0xb4660027aa3541a8bb5c55da52c6933f6f5f85d54386271c42dd011e7456626f, finalizedBlockHash=0x7ad668983cd80d380a9053b5bd31427096e7b6499f2baf8d0bb7f281b5e1efe9 message=Bad Request: {
  "jsonrpc" : "2.0",
  "id" : 1183,
  "error" : {
    "code" : -32600,
    "message" : "Invalid Request"
  }
}
Error: Bad Request: {
  "jsonrpc" : "2.0",
  "id" : 1183,
  "error" : {
    "code" : -32600,
    "message" : "Invalid Request"
  }
}
    at JsonRpcHttpClient.fetchJsonOneUrl (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:138:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at JsonRpcHttpClient.fetchJson (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:82:16)
    at JsonRpcHttpClient.fetch (/home/seamonkey/Downloads/merge-testnets/kintsugi/lodestar/packages/lodestar/src/eth1/provider/jsonRpcHttpClient.ts:59:34)
```

**Desktop (please complete the following information):**

- OS: Linux Mint
- Version: 20.3
- Branch: master
- Commit hash: 9be6d13474b985ce4a735a6070ee08a972801041

**Comment by philknows** [comment]
Although this version was several commits back from where we're at now, I'd like to know if this persists as we move forward with the new Kiln testnet before putting in more time to dig deeper into it. Feel free to now if time permits @g11tech, but after spec freeze will be the best time to start hammering away at these bugs IMO. Thanks for posting the issue though!

**Comment by g11tech** [comment]
@philknows @SeaMonkey82  My theory behind this is: 
On restarts lodestar always start from a little behind till it synced last time (as we start from last finalized state written into the DB which could be a few epochs behind). 
So the fcUs request by lodestar to reorg the chain back might be causing these errors. But yes, this would need to be investigated and confirmed.

**Comment by dapplion** [comment]
Related to https://github.com/ChainSafe/lodestar/issues/3717

Closing for https://github.com/ChainSafe/lodestar/issues/4000
