### ISSUE TITLE
Error adding gossip attestations to forkchoice

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3665]
**Describe the bug**

Found this in the log of prater node:
```
Jan-25 11:28:50.045 [NETWORK]         error: Error adding aggregated attestation to forkchoice slot=2216511 code=FORKCHOICE_ERROR_INVALID_ATTESTATION, err={"code":"PAST_EPOCH","attestationEpoch":69265,"currentEpoch":69267}
Error: FORKCHOICE_ERROR_INVALID_ATTESTATION
    at ForkChoice.validateAttestationData (/root/lodestar/packages/fork-choice/src/forkChoice/forkChoice.ts:786:13)
    at ForkChoice.validateOnAttestation (/root/lodestar/packages/fork-choice/src/forkChoice/forkChoice.ts:763:10)
    at ForkChoice.onAttestation (/root/lodestar/packages/fork-choice/src/forkChoice/forkChoice.ts:421:10)
    at beacon_aggregate_and_proof (/root/lodestar/packages/lodestar/src/network/gossip/handlers/index.ts:179:28)
    at Object.gossipValidatorFn [as beacon_aggregate_and_proof] (/root/lodestar/packages/lodestar/src/network/gossip/validation/index.ts:110:7)
    at Eth2Gossipsub.validate (/root/lodestar/packages/lodestar/src/network/gossip/gossipsub.ts:282:7)
    at Eth2Gossipsub._processRpcMessage (/root/lodestar/node_modules/libp2p-interfaces/src/pubsub/index.js:449:7)
Jan-25 11:28:50.707 [NETWORK]         error: Error adding aggregated attestation to forkchoice slot=2216511 code=FORKCHOICE_ERROR_INVALID_ATTESTATION, err={"code":"PAST_EPOCH","attestationEpoch":69265,"currentEpoch":69267}
Error: FORKCHOICE_ERROR_INVALID_ATTESTATION
    at ForkChoice.validateAttestationData (/root/lodestar/packages/fork-choice/src/forkChoice/forkChoice.ts:786:13)
```

**Expected behavior**

No error

**Comment by twoeths** [comment]
this happens at the last slot of epoch. At the time we validate aggregated attestation, the slot is acceptable. Right after that, the clock is ticked to next epoch so the aggregated attestation becomes invalid when passing to forkchoice.

The only issue I see is logging level: the log is at error level while it's not really an error.
