### ISSUE TITLE
BackfillSync logs frequent errors

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3690]
**Describe the bug**

At least in one of our Mainnet nodes BackfillSync errors logs are the only found log besides the notifier. Some examples include

```
Feb-02 00:01:17.825 [SYNC]            error: BackfillSync sync error message=stream reset
Error: stream reset
    at Object.reset (/usr/app/node_modules/libp2p-mplex/src/stream.js:71:27)
    at Mplex._handleIncoming (/usr/app/node_modules/libp2p-mplex/src/mplex.js:227:16)
    at /usr/app/node_modules/libp2p-mplex/src/mplex.js:156:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Mplex.sink (/usr/app/node_modules/libp2p-mplex/src/mplex.js:149:9)
``` 

```
Feb-01 23:59:27.869 [SYNC]            error: BackfillSync sync error code=not_anchored
Error: not_anchored
    at verifyBlockSequence (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/verify.ts:32:15)
    at BackfillSync.syncRange (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/backfill.ts:786:68)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BackfillSync.sync (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/backfill.ts:441:11)
Feb-01 23:59:28.353 [SYNC]            error: BackfillSync sync error code=not_anchored
Error: not_anchored
    at verifyBlockSequence (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/verify.ts:32:15)
    at BackfillSync.syncRange (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/backfill.ts:786:68)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BackfillSync.sync (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/backfill.ts:441:11)
```

```
Feb-01 23:46:25.930 [SYNC]            error: BackfillSync sync error code=not_anchored
Error: not_anchored
    at verifyBlockSequence (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/verify.ts:32:15)
    at BackfillSync.syncRange (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/backfill.ts:786:68)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BackfillSync.sync (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/backfill.ts:441:11)
Feb-01 23:46:26.543 [SYNC]            error: BackfillSync sync error code=not_anchored
Error: not_anchored
    at verifyBlockSequence (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/verify.ts:32:15)
    at BackfillSync.syncRange (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/backfill.ts:786:68)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BackfillSync.sync (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/backfill.ts:441:11)
Feb-01 23:46:27.046 [SYNC]            error: BackfillSync sync error message=InvalidBlockSyncedFromPeer
Error: InvalidBlockSyncedFromPeer
    at BackfillSync.syncBlockByRoot (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/backfill.ts:731:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BackfillSync.sync (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/backfill.ts:436:11)
```

```
Feb-01 23:06:17.795 [SYNC]            error: BackfillSync sync error method=beacon_blocks_by_range, encoding=ssz_snappy, peer=16...RPU3qj, code=REQUEST_ERROR_DIAL_TIMEOUT
Error: REQUEST_ERROR_DIAL_TIMEOUT
    at sendRequest (/usr/app/node_modules/@chainsafe/lodestar/src/network/reqresp/request/index.ts:173:13)
    at ReqResp.sendRequest (/usr/app/node_modules/@chainsafe/lodestar/src/network/reqresp/reqResp.ts:156:22)
    at ReqResp.beaconBlocksByRange (/usr/app/node_modules/@chainsafe/lodestar/src/network/reqresp/reqResp.ts:116:20)
    at BackfillSync.syncRange (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/backfill.ts:767:20)
    at BackfillSync.sync (/usr/app/node_modules/@chainsafe/lodestar/src/sync/backfill/backfill.ts:441:11)
```

**Expected behavior**

We must log un-expected errors, however we should review why BackfillSync in particular encounters frequent errors and maybe consider increasing the retry count before logging errors to console.

**Comment by dapplion** [comment]
Closing, re-open if it still happens when backfill is refactored
