### ISSUE TITLE
Empty SyncCommitteeCache error on a local devnet run

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3752]
This error came up on the kurtosis local testnet runs (2 lodestar beacon nodes with attached validators), where altair epoch =1, bellatrix 2 and was consistently reproducible.
```
Feb-11 16:59:56.001 []                 info: Synced - slot: -1 - head: 0 0xf9ba…d781 - finalized: 0x0000…0000:0 - peers: 1
Feb-11 16:59:58.004 [NETWORK]          info: Subscribing gossip topics to next fork nextFork=bellatrix
Feb-11 16:59:58.004 [NETWORK]          info: Suscribing to random attnets to next fork nextFork=bellatrix
Feb-11 16:59:58.005 [NETWORK]          info: Suscribing to random attnets to next fork nextFork=bellatrix
Feb-11 16:59:58.006 [NETWORK]          info: Subscribed gossip core topics
Feb-11 16:59:58.012 [SYNC]             info: Subscribed gossip core topics
Feb-11 16:59:58.477 [API]             error: Req req-h getSyncCommitteeDuties error message=Empty SyncCommitteeCache
Error: Empty SyncCommitteeCache
    at SyncCommitteeCacheEmpty.get validatorIndexMap [as validatorIndexMap] (/usr/app/node_modules/@chainsafe/lodestar-beacon-state-transition/src/cache/syncCommitteeCache.ts:27:11)
    at Object.getSyncCommitteeDuties (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:392:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:70:23)
Feb-11 16:59:58.535 [API]             error: Req req-j getSyncCommitteeDuties error message=Empty SyncCommitteeCache
Error: Empty SyncCommitteeCache
    at SyncCommitteeCacheEmpty.get validatorIndexMap [as validatorIndexMap] (/usr/app/node_modules/@chainsafe/lodestar-beacon-state-transition/src/cache/syncCommitteeCache.ts:27:11)
    at Object.getSyncCommitteeDuties (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:392:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:70:23)
```

Expected: no error

**Comment by dapplion** [comment]
So ALTAIR_FORK_EPOCH = 1, and this error happens at slot -1 all the way through epoch 1? Did the error stop at some point?

Seems that the validator is requesting for sync committee too early, could that be?

**Comment by g11tech** [comment]
> So ALTAIR_FORK_EPOCH = 1, and this error happens at slot -1 all the way through epoch 1? Did the error stop at some point?
> 
> Seems that the validator is requesting for sync committee too early, could that be?

All i remember for now its a huge scroll of screen filled with these errors and yes, it resolves after this storm is over. Will replicate and update! :+1:

**Comment by dapplion** [comment]
The validator client starts requesting duties 1 epoch early

https://github.com/ChainSafe/lodestar/blob/e274b2139d7603e89c8bed91197022d224451b0f/packages/validator/src/services/syncCommitteeDuties.ts#L17-L18

could this be the cause of the errors?

- I'm not sure why that would result in a flood of errors. It should try once and error.
- Is the beacon node able to provide syncCommittee one epoch early? Otherwise we should set the constant to zero

**Comment by g11tech** [comment]
> The validator client starts requesting duties 1 epoch early
> 
> https://github.com/ChainSafe/lodestar/blob/e274b2139d7603e89c8bed91197022d224451b0f/packages/validator/src/services/syncCommitteeDuties.ts#L17-L18
> 
> could this be the cause of the errors?

Most likely as timeline lines up!

>     * I'm not sure why that would result in a flood of errors. It should try once and error.

yes you are correct! just two throws for current and next
```
Feb-18 08:38:47.501[]                 info: Synced - slot: -3 - head: 0 0xed9b…c00a - finalized: 0x0000…0000:0 - peers: 1
Feb-18 08:38:50.502[]                 info: Synced - slot: -2 - head: 0 0xed9b…c00a - finalized: 0x0000…0000:0 - peers: 1
Feb-18 08:38:53.502[]                 info: Synced - slot: -1 - head: 0 0xed9b…c00a - finalized: 0x0000…0000:0 - peers: 1
Feb-18 08:38:55.017[NETWORK]          info: Subscribing gossip topics to next fork nextFork=bellatrix
Feb-18 08:38:55.017[NETWORK]          info: Suscribing to random attnets to next fork nextFork=bellatrix
Feb-18 08:38:55.018[NETWORK]          info: Suscribing to random attnets to next fork nextFork=bellatrix
Feb-18 08:38:55.018[NETWORK]          info: Subscribed gossip core topics
Feb-18 08:38:55.025[SYNC]             info: Subscribed gossip core topics
Feb-18 08:38:55.027[API]             error: Req req-g getSyncCommitteeDuties error  Empty SyncCommitteeCache
Error: Empty SyncCommitteeCache
    at SyncCommitteeCacheEmpty.get validatorIndexMap [as validatorIndexMap] (/usr/app/node_modules/@chainsafe/lodestar-beacon-state-transition/src/cache/syncCommitteeCache.ts:27:11)
    at Object.getSyncCommitteeDuties (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:392:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:70:23)
Feb-18 08:38:55.126[API]             error: Req req-j getSyncCommitteeDuties error  Empty SyncCommitteeCache
Error: Empty SyncCommitteeCache
    at SyncCommitteeCacheEmpty.get validatorIndexMap [as validatorIndexMap] (/usr/app/node_modules/@chainsafe/lodestar-beacon-state-transition/src/cache/syncCommitteeCache.ts:27:11)
    at Object.getSyncCommitteeDuties (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:392:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:70:23)
Feb-18 08:38:56.500[]                 info: Synced - slot: 0 - head: 0 0xed9b…c00a - finalized: 0x0000…0000:0 - peers: 1
Feb-18 08:38:59.501[]                 info: Synced - slot: 1 - head: 1 0x911e…2c66 - finalized: 0x0000…0000:0 - peers: 1
Feb-18 08:39:02.500[]                 info: Synced - slot: 2 - head: 2 0xc22d…78d1 - finalized: 0x0000…0000:0 - peers: 1
Feb-18 08:39:05.501[]                 info: Synced - slot: 3 - head: 3 0x4820…c399 - finalized: 0x0000…0000:0 - peers: 1
```

I think the scroll of error was for finalityHeader errors, for which I see you opened a PR! :slightly_smiling_face: 

> 
>     * Is the beacon node able to provide syncCommittee one epoch early? Otherwise we should set the constant to zero

No, we have this pre-altair:

```
/** Placeholder object for pre-altair fork */
export class SyncCommitteeCacheEmpty implements SyncCommitteeCache {
  get validatorIndices(): ValidatorIndex[] {
    throw Error("Empty SyncCommitteeCache");
  }

  get validatorIndexMap(): SyncComitteeValidatorIndexMap {
    throw Error("Empty SyncCommitteeCache");
  }
}
```
