### ISSUE TITLE
Error printed to dial each character of the IP address

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3762]
**Describe the bug**

With current master

```
Feb-15 16:00:23.358 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50.65.36.10:9000
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.358 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50.65.36.10:900
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.358 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50.65.36.10:90
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.358 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50.65.36.10:9
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.358 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50.65.36.10:
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.358 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50.65.36.10
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.358 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50.65.36.1
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.359 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50.65.36.
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.359 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50.65.36
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.359 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50.65.3
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.359 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50.65.
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.359 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50.65
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.359 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50.6
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.359 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50.
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.359 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 50
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.359 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 5
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb-15 16:00:23.359 [NETWORK]         debug: Error dialing discovered peer peer=16...xQtiG7 message=Error: connect ECONNREFUSED 
AggregateError: Error: connect ECONNREFUSED 50.65.36.10:9000
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Expected behavior**

Dial the full IP

**Comment by dapplion** [comment]
The full error below `Error: connect ECONNREFUSED 50.65.36.10:9000` shows the proper IP, is this a logger issue?

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
