### ISSUE TITLE
Invalid State Root error

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3764]
**Describe the bug**

With latest master, this error happened twice from yesterday:
```
ull,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]},"shift":15,"tail":[0,0,0,0,0,0,0,0,0,0,0,0,0,0],"length":277294}}}}
Feb 15 16:05:25 vmi768848 lodestar[263068]: Error: BLOCK_ERROR_INVALID_STATE_ROOT
Feb 15 16:05:25 vmi768848 lodestar[263068]:     at verifyBlockStateTransition (/home/staker/lodestar/packages/lodestar/src/chain/blocks/verifyBlock.ts:276:11)
Feb 15 16:05:25 vmi768848 lodestar[263068]:     at verifyBlock (/home/staker/lodestar/packages/lodestar/src/chain/blocks/verifyBlock.ts:45:40)
Feb 15 16:05:25 vmi768848 lodestar[263068]:     at processChainSegment (/home/staker/lodestar/packages/lodestar/src/chain/blocks/index.ts:101:34)
Feb 15 16:05:25 vmi768848 lodestar[263068]:     at JobItemQueue.runJob (/home/staker/lodestar/packages/lodestar/src/util/queue/itemQueue.ts:90:22)
```

memory spiked due to this circular reference log

```
"CIRCULAR_REFERENCE","value":{"pubkey":"0x93b67282fb969f1edaed74b3783a00cea5db1d78c52bca349d10b64294c412e6cceeecf635544ea4e74e270b68b2a0a0","withdrawalCredentials":"0x00be4ea92c089d35c3193aa6273bfceec7304c76807eadf3e5b7e82ab61316f9","effectiveBalance":32000000000,"slashed":false,"activationEligibilityEpoch":0,"activationEpoch":0,"exitEpoch":null,"withdrawableEpoch":null}}},"_right":{"h0":1482271310,"h1":-296990451,"h2":-1327100512,"h3":-1538294996,"h4":-858908230,"h5":-694385282,"h6":370182545,"h7":1063229127,"_left":{"h0":-2020796176,"h1":1898865535,"h2":-114344170,"h3":-1873026616,"h4":-548623425,"h5":1441317735,"h6":178512011,"h7":-602916184,"type":"CIRCULAR_REFERENCE"
```

peers left us, and some node could recover, some couldn't

**Expected behavior**

+ Root cause is "Invalid state root" issue
+ Make sure no giant "CIRCULAR_REFERENCE" log

**Comment by twoeths** [comment]
So I was able to download preState, postState and the signedBlock of the issue. It turns out the preState is incorrect, and the preState is actually a checkpoint state (which is produced right after we `processEpoch`)

1. If I download state 2365150 and process block 2365154, it works as expected.

2. If I run state transition from download pre state with the downloaded signed block 2365154, I do get the "incorrect state root" error
3. It means the downloaded Prestate (slot 2365152) is incorrect, compared to downloaded state 2365150 processing to the next epoch (which becomes state at slot 2365152), the only difference is at validator 277249:
```json
{
         "activation_eligibility_epoch": "18446744073709551615"
         "activation_epoch": "18446744073709551615"
      -  "effective_balance": "16000000000"
      +  "effective_balance": "32000000000"
         "exit_epoch": "18446744073709551615"
         "pubkey": "0x800f9f44afe18c16a673d35a909ee8ac9d0bb8bedbbf222163d0ac2b3bebec6817b2f28c9e89bb71e3a7525320e4705f"
         "slashed": false
         "withdrawable_epoch": "18446744073709551615"
```

somehow the effective balance of validator 277249 is 16ETH while it should be 32ETH. 

I notice that the issue happens at epoch 73911, however validator 277249 only submitted attestations from epoch 73927 as shown in https://prater.beaconcha.in/validator/277249#attestations
