### ISSUE TITLE
Requesting JSON representation of state returns Internal Server Error

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#3872]
**Describe the bug**

Requesting the state via the endpoint:  http://localhost:{port}/eth/v1/debug/beacon/states/:stateId leads to an internal error being returned and the following error logged:

```
TypeError: Cannot read properties of undefined (reading 'length')
    at CompositeListType.struct_getLength (/lodestar/node_modules/@chainsafe/ssz/src/types/composite/list.ts:376:18)
    at CompositeListType.struct_convertToJson (/lodestar/node_modules/@chainsafe/ssz/src/types/composite/array.ts:474:37)
    at CompositeListType.toJson (/lodestar/node_modules/@chainsafe/ssz/src/types/composite/abstract.ts:394:17)
    at ContainerType.struct_convertToJson (/lodestar/node_modules/@chainsafe/ssz/src/types/composite/container.ts:273:82)
    at ContainerType.toJson (/lodestar/node_modules/@chainsafe/ssz/src/types/composite/abstract.ts:394:17)
    at Object.toJson (/lodestar/packages/api/src/utils/types.ts:117:22)
    at Object.handler (/lodestar/packages/api/src/server/debug.ts:28:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 ```

Requesting the binary representation of the state (by setting header: accept: application/octet-stream) works fine. That is:

```
curl -H "accept: application/octet-stream" http://localhost:9596/eth/v1/debug/beacon/states/head > state
```

**Expected behavior**

Requesting the JSON representation of state should work.

**Comment by dapplion** [comment]
Just run this command against current master and got the state without errors. Please re-open if happens again

```
curl -H "accept: application/octet-stream" http://localhost:9596/eth/v1/debug/beacon/states/head > state
```
