### ISSUE TITLE
ENOTEMPTY: directory not empty peerstore.pre-0.36.0.bak

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3902]
**Describe the bug**

All our instances in the prater beta group went offline due to the same error

```
Apr 09 15:43:31 contabo-13 beacon_run.sh[1462791]: Apr-09 15:43:31.476[]                 info: Lodestar version=v0.36.0/HEAD//43111801 (git), network=prater
Apr 09 15:43:31 contabo-13 beacon_run.sh[1462791]: Apr-09 15:43:31.512[]                 info: Connected to LevelDB database name=/home/devops/beacon/peerstore
Apr 09 15:43:31 contabo-13 beacon_run.sh[1462791]:  ✖ Error: ENOTEMPTY: directory not empty, rename '/home/devops/beacon/peerstore' -> '/home/devops/beacon/peerstore.pre-0.36.0.bak'
Apr 09 15:43:31 contabo-13 beacon_run.sh[1462791]:     at Object.renameSync (node:fs:980:3)
Apr 09 15:43:31 contabo-13 beacon_run.sh[1462791]:     at deleteOldPeerstorePreV036 (/usr/src/lodestar/packages/cli/src/migrations/deleteOldPeerstore.ts:35:8)
Apr 09 15:43:31 contabo-13 beacon_run.sh[1462791]:     at Object.beaconHandler [as handler] (/usr/src/lodestar/packages/cli/src/cmds/beacon/handler.ts:60:3)
```

**Expected behavior**

This backup is complimentary, and has nuked servers multiple times in the past @wemeetagain can you check if it's really necessary to keep this backup?

**Comment by wemeetagain** [comment]
It's not necessary to keep the backup. Especially considering we only decided to keep it as a precautionary step, with no plan or desire to use it in the future.
