### ISSUE TITLE
Timeout publishing unaggregated attestation

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3922]
**Describe the bug**

There's a missed attestation in contabo-16, the attestation reached the server too late (20s delay)

```
Apr-13 22:00:25.898[VMON]            ^[[34mdebug^[[39m: Local validator published unaggregated attestation validatorIndex=257082, slot=2781600, committeeIndex=48, subnet=48, sentPeers=20, delaySec=20.79200005531311
```

at the validator side, it throws Timeout error
```
Apr-13 22:00:25.020[]                ^[[31merror^[[39m: Error publishing attestations slot=2781600, index=48 Timeout request
Error: Timeout request
    at HttpClient.request (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:111:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HttpClient.json (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:66:12)
    at Object.request [as submitPoolAttestations] (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/client.ts:74:19)
    at AttestationService.publishAttestations (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:177:9)
```

**Expected behavior**

No timeout error

**Comment by twoeths** [comment]
root cause is #4002
