### ISSUE TITLE
Error syncing lightclient

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3933]
**Describe the bug**

Got this error syncing lightclient from finalized foot of epoch 86000
```
Error sync {} Error: Invalid aggregate signature
    at assertValidSignedHeader (/Users/tuyennguyen/Projects/lodestar/packages/light-client/src/validation.ts:161:11)
    at assertValidLightClientUpdate (/Users/tuyennguyen/Projects/lodestar/packages/light-client/src/validation.ts:51:3)
    at Lightclient.processSyncCommitteeUpdate (/Users/tuyennguyen/Projects/lodestar/packages/light-client/src/index.ts:458:33)
    at Lightclient.sync (/Users/tuyennguyen/Projects/lodestar/packages/light-client/src/index.ts:248:14)
    at Lightclient.runLoop (/Users/tuyennguyen/Projects/lodestar/packages/light-client/src/index.ts:274:11)
```

`signedHeaderRoot=0x5ff5d5f10b63f56b5a032ffe53f082d3cead4f627a4e1003eccb157d197be6b5, signedHeaderSlot=2785278`

**Expected behavior**

No error

**Comment by twoeths** [comment]
This actually is an edge case where the attested header belongs to sync period 339 while the block containing syncAggregate (2785280) belongs to sync period 340. So lightclient used sync commitee 340 to validate attested header of sync period 339.

In this case, the LightClient server should store `PartialLightClientUpdate` for sync period 340 instead of 339.
