### ISSUE TITLE
PeerManager failed to connect to subnet peers

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#3940]
**Describe the bug**

In hetzner-c0, there is a missed attestation after I deploy master there:
```
Apr-20 02:54:24.422[]                ^[[31merror^[[39m: Error publishing attestations slot=3633270 Internal Server Error: PublishError.InsufficientPeers
Error: Internal Server Error: PublishError.InsufficientPeers
    at HttpClient.request (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:109:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HttpClient.json (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/httpClient.ts:71:12)
    at Object.request [as submitPoolAttestations] (/usr/app/node_modules/@chainsafe/lodestar-api/src/client/utils/client.ts:74:19)
    at AttestationService.signAndPublishAttestations (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:156:9)
    at AttestationService.runAttestationTasks (/usr/app/node_modules/@chainsafe/lodestar-validator/src/services/attestation.ts:69:5)
```

PeerManager is supposed to find subnet peers before validator submit subnet attestations but it failed to do that

**Expected behavior**

PeerManager should be able to find and connect to subnet peers before validators submit subnet attestations

**Comment by twoeths** [comment]
part of #3527

**Comment by twoeths** [comment]
it shows that some of our peers have 0 long lived subnets, we should prefer disconnecting those peers per heartbeat 

<img width="796" alt="Screen Shot 2022-04-22 at 10 14 46" src="https://user-images.githubusercontent.com/10568965/164589604-d9d9d7c6-9254-4296-b3d1-67c9dd6b504c.png">


also just double check that lighthouse does that

**Comment by twoeths** [comment]
`grep -e "PublishError.InsufficientPeers" -rn validator*.log | wc -l` returns 100 after 4 days

also there are a lot of unaggregated attestations that's sent to 1 peer
`grep -e "sentPeers=1" -rn beacon*.log | wc -l` returns 786

<img width="1284" alt="Screen Shot 2022-04-24 at 16 51 36" src="https://user-images.githubusercontent.com/10568965/164970758-9f4e4460-bbe0-483e-ad17-dbbdf6e6ab44.png">

**Comment by twoeths** [comment]
the issue is not reproducable on prater
<img width="1367" alt="Screen Shot 2022-04-24 at 16 58 21" src="https://user-images.githubusercontent.com/10568965/164971040-7ba10340-49af-4ff7-970d-121b41ff5ae8.png">

**Comment by twoeths** [comment]
The missed attestation in hetzner-c0 is very correlated to the low long-lived subnets metric

<img width="815" alt="Screen Shot 2022-05-02 at 10 43 40" src="https://user-images.githubusercontent.com/10568965/166181670-cbadb486-7b25-4055-b700-f78ccc688056.png">


<img width="806" alt="Screen Shot 2022-05-02 at 10 44 24" src="https://user-images.githubusercontent.com/10568965/166181709-8e3e0008-be7a-436d-bd65-25411a3f646d.png">

**Comment by twoeths** [comment]
#3955 and #3956 resolved the issue
