### ISSUE TITLE
Mainnet shadow fork 2 - empty deposit tree ETH1_ERROR_WRONG_DEPOSIT_ROOT

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3947]
**Describe the bug**

Shadow fork 2 lodestar geth combination (only checked this one) failed to propose all blocks between genesis and genesis +3 hours

```
Apr-22 09:58:48.067[API]             error: Req req-1f2 produceBlock error  code=ETH1_ERROR_WRONG_DEPOSIT_ROOT, root=0xff836677895bc3325cfcc752ff966cda93fd773ee6e602b18977630d5e527932, expectedRoot=0xd70a234731285c6804c2a4f56711ddb8c82c99740f207854891028af34e27e5e
Error: ETH1_ERROR_WRONG_DEPOSIT_ROOT
    at getDepositsWithProofs (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/utils/deposits.ts:52:11)
    at Eth1DepositsCache.get (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositsCache.ts:34:33)
    at getDeposits (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/utils/deposits.ts:30:20)
    at Eth1DepositDataTracker.getDeposits (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:116:12)
    at Eth1DepositDataTracker.getEth1DataAndDeposits (/usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:77:22)
    at assembleBody (/usr/app/node_modules/@chainsafe/lodestar/src/chain/factory/block/body.ts:64:32)
    at assembleBlock (/usr/app/node_modules/@chainsafe/lodestar/src/chain/factory/block/index.ts:43:11)
    at Object.produceBlock (/usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:180:21)
    at Object.handler (/usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:61:23)
```

at genesis +3 hours the node restarted and could propose 100% of blocks.

Note that the deposit queue is empty during the first 4 hours because there has not been a vote yet on eth1 data. Could it be some issue handling an empty deposit tree?

**Expected behavior**

Propose all blocks

**Comment by philknows** [comment]
Are we still experiencing this?

**Comment by dapplion** [comment]
> Are we still experiencing this?

The only way to experience this is with a shadow-fork that has an empty deposit contract for more than 1 eth1 voting period. This condition doesn't happen on any existing network. We may choose to put this issue on ice until shadow forks happen again for capella

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar
