### ISSUE TITLE
Error: stream ended before 1 bytes became available

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#3948]
**Describe the bug**

Marius reported a spam log from Lodestar as seen below

```
Apr-22 09:31:39.295[NETWORK]         debug: Error dialing discovered peer peer=16...CKQifn Error: stream ended before 1 bytes became available
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.295[NETWORK]         debug: Error dialing discovered peer peer=16...CKQifn Error: stream ended before 1 bytes became availabl
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.295[NETWORK]         debug: Error dialing discovered peer peer=16...CKQifn Error: stream ended before 1 bytes became availab
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.295[NETWORK]         debug: Error dialing discovered peer peer=16...CKQifn Error: stream ended before 1 bytes became availa
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.295[NETWORK]         debug: Error dialing discovered peer peer=16...CKQifn Error: stream ended before 1 bytes became avail
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.296[NETWORK]         debug: Error dialing discovered peer peer=16...CKQifn Error: stream ended before 1 bytes became avai
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.296[NETWORK]         debug: Error dialing discovered peer peer=16...CKQifn Error: stream ended before 1 bytes became ava
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.304[NETWORK]         debug: Error dialing discovered peer peer=16...wkrmDy Error: stream ended before 1 bytes became available
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.304[NETWORK]         debug: Error dialing discovered peer peer=16...wkrmDy Error: stream ended before 1 bytes became availabl
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.304[NETWORK]         debug: Error dialing discovered peer peer=16...wkrmDy Error: stream ended before 1 bytes became availab
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.305[NETWORK]         debug: Error dialing discovered peer peer=16...cyuEm5 Error: stream ended before 1 bytes became available
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.305[NETWORK]         debug: Error dialing discovered peer peer=16...cyuEm5 Error: stream ended before 1 bytes became availabl
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.305[NETWORK]         debug: Error dialing discovered peer peer=16...cyuEm5 Error: stream ended before 1 bytes became availab
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.305[NETWORK]         debug: Error dialing discovered peer peer=16...cyuEm5 Error: stream ended before 1 bytes became availa
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.305[NETWORK]         debug: Error dialing discovered peer peer=16...cyuEm5 Error: stream ended before 1 bytes became avail
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.306[NETWORK]         debug: Error dialing discovered peer peer=16...cyuEm5 Error: stream ended before 1 bytes became avai
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Apr-22 09:31:39.306[NETWORK]         debug: Error dialing discovered peer peer=16...cyuEm5 Error: stream ended before 1 bytes became ava
AggregateError: Error: stream ended before 1 bytes became available
    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)
    at /usr/app/node_modules/p-some/index.js:69:23
```

**Expected behavior**

**Comment by dapplion** [comment]
Related to https://github.com/ChainSafe/lodestar/issues/3762

**Comment by philknows** [comment]
Catch and suppress this error? Because it's a spammy error in the logs. We don't need to see this because others are hanging up on us. Not meaningful.

**Comment by wemeetagain** [comment]
closing as this is no longer happening
