### ISSUE TITLE
Lodestar validator <> Prysm BN: failed to get Sync duties

### ISSUE THREAD

**Issue by g11tech** [ChainSafe/lodestar#3981]
On testing out lodestar validator (primarily for Obol network), lodestar validator requests to Prysm BN to get the syncDuties failed with this:

```bash
May-06 12:29:00.844[]                error: Failed to download SyncDuties epoch=12841 Failed to obtain SyncDuties - Internal Server Error: could not decode body: json: cannot unmarshal number into Go value of type string
Error: Failed to obtain SyncDuties - Internal Server Error: could not decode body: json: cannot unmarshal number into Go value of type string
    at HttpClient.request (/usr/app/packages/api/src/client/utils/httpClient.ts:109:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HttpClient.json (/usr/app/packages/api/src/client/utils/httpClient.ts:71:12)
    at Object.request [as getSyncCommitteeDuties] (/usr/app/packages/api/src/client/utils/client.ts:74:19)
    at SyncCommitteeDutiesService.pollSyncCommitteesForEpoch (/usr/app/packages/validator/src/services/syncCommitteeDuties.ts:218:24)
    at SyncCommitteeDutiesService.pollSyncCommittees (/usr/app/packages/validator/src/services/syncCommitteeDuties.ts:165:7)
    at async Promise.all (index 0)
    at SyncCommitteeDutiesService.runDutiesTasks (/usr/app/packages/validator/src/services/syncCommitteeDuties.ts:127:5)
    at Clock.runAtMostEvery (/usr/app/packages/validator/src/util/clock.ts:77:7)
May-06 12:29:12.011[]                debug: HttpClient request routeId=getProposerDuties
```

This could primarily be an issue on prysm side as this issue didn't occur on lodestar interop with the lighthouse BN (after taking care of the casing issue for which PR has been raised already).

**Comment by dapplion** [comment]
It's complaining that a property that's expected to be a string is actually a number right?
```
cannot unmarshal number into Go value of type string
```

**Comment by g11tech** [comment]
> It's complaining that a property that's expected to be a string is actually a number right?
> 
> ```
> cannot unmarshal number into Go value of type string
> ```

yes

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
