### ISSUE TITLE
error: uncaughtException: Error parsing address: Invalid address Uint8Array: 29034163ec9102238c

### ISSUE THREAD

**Issue by q9f** [ChainSafe/lodestar#4035]
I don't have discord.

**Describe the bug**

Running `lodestar beacon --network prater` causes uncaught exceptions parsing peer addresses.

**Expected behavior**

Correctly parse the peer address or handle the exception.

**Steps to Reproduce**

Install Lodestar from the latest master version `v0.37.0/01e6ffe` and run a beacon node on the Prater network; using Node 18.2.0 (stable).

**Screenshots**

```
May-18 12:44:53.049[]                 info: Lodestar network=prater, version=v0.37.0/01e6ffe, commit=01e6ffee4e713d5d36d5c95d43ca825994ef470e
May-18 12:44:53.187[]                 info: Connected to LevelDB database name=/home/user/.local/share/lodestar/prater/peerstore
May-18 12:44:53.259[DB]               info: Connected to LevelDB database name=/home/user/.local/share/lodestar/prater/chain-db
May-18 12:44:59.523[]                 info: Initializing beacon state from anchor state slot=0, epoch=0, stateRoot=0x895390e92edc03df7096e9f51e51896e8dbe6e7e838180dadbfd869fdd77a659
May-18 12:45:06.499[API]              info: Started REST api server address=http://127.0.0.1:9596, namespaces=beacon,config,events,node,validator
May-18 12:45:06.539[NETWORK]          info: PeerId 16Uiu2HAm65fCHnnVnvxpQr7YUzThrWzbPumP4FQCvD4ykJydgKkq, Multiaddrs 
May-18 12:45:06.540[]                 warn: Low peer count peers=0
May-18 12:45:06.540[]                 info: Searching peers - peers: 0 - slot: 3030225 (skipped 3030225) - head: 0 0x8c0e…ee87 - finalized: 0x0000…0000:0
May-18 12:45:18.002[]                 info: Searching peers - peers: 0 - slot: 3030226 (skipped 3030226) - head: 0 0x8c0e…ee87 - finalized: 0x0000…0000:0
May-18 12:45:30.000[]                 info: Searching peers - peers: 0 - slot: 3030227 (skipped 3030227) - head: 0 0x8c0e…ee87 - finalized: 0x0000…0000:0
May-18 12:45:36.615[]                error: uncaughtException: Error parsing address: Invalid address Uint8Array: 29034163ec9102238c
Error: Error parsing address: Invalid address Uint8Array: 29034163ec9102238c
    at ParseError (/home/user/lodestar/node_modules/multiaddr/src/codec.js:273:10)
    at bytesToTuples (/home/user/lodestar/node_modules/multiaddr/src/codec.js:194:13)
    at validateBytes (/home/user/lodestar/node_modules/multiaddr/src/codec.js:249:5)
    at fromBytes (/home/user/lodestar/node_modules/multiaddr/src/codec.js:239:15)
    at tuplesToBytes (/home/user/lodestar/node_modules/multiaddr/src/codec.js:139:10)
    at stringToBytes (/home/user/lodestar/node_modules/multiaddr/src/codec.js:223:10)
    at Object.fromString (/home/user/lodestar/node_modules/multiaddr/src/codec.js:231:10)
    at new Multiaddr (/home/user/lodestar/node_modules/multiaddr/src/index.js:56:26)
    at Socket.UDPTransportService.handleIncoming (/home/user/lodestar/node_modules/@chainsafe/discv5/lib/transport/udp.js:34:31)
    at Socket.emit (node:events:527:28) Error parsing address: Invalid address Uint8Array: 29034163ec9102238c
Error: Error parsing address: Invalid address Uint8Array: 29034163ec9102238c
    at ParseError (/home/user/lodestar/node_modules/multiaddr/src/codec.js:273:10)
    at bytesToTuples (/home/user/lodestar/node_modules/multiaddr/src/codec.js:194:13)
    at validateBytes (/home/user/lodestar/node_modules/multiaddr/src/codec.js:249:5)
    at fromBytes (/home/user/lodestar/node_modules/multiaddr/src/codec.js:239:15)
    at tuplesToBytes (/home/user/lodestar/node_modules/multiaddr/src/codec.js:139:10)
    at stringToBytes (/home/user/lodestar/node_modules/multiaddr/src/codec.js:223:10)
    at Object.fromString (/home/user/lodestar/node_modules/multiaddr/src/codec.js:231:10)
    at new Multiaddr (/home/user/lodestar/node_modules/multiaddr/src/index.js:56:26)
    at Socket.UDPTransportService.handleIncoming (/home/user/lodestar/node_modules/@chainsafe/discv5/lib/transport/udp.js:34:31)
    at Socket.emit (node:events:527:28)
```

**Desktop (please complete the following information):**

- OS: Archlinux, btw
- Version: `v0.37.0/01e6ffe`
- Branch: `master`
- Commit hash: 01e6ffe

**Comment by q9f** [comment]
Looks like I cannot connect to any peer.

```
May-18 12:51:42.001[]                 info: Searching peers - peers: 0 - slot: 3030258 (skipped 3030258) - head: 0 0x8c0e…ee87 - finalized: 0x0000…0000:0                                                                                      
May-18 12:51:54.001[]                 info: Searching peers - peers: 0 - slot: 3030259 (skipped 3030259) - head: 0 0x8c0e…ee87 - finalized: 0x0000…0000:0                                                                                      
May-18 12:52:06.000[]                 info: Searching peers - peers: 0 - slot: 3030260 (skipped 3030260) - head: 0 0x8c0e…ee87 - finalized: 0x0000…0000:0                                                                                      
May-18 12:52:06.635[]                error: uncaughtException: Error parsing address: Invalid address Uint8Array: 291275d0d191022328                                                                                                           
Error: Error parsing address: Invalid address Uint8Array: 291275d0d191022328  
```

Gonna try to run the latest release instead.

**Comment by q9f** [comment]
Also affected:

- `v0.36.0/HEAD//28e2c74c`
- `v0.35.0/HEAD//82219149`
- `v0.34.0 (alpha)`
- `v0.32.0/HEAD/+36/56de7342` (should be 0.33.0)

Let me know if you want me to continue testing older versions.

**Comment by wemeetagain** [comment]
Can you downgrade NPM to v16 for now? (Or force installation of discv5 v0.7.1?) We have a fix for this in discv5 v0.7.1, we just haven't yet pushed it here.

**Comment by q9f** [comment]
Yes totally, do you document the recommended node version somewhere?

**Comment by wemeetagain** [comment]
Yea we enforce 16+ in the package.json. We also have a banner item in the root README and a note in the CONTRIBUTING doc mentioning node 16.

But we should also support v18, perhaps even encourage its use (updated v8 engine etc may give some performance benefits).

Definitely a bug we want to fix quickly.

**Comment by philknows** [comment]
> Yes totally, do you document the recommended node version somewhere?

On the main page, the shields badge states Node 16.x but I'll update in the documentation [here](https://chainsafe.github.io/lodestar/installation/) that we recommend 16.x

**Comment by q9f** [comment]
Ah, I scrolled over the badges :)
