### ISSUE TITLE
Better errors when parsing files in CLI start

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4082]
**Describe the bug**

Discord user _Sea Monkey_ reported

```
➜  lodestar git:(master) ✗ ./lodestar beacon --rootDir="$HOME/eth/kiln-lodestar-geth" --paramsFile="../config.yaml" --genesisStateFile="../genesis.ssz"  --eth1.enabled=true --execution.urls="http://127.0.0.1:8552" --network.connectToDiscv5Bootnodes --network.discv5.enabled=true --jwt-secret="/tmp/jwtsecret" --network.discv5.bootEnrs="enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk" --port 13442 --enr.ip "1.2.3.4" --enr.tcp 13442 --enr.udp 13442 --eth1.depositContractDeployBlock 0 --eth1.providerUrls="http://127.0.0.1:8546"
 ✖ Error: string encoded ENR must start with 'enr:'
    at Function.decodeTxt (/home/seamonkey/Downloads/merge-testnets/kiln/lodestar/node_modules/@chainsafe/discv5/lib/enr/enr.js:92:19)
    at readEnr (file:///home/seamonkey/Downloads/merge-testnets/kiln/lodestar/packages/cli/src/config/enr.ts:28:14)
    at persistOptionsAndConfig (file:///home/seamonkey/Downloads/merge-testnets/kiln/lodestar/packages/cli/src/cmds/init/handler.ts:93:17)
    at Object.beaconHandler [as handler] (file:///home/seamonkey/Downloads/merge-testnets/kiln/lodestar/packages/cli/src/cmds/beacon/handler.ts:23:3)
```

File `$HOME/eth/kiln-lodestar-geth/enr` existed but was empty.

The error is thrown here:

https://github.com/ChainSafe/lodestar/blob/c1ed45d8ef02ce5380c1d40c9a19f1c00c143faf/packages/cli/src/cmds/init/handler.ts#L93

**Expected behavior**

Print more descriptive error, like "File at location <filepath> is invalid: <error.message>"

**Steps to Reproduce**

- Create empty enr file at expected path by CLI
- Run `lodestar beacon` cmd

**Comment by dapplion** [comment]
This has killed some of our nodes, and needed manual intervention. The fix for this should be very easy, let's implement it for the next release
