### ISSUE TITLE
Error proposing blocks in Ropsten beacon chain

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4088]
**Describe the bug**

All of our ropsten nodes fail to produce blocks during certain time only. https://beaconchain.ropsten.ethdevops.io/blocks?q=lodestar confirms this pattern with gaps on the times shown in the chart. Chart is GMT+7 timezone.

![Screenshot from 2022-05-31 09-08-21](https://user-images.githubusercontent.com/35266934/171079021-d47259b9-ac81-4082-ac07-372f65e124c4.png)

From `hetzner-ropsten-0`

```
May-31 01:10:36.091[API]             error: Req req-137a produceBlock error  code=ETH1_ERROR_WRONG_DEPOSIT_ROOT, root=0x0aaa0f8770b01734c82342a56ef0de51e9e3eec86a124b0abbde1356e8b82dd7, expectedRoot=0xd70a234731285c6804c2a4f56711ddb8c82c99740f207854891028af34e27e5e
Error: ETH1_ERROR_WRONG_DEPOSIT_ROOT
    at getDepositsWithProofs (file:///usr/app/node_modules/@chainsafe/lodestar/src/eth1/utils/deposits.ts:52:11)
    at Eth1DepositsCache.get (file:///usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositsCache.ts:34:12)
    at getDeposits (file:///usr/app/node_modules/@chainsafe/lodestar/src/eth1/utils/deposits.ts:30:20)
    at Eth1DepositDataTracker.getDeposits (file:///usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:115:12)
    at Eth1DepositDataTracker.getEth1DataAndDeposits (file:///usr/app/node_modules/@chainsafe/lodestar/src/eth1/eth1DepositDataTracker.ts:76:22)
    at assembleBody (file:///usr/app/node_modules/@chainsafe/lodestar/src/chain/factory/block/body.ts:68:32)
    at assembleBlock (file:///usr/app/node_modules/@chainsafe/lodestar/src/chain/factory/block/index.ts:42:11)
    at Object.produceBlock (file:///usr/app/node_modules/@chainsafe/lodestar/src/api/impl/validator/index.ts:186:21)
    at Object.handler (file:///usr/app/node_modules/@chainsafe/lodestar-api/src/server/utils/server.ts:61:23)
```

**Expected behavior**

Propose blocks

**Comment by twoeths** [comment]
as in https://beaconchain.ropsten.ethdevops.io/block/3020, the expectedRoot (`eth1Data.depositRoot`) above is for depositCount = 0

the deposit root fetched from our deposit tree somehow is not correct
```typescript
// Get tree at this particular depositCount to compute correct proofs
  const viewAtDepositCount = depositRootTree.sliceTo(eth1Data.depositCount - 1);

  const depositRoot = viewAtDepositCount.hashTreeRoot();
```
