### ISSUE TITLE
Make logs less scary

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4146]
From discord: https://discord.com/channels/593655374469660673/593655641445367808/985190327600156712

Lodestar syncing Ropsten from scratch with Geth, can get kinda noisy. It'd be friendly to make these logs look less scary:
```
consensus_1          | Jun-11 14:32:54.003[]                 info: Syncing - 1.8 hours left - 6.81 slots/s - slot: 86264 (skipped 45275) - head: 40989 0xf0f4…e5b1 - finalized: 0xd37c…7768:1278 - peers: 50
consensus_1          | Jun-11 14:33:06.003[]                 info: Syncing - 1.9 hours left - 6.70 slots/s - slot: 86265 (skipped 45196) - head: 41069 0x9bf2…6e0d - finalized: 0xab60…7236:1281 - peers: 51
consensus_1          | Jun-11 14:33:15.450[CHAIN]           error: Error onSyncAggregate  attestedData not available
consensus_1          | Error: attestedData not available
consensus_1          |     at LightClientServer.onSyncAggregate (file:///usr/app/packages/lodestar/src/chain/lightClient/index.ts:446:15)
consensus_1          |     at LightClientServer.onImportBlockHead (file:///usr/app/packages/lodestar/src/chain/lightClient/index.ts:209:10)
consensus_1          |     at importBlock (file:///usr/app/packages/lodestar/src/chain/blocks/importBlock.ts:211:33)
consensus_1          |     at processChainSegment (file:///usr/app/packages/lodestar/src/chain/blocks/index.ts:101:13)
consensus_1          |     at JobItemQueue.runJob (file:///usr/app/packages/lodestar/src/util/queue/itemQueue.ts:92:22)
consensus_1          | Jun-11 14:33:18.000[]                 info: Syncing - 1.9 hours left - 6.63 slots/s - slot: 86266 (skipped 45113) - head: 41153 0x0d0f…e32d - finalized: 0xc2f0…f091:1284 - peers: 51
consensus_1          | Error: REQUEST_ERROR_EMPTY_RESPONSE
consensus_1          |     at file:///usr/app/packages/lodestar/src/network/reqresp/request/collectResponses.ts:20:13
consensus_1          |     at runMicrotasks (<anonymous>)
consensus_1          |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
consensus_1          |     at withTimeout (file:///usr/app/packages/utils/src/timeout.ts:19:12)
consensus_1          |     at sendRequest (file:///usr/app/packages/lodestar/src/network/reqresp/request/index.ts:137:25)
consensus_1          |     at ReqResp.sendRequest (file:///usr/app/packages/lodestar/src/network/reqresp/reqResp.ts:158:22)
consensus_1          |     at ReqResp.goodbye (file:///usr/app/packages/lodestar/src/network/reqresp/reqResp.ts:100:5)
consensus_1          |     at PeerManager.goodbyeAndDisconnect (file:///usr/app/packages/lodestar/src/network/peers/peerManager.ts:603:7)
consensus_1          | Error: REQUEST_ERROR_EMPTY_RESPONSE
consensus_1          |     at sendRequest (file:///usr/app/packages/lodestar/src/network/reqresp/request/index.ts:175:13)
consensus_1          |     at runMicrotasks (<anonymous>)
consensus_1          |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
consensus_1          |     at ReqResp.sendRequest (file:///usr/app/packages/lodestar/src/network/reqresp/reqResp.ts:158:22)
consensus_1          |     at ReqResp.goodbye (file:///usr/app/packages/lodestar/src/network/reqresp/reqResp.ts:100:5)
consensus_1          |     at PeerManager.goodbyeAndDisconnect (file:///usr/app/packages/lodestar/src/network/peers/peerManager.ts:603:7)
consensus_1          | Jun-11 14:33:30.002[]                 info: Syncing - 1.9 hours left - 6.62 slots/s - slot: 86267 (skipped 45025) - head: 41242 0x6af7…3203 - finalized: 0x1c5e…1b65:1286 - peers: 50
```

**Comment by dapplion** [comment]
Yep would love to have someone devoting time on making Lodestar print less red

**Comment by philknows** [comment]
Has anyone been seeing this response lately (v1.7.x and up) while syncing from scratch? If not, I think it's justified to close this and reopen a new issue due to lack of clarity here about what the specific task/action involves.

**Comment by wemeetagain** [comment]
:+1: closing
