### ISSUE TITLE
Unknown block sync peerId conversion issue

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4246]
In Sepolia, seems an error of conversion

```
Jul-06 14:24:35.555[SYNC]            error: Downloaded block parent is before finalized slot finalizedSlot=115200, parentSlot=115192, parentRoot=0xd1670e16e8614871ea41daddd96aeab17f55b0a331afb5577e99100a7a83c1db
Jul-06 14:24:35.559[SYNC]            error: Removing unknown parent block root=0x1815dbd1a77bf2530893ef2c9bf6250a84be6b913cfe76d164d5f9c716d8728d, slot=115208
Jul-06 14:24:35.559[SYNC]            error: Removing unknown parent block root=0x01da944e86c181f131a3d2bf50fd9b599150e687b53c991d969715d8d86a5e5e, slot=115210
Jul-06 14:24:35.559[SYNC]            error: Removing unknown parent block root=0xacd63ca2b12641cb281fe40a479a5bf37debbba9ae324e4c9089742fdbbe1403, slot=115224
Jul-06 14:24:35.559[SYNC]            error: Removing unknown parent block root=0x6363c1500f9f25e3ce68e81444f9a5a5229b6ddad8c2b32e2abff5bc02b8c350, slot=115245
Jul-06 14:24:35.559[SYNC]            error: Removing unknown parent block root=0x4cd26ac871cbbd8c78558bf3f7be212c0da4fd549947b79461ede7164a8592be, slot=115255
Jul-06 14:24:35.559[SYNC]            error: Removing unknown parent block root=0xa88ce720f7907631dc7a0bc2e6ef6934eaa38737c914e7c5ac728b28e9ea6d9e, slot=115256
Jul-06 14:24:35.560[SYNC]            error: Removing unknown parent block root=0xf730df20bae1f30477f016bfd7820997dcf81e113fc44b7b5d0ce747520efc28, slot=115264
Jul-06 14:24:35.560[SYNC]            error: Removing unknown parent block root=0x46877c82c449986ed63db6e04b235674b83131803f78cc35a1ca931565766d9f, slot=115274
Jul-06 14:24:35.560[SYNC]            error: Removing unknown parent block root=0x0479c0245a7500c042e97643d27b09755a9d89e366c49c5a0ce1713b26c986d8, slot=115299
Jul-06 14:24:35.560[SYNC]            error: Removing unknown parent block root=0x1578a4b35fa6b97f4687185c6cdb843bf1e52bd678de402d3e28fa3c1af85d4d, slot=115302
Jul-06 14:24:35.560[SYNC]            error: Removing unknown parent block root=0xf24596e26f9049215b14bece1e4d59d0dd03ef312a2dc386dc36ddb479406222, slot=115319
Jul-06 14:24:35.560[SYNC]            error: Removing unknown parent block root=0x2ab54e9efc3c690d0882ce1bc94bb8bb9fe30e5f23e0e929eba21d7c85080162, slot=115321
Jul-06 14:24:35.560[SYNC]            error: Banning unknown parent block root=0x1815dbd1a77bf2530893ef2c9bf6250a84be6b913cfe76d164d5f9c716d8728d, slot=115208
Jul-06 14:24:35.561[SYNC]            error: Banning unknown parent block root=0x01da944e86c181f131a3d2bf50fd9b599150e687b53c991d969715d8d86a5e5e, slot=115210
Jul-06 14:24:35.562[SYNC]            error: Banning unknown parent block root=0xacd63ca2b12641cb281fe40a479a5bf37debbba9ae324e4c9089742fdbbe1403, slot=115224
Jul-06 14:24:35.562[SYNC]            error: Banning unknown parent block root=0x6363c1500f9f25e3ce68e81444f9a5a5229b6ddad8c2b32e2abff5bc02b8c350, slot=115245
Jul-06 14:24:35.562[SYNC]            error: Banning unknown parent block root=0x4cd26ac871cbbd8c78558bf3f7be212c0da4fd549947b79461ede7164a8592be, slot=115255
Jul-06 14:24:35.562[SYNC]            error: Banning unknown parent block root=0xa88ce720f7907631dc7a0bc2e6ef6934eaa38737c914e7c5ac728b28e9ea6d9e, slot=115256
Jul-06 14:24:35.563[SYNC]            error: Banning unknown parent block root=0xf730df20bae1f30477f016bfd7820997dcf81e113fc44b7b5d0ce747520efc28, slot=115264
Jul-06 14:24:35.563[SYNC]            error: Banning unknown parent block root=0x46877c82c449986ed63db6e04b235674b83131803f78cc35a1ca931565766d9f, slot=115274
Jul-06 14:24:35.563[SYNC]            error: Banning unknown parent block root=0x0479c0245a7500c042e97643d27b09755a9d89e366c49c5a0ce1713b26c986d8, slot=115299
Jul-06 14:24:35.563[SYNC]            error: Banning unknown parent block root=0x1578a4b35fa6b97f4687185c6cdb843bf1e52bd678de402d3e28fa3c1af85d4d, slot=115302
Jul-06 14:24:35.564[SYNC]            error: Banning unknown parent block root=0xf24596e26f9049215b14bece1e4d59d0dd03ef312a2dc386dc36ddb479406222, slot=115319
Jul-06 14:24:35.564[SYNC]            error: Unexpect error - downloadParentBlock  Non-base58btc character
Error: Non-base58btc character
    at decode (/usr/app/node_modules/multiformats/cjs/vendor/base-x.js:125:11)
    at Decoder.decode [as baseDecode] (/usr/app/node_modules/multiformats/cjs/src/bases/base.js:90:34)
    at Decoder.decode (/usr/app/node_modules/multiformats/cjs/src/bases/base.js:37:19)
    at Codec.decode (/usr/app/node_modules/multiformats/cjs/src/bases/base.js:80:25)
    at Function.exports.createFromB58String (/usr/app/node_modules/@chainsafe/lodestar/node_modules/peer-id/src/index.js:286:44)
    at UnknownBlockSync.removeAndDownscoreAllDescendants (file:///usr/app/node_modules/@chainsafe/lodestar/src/sync/unknownBlock.ts:313:29)
    at UnknownBlockSync.downloadParentBlock (file:///usr/app/node_modules/@chainsafe/lodestar/src/sync/unknownBlock.ts:157:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by dapplion** [comment]
- Seen again in `lodestar-nethermind-1` of https://github.com/gnosischain/consensus-deployment-ansible/issues/9

```
Jul-03 05:19:55.814[SYNC]            error: Unexpect error - processBlock  Non-base58btc character
Error: Non-base58btc character
    at decode (/usr/app/node_modules/multiformats/cjs/vendor/base-x.js:125:11)
    at Decoder.decode [as baseDecode] (/usr/app/node_modules/multiformats/cjs/src/bases/base.js:90:34)
    at Decoder.decode (/usr/app/node_modules/multiformats/cjs/src/bases/base.js:37:19)
    at Codec.decode (/usr/app/node_modules/multiformats/cjs/src/bases/base.js:80:25)
    at Function.exports.createFromB58String (/usr/app/node_modules/@chainsafe/lodestar/node_modules/peer-id/src/index.js:286:44)
    at UnknownBlockSync.removeAndDownscoreAllDescendants (file:///usr/app/node_modules/@chainsafe/lodestar/src/sync/unknownBlock.ts:313:29)
    at UnknownBlockSync.processBlock (file:///usr/app/node_modules/@chainsafe/lodestar/src/sync/unknownBlock.ts:233:18)
    at runMicrotasks (<anonymous>)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
```

**Comment by dapplion** [comment]
I couldn't find any immediate codepath that could produce bad PeerIdStr or mix different encodings.

- Opened this PR to help debug future occurrences of this issue https://github.com/ChainSafe/lodestar/pull/4479

Meanwhile I'll leave open but there's not much I can do

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
