### ISSUE TITLE
No block found for id 'finalized'

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/lodestar#4253]
**Describe the bug**

- From a host running a metrics exporter https://github.com/samcm/ethereum-metrics-exporter in https://github.com/gnosischain/consensus-deployment-ansible/issues/9

```
Jul-03 04:44:46.921[API]             error: Req req-m250 getBlockV2 error  No block found for id 'finalized'
Error: No block found for id 'finalized'
    at resolveBlockId (file:///usr/app/node_modules/@chainsafe/lodestar/src/api/impl/beacon/blocks/utils.ts:33:11)
    at Object.getBlockV2 (file:///usr/app/node_modules/@chainsafe/lodestar/src/api/impl/beacon/blocks/index.ts:105:21)
    at Object.handler (file:///usr/app/node_modules/@chainsafe/lodestar-api/src/utils/server/genericJsonServer.ts:39:23)

```

**Comment by philknows** [comment]
Is this still an issue? I'm not seeing this anymore as of v1.11.3

**Comment by nflaig** [comment]
Shouldn't be an issue anymore, I am able to retrieve finalized blocks
