### ISSUE TITLE
Intermittent PublishError.InsufficientPeers on Ropsten with v0.40.0-dev.57d13e1d9d using merge-script

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#4264]
**Describe the bug**

Intermittent issues with publishing attestations on Ropsten using Lodestar `v0.40.0-dev.57d13e1d9d`. Consistently 0 mesh + topic peers in sync_committee and low attnet mesh peers per subnet. Topic peer count is consistently high however.

Lots of errors logging:
```
Jul-07 19:35:15.424[]                error: Error publishing attestations slot=274976 Internal Server Error: PublishError.InsufficientPeers
Error: Internal Server Error: PublishError.InsufficientPeers
    at HttpClient.requestWithBody (file:///usr/app/node_modules/@lodestar/api/src/utils/client/httpClient.ts:121:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HttpClient.request (file:///usr/app/node_modules/@lodestar/api/src/utils/client/httpClient.ts:79:12)
    at Object.request [as submitPoolAttestations] (file:///usr/app/node_modules/@lodestar/api/src/utils/client/client.ts:82:9)
    at AttestationService.signAndPublishAttestations (file:///usr/app/node_modules/@lodestar/validator/src/services/attestation.ts:159:7)
    at AttestationService.runAttestationTasks (file:///usr/app/node_modules/@lodestar/validator/src/services/attestation.ts:63:5)
    at Clock.runAtMostEvery (file:///usr/app/node_modules/@lodestar/validator/src/util/clock.ts:96:7)
Jul-07 19:35:20.151[]                 info: Published aggregateAndProofs slot=274976, index=7, count=1
Jul-07 19:40:14.353[]                 info: Published attestations slot=275001, count=1
Jul-07 19:41:04.114[]                 info: Published attestations slot=275005, count=1
Jul-07 19:41:39.153[]                 info: Published attestations slot=275008, count=1
Jul-07 19:44:02.422[]                error: Error publishing attestations slot=275020 Internal Server Error: PublishError.InsufficientPeers
Error: Internal Server Error: PublishError.InsufficientPeers
    at HttpClient.requestWithBody (file:///usr/app/node_modules/@lodestar/api/src/utils/client/httpClient.ts:121:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HttpClient.request (file:///usr/app/node_modules/@lodestar/api/src/utils/client/httpClient.ts:79:12)
    at Object.request [as submitPoolAttestations] (file:///usr/app/node_modules/@lodestar/api/src/utils/client/client.ts:82:9)
    at AttestationService.signAndPublishAttestations (file:///usr/app/node_modules/@lodestar/validator/src/services/attestation.ts:159:7)
    at AttestationService.runAttestationTasks (file:///usr/app/node_modules/@lodestar/validator/src/services/attestation.ts:63:5)
    at Clock.runAtMostEvery (file:///usr/app/node_modules/@lodestar/validator/src/util/clock.ts:96:7)
```

I initially set this up with `merge-script` to test out keystores integration from https://github.com/ChainSafe/lodestar/pull/4234 and left it running to discover this issue.

Poor performance can be seen here: https://ropsten.beaconcha.in/validator/0xa30147006edd615ffc5a5d9351e0fbdcc6318cc2c432e22b7134d7ace9cb90a4b276468660afdcc0be07810190f3eaed#attestations

**Expected behavior**
We should have better peering to perform consistent attestations on the network.

**Screenshots**

![Screen Shot 2022-07-07 at 1 36 51 PM](https://user-images.githubusercontent.com/58080811/177859145-ae3f25fb-2368-4d95-b0f2-a5aa6fb1855a.png)

**Comment by philknows** [comment]
Only seeing this while using the merge-script... confirmed it's not an issue with all setups. Debugging with @g11tech .

**Comment by dapplion** [comment]
Thanks for pasting the metrics! Node seems to have good mesh stability so probably it's not able to switch peers fast enough to get peers on the target subnets

**Comment by philknows** [comment]
After a complete wipe and starting from scratch, the peers *eventually* pick back up and issue is gone. Only seen with Nethermind as EL, otherwise Geth is fine. Closing.
