### ISSUE TITLE
Feature: Import keystore files with missing `path`

### ISSUE THREAD

**Issue by yorickdowne** [ChainSafe/lodestar#4320]
**Is your feature request related to a problem? Please describe.**

Prysm exports keystore json files without `path`. These import without issue in the other three clients, but not in Lodestar.

**Describe the solution you'd like**

Ignore the missing `path`

**Additional context**

```
 ✖ Error: : should have required property 'path'
    at Object.validateKeystore (/usr/app/node_modules/@chainsafe/bls-keystore/lib/functional.js:111:15)
    at Function.fromObject (/usr/app/node_modules/@chainsafe/bls-keystore/lib/class.js:46:22)
    at Function.parse (/usr/app/node_modules/@chainsafe/bls-keystore/lib/class.js:53:25)
    at Object.handler (file:///usr/app/node_modules/@chainsafe/lodestar-cli/src/cmds/validator/import.ts:112:33)
    at Object.runCommand (file:///usr/app/node_modules/yargs/build/lib/command.js:174:48)
    at Object.parseArgs [as _parseArgs] (file:///usr/app/node_modules/yargs/build/lib/yargs-factory.js:992:55)
    at Object.runCommand (file:///usr/app/node_modules/yargs/build/lib/command.js:138:36)
    at Object.parseArgs [as _parseArgs] (file:///usr/app/node_modules/yargs/build/lib/yargs-factory.js:992:55)
    at Object.parse (file:///usr/app/node_modules/yargs/build/lib/yargs-factory.js:555:31)
    at file:///usr/app/node_modules/@chainsafe/lodestar-cli/src/index.ts:31:4
    ```

**Comment by yorickdowne** [comment]
Potuz comments:
"A keystore can be constructed from any single private key, it does not need to be derived from an HD one. While many have used the deposit-cli, we cannot assume this is the case. Why does lodestar need the path to import it?"

**Comment by wemeetagain** [comment]
We're just following the EIP :shrug:  
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2335.md#json-schema
According to the schema the `path` is required.
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2335.md#path
And the path should be set to `""` if its not known or relevant.

Ofc we're happy to relax our validation. We should probably update the EIP if it seems like that isn't what we want tho.

**Comment by yorickdowne** [comment]
Closing this. Prysm is looking at returning `""`.
