### ISSUE TITLE
Cannot download weak subjectivity state

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4368]
**Describe the bug**
Got this error
```
Aug 05 16:46:38 hz-ax41-dev-4 beacon_run.sh[152245]:  ✖ Error: Unable to fetch weak subjectivity state: First offset must equal to fixedEnd 2736633 != 2736629. Consider downloading a state manually and using the --weakSubjectivityStateFile option.
Aug 05 16:46:38 hz-ax41-dev-4 beacon_run.sh[152245]:     at fetchWeakSubjectivityState (file:///usr/src/lodestar/packages/cli/src/networks/index.ts:203:11)
Aug 05 16:46:38 hz-ax41-dev-4 beacon_run.sh[152245]:     at runMicrotasks (<anonymous>)
Aug 05 16:46:38 hz-ax41-dev-4 beacon_run.sh[152245]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Aug 05 16:46:38 hz-ax41-dev-4 beacon_run.sh[152245]:     at initFromWSState (file:///usr/src/lodestar/packages/cli/src/cmds/beacon/initBeaconState.ts:153:37)
Aug 05 16:46:38 hz-ax41-dev-4 beacon_run.sh[152245]:     at initBeaconState (file:///usr/src/lodestar/packages/cli/src/cmds/beacon/initBeaconState.ts:94:12)
Aug 05 16:46:38 hz-ax41-dev-4 beacon_run.sh[152245]:     at Object.beaconHandler [as handler] (file:///usr/src/lodestar/packages/cli/src/cmds/beacon/handler.ts:68:41)
```

**Expected behavior**

No error

**Comment by twoeths** [comment]
this could be an issue with infura node, was able to download state from another node and start from there

**Comment by twoeths** [comment]
ignore my previous comment, this happens quite randomly

**Comment by twoeths** [comment]
This only happens with `caymay/update_libp2p` branch. Same error happens if starting syncing from db:

```
Aug 06 09:30:15 hz-cx41-dev-3 beacon_run.sh[167962]:  ✖ Error: First offset must equal to fixedEnd 2736633 != 2736629
Aug 06 09:30:15 hz-cx41-dev-3 beacon_run.sh[167962]:     at readVariableOffsets (/usr/src/lodestar/node_modules/@chainsafe/ssz/src/type/container.ts:448:15)
Aug 06 09:30:15 hz-cx41-dev-3 beacon_run.sh[167962]:     at ContainerType.getFieldRanges (/usr/src/lodestar/node_modules/@chainsafe/ssz/src/type/container.ts:399:21)
Aug 06 09:30:15 hz-cx41-dev-3 beacon_run.sh[167962]:     at ContainerType.tree_deserializeFromBytes (/usr/src/lodestar/node_modules/@chainsafe/ssz/src/type/container.ts:249:30)
Aug 06 09:30:15 hz-cx41-dev-3 beacon_run.sh[167962]:     at ContainerType.deserializeToViewDU (/usr/src/lodestar/node_modules/@chainsafe/ssz/src/type/composite.ts:157:23)
Aug 06 09:30:15 hz-cx41-dev-3 beacon_run.sh[167962]:     at StateArchiveRepository.decodeValue (file:///usr/src/lodestar/packages/beacon-node/src/db/repositories/stateArchive.ts:26:53)
Aug 06 09:30:15 hz-cx41-dev-3 beacon_run.sh[167962]:     at file:///usr/src/lodestar/packages/db/src/abstractRepository.ts:152:44
Aug 06 09:30:15 hz-cx41-dev-3 beacon_run.sh[167962]:     at Array.map (<anonymous>)
Aug 06 09:30:15 hz-cx41-dev-3 beacon_run.sh[167962]:     at StateArchiveRepository.values (file:///usr/src/lodestar/packages/db/src/abstractRepository.ts:152:25)
Aug 06 09:30:15 hz-cx41-dev-3 beacon_run.sh[167962]:     at StateArchiveRepository.lastValue (file:///usr/src/lodestar/packages/db/src/abstractRepository.ts:216:20)
Aug 06 09:30:15 hz-cx41-dev-3 beacon_run.sh[167962]:     at initBeaconState (file:///usr/src/lodestar/packages/cli/src/cmds/beacon/initBeaconState.ts:90:23)
```

**Comment by twoeths** [comment]
should set `BELLATRIX_FORK_EPOCH` to  112260 in that branch
