### ISSUE TITLE
error: Error updating eth1 chain cache  Timeout request

### ISSUE THREAD

**Issue by come-maiz** [ChainSafe/lodestar#4395]
**Describe the bug**

I'm running lodestar from the unstable branch to test mev-boost.

I'm following these instructions: https://github.com/flashbots/mev-boost/wiki/Testing/fa8b3f72058255fe394066bab285a3e6a9be92fd#lodestar

When I start it to run the beacon node, this error appears:

```
$ ./lodestar beacon --network kiln --builder.enabled --builder.urls http://127.0.0.1:18550 --jwt-secret=/home/$USER/workspace/sec
ret                                                                                                                                                                         
[...]
Aug-11 01:00:30.001[]                 info: Searching peers - peers: 0 - slot: 1097677 (skipped 1092399) - head: 5278 0xe4da…c856 - execution: premerge - finalized: 0x86f0…
5bf5:163
Aug-11 01:00:42.342[]                 info: Syncing - ? left - 0.00 slots/s - slot: 1097678 (skipped 1092400) - head: 5278 0xe4da…c856 - execution: premerge - finalized: 0x
86f0…5bf5:163 - peers: 6
Aug-11 01:00:54.466[]                 info: Syncing - ? left - 0.00 slots/s - slot: 1097679 (skipped 1092401) - head: 5278 0xe4da…c856 - execution: premerge - finalized: 0x
86f0…5bf5:163 - peers: 5
Aug-11 01:01:06.227[]                 info: Syncing - 8.1 days left - 1.57 slots/s - slot: 1097680 (skipped 1092242) - head: 5438 0x00db…4ff7 - execution: premerge - finali
zed: 0xf1e2…3890:168 - peers: 4
Aug-11 01:01:09.303[ETH1]            error: Error updating eth1 chain cache  Timeout request
Error: Timeout request
    at JsonRpcHttpClient.fetchJsonOneUrl (file:///mnt/data/workspace/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:239:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at JsonRpcHttpClient.fetchJson (file:///mnt/data/workspace/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:160:16)
    at JsonRpcHttpClient.fetchBatch (file:///mnt/data/workspace/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:143:39)
    at async Promise.all (index 0)
    at retry (file:///mnt/data/workspace/lodestar/packages/utils/src/retry.ts:33:14)
    at Eth1Provider.getBlocksByNumber (file:///mnt/data/workspace/lodestar/packages/beacon-node/src/eth1/provider/eth1Provider.ts:114:23)
    at Eth1DepositDataTracker.updateBlockCache (file:///mnt/data/workspace/lodestar/packages/beacon-node/src/eth1/eth1DepositDataTracker.ts:260:23)
    at Eth1DepositDataTracker.update (file:///mnt/data/workspace/lodestar/packages/beacon-node/src/eth1/eth1DepositDataTracker.ts:192:31)
Aug-11 01:01:18.260[]                 info: Syncing - 5 days left - 2.52 slots/s - slot: 1097681 (skipped 1092179) - head: 5502 0x1361…0c82 - execution: premerge - finalize
d: 0xcfc5…ea47:170 - peers: 4
Aug-11 01:01:30.141[]                 info: Syncing - 4.3 days left - 2.96 slots/s - slot: 1097682 (skipped 1092147) - head: 5535 0x8a04…257a - execution: premerge - finali
zed: 0x6b85…bab5:171 - peers: 6
```

The error appears like every minute.
It seems to be syncing, so this error does not seem problematic so far. 

I'm running this with nethermind. I'm not sure if the issue is in here or there. Filing here to start digging.

**Expected behavior**

The beacon node syncs with no errors shown.

**Steps to Reproduce**

Follow this instructions to compile and run:
https://github.com/flashbots/mev-boost/wiki/Testing/fa8b3f72058255fe394066bab285a3e6a9be92fd#lodestar

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version: 22.04
- Branch: unstable
- Commit hash: 0de01443f1f4cfa6efc12783c5783f0035e4e29f

```
$ ./lodestar --version
🌟 Lodestar: TypeScript Implementation of the Ethereum Consensus Beacon Chain.
  * Version: v0.41.0/0de0144
  * by ChainSafe Systems, 2018-2022
```

**Comment by g11tech** [comment]
@come-maiz seems from the logs that the issue resolved and the sync move forward, we have a tracker issue to reduce/remove such harmless/intermittent/self resolvable error loggin https://github.com/ChainSafe/lodestar/issues/4348

Closing this issue for now as part of #4348
