### ISSUE TITLE
Not able to validate attestation: Requesting slot committee out of range

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4396]
**Describe the bug**

Around the prater/goerli merge, we got

```
Aug-11 02:29:30.011[]                 info: Synced - slot: 3639747 - head: 3639747 0xaace…1edd - execution: valid(0x62bd…24b8) - finalized: 0x9469…c31e:113739 - peers: 50
Aug-11 02:29:41.278[NETWORK]         error: Gossip validation beacon_attestation threw a non-GossipActionError  Requesting slot committee out of range epoch: 113742 current: 113740
Error: Requesting slot committee out of range epoch: 113742 current: 113740
    at EpochContext.getShufflingAtEpoch (file:///usr/app/node_modules/@lodestar/state-transition/src/cache/epochContext.ts:720:13)
    at EpochContext.getShufflingAtSlot (file:///usr/app/node_modules/@lodestar/state-transition/src/cache/epochContext.ts:709:17)
    at getCommitteeIndices (file:///usr/app/node_modules/@lodestar/beacon-node/src/chain/validation/attestation.ts:287:56)
    at validateGossipAttestation (file:///usr/app/node_modules/@lodestar/beacon-node/src/chain/validation/attestation.ts:91:28)
    at runMicrotasks (<anonymous>)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at validateGossipAttestationRetryUnknownRoot (file:///usr/app/node_modules/@lodestar/beacon-node/src/network/gossip/handlers/index.ts:349:14)
    at beacon_attestation (file:///usr/app/node_modules/@lodestar/beacon-node/src/network/gossip/handlers/index.ts:182:28)
```

note that the sync status stated the head 3639747 at epoch 113742, not sure why the head epoch of 113740 was used to validate attestation

**Expected behavior**

No error

**Comment by twoeths** [comment]
the attestation was from some out-of-synced node which voted for some old block, lodestar used the state at that block and was not able to get committee.

In this case, since that node is out-of-synced, that attestation is not valid since validator is already not part of committee, so the error is expected. Maybe we should find a better way to log the error.

**Comment by philknows** [comment]
Agreed that this can be a scary looking error. Errors generally mean that the user themselves incorrectly did something and need to take action to fix it. This is not something that the user itself can fix. Would either:
- Add additional information to explain why this happens or 
- Downgrade this to some sort of info or warning that provides this notice, but not a scary looking error.

**Comment by twoeths** [comment]
got same issue around the time of merge
