### ISSUE TITLE
Failed to download SyncDuties while connected to lighthouse or teku beacon node

### ISSUE THREAD

**Issue by TobiWo** [ChainSafe/lodestar#4402]
The following was tested on Goerli (before the merge):
While connecting the lodestar validator to a lighthouse or teku beacon node I receive the following error:

```
Aug-01 21:22:01.648[] error: Failed to download SyncDuties epoch=111669 JSON expected key dependent_root is undefined - Failed to obtain SyncDuties
    Error: JSON expected key dependent_root is undefined - Failed to obtain SyncDuties
    at ContainerType.fromJson (/usr/app/node_modules/@chainsafe/ssz/src/type/container.ts:340:15)
    at Object.request [as getSyncCommitteeDuties] (file:///usr/app/node_modules/@lodestar/api/src/utils/client/client.ts:77:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at SyncCommitteeDutiesService.pollSyncCommitteesForEpoch (file:///usr/app/node_modules/@lodestar/validator/src/services/syncCommitteeDuties.ts:234:24)
    at SyncCommitteeDutiesService.pollSyncCommittees (file:///usr/app/node_modules/@lodestar/validator/src/services/syncCommitteeDuties.ts:179:7)
    at async Promise.all (index 1)
    at SyncCommitteeDutiesService.runDutiesTasks (file:///usr/app/node_modules/@lodestar/validator/src/services/syncCommitteeDuties.ts:141:5)
    at Clock.runAtMostEvery (file:///usr/app/node_modules/@lodestar/validator/src/util/clock.ts:96:7)
```

The validator still produces attestations but I don't know if it produces blocks.

lodestar version: 0.41.0
teku version: 22.8.0
ligththouse version: 2.5.1

For reference: I'm trying to keep track of most client combinations here: https://github.com/TobiWo/ethereum-consensus-client-cross-connectivity

**Comment by dapplion** [comment]
That's an awesome initiative, thank you so much testing interop.

**Comment by dapplion** [comment]
@TobiWo If you need to use an image of Lodestar with this fix, please pull `chainsafe/lodestar:next`
