### ISSUE TITLE
Pubsub has not started

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4543]
running 1.0.0 mainnet
```
Sep-13 04:58:51.276[NETWORK]          ^[[32minfo^[[39m: Subscribed gossip core topics 
Sep-13 04:58:51.277[NETWORK]       ^[[36mverbose^[[39m: Subscribe to gossipsub topic topic=/eth2/4a26c58b/beacon_block/ssz_snappy
Sep-13 04:58:51.277[NETWORK]         ^[[31merror^[[39m: Error onRequest handler  Pubsub has not started
Error: Pubsub has not started
    at Eth2Gossipsub.subscribe (/srv/lodestar/node_modules/libp2p-gossipsub/src/index.js:1151:19)
    at Eth2Gossipsub.subscribeTopic (file:///srv/lodestar/packages/beacon-node/src/network/gossip/gossipsub.ts:185:10)
    at Network.subscribeCoreTopicsAtFork (file:///srv/lodestar/packages/beacon-node/src/network/network.ts:301:17)
    at Network.subscribeGossipCoreTopics (file:///srv/lodestar/packages/beacon-node/src/network/network.ts:217:12)
    at BeaconSync.updateSyncState (file:///srv/lodestar/packages/beacon-node/src/sync/sync.ts:184:20)
    at NetworkEventBus.BeaconSync.addPeer (file:///srv/lodestar/packages/beacon-node/src/sync/sync.ts:160:10)
    at NetworkEventBus.emit (node:events:539:35)
    at PeerManager.onStatus (file:///srv/lodestar/packages/beacon-node/src/network/peers/peerManager.ts:333:28)
    at NetworkEventBus.PeerManager.onRequest (file:///srv/lodestar/packages/beacon-node/src/network/peers/peerManager.ts:245:23)
    at NetworkEventBus.emit (node:events:527:28)
```

**Comment by twoeths** [comment]
This is rare, the sync finished even before the network is started

**Comment by philknows** [comment]
I think Cayman is the first one to experience this!
