### ISSUE TITLE
Failed to start libp2p (and lodestar)

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4544]
**Describe the bug**

Got this in feat2 md16 node:

```
Sep 14 03:42:42 feat2-md16-ctvpsm beacon_run.sh[1244904]: Sep-14 03:42:42.584[]                 info: Lodestar network=goerli, version=v1.0.0/5f3509e, commit=5f3509e5537c0b1c336f68f5ba5d2eb95a8295e6
Sep 14 03:42:42 feat2-md16-ctvpsm beacon_run.sh[1244904]: Sep-14 03:42:42.722[DB]               info: Connected to LevelDB database name=/home/devops/beacon/chain-db
Sep 14 03:43:00 feat2-md16-ctvpsm beacon_run.sh[1244904]: Sep-14 03:43:00.053[]                 info: Initializing beacon state from anchor state slot=3829408, epoch=119669, stateRoot=0xb7d9ed03bb254078423ac5685f6d83a13d2c3824e15b050fe7aa027b8fd51f5d



Sep 14 03:43:27 feat2-md16-ctvpsm beacon_run.sh[1244904]: Sep-14 03:43:27.243[METRICS]          info: Starting metrics HTTP server port=8008, address=127.0.0.1
Sep 14 03:43:27 feat2-md16-ctvpsm beacon_run.sh[1244904]: Sep-14 03:43:27.497[API]              info: Started REST api server address=http://127.0.0.1:9596


Sep 14 03:44:00 feat2-md16-ctvpsm beacon_run.sh[1244904]: Sep-14 03:44:00.011[CHAIN]            info: Validated transition configuration with execution client terminalTotalDifficulty=0xa4a470, terminalBlockHash=0x0000000000000000000000000000000000000000000000000000000000000000, terminalBlockNumber=0x0

Sep 14 03:44:17 feat2-md16-ctvpsm beacon_run.sh[1244904]:  ✖ RangeError: index out of range: 36 + 9443 > 81
Sep 14 03:44:17 feat2-md16-ctvpsm beacon_run.sh[1244904]:     at indexOutOfRange (/usr/src/lodestar/node_modules/protobufjs/src/reader.js:13:12)
Sep 14 03:44:17 feat2-md16-ctvpsm beacon_run.sh[1244904]:     at BufferReader.read_bytes [as bytes] (/usr/src/lodestar/node_modules/protobufjs/src/reader.js:310:15)
Sep 14 03:44:17 feat2-md16-ctvpsm beacon_run.sh[1244904]:     at Function.decode (/usr/src/lodestar/node_modules/libp2p/src/peer-store/pb/peer.js:173:30)
Sep 14 03:44:17 feat2-md16-ctvpsm beacon_run.sh[1244904]:     at PersistentStore.load (/usr/src/lodestar/node_modules/libp2p/src/peer-store/store.js:73:25)
Sep 14 03:44:17 feat2-md16-ctvpsm beacon_run.sh[1244904]:     at PersistentStore.all (/usr/src/lodestar/node_modules/libp2p/src/peer-store/store.js:258:7)
Sep 14 03:44:17 feat2-md16-ctvpsm beacon_run.sh[1244904]:     at DefaultPeerStore.getPeers (/usr/src/lodestar/node_modules/libp2p/src/peer-store/index.js:52:24)
Sep 14 03:44:17 feat2-md16-ctvpsm beacon_run.sh[1244904]:     at NodejsNode._onDidStart (/usr/src/lodestar/node_modules/libp2p/src/index.js:698:22)
Sep 14 03:44:17 feat2-md16-ctvpsm beacon_run.sh[1244904]:     at NodejsNode.start (/usr/src/lodestar/node_modules/libp2p/src/index.js:389:7)
Sep 14 03:44:17 feat2-md16-ctvpsm beacon_run.sh[1244904]:     at Network.start (file:///usr/src/lodestar/packages/beacon-node/src/network/network.ts:130:5)
Sep 14 03:44:17 feat2-md16-ctvpsm beacon_run.sh[1244904]:     at Function.init (file:///usr/src/lodestar/packages/beacon-node/src/node/nodejs.ts:225:5)
Sep 14 03:44:19 feat2-md16-ctvpsm systemd[1]: beacon.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 03:44:19 feat2-md16-ctvpsm systemd[1]: beacon.service: Failed with result 'exit-code'.
Sep 14 03:44:19 feat2-md16-ctvpsm systemd[1]: beacon.service: Consumed 2min 13.431s CPU time.
Sep 14 03:44:19 feat2-md16-ctvpsm systemd[1]: beacon.service: Scheduled restart job, restart counter is at 372.
Sep 14 03:44:19 feat2-md16-ctvpsm systemd[1]: Stopped Lodestar beacon.
Sep 14 03:44:19 feat2-md16-ctvpsm systemd[1]: beacon.service: Consumed 2min 13.431s CPU time.
Sep 14 03:44:19 feat2-md16-ctvpsm systemd[1]: Started Lodestar beacon.
Sep 14 03:44:23 feat2-md16-ctvpsm beacon_run.sh[1245101]: Sep-14 03:44:23.477[]                 info: Lodestar network=goerli, version=v1.0.0/5f3509e, commit=5f3509e5537c0b1c336f68f5ba5d2eb95a8295e6
Sep 14 03:44:23 feat2-md16-ctvpsm beacon_run.sh[1245101]: Sep-14 03:44:23.606[DB]               info: Connected to LevelDB database name=/home/devops/beacon/chain-db
```

**Expected behavior**

No error

**Comment by twoeths** [comment]
removing peerstore dir does fix the issue

**Comment by twoeths** [comment]
libp2p failed to load a peer and it throws an error, need to wait for the latest libp2p (0.37.* atm) to see if the issue is still there

ideally, libp2p should ignore if it fails to load a peer, or provide a hook so that lodestar can handle it ourself - remove peer store and try again

blocked by #4114

**Comment by twoeths** [comment]
not an issue with lodestar v1.2.1 (libp2p 0.39.2)
