### ISSUE TITLE
MaxListenersExceededWarning emanating from libp2p

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/lodestar#4550]
**Describe the bug**
Another MaxListenersExceededWarning reported by a use. See original Discord [message](https://discord.com/channels/593655374469660673/593655641445367808/1019907933837996093)

The trace shared is as follows:

```
reproduced with --trace-warnings on:
ep-15 04:20:29.000[]                 info: Searching peers - peers: 0 - slot: 4700800 (skipped 96) - head: 4700704 0x9ad5…630b - execution: syncing(0xb17f…4a07) - finalized: 0xb754…1a5c:146895
(node:219718) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at Socket.addListener (node:events:605:10)
    at Socket.Readable.on (node:internal/streams/readable:875:35)
    at Socket.once (node:events:649:8)
    at /lodestar-fixed-mainnet/node_modules/libp2p-tcp/src/socket-to-conn.js:112:16
    at new Promise (<anonymous>)
    at Object.close (/lodestar-fixed-mainnet/node_modules/libp2p-tcp/src/socket-to-conn.js:89:14)
    at Connection.close [as _close] (/lodestar-fixed-mainnet/node_modules/libp2p/src/upgrader.js:349:22)
    at Connection.close (/lodestar-fixed-mainnet/node_modules/libp2p/node_modules/libp2p-interfaces/src/connection/connection.js:226:32)
(node:219718) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to
[Socket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at Socket.addListener (node:events:605:10)
    at Socket.Readable.on (node:internal/streams/readable:875:35)
    at Socket.once (node:events:649:8)
    at /lodestar-fixed-mainnet/node_modules/libp2p-tcp/src/socket-to-conn.js:112:16
    at new Promise (<anonymous>)
    at Object.close (/lodestar-fixed-mainnet/node_modules/libp2p-tcp/src/socket-to-conn.js:89:14)
    at Connection.close [as _close] (/lodestar-fixed-mainnet/node_modules/libp2p/src/upgrader.js:349:22)
    at Connection.close (/lodestar-fixed-mainnet/node_modules/libp2p/node_modules/libp2p-interfaces/src/connection/connection.js:226:32)
Sep-15 04:20:41.461[]                 info: Syncing - ? left - 0.00 slots/s - slot: 4700801 (skipped 97) - head: 4700704 0x9ad5…630b - execution: syncing(0xb17f…4a07) - finalized: 0xb754…1a5c:146895 - peers: 8
```

It looks like the warning is bubbling up from within libp2p and not lodestar application code. The last line of code from the stack trace is [here](https://github.com/libp2p/js-libp2p-interfaces/blob/libp2p-interfaces%404.0.6/packages/interfaces/src/connection/connection.js#L226)

**Expected behavior**

Avoid having MaxListenersExceededWarning show up in the log.

**Comment by philknows** [comment]
No longer seen post v1.3.0. Closing.
