### ISSUE TITLE
Annoying error stacks in logs

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#4559]
```
Sep-15 19:14:04.001[NETWORK]       ^[[36mverbose^[[39m: Req  error method=ping, encoding=ssz_snappy, client=Unknown, peer=16...jKuNyS, requestId=1755820 code=REQUEST_ERROR_DIAL_ERROR, error=stream ended before 1 bytes became available
Error: stream ended before 1 bytes became available
    at file:///srv/lodestar/node_modules/it-reader/src/index.ts:44:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.next (file:///srv/lodestar/node_modules/@libp2p/multistream-select/src/multistream.ts:58:23)
    at abortable (file:///srv/lodestar/node_modules/abortable-iterator/src/index.ts:42:18)
    at decoder (file:///srv/lodestar/node_modules/it-length-prefixed/src/decode.ts:58:22)
    at first (/srv/lodestar/node_modules/it-first/index.js:11:20)
    at file:///srv/lodestar/node_modules/@libp2p/multistream-select/src/multistream.ts:77:23
    at read (file:///srv/lodestar/node_modules/@libp2p/multistream-select/src/multistream.ts:74:15)
    at Module.readString (file:///srv/lodestar/node_modules/@libp2p/multistream-select/src/multistream.ts:92:15)
Error: REQUEST_ERROR_DIAL_ERROR
    at file:///srv/lodestar/packages/beacon-node/src/network/reqresp/request/index.ts:101:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at sendRequest (file:///srv/lodestar/packages/beacon-node/src/network/reqresp/request/index.ts:87:20)
    at ReqResp.sendRequest (file:///srv/lodestar/packages/beacon-node/src/network/reqresp/reqResp.ts:153:22)
    at ReqResp.ping (file:///srv/lodestar/packages/beacon-node/src/network/reqresp/reqResp.ts:99:12)
    at PeerManager.requestPing (file:///srv/lodestar/packages/beacon-node/src/network/peers/peerManager.ts:348:25)
```

Our logs are 99% logs like ^

For things that we know are bound to happen A LOT, we don't need actual stacks ( or double-stacked stacks :stuck_out_tongue_closed_eyes: ).

We should analyze the logs for worst offenders and either fix upstream or in lodestar, wherever it makes the most sense.

**Comment by nazarhussain** [comment]
With the recent changes specially from @wemeetagain related to `libp2p`, hope all such cases where we had such double tracing is fixed. If we face this issue again, will reopen the issue.
