### ISSUE TITLE
Error updating eth1 chain cache

### ISSUE THREAD

**Issue by kornface13** [ChainSafe/lodestar#4587]
I'm seeing the following error in lodestar: `error: Error updating eth1 chain cache  Timeout request`

Here is a log snippet:
```Sep-22 17:12:30.000[]                 info: Synced - slot: 3946562 (skipped 2) - head: 3946560 0x4fb5…48e8 - execution: valid(0xe776…bf24) - finalized: 0xacca…4f95:123328 - peers: 47
Sep-22 17:12:42.001[]                 info: Synced - slot: 3946563 - head: 3946563 0x25b5…ddc0 - execution: valid(0x3898…13bf) - finalized: 0xacca…4f95:123328 - peers: 50
Sep-22 17:12:54.014[]                 info: Synced - slot: 3946564 - head: 3946564 0x7475…08ef - execution: valid(0x67e7…a6e1) - finalized: 0xacca…4f95:123328 - peers: 49
Sep-22 17:13:06.003[]                 info: Synced - slot: 3946565 (skipped 1) - head: 3946564 0x7475…08ef - execution: valid(0x67e7…a6e1) - finalized: 0xacca…4f95:123328 - peers: 52
Sep-22 17:13:18.000[]                 info: Synced - slot: 3946566 - head: 3946566 0xce90…e051 - execution: valid(0x2915…3c63) - finalized: 0xacca…4f95:123328 - peers: 49
Sep-22 17:13:30.001[]                 info: Synced - slot: 3946567 - head: 3946567 0xde06…7eb1 - execution: valid(0xa561…8bbf) - finalized: 0xacca…4f95:123328 - peers: 50
Sep-22 17:13:32.831[ETH1]            error: Error updating eth1 chain cache  Timeout request
Error: Timeout request
    at JsonRpcHttpClient.fetchJsonOneUrl (file:///usr/app/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:239:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at JsonRpcHttpClient.fetchJson (file:///usr/app/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:160:16)
    at JsonRpcHttpClient.fetchBatch (file:///usr/app/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:143:39)
    at async Promise.all (index 0)
    at retry (file:///usr/app/packages/utils/src/retry.ts:33:14)
    at Eth1Provider.getBlocksByNumber (file:///usr/app/packages/beacon-node/src/eth1/provider/eth1Provider.ts:114:23)
    at Eth1DepositDataTracker.updateBlockCache (file:///usr/app/packages/beacon-node/src/eth1/eth1DepositDataTracker.ts:260:23)
    at Eth1DepositDataTracker.update (file:///usr/app/packages/beacon-node/src/eth1/eth1DepositDataTracker.ts:192:31)```

This happens continually.  The lodestar validator still submits attestations correctly.  

Nethermind is rapidly scrolling lines similar to:
```2022-09-22 17:14:33.1075|Executing JSON RPC call eth_getBlockByNumber with params [0x61a51e, False]
2022-09-22 17:14:33.1781|Executing JSON RPC call eth_getBlockByNumber with params [0x61a51f, False]
2022-09-22 17:14:33.1817|Executing JSON RPC call eth_getBlockByNumber with params [0x61a520, False]
2022-09-22 17:14:33.1870|Executing JSON RPC call eth_getBlockByNumber with params [0x61a521, False]```

These do not ever seem to stop.  If I close Lodestar and use nimbus or lighthouse with nethermind, I get these lines occasionally but not at the extreme rate they appear when using Lodestar and Nethermind.


When I tell lodestar to communicate with Geth, this timeout does not occur.  

<!--A clear and concise description of what the bug is and steps to reproduce it.-->

I start nethermind with the following docker command:
`docker run -d -p 8545:8545 -p 8551:8551 -p 30303:30303/tcp -p 30303:30303/udp -v /media/2tb/nethermind/data:/nethermind/data  -v /media/2tb/jwtsecret:/tmp/jwtsecret nethermind/nethermind --JsonRpc.Enabled true --JsonRpc.Host 0.0.0.0 --JsonRpc.EnginePort 8551 --JsonRpc.EngineHost 0.0.0.0 --JsonRpc.JwtSecretFile=/tmp/jwtsecret --config goerli --datadir data --HealthChecks.Enabled true --HealthChecks.UIEnabled true --Sync.SnapSync true`

Nethermind version: `Nethermind/v1.14.2-0-08354f9fa-20220922/X64-Linux/6.0.9`

I start Lodestar using eth-docker and just have `EL_NODE=http://192.168.13.99:8551` in my .env file. 
Lodestar version: 1.0.0 

<!--A clear and concise description of what you expected to happen.-->

I expect to never see timeouts talking to the execution layer.  I also do not expect to see Nethermind scrolling logs so rapidly.  




- OS: Ubuntu 
- Version: 22.04.1

**Comment by g11tech** [comment]
already resolved in https://github.com/ChainSafe/lodestar/pull/4532, could you try `next` docker image tag, it should have this fix, and let know if the timeout issues automatically resolves (you will still see some timeouts which will make lodestar dynamically adjust its load to nethermind)
once confirmed resolve we can close off this issue cc @philknows

**Comment by philknows** [comment]
Resolved as mentioned in the Discord chat. Thanks for writing this up as documentation for others!
