### ISSUE TITLE
If targetPeers is set as 100, beacon node process exits after a couple of seconds later

### ISSUE THREAD

**Issue by canbal99** [ChainSafe/lodestar#4592]
**Description:**

If I try to set "targetPeers" param for beacon node as "100", then process exits with error message:

Sep-23 13:22:25.379[]                 info: Initializing beacon state from anchor state slot=3951936, epoch=123498, stateRoot=0xc6f726a12f27f97bc34a35e033da0c2d9a90348dbf0707d13d4a5e0ff84fdf50
 ✖ Error: Connection Manager maxConnections must be greater than minConnections
    at new ConnectionManager (/home/can/eth2/data/beaconchain/lodestar/bin/node_modules/libp2p/src/connection-manager/index.js:80:21)
    at new Libp2p (/home/can/eth2/data/beaconchain/lodestar/bin/node_modules/libp2p/src/index.js:215:30)
    at new NodejsNode (file:///home/can/eth2/data/beaconchain/lodestar/bin/packages/beacon-node/src/network/nodejs/bundle.ts:25:5)
    at createNodeJsLibp2p (file:///home/can/eth2/data/beaconchain/lodestar/bin/packages/beacon-node/src/network/nodejs/util.ts:65:10)
    at Object.beaconHandler [as handler] (file:///home/can/eth2/data/beaconchain/lodestar/bin/packages/cli/src/cmds/beacon/handler.ts:78:15)
beaconchain.lodestar.goerli.service: Main process exited, code=exited, status=1/FAILURE

**Screenshots**

**Desktop (please complete the following information):**

- OS: ubuntu
- Version: 22.04
- Branch: tag v1.0.0
- Commit hash: 4fb7950

**Comment by dapplion** [comment]
Hey @canbal99 indeed there's a bug where maxPeers default is not changed if you increase targetPeers. Then libp2p throws with the above error. Will fix asap. In the meantime, please set `--network.maxPeers 110` or some value greater than targetPeers.

**Comment by canbal99** [comment]
@dapplion thanks for the trick...
Then I will watch #4606
