### ISSUE TITLE
Allow Lodestar to Continue Running After PROTO_ARRAY_INVALID_LVH_EXECUTION_RESPONSE

### ISSUE THREAD

**Issue by SeaMonkey82** [ChainSafe/lodestar#4708]
The current behavior of Lodestar is to exit if the EL client is attempting to invalidate a previously valid block and `PROTO_ARRAY_INVALID_LVH_EXECUTION_RESPONSE` is encountered.  I think Lodestar should continue to run and produce errors as opposed to exiting entirely.  That way, once the issue with the EL has been resolved, Lodestar can resume syncing without any further interaction.

Here is a log of the current behavior.

```
Oct-31 15:38:19.336[chain]           error: Block error slot=4219531 code=BLOCK_ERROR_EXECUTION_ERROR, execStatus=INVALID, errorMessage=Block already present in bad block manager.
Error: BLOCK_ERROR_EXECUTION_ERROR
    at verifyBlockExecutionPayload (file:///home/seamonkey/Downloads/goerli/lodestar/packages/beacon-node/src/chain/blocks/verifyBlocksExecutionPayloads.ts:292:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at verifyBlocksExecutionPayload (file:///home/seamonkey/Downloads/goerli/lodestar/packages/beacon-node/src/chain/blocks/verifyBlocksExecutionPayloads.ts:151:28)
    at async Promise.all (index 2)
    at BeaconChain.verifyBlocksInEpoch (file:///home/seamonkey/Downloads/goerli/lodestar/packages/beacon-node/src/chain/blocks/verifyBlock.ts:67:72)
    at BeaconChain.processBlocks (file:///home/seamonkey/Downloads/goerli/lodestar/packages/beacon-node/src/chain/blocks/index.ts:71:68)
    at JobItemQueue.runJob (file:///home/seamonkey/Downloads/goerli/lodestar/packages/beacon-node/src/util/queue/itemQueue.ts:92:22)
Oct-31 15:38:20.099[chain]           error: Failed to run prepareForNextSlot nextEpoch=132128, isEpochTransition=false, prepareSlot=4228092 code=PROTO_ARRAY_INVALID_LVH_EXECUTION_RESPONSE, lvhCode=ValidToInvalid, blockRoot=0xbcc5e6a208351b4aef9e6ab56e79a553900677a0b1dff4ded201c27871e5cee0, execHash=0x78a8667d2be1e381b02650e45df7eb8250735b075592466fd94d205b87580398
Error: PROTO_ARRAY_INVALID_LVH_EXECUTION_RESPONSE
    at ProtoArray.findHead (file:///home/seamonkey/Downloads/goerli/lodestar/packages/fork-choice/src/protoArray/protoArray.ts:457:13)
    at ForkChoice.updateHead (file:///home/seamonkey/Downloads/goerli/lodestar/packages/fork-choice/src/forkChoice/forkChoice.ts:230:38)
    at BeaconChain.recomputeForkChoiceHead (file:///home/seamonkey/Downloads/goerli/lodestar/packages/beacon-node/src/chain/chain.ts:412:30)
    at ChainEventEmitter.PrepareNextSlotScheduler.prepareForNextSlot (file:///home/seamonkey/Downloads/goerli/lodestar/packages/beacon-node/src/chain/prepareNextSlot.ts:75:64)
Oct-31 15:38:24.307[]                error: Process shutdown requested  code=PROTO_ARRAY_INVALID_LVH_EXECUTION_RESPONSE, lvhCode=ValidToInvalid, blockRoot=0xbcc5e6a208351b4aef9e6ab56e79a553900677a0b1dff4ded201c27871e5cee0, execHash=0x78a8667d2be1e381b02650e45df7eb8250735b075592466fd94d205b87580398
Error: PROTO_ARRAY_INVALID_LVH_EXECUTION_RESPONSE
    at ProtoArray.invalidateNodeByIndex (file:///home/seamonkey/Downloads/goerli/lodestar/packages/fork-choice/src/protoArray/protoArray.ts:421:13)
    at ProtoArray.validateLatestHash (file:///home/seamonkey/Downloads/goerli/lodestar/packages/fork-choice/src/protoArray/protoArray.ts:318:14)
    at ForkChoice.validateLatestHash (file:///home/seamonkey/Downloads/goerli/lodestar/packages/fork-choice/src/forkChoice/forkChoice.ts:787:23)
    at BeaconChain.processBlocks (file:///home/seamonkey/Downloads/goerli/lodestar/packages/beacon-node/src/chain/blocks/index.ts:82:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at JobItemQueue.runJob (file:///home/seamonkey/Downloads/goerli/lodestar/packages/beacon-node/src/util/queue/itemQueue.ts:92:22)
Oct-31 15:38:24.365[]                 info: Stopping gracefully, use Ctrl+C again to force process exit
```

**Comment by dapplion** [comment]
@g11tech can review but I think this is an un-recoverable error. Killing the process allows Lodestar to drop the in-memory fork-choice structure and retry + alert node runners that the process is a very unhealthy state since it's restarting

**Comment by g11tech** [comment]
Yea we had a discussion about this in discord, will see if in some conditions we can also just reject the block (and the forkchoice statuses have not yet been fipped)

**Comment by g11tech** [comment]
Thought over and realized the best and least error prone option would be to throw away current forkchoice and sync from last synced, 

now that lodestar always writes finalized state onto the disk from where it can begin re-sync on restarts, restarting lodestar which automatically throws away forkchoice and syncs from last available finalized state in disk (which is last finalized now) seems to be the cleanest and least technical debt solution.

Closing for now, pls reopen if the issue author feels this still needs to be addressed
