### ISSUE TITLE
Failed to register validators to builder

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4740]
**Describe the bug**

Got a lot of errors like this in mainnet nodes of 100 validators:

```
Nov-09 00:03:39.890[]                ^[[31merror^[[39m: Failed to register validator registrations with builder epoch=159188 Bad Gateway: Bad Gateway: no successful relay response
Error: Bad Gateway: Bad Gateway: no successful relay response
    at HttpClient.requestWithBody (file:///usr/app/packages/api/src/utils/client/httpClient.ts:121:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HttpClient.request (file:///usr/app/packages/api/src/utils/client/httpClient.ts:79:12)
    at Object.request [as registerValidator] (file:///usr/app/packages/api/src/utils/client/client.ts:82:9)
    at registerValidator (file:///usr/app/packages/validator/src/services/prepareBeaconProposer.ts:110:11)
    at Clock.runAtMostEvery (file:///usr/app/packages/validator/src/util/clock.ts:96:7)
```

**Expected behavior**

No error

**Comment by g11tech** [comment]
> **Describe the bug**
> 
> Got a lot of errors like this in mainnet nodes of 100 validators:
> 
> ```
> Nov-09 00:03:39.890[]                ^[[31merror^[[39m: Failed to register validator registrations with builder epoch=159188 Bad Gateway: Bad Gateway: no successful relay response
> Error: Bad Gateway: Bad Gateway: no successful relay response
>     at HttpClient.requestWithBody (file:///usr/app/packages/api/src/utils/client/httpClient.ts:121:15)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at HttpClient.request (file:///usr/app/packages/api/src/utils/client/httpClient.ts:79:12)
>     at Object.request [as registerValidator] (file:///usr/app/packages/api/src/utils/client/client.ts:82:9)
>     at registerValidator (file:///usr/app/packages/validator/src/services/prepareBeaconProposer.ts:110:11)
>     at Clock.runAtMostEvery (file:///usr/app/packages/validator/src/util/clock.ts:96:7)
> ```
> 
> **Expected behavior**
> 
> No error

this is the external builder  builder itself throwing error `Bad Gateway`, i don't think there is much we can do over here.
