### ISSUE TITLE
Failed to produce block

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4743]
**Describe the bug**

This happens on mainnet, v1.2.0

Validator log

```
34943:Nov-09 19:07:11.219[]                error: Error proposing block slot=5099734, validator=0x9458…b482 Failed to produce engine or builder block - Failed to produce block
```

Beacon log

```
Nov-09 19:07:11.175[rest]            ^[[31merror^[[39m: Req req-54l produceBlockV2 error  No block for root 0x858b12df7d85d42459c04ae99d4142a593dd0a990d720cf3b68cc98a5e0cccc8
Error: No block for root 0x858b12df7d85d42459c04ae99d4142a593dd0a990d720cf3b68cc98a5e0cccc8
    at ProtoArray.getBlockReadonly (file:///usr/app/packages/fork-choice/src/protoArray/protoArray.ts:879:13)
    at ForkChoice.getDependentRoot (file:///usr/app/packages/fork-choice/src/forkChoice/forkChoice.ts:842:29)
    at isValidAttestationData (file:///usr/app/packages/beacon-node/src/chain/opPools/aggregatedAttestationPool.ts:449:47)
    at AggregatedAttestationPool.getAttestationsForBlock (file:///usr/app/packages/beacon-node/src/chain/opPools/aggregatedAttestationPool.ts:137:14)
    at BeaconChain.produceBlockBody (file:///usr/app/packages/beacon-node/src/chain/produceBlock/produceBlockBody.ts:91:55)
    at BeaconChain.produceBlockWrapper (file:///usr/app/packages/beacon-node/src/chain/chain.ts:366:36)
    at Object.produceBlock (file:///usr/app/packages/beacon-node/src/api/impl/validator/index.ts:228:21)
    at Object.handler (file:///usr/app/packages/api/src/utils/server/genericJsonServer.ts:41:23)
```

**Expected behavior**

Lodestar should be able to produce block

**Comment by twoeths** [comment]
this issue does happen on goerli but it's so rare

```
grep -e "produceBlockV2" -rn beacon-2022-11-* | wc -l
124
```

```
grep -e " produceBlockV2 error  No block for root" -rn beacon-2022-11-* | wc -l
2
```

**Comment by twoeths** [comment]
at slot 5099733, epoch 159364 was finalized (slot 5099648)

```
Nov-09 19:07:05.001[]                 ^[[32minfo^[[39m: Synced - slot: 5099733 - head: 5099733 0x59a2…ff6a - execution: valid(0xe98c…b056) - finalized: 0xda3c…ba57:159364 - peers: 50
```

but the `forkchoice.getDependentRoot()` api tries to jump to slot 5099647 (`0x858b12df7d85d42459c04ae99d4142a593dd0a990d720cf3b68cc98a5e0cccc8`) which is before the finalized slot, that's why we got the error

also this only happens on v1.2.0 since #4555

**Comment by twoeths** [comment]
closed via https://github.com/ChainSafe/lodestar/pull/4745
