### ISSUE TITLE
Failed eth1 e2e test on CI

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4746]
**Describe the bug**

This happened on CI https://github.com/ChainSafe/lodestar/actions/runs/3434656983/jobs/5726174256

```
@lodestar/beacon-node:   1) Eth1 streams
@lodestar/beacon-node:        Should fetch 1000 deposits with getDepositsAndBlockStreamForGenesis:
@lodestar/beacon-node:      Error: Too Many Requests: {"jsonrpc":"2.0","id":3,"error":{"code":-32005,"message":"project ID request rate exceeded","data":{"rate":{"allowed_rps":5,"backoff_seconds":30,"current_rps":45.46666666666667},"see":"https://infura.io/docs/ethereum#section/Rate-Limits"}}}
@lodestar/beacon-node:       at JsonRpcHttpClient.fetchJsonOneUrl (file:///home/runner/work/lodestar/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:227:15)
@lodestar/beacon-node:       at runMicrotasks (<anonymous>)
@lodestar/beacon-node:       at processTicksAndRejections (node:internal/process/task_queues:96:5)
@lodestar/beacon-node:       at async JsonRpcHttpClient.fetchJson (file:///home/runner/work/lodestar/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:160:16)
@lodestar/beacon-node:       at async JsonRpcHttpClient.fetch (file:///home/runner/work/lodestar/lodestar/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:109:34)
@lodestar/beacon-node:       at async Eth1Provider.getBlockByNumber (file:///home/runner/work/lodestar/lodestar/packages/beacon-node/src/eth1/provider/eth1Provider.ts:107:12)
@lodestar/beacon-node:       at async Promise.all (index 1)
@lodestar/beacon-node:       at async getDepositsAndBlockStreamForGenesis (file:///home/runner/work/lodestar/lodestar/packages/beacon-node/src/eth1/stream.ts:52:30)
@lodestar/beacon-node:       at async Context.<anonymous> (file:///home/runner/work/lodestar/lodestar/packages/beacon-node/test/e2e/eth1/stream.test.ts:61:30)
```

**Expected behavior**

No error

**Comment by dapplion** [comment]
This e2e test still relies on an external provider. This is a no-go but we never had the time to fix it since setting a local EL with deposits is a lot of hassle. Maybe @nazarhussain could you do some preliminary assessment if this is doable without to much effort?

**Comment by dapplion** [comment]
Closing for https://github.com/ChainSafe/lodestar/issues/4014
