### ISSUE TITLE
Test ProduceBlock call: error calling notifyForkchoiceUpdate

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4752]
**Describe the bug**

on a goerli node when issuing a `produceBlockV2` call from a curl command similar to the below:

```
curl http://localhost:9596/eth/v2/validator/blocks/4303954?randao_reveal=0x81e12358643ce7c2feb447e7b01952d8be91e2fd2d0ceaa45ab107233d07a4371146b5805db04ce8306dce7d228001bd12a8512b782c019d831944f6b80e81a7bd4bd2ea00e0b714637a5e03e57c43fa0c431b6d8d0ab48ed5c382cce7c979fc
```

sometimes I got this error

```
Nov-11 08:30:49.411[rest]            ^[[31merror^[[39m: Req req-cm8 produceBlockV2 error  Received invalid payloadId=null
Error: Received invalid payloadId=null
    at ExecutionEngineHttp.notifyForkchoiceUpdate (file:///usr/app/packages/beacon-node/src/execution/engine/http.ts:257:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareExecutionPayload (file:///usr/app/packages/beacon-node/src/chain/produceBlock/produceBlockBody.ts:259:17)
    at BeaconChain.produceBlockBody (file:///usr/app/packages/beacon-node/src/chain/produceBlock/produceBlockBody.ts:149:28)
    at BeaconChain.produceBlockWrapper (file:///usr/app/packages/beacon-node/src/chain/chain.ts:366:13)
    at Object.produceBlock (file:///usr/app/packages/beacon-node/src/api/impl/validator/index.ts:228:21)
    at Object.handler (file:///usr/app/packages/api/src/utils/server/genericJsonServer.ts:41:23)
Nov-11 08:30:49.418[rest]            ^[[34mdebug^[[39m: Res req-cm8 produceBlockV2 - 500
```

or 

```
Nov-11 08:26:48.994[rest]            ^[[34mdebug^[[39m: Req req-ch2 127.0.0.1 produceBlockV2
Nov-11 08:26:49.170[rest]            ^[[31merror^[[39m: Req req-ch2 produceBlockV2 error  JSON RPC error: Invalid payload attributes, engine_forkchoiceUpdatedV1
Error: JSON RPC error: Invalid payload attributes, engine_forkchoiceUpdatedV1
    at parseRpcResponse (file:///usr/app/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:258:11)
    at JsonRpcHttpClient.fetchWithRetries (file:///usr/app/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:133:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Timeout.JobItemQueue.runJob [as _onTimeout] (file:///usr/app/packages/beacon-node/src/util/queue/itemQueue.ts:92:22)
Nov-11 08:26:49.171[rest]            ^[[34mdebug^[[39m: Res req-ch2 produceBlockV2 - 500
```

**Expected behavior**

No error, or a good explanation of the error (from geth)

**Comment by dapplion** [comment]
Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable
