### ISSUE TITLE
Investigate InsufficientPeers issue when submitPoolAttestations in sim tests

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4764]
I am seeing lot of these error messages on the `unstable` branch during the sim tests. 

```
Eph 4/4 1.635[node-2-cl-lodestar/api] [31merror[39m: Error on submitPoolAttestations [0] slot=36, index=2 PublishError.InsufficientPeers
Error: PublishError.InsufficientPeers
    at EventTarget.publish (file:///home/runner/work/lodestar/lodestar/node_modules/@chainsafe/libp2p-gossipsub/src/index.ts:1957:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EventTarget.publishObject (file:///home/runner/work/lodestar/lodestar/packages/beacon-node/src/network/gossip/gossipsub.ts:171:20)
    at EventTarget.publishBeaconAttestation (file:///home/runner/work/lodestar/lodestar/packages/beacon-node/src/network/gossip/gossipsub.ts:213:12)
    at file:///home/runner/work/lodestar/lodestar/packages/beacon-node/src/api/impl/beacon/pool/index.ts:52:31
    at async Promise.all (index 0)
    at Object.submitPoolAttestations (file:///home/runner/work/lodestar/lodestar/packages/beacon-node/src/api/impl/beacon/pool/index.ts:46:7)
    at Object.handler (file:///home/runner/work/lodestar/lodestar/packages/api/src/utils/server/genericJsonServer.ts:41:23)
```

_Originally posted by @nazarhussain in https://github.com/ChainSafe/lodestar/issues/4660#issuecomment-1311457914_

**Comment by twoeths** [comment]
this used to happen in e2e tests when we have single node, it's gone after we configured `network: {allowPublishToZeroPeers: true},` in `getDevBeaconNode` api

**Comment by dapplion** [comment]
> this used to happen in e2e tests when we have single node, it's gone after we configured `network: {allowPublishToZeroPeers: true},` in `getDevBeaconNode` api

In this test the network always has 4 peers connected with each other. `allowPublishToZeroPeers` of course suppresses the error, that the purpose of the flag. However:
- The network has 4 peers each running >= 32 validators
- Then, all nodes _should_ be subscribed to all subnets and all syncnets
- If scores are good all nodes should be meshed with each other
- Then, when publishing any gossip object it should be sent to at least 1 peer. So, why does the `InsufficientPeers` error happen?

**Comment by twoeths** [comment]
@dapplion I just want to give info to this issue, I didn't mean the issue happened in any e2e tests. I also wasn't able to find a sim test in CI that has this error, @nazarhussain will help me with that

**Comment by q9f** [comment]
@tuyennhv I have the same issue on a local testnet if you want to debug this further (5 peers, 8 validators).

is this related btw: #4816

```
Dec-01 00:19:38.001[]                 info: Synced - slot: 181 - head: 181 0x3603…3f34 - execution: valid(0xec5a…6cd4) - finalized: 0x1eb0…9fba:3 - peers: 4                                                                                   
Dec-01 00:19:44.514[api]             error: Error on submitPoolSyncCommitteeSignatures [0] slot=182, validatorIndex=0 PublishError.InsufficientPeers                                                                                           
Error: PublishError.InsufficientPeers                                                                                                                                                                                                          
    at EventTarget.publish (file:///home/user/.opt/ChainSafe/lodestar/node_modules/@chainsafe/libp2p-gossipsub/src/index.ts:1957:13)                                                                                                           
    at EventTarget.publishObject (file:///home/user/.opt/ChainSafe/lodestar/packages/beacon-node/src/network/gossip/gossipsub.ts:171:20)                                                                                                       
    at EventTarget.publishSyncCommitteeSignature (file:///home/user/.opt/ChainSafe/lodestar/packages/beacon-node/src/network/gossip/gossipsub.ts:242:5)                                                                                        
    at async Promise.all (index 0)                                                                                                                                                                                                             
    at file:///home/user/.opt/ChainSafe/lodestar/packages/beacon-node/src/api/impl/beacon/pool/index.ts:146:13                                                                                                                                 
    at async Promise.all (index 0)                                                                                                                                                                                                             
    at Object.submitPoolSyncCommitteeSignatures (file:///home/user/.opt/ChainSafe/lodestar/packages/beacon-node/src/api/impl/beacon/pool/index.ts:116:7)
    at Object.handler (file:///home/user/.opt/ChainSafe/lodestar/packages/api/src/utils/server/genericJsonServer.ts:41:23)
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
Error: Multiple errors on publishAggregateAndProofs
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
    at Object.submitPoolSyncCommitteeSignatures (file:///home/user/.opt/ChainSafe/lodestar/packages/beacon-node/src/api/impl/beacon/pool/index.ts:170:15)
    at Object.handler (file:///home/user/.opt/ChainSafe/lodestar/packages/api/src/utils/server/genericJsonServer.ts:41:23)
Dec-01 00:19:50.004[]                 info: Synced - slot: 182 - head: 182 0x3298…a96e - execution: valid(0xadd1…27ef) - finalized: 0x1eb0…9fba:3 - peers: 4
```

**Comment by twoeths** [comment]
> @tuyennhv I have the same issue on a local testnet if you want to debug this further (5 peers, 8 validators).

@q9f could you show me how to set up the network? it's not an issue if it happens some slots after a node is started because peer discovery needs some time to get stable subnet peers

> is this related btw: https://github.com/ChainSafe/lodestar/issues/4816

no, that's peer drop issue while this is about not enough subnet peers even through we have enough peers

**Comment by q9f** [comment]
> @q9f could you show me how to set up the network? it's not an issue if it happens some slots after a node is started because peer discovery needs some time to get stable subnet peers

I have two execution clients (geth), five beacon nodes (lodestar), and one validator (lodestar, with 8 keys)

```shell
geth \
  --networkid 11166111 \
  --datadir "/tmp/holesovice/execution/1" \
  --authrpc.port 8651 \
  --port 31303 \
  --bootnodes "enode://d5704c15a444908cacdea75c25139530024c248b05815e7e260c415bea2381465fa7cd4f78d778700e37a2be9fe480642d308e74a704bcf146bf7cb53732ab83@127.0.0.1:30303,enode://eb271cb12a0f227265e79322fb3e8fc9e87e5401d1781f328b2002584dcfc200686f76644c614f629fcea10ca81b06c5ceb357da5aadd62934e8c26fc39944b3@127.0.0.1:31303"

lodestar beacon \
  --suggestedFeeRecipient "0xCaA29806044A08E533963b2e573C1230A2cd9a2d" \
  --execution.urls "http://127.0.0.1:8551" \
  --jwt-secret "/tmp/holesovice/execution/0/geth/jwtsecret" \
  --dataDir "/tmp/holesovice/consensus/4" \
  --paramsFile "/home/user/.opt/eth-clients/holesovice/consensus/config.yaml" \
  --genesisStateFile "/home/user/.opt/eth-clients/holesovice/consensus/genesis.ssz" \
  --enr.ip 127.0.0.1 \
  --rest.port 9996 \
  --port 9400 \
  --network.connectToDiscv5Bootnodes true \
  --bootnodes "enr:-Ku4QFQtoQ8Os6ePsGnaVhQHVOJpG1AdD8lI5eVin-LVXhDIY5GtGfZhJfWiN9sx59y9rt5kKEdA3hlVd5NcbVr97gkFh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDfrT8vAhZhEf__________gmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQL8-KCPND2kixBj-wDqGG33ySHYJflbz7XkGL5JsVxJnYN0Y3CCIyg,enr:-Ku4QNOQz2TatOuWhuFvuzfXpDsPrv4An-P5P60SwG3nR-pWdsj2G0Is7M5lJ0cqfGFrg0QLEb1Bj5l3u6gvo4PmFDEFh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDfrT8vAhZhEf__________gmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQPZxnhiMNp6Kwt0xg29s8bcCYsWheIyQ3GKamZ4lnipLIN0Y3CCI4w,enr:-Ku4QHFo3nbJPxWY0je6z34UPfma9xqP9os0ML3GIgUCnsyhRGC84B0BvHOOuxEVBEzKPAoCv7hbMkGGkbCPqMhMclUFh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDfrT8vAhZhEf__________gmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQP9MEV7lchABvza09gZKSuSb1pEv99SlFjrHSQujh7lb4N0Y3CCI_A,enr:-Ku4QHJ3K_HhJWuLid32jpxwZipds0-YgtX8IW43BvJqUQutJ6il5EIQY71qS9T_vHNst5Y_Bm0OOdh84xnxVF4hsLoFh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDfrT8vAhZhEf__________gmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQMmaG17UMfVGG8NAuAmMzFd88xWstoO_gHMOO5RnaWNi4N0Y3CCJFQ,enr:-Ku4QD_lKVwo52Y9JOrZibU9I6qh-QOiA213HAELfLHfnB4reWQhZq0YVS1rsf1GU7afqjD7UvKfWQTi6LsdjGNkMSwFh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDfrT8vAhZhEf__________gmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQJsajVPzBxl8CS8W2Jj7CKpxojG5t85yrQ32WuMD1h4eoN0Y3CCJLg"

lodestar validator \
  --dataDir "/tmp/holesovice/consensus/0" \
  --suggestedFeeRecipient "0xCaA29806044A08E533963b2e573C1230A2cd9a2d" \
  --graffiti "YOLO HOLESOVICE LODESTAR" \
  --paramsFile "/home/user/.opt/eth-clients/holesovice/consensus/config.yaml" \
  --importKeystores "/home/user/.opt/eth-clients/holesovice/consensus/validator_keys" \
  --importKeystoresPassword "/home/user/.opt/eth-clients/holesovice/consensus/validator_keys/password.txt"
```

Just realized it's an `Error on submitPoolSyncCommitteeSignatures` not `submitPoolAttestations` though.

**Comment by q9f** [comment]
I just tried again and keep having this. My beacon node has 4 peers but I keep seeing this:

```
Error: Multiple errors on publishAggregateAndProofs
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
    at Object.submitPoolSyncCommitteeSignatures (file:///home/user/.opt/ChainSafe/lodestar/packages/beacon-node/src/api/impl/beacon/pool/index.ts:170:15)
    at Object.handler (file:///home/user/.opt/ChainSafe/lodestar/packages/api/src/utils/server/genericJsonServer.ts:41:23)
Dec-21 11:28:09.001[]                 info: Synced - slot: 4849 - head: 4849 0x899f…360f - execution: valid(0xeddb…56c1) - finalized: 0xc353…c3b5:149 - peers: 4
```

**Comment by avenbreaks** [comment]
> @tuyennhvSaya memiliki masalah yang sama di testnet lokal jika Anda ingin men-debug ini lebih lanjut (5 rekan, 8 validator).
> 
> apakah ini terkait btw: #4816
> 
> ```
> Dec-01 00:19:38.001[]                 info: Synced - slot: 181 - head: 181 0x3603…3f34 - execution: valid(0xec5a…6cd4) - finalized: 0x1eb0…9fba:3 - peers: 4                                                                                   
> Dec-01 00:19:44.514[api]             error: Error on submitPoolSyncCommitteeSignatures [0] slot=182, validatorIndex=0 PublishError.InsufficientPeers                                                                                           
> Error: PublishError.InsufficientPeers                                                                                                                                                                                                          
>     at EventTarget.publish (file:///home/user/.opt/ChainSafe/lodestar/node_modules/@chainsafe/libp2p-gossipsub/src/index.ts:1957:13)                                                                                                           
>     at EventTarget.publishObject (file:///home/user/.opt/ChainSafe/lodestar/packages/beacon-node/src/network/gossip/gossipsub.ts:171:20)                                                                                                       
>     at EventTarget.publishSyncCommitteeSignature (file:///home/user/.opt/ChainSafe/lodestar/packages/beacon-node/src/network/gossip/gossipsub.ts:242:5)                                                                                        
>     at async Promise.all (index 0)                                                                                                                                                                                                             
>     at file:///home/user/.opt/ChainSafe/lodestar/packages/beacon-node/src/api/impl/beacon/pool/index.ts:146:13                                                                                                                                 
>     at async Promise.all (index 0)                                                                                                                                                                                                             
>     at Object.submitPoolSyncCommitteeSignatures (file:///home/user/.opt/ChainSafe/lodestar/packages/beacon-node/src/api/impl/beacon/pool/index.ts:116:7)
>     at Object.handler (file:///home/user/.opt/ChainSafe/lodestar/packages/api/src/utils/server/genericJsonServer.ts:41:23)
> PublishError.InsufficientPeers
> PublishError.InsufficientPeers
> PublishError.InsufficientPeers
> PublishError.InsufficientPeers
> PublishError.InsufficientPeers
> PublishError.InsufficientPeers
> PublishError.InsufficientPeers
> PublishError.InsufficientPeers
> Error: Multiple errors on publishAggregateAndProofs
> PublishError.InsufficientPeers
> PublishError.InsufficientPeers
> PublishError.InsufficientPeers
> PublishError.InsufficientPeers
> PublishError.InsufficientPeers
> PublishError.InsufficientPeers
> PublishError.InsufficientPeers
> PublishError.InsufficientPeers
>     at Object.submitPoolSyncCommitteeSignatures (file:///home/user/.opt/ChainSafe/lodestar/packages/beacon-node/src/api/impl/beacon/pool/index.ts:170:15)
>     at Object.handler (file:///home/user/.opt/ChainSafe/lodestar/packages/api/src/utils/server/genericJsonServer.ts:41:23)
> Dec-01 00:19:50.004[]                 info: Synced - slot: 182 - head: 182 0x3298…a96e - execution: valid(0xadd1…27ef) - finalized: 0x1eb0…9fba:3 - peers: 4
> ```

im getting same error : 

```
Error: Internal Server Error: PublishError.InsufficientPeers
    at HttpClient.requestWithBody (file:///mnt/block-volume/lodestar/packages/api/src/utils/client/httpClient.ts:258:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HttpClient.request (file:///mnt/block-volume/lodestar/packages/api/src/utils/client/httpClient.ts:132:12)
    at Object.request [as submitPoolAttestations] (file:///mnt/block-volume/lodestar/packages/api/src/utils/client/client.ts:82:9)
    at AttestationService.signAndPublishAttestations (file:///mnt/block-volume/lodestar/packages/validator/src/services/attestation.ts:158:7)
    at AttestationService.runAttestationTasks (file:///mnt/block-volume/lodestar/packages/validator/src/services/attestation.ts:74:5)
    at Clock.runAtMostEvery (file:///mnt/block-volume/lodestar/packages/validator/src/util/clock.ts:96:7)
Feb-24 14:19:33.428[]                [31merror[39m: Error publishing SyncCommitteeMessage slot=3 Internal Server Error: Multiple errors on publishAggregateAndProofs
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
Error: Internal Server Error: Multiple errors on publishAggregateAndProofs
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
PublishError.InsufficientPeers
    at HttpClient.requestWithBody (file:///mnt/block-volume/lodestar/packages/api/src/utils/client/httpClient.ts:258:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HttpClient.request (file:///mnt/block-volume/lodestar/packages/api/src/utils/client/httpClient.ts:132:12)
    at Object.request [as submitPoolSyncCommitteeSignatures] (file:///mnt/block-volume/lodestar/packages/api/src/utils/client/client.ts:82:9)
    at SyncCommitteeService.produceAndPublishSyncCommittees (file:///mnt/block-volume/lodestar/packages/validator/src/services/syncCommittee.ts:148:9)
    at SyncCommitteeService.runSyncCommitteeTasks (file:///mnt/block-volume/lodestar/packages/validator/src/services/syncCommittee.ts:67:31)
    at Clock.runAtMostEvery (file:///mnt/block-volume/lodestar/packages/validator/src/util/clock.ts:96:7)
Feb-24 14:19:41.203[]                 [32minfo[39m: Published aggregateAndProofs slot=3, index=0, count=1
Feb-24 14:19:41.205[]                 [32minfo[39m: Published SyncCommitteeContribution slot=3, index=1, count=1
Feb-24 14:19:41.209[]                 [32minfo[39m: Published SyncCommitteeContribution slot=3, index=2, count=1
Feb-24 14:19:41.210[]                 [32minfo[39m: Published SyncCommitteeContribution slot=3, index=3, count=1
Feb-24 14:19:45.143[]                 [32minfo[39m: Published block slot=4, validator=0xa750…9b5d, graffiti=YOLO MERGEDNET GETH LODESTAR, source=engine, feeRecipient=0xcaa29806044a08e533963b2e573c1230a2cd9a2d, transactions=0
Feb-24 14:19:45.415[]                [31merror[39m: Error publishing SyncCommitteeMessage slot=4 Internal Server Error: Multiple errors on publishAggregateAndProofs
```

**Comment by twoeths** [comment]
this could be due to https://github.com/ChainSafe/lodestar/issues/5198#issuecomment-1445879443

**Comment by philknows** [comment]
Stale. If happens again, open new issue please.
