### ISSUE TITLE
Failed sim test ci

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#4960]
**Describe the bug**

Sim tests randomly failed with

```
Simulation environment "multi-fork" is stopping: Sim run timedout in 437000 ms 
DockerRunner stopping 'node-1-el-geth'...
DockerRunner stopping 'node-2-el-nethermind'...
DockerRunner stopping 'node-3-el-geth'...
DockerRunner stopping 'node-4-el-nethermind'...
file:///home/runner/work/lodestar/lodestar/packages/utils/src/sleep.ts:24
      reject(new ErrorAborted());
             ^
ErrorAborted: Aborted 
    at EventTarget.onAbort (file:///home/runner/work/lodestar/lodestar/packages/utils/src/sleep.ts:24:14)
    at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:731:20)
    at EventTarget.dispatchEvent (node:internal/event_target:673:26)
    at abortSignal (node:internal/abort_controller:308:10)
    at AbortController.abort (node:internal/abort_controller:338:5)
    at SimulationEnvironment.stop (file:///home/runner/work/lodestar/lodestar/packages/cli/test/utils/simulation/SimulationEnvironment.ts:237:29)
    at Timeout._onTimeout (file:///home/runner/work/lodestar/lodestar/packages/cli/test/utils/simulation/SimulationEnvironment.ts:145:12)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

for example https://github.com/ChainSafe/lodestar/actions/runs/3792403436/jobs/6448569972 https://github.com/ChainSafe/lodestar/actions/runs/3798818524/jobs/6471882574

**Expected behavior**

No error

**Comment by nazarhussain** [comment]
I found these weird and unusual errors in linked failed run. And there are really a lot of these errors. Trying to reproduce. 

```
2022-12-28T07:24:24.298Z libp2p:mplex:stream:trace receiver stream 7 abort Error: Too many inbound protocol streams for protocol "/ipfs/id/push/1.0.0" - limit 1
    at file:///home/runner/work/lodestar/lodestar/node_modules/libp2p/src/upgrader.ts:372:43
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_TOO_MANY_INBOUND_PROTOCOL_STREAMS'
}
```

```
Eph 6/7 1.557[node-2-cl-lodestar/network] [36mverbose[39m: Resp error method=status, client=unknown, peer=16...n9CSSs, requestId=116 peer=16Uiu2HAmJCZbq2HV1AwGj3ZadTizw8SQhN4wNMDUNQgeMqn9CSSs, method=status, encoding=ssz_snappy, code=REQUEST_ERROR_RATE_LIMITED
```

**Comment by nazarhussain** [comment]
Compared to a successful execution, it seems these **rate limiting errors** are the culprit and not visible in successful execution. @tuyennhv Do you remember making any change, which could result into rate limiting errors?
