### ISSUE TITLE
Feature: Add sanity check for checkpoint chain mismatch

### ISSUE THREAD

**Issue by yorickdowne** [ChainSafe/lodestar#4983]
**Is your feature request related to a problem? Please describe.**

A misconfiguration where checkpoint and configured chain do not match is not detected.

Set Lodestar to `goerli` network and use `https://beaconstate.info` mainnet checkpoint.

Logs:
```
eth-docker-devel-consensus-1  | Jan-06 15:11:07.956[]                 info: Lodestar network=goerli, version=v1.3.0/031e42c, commit=031e42cbe8015109e2af6e9cdec1b15dd66fc937
eth-docker-devel-consensus-1  | Jan-06 15:11:07.981[]                 info: Connected to LevelDB database path=/var/lib/lodestar/consensus/chain-db
eth-docker-devel-consensus-1  | Jan-06 15:11:07.986[]                 info: Fetching checkpoint state checkpointSyncUrl=https://beaconstate.info
eth-docker-devel-consensus-1  | Jan-06 15:11:11.983[]                 info: Download completed
eth-docker-devel-consensus-1  | Jan-06 15:11:25.612[]                 info: Initializing beacon from a valid checkpoint state slot=5516064, epoch=172377, stateRoot=0xb7858fd7170ab4b51dddf6f1c5dd81de58ced47486eaba7e962d733049899a72, isWithinWeakSubjectivityPeriod=true
...
eth-docker-devel-consensus-1  | Jan-06 15:12:18.782[rest]            error: Req req-9 getBlockV2 error  No block found for id '0'
eth-docker-devel-consensus-1  | Error: No block found for id '0'
eth-docker-devel-consensus-1  |     at resolveBlockId (file:///usr/app/packages/beacon-node/src/api/impl/beacon/blocks/utils.ts:33:11)
eth-docker-devel-consensus-1  |     at Object.getBlockV2 (file:///usr/app/packages/beacon-node/src/api/impl/beacon/blocks/index.ts:117:21)
eth-docker-devel-consensus-1  |     at Object.handler (file:///usr/app/packages/api/src/utils/server/genericJsonServer.ts:41:23)
eth-docker-devel-consensus-1  | Jan-06 15:12:21.907[rest]            error: Req req-b getBlockV2 error  No block found for id 'finalized'
eth-docker-devel-consensus-1  | Error: No block found for id 'finalized'
eth-docker-devel-consensus-1  |     at resolveBlockId (file:///usr/app/packages/beacon-node/src/api/impl/beacon/blocks/utils.ts:33:11)
eth-docker-devel-consensus-1  |     at Object.getBlockV2 (file:///usr/app/packages/beacon-node/src/api/impl/beacon/blocks/index.ts:117:21)
eth-docker-devel-consensus-1  |     at Object.handler (file:///usr/app/packages/api/src/utils/server/genericJsonServer.ts:41:23)
```

Then when attempting to import keys with slashing protection:

```
Internal server error. Error: ERR_INTERCHANGE_GENESIS_VALIDATOR_MISMATCH
```

😅

**Describe the solution you'd like**

Detect that checkpoint and chain don't match. Either exit, preferable; or start a genesis sync. Exit would be better as the user clearly means to use a checkpoint and just has to provide the correct one.

**Comment by dapplion** [comment]
- Unstable includes a check just for that, should cover the exact case you bring up https://github.com/ChainSafe/lodestar/pull/4938

**Comment by philknows** [comment]
Tried it the other way around and confirm it errors in latest `unstable` Closing.

```
Jan-10 18:46:39.458[]                 info: Lodestar network=mainnet, version=v1.3.0/5f1c368, commit=5f1c368693cf430419b6b976529360c0702a5625
Jan-10 18:46:39.474[]                 info: Connected to LevelDB database path=/data/chain-db
Jan-10 18:46:39.477[]                 info: Fetching checkpoint state checkpointSyncUrl=https://goerli.checkpoint-sync.ethdevops.io
 ✖ Error: Unable to fetch weak subjectivity state: Internal Server Error: block not found
    at fetchWeakSubjectivityState (file:///usr/app/packages/cli/src/networks/index.ts:161:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fetchWSStateFromBeaconApi (file:///usr/app/packages/cli/src/cmds/beacon/initBeaconState.ts:194:35)
    at initBeaconState (file:///usr/app/packages/cli/src/cmds/beacon/initBeaconState.ts:125:12)
    at Object.beaconHandler [as handler] (file:///usr/app/packages/cli/src/cmds/beacon/handler.ts:76:41)
```

**Comment by philknows** [comment]
```
Jan-10 18:54:58.379[]                 info: Lodestar network=goerli, version=v1.3.0/5f1c368, commit=5f1c368693cf430419b6b976529360c0702a5625
Jan-10 18:54:58.405[]                 info: Connected to LevelDB database path=/data/chain-db
Jan-10 18:54:58.408[]                 info: Fetching checkpoint state checkpointSyncUrl=https://beaconstate.info
Jan-10 18:55:04.784[]                 info: Download completed
 ✖ Error: State current fork version 0x02000000 not equal to current config 0x02001020. Maybe caused by importing a state from a different network
    at initStateFromAnchorState (file:///usr/app/packages/beacon-node/src/chain/initState.ts:175:11)
    at initAndVerifyWeakSubjectivityState (file:///usr/app/packages/cli/src/cmds/beacon/initBeaconState.ts:70:23)
    at fetchWSStateFromBeaconApi (file:///usr/app/packages/cli/src/cmds/beacon/initBeaconState.ts:197:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at initBeaconState (file:///usr/app/packages/cli/src/cmds/beacon/initBeaconState.ts:125:12)
    at Object.beaconHandler [as handler] (file:///usr/app/packages/cli/src/cmds/beacon/handler.ts:76:41)
```
