### ISSUE TITLE
Nethermind v1.16.0: Error updating eth1 chain cache  resArr.map is not a function on on Goerli

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar#5032]
**Describe the bug**

Using Lodestar with the latest Nethermind release 2 days ago seems to break with Lodestar. Below is the error from the Lodestar beacon. This seems to only affect Goerli. Testing now on mainnet.

```
Jan-21 18:46:12.261[eth1]            error: Error updating eth1 chain cache  resArr.map is not a function
TypeError: resArr.map is not a function
    at JsonRpcHttpClient.fetchBatch (file:///usr/app/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:147:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Eth1Provider.getBlocksByNumber (file:///usr/app/packages/beacon-node/src/eth1/provider/eth1Provider.ts:93:23)
    at Eth1DepositDataTracker.updateBlockCache (file:///usr/app/packages/beacon-node/src/eth1/eth1DepositDataTracker.ts:295:19)
    at Eth1DepositDataTracker.update (file:///usr/app/packages/beacon-node/src/eth1/eth1DepositDataTracker.ts:208:31)
    at Eth1DepositDataTracker.runAutoUpdate (file:///usr/app/packages/beacon-node/src/eth1/eth1DepositDataTracker.ts:170:29)
```

**Expected behavior**

Should not have any issues with updating eth1 cache.

**Steps to Reproduce**

<!--Steps to reproduce the behavior:
1. Run Nethermind 1.16.0
2. Use any Lodestar version (tried with `next` (`a130d41`) and `latest` (v1.3.0)

**Comment by philknows** [comment]
Fixed via https://github.com/NethermindEth/nethermind/pull/5198
