### ISSUE TITLE
Failed to getClient while connecting to lighthouse on bellatrix fork

### ISSUE THREAD

**Issue by AmanRaj1608** [ChainSafe/lodestar#5035]
**Describe the bug**

When trying to run lightclient via
```sh
./lodestar lightclient --beaconApiUrl https://lodestar-mainnet.chainsafe.io --checkpointRoot 0x7da401b3683174e55b2c347251fb1612127ac9b63bf55115ee216d271989f5cd
```

Getting this error: 
```
 Error: JSON expected key beacon is undefined
    at ContainerType.fromJson (/Users/aman/Desktop/coding/lodestar/node_modules/@chainsafe/ssz/src/type/container.ts:340:15)
    at ContainerType.fromJson (/Users/aman/Desktop/coding/lodestar/node_modules/@chainsafe/ssz/src/type/container.ts:342:36)
    at Object.fromJson (file:///Users/aman/Desktop/coding/lodestar/packages/api/src/utils/types.ts:175:44)
    at Object.request [as getBootstrap] (file:///Users/aman/Desktop/coding/lodestar/packages/api/src/utils/client/client.ts:80:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Function.initializeFromCheckpointRoot (file:///Users/aman/Desktop/coding/lodestar/packages/light-client/src/index.ts:156:31)
    at Object.lightclientHandler [as handler] (file:///Users/aman/Desktop/coding/lodestar/packages/cli/src/cmds/lightclient/handler.ts:21:18)
```

**Desktop (please complete the following information):**

- OS:  OSX Ventura
- Version: 13.0.1
- Branch: unstable
- Commit hash: 3c1db8d850c18dea8d5cb9beaf4a28066e51b61e

**Comment by AmanRaj1608** [comment]
When the `generateGenericJsonClient` calls the `returnType.fromJson(res.body)` the data is, but somehow it expects a key of `beacon`. Not sure where this is coming from.

```
{
  data: {
    header: {
      slot: '5616736',
      proposer_index: '18530',
      parent_root: '0x7e3f175323819fb142c73795ba33d409aa9965de3206361a986ab9ce57389d9c',
      state_root: '0xea9993852f644502967d886c5fefd240ccede0c5005fe02b2f2285287fdc31b3',
      body_root: '0xfe2d975edb742291343be23418c1e22211798ba328908467cadea0ea2556b781'
    },
    current_sync_committee: {
      pubkeys: [Array],
      aggregate_pubkey: '0xab396058b1aa06483751e09bc6ef2b583417c8a34eef24463bb295f20da981f95c6f4cc5e9265aa88da78dd82461d93b'
    },
    current_sync_committee_branch: [
      '0x59e5f91b26fd4a59a559a1e0041f5b30e560f56070178107d172bde8d92a7a19',
      '0x7873901f50dc7207a3c3f426b059b20b17902b9c91c34e604473a34f50dd3536',
      '0x973ac358aa1a259f898047d832c110ea634af969e697be5590f5a4f7a0d8c608',
      '0xa1bfe4a78f709538bb4662b0e537cf371fd38610dc4b1b54b1fc689f4328b7fa',
      '0x98829d99e92456e065f4e4e5abbddc5e5ed939f48a944894f84046a04c7f81d7'
    ]
  },
  version: 'bellatrix'
}
```

**Comment by dapplion** [comment]
@AmanRaj1608 Specs changed recently, causing a breaking change. Lighthouse is probably not yet updated
- see https://github.com/ChainSafe/lodestar/pull/5011

**Comment by AmanRaj1608** [comment]
Thanks makes sense, working fine on stable version.
