### ISSUE TITLE
Validator: wrong publish error log

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5140]
**Describe the bug**

Found this in the log

```
validator-2023-02-09.log:39664:Feb-09 09:04:14.522[]                error: Error proposing block slot=5759119, validator=0x810e…7963  - Internal Server Error: PublishError.Duplicate - Failed to publish block
validator-2023-02-10.log:8356:Feb-10 01:56:27.419[]                error: Error proposing block slot=5764180, validator=0xa8dc…7536  - Internal Server Error: PublishError.Duplicate - Failed to publish block
```

However as we can see those 2 blocks are all success

**Expected behavior**

- No error

**Screenshots**

<img width="817" alt="Screen Shot 2023-02-13 at 15 28 32" src="https://user-images.githubusercontent.com/10568965/218407798-8b900921-5de9-42f9-bd1c-0752084d5a87.png">

**Desktop (please complete the following information):**

- Version: v1.4.2
- Network: mainnet

**Comment by twoeths** [comment]
more log:

```
Feb-10 01:56:25.663[]                ^[[34mdebug^[[39m: Request error, retrying  Internal Server Error: PublishError.Duplicate
Error: Internal Server Error: PublishError.Duplicate
    at HttpClient.requestWithBody (file:///usr/app/packages/api/src/utils/client/httpClient.ts:285:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Feb-10 01:56:25.663[]                ^[[34mdebug^[[39m: Requesting fallback URL routeId=publishBlindedBlock, baseUrl=http://***:9596, score=2
Feb-10 01:56:25.663[]                ^[[34mdebug^[[39m: HttpClient request routeId=publishBlindedBlock
Feb-10 01:56:27.419[]                ^[[31merror^[[39m: Error proposing block slot=5764180, validator=0xa8dc…7536  - Internal Server Error: PublishError.Duplicate - Failed to publish block
Error:  - Internal Server Error: PublishError.Duplicate - Failed to publish block
    at Function.assert (file:///usr/app/packages/api/src/utils/client/httpClient.ts:44:13)
    at BlockProposingService.publishBlockWrapper (file:///usr/app/packages/validator/src/services/block.ts:107:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlockProposingService.createAndPublishBlock (file:///usr/app/packages/validator/src/services/block.ts:95:7)
    at async Promise.all (index 0)
```
