### ISSUE TITLE
Missed attestions with - Error: ATTESTATION_ERROR_UNKNOWN_OR_PREFINALIZED_BEACON_BLOCK_ROOT

### ISSUE THREAD

**Issue by Chozowarrior** [ChainSafe/lodestar#5152]
The validators assigned to the node are missing a lot of attestations. After inspecting the log it seems the error below is thrown out over and over. I am running Lodestar v1.4.3 (stable) with Nethermind v 1.16.1 (stable)

Error:
Feb-14 12:45:50.129[rest]            [34mdebug[39m: Req req-rid 192.168.178.35 submitPoolAttestations
Feb-14 12:45:50.129[api]             [31merror[39m: Error on submitPoolAttestations [0] slot=5795927, index=19 code=ATTESTATION_ERROR_UNKNOWN_OR_PREFINALIZED_BEACON_BLOCK_ROOT, root=0xbbcdca6fbd6358436c69cf721a3d9e52495f974f12f9110003d3baaaaff09f25
Error: ATTESTATION_ERROR_UNKNOWN_OR_PREFINALIZED_BEACON_BLOCK_ROOT
    at verifyHeadBlockIsKnown (file:///home/ethereum/lodestar/packages/beacon-node/src/chain/validation/attestation.ts:229:11)
    at verifyHeadBlockAndTargetRoot (file:///home/ethereum/lodestar/packages/beacon-node/src/chain/validation/attestation.ts:207:21)
    at validateGossipAttestation (file:///home/ethereum/lodestar/packages/beacon-node/src/chain/validation/attestation.ts:66:24)
    at file:///home/ethereum/lodestar/packages/beacon-node/src/api/impl/beacon/pool/index.ts:54:56
    at Array.map (<anonymous>)
    at Object.submitPoolAttestations (file:///home/ethereum/lodestar/packages/beacon-node/src/api/impl/beacon/pool/index.ts:52:22)
    at Object.handler (file:///home/ethereum/lodestar/packages/api/src/utils/server/genericJsonServer.ts:45:41)
    at preHandlerCallback (/home/ethereum/lodestar/node_modules/fastify/lib/handleRequest.js:126:28)
    at preValidationCallback (/home/ethereum/lodestar/node_modules/fastify/lib/handleRequest.js:109:5)
    at handler (/home/ethereum/lodestar/node_modules/fastify/lib/handleRequest.js:72:7)
Feb-14 12:45:50.130[rest]            [31merror[39m: Req req-rid submitPoolAttestations error  code=ATTESTATION_ERROR_UNKNOWN_OR_PREFINALIZED_BEACON_BLOCK_ROOT, root=0xbbcdca6fbd6358436c69cf721a3d9e52495f974f12f9110003d3baaaaff09f25

**Comment by Chozowarrior** [comment]
I just deleted the beacon chain database but even after resyncing the error still pops up so perhaps it is more on the validator side.

**Comment by Chozowarrior** [comment]
also deleting the validator database does not resolve the issue.

**Comment by twoeths** [comment]
@Chozowarrior did you configure any fallback urls at your validator side? This could happen if validator produce attestation data from one beacon node and submit that attestation to another beacon node which hasn't had that block head yet, see https://github.com/ChainSafe/lodestar/issues/5098#issuecomment-1427504993

it happened to my node and I checked that attestations were not missed

**Comment by Chozowarrior** [comment]
Yes there are fallbacks configured. At the moment the Lodestar node is configured as a fallback for a Teku node. The otherway around is also configured but this does not seem to work (as a side note Teku does not except the socket type from Lodestar somehow. Is there a way to get rid of the error message since it is still there even after a fresh sync of the beaconnode?

**Comment by twoeths** [comment]
@Chozowarrior could you confirm that it's not a missed attestations?

>  Is there a way to get rid of the error message since it is still there even after a fresh sync of the beaconnode?

yes working on that

**Comment by Chozowarrior** [comment]
@tuyennhv confirm is indeed not related to a missed attestation.
