### ISSUE TITLE
Error producing aggregateAndProofs

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5214]
**Describe the bug**

When setting up lodestar as a fallback node, this error could happen producing AggregateAndProof (log at validator side)

```
Error: Error producing aggregateAndProofs - Internal Server Error: No attestation for slot=5853500 dataRoot=0x7196516447183be4e49b0c37a88cdf80f8182d7f4b58a7705a093c47ffba857e
    at Function.assert (file:///usr/app/packages/api/src/utils/client/httpClient.ts:44:13)
    at AttestationService.produceAndPublishAggregates (file:///usr/app/packages/validator/src/services/attestation.ts:192:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at AttestationService.runAttestationTasks (file:///usr/app/packages/validator/src/services/attestation.ts:86:5)
    at Clock.runAtMostEvery (file:///usr/app/packages/validator/src/util/clock.ts:96:7)
```

**Expected behavior**

No error

**Comment by twoeths** [comment]
a lode fallback node should subscribe to all subnets
