### ISSUE TITLE
Rejected BlsToExecutionChange gossip messages

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5372]
**Describe the bug**

This happens **only** on test mainnet nodes, got p4 penalties due to rejected BlsToExecutionChange gossip messages

<img width="1300" alt="Screenshot 2023-04-18 at 14 21 02" src="https://user-images.githubusercontent.com/10568965/232701814-6c8bfb94-61f8-4ad7-8c3d-00c1b0adf781.png">

With v1.7.2 we don't see the log, with latest gossip implementation, the log is like below:

```
Apr-18 06:47:07.492[network]         ^[[34mdebug^[[39m: Gossip validation bls_to_execution_change rejected  code=BLS_TO_EXECUTION_CHANGE_ERROR_INVALID
Error: BLS_TO_EXECUTION_CHANGE_ERROR_INVALID
    at validateBlsToExecutionChange (file:///usr/app/packages/beacon-node/src/chain/validation/blsToExecutionChange.ts:33:11)
    at Object.bls_to_execution_change (file:///usr/app/packages/beacon-node/src/network/processor/gossipHandlers.ts:378:13)
    at NetworkWorker.gossipValidatorFn (file:///usr/app/packages/beacon-node/src/network/processor/gossipValidatorFn.ts:35:54)
    at NetworkWorker.processPendingGossipsubMessage (file:///usr/app/packages/beacon-node/src/network/processor/worker.ts:32:35)
    at NetworkEventBus.emit (node:events:513:28)
    at Timeout._onTimeout (file:///usr/app/packages/beacon-node/src/network/gossip/gossipsub.ts:413:19)
    at listOnTimeout (node:internal/timers:569:17)
```

**Expected behavior**

- Investigate why I don't see this on prod mainnet nodes?
- Investigate why the validation failed

**Desktop (please complete the following information):**

- Version: v1.7.2

**Comment by dapplion** [comment]
Validity conditions are:
- Refers to known index
- Signature is correct
- Credentials have not already been changed

It must be the last one, where nodes are rebroadcasting messages for changes that have already been applied, but should double check. I won't imagine having large amounts of credentials changes with invalid signatures. Are we using the right state to validate?

**Comment by twoeths** [comment]
there is no epoch/slot in `BlsToExecutionChange` message, we just use head state
yes the reason message was rejected is because withdrawal credential was already changed in the head state, and that's due to the fact that we used to delay the gossip message validation a lot (up to minutes)
that explains why it only happen with `unstable` not with `stable(v1.7.2)`
since this PR https://github.com/ChainSafe/lodestar/pull/5407 I haven't seen this issue anymore

<img width="1312" alt="Screenshot 2023-04-27 at 06 00 50" src="https://user-images.githubusercontent.com/10568965/234720601-00a4e638-9d35-46c5-81ea-613d3e3c1fc9.png">
