### ISSUE TITLE
Validators failed to start

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5386]
**Describe the bug**

Validators failed to start in unstable group, looks like it's related to some recent yarg/lerna upgrade?

```
^[[AApr-19 12:39:41.452[]                 info: Lodestar network=goerli, version=v1.7.2/3ee1d8a, commit=3ee1d8a5acb09160827b185c79d2ead80442c0e7
Apr-19 12:39:41.454[]                 info: Connecting to LevelDB database path=/data/validator-db
 ✖ Error: invalid mnemonic
    at deriveKeyFromMnemonic (/usr/app/node_modules/@chainsafe/bls-keygen/src/index.ts:25:11)
    at getSignersFromArgs (file:///usr/app/packages/cli/src/cmds/validator/signers/index.ts:70:22)
    at Object.validatorHandler [as handler] (file:///usr/app/packages/cli/src/cmds/validator/handler.ts:80:25)
    at file:///usr/app/packages/cli/node_modules/yargs/build/lib/command.js:206:54
    at maybeAsyncResult (file:///usr/app/packages/cli/node_modules/yargs/build/lib/utils/maybe-async-result.js:9:15)
    at CommandInstance.handleValidationAndGetResult (file:///usr/app/packages/cli/node_modules/yargs/build/lib/command.js:205:25)
    at CommandInstance.applyMiddlewareAndGetResult (file:///usr/app/packages/cli/node_modules/yargs/build/lib/command.js:245:20)
    at CommandInstance.runCommand (file:///usr/app/packages/cli/node_modules/yargs/build/lib/command.js:128:20)
    at YargsInstance.[runYargsParserAndExecuteCommands] (file:///usr/app/packages/cli/node_modules/yargs/build/lib/yargs-factory.js:1386:105)
    at YargsInstance.parse (file:///usr/app/packages/cli/node_modules/yargs/build/lib/yargs-factory.js:707:63)
```

**Expected behavior**

no error

**Comment by wemeetagain** [comment]
Our ansible scripts were adding an additional level of quotes. eg: `"'{{mnemonic}}'"`.
Resolved by removing the additional quotes, eg: `"{{mnemonic}}"`
