### ISSUE TITLE
Unstable subnet topic peers

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5412]
**Describe the bug**

Subnet topic peers are unstable, I see different patterns on different nodes

<img width="1286" alt="Screenshot 2023-04-24 at 20 51 35" src="https://user-images.githubusercontent.com/10568965/234016885-a190ba19-1ba6-4342-b619-afa8d24acb7d.png">

<img width="1302" alt="Screenshot 2023-04-24 at 20 52 01" src="https://user-images.githubusercontent.com/10568965/234016981-7a0f083c-e3fd-4c51-985b-84c821c927ce.png">

<img width="1302" alt="Screenshot 2023-04-24 at 20 52 33" src="https://user-images.githubusercontent.com/10568965/234017122-1d72f648-7f67-4cb0-a393-a6b76829040a.png">

In worse case, user reported missed attestation due to no subnet peers

```
beacon_node_1  | Apr-24 04:03:24.868[api]             error: Error on submitPoolAttestations [0] slot=6290415, index=2 PublishError.InsufficientPeers
beacon_node_1  | Error: PublishError.InsufficientPeers
beacon_node_1  |     at Eth2Gossipsub.publish (file:///usr/app/node_modules/@chainsafe/libp2p-gossipsub/src/index.ts:2038:13)
beacon_node_1  |     at Eth2Gossipsub.publishObject (file:///usr/app/packages/beacon-node/src/network/gossip/gossipsub.ts:176:20)
beacon_node_1  |     at file:///usr/app/packages/beacon-node/src/api/impl/beacon/pool/index.ts:69:31
beacon_node_1  |     at async Promise.all (index 0)
beacon_node_1  |     at Object.submitPoolAttestations (file:///usr/app/packages/beacon-node/src/api/impl/beacon/pool/index.ts:52:7)
beacon_node_1  |     at Object.handler (file:///usr/app/packages/api/src/utils/server/genericJsonServer.ts:44:23)
beacon_node_1  | Apr-24 04:03:24.869[rest]            error: Req req-9exg submitPoolAttestations error  PublishError.InsufficientPeers
beacon_node_1  | Error: PublishError.InsufficientPeers
beacon_node_1  |     at Eth2Gossipsub.publish (file:///usr/app/node_modules/@chainsafe/libp2p-gossipsub/src/index.ts:2038:13)
beacon_node_1  |     at Eth2Gossipsub.publishObject (file:///usr/app/packages/beacon-node/src/network/gossip/gossipsub.ts:176:20)
beacon_node_1  |     at file:///usr/app/packages/beacon-node/src/api/impl/beacon/pool/index.ts:69:31
beacon_node_1  |     at async Promise.all (index 0)
beacon_node_1  |     at Object.submitPoolAttestations (file:///usr/app/packages/beacon-node/src/api/impl/beacon/pool/index.ts:52:7)
beacon_node_1  |     at Object.handler (file:///usr/app/packages/api/src/utils/server/genericJsonServer.ts:44:23)
```

more context https://discord.com/channels/593655374469660673/593655641445367808/1099907367442845786

**Expected behavior**

- Stable good number of subnet peers

**Comment by twoeths** [comment]
this issue does not happen with v1.10.0, this sent peers pattern is common in nodes

<img width="1293" alt="Screenshot 2023-08-20 at 13 20 44" src="https://github.com/ChainSafe/lodestar/assets/10568965/c804aeab-c6b2-4ef2-9766-e824e4925ce9">
