### ISSUE TITLE
`MaxListenersExceededWarning` when creating >10 child loggers

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5529]
`MaxListenersExceededWarning` warnings for `DailyRotateFile` on current `unstable` branch, might be related to changes done in
- https://github.com/ChainSafe/lodestar/pull/5490

Logs with `--trace-warnings`

```
(node:13306) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added to [DailyRotateFile]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at DailyRotateFile.addListener (node:events:605:10)
    at DerivedLogger.Readable.pipe (/home/nico/projects/ethereum/lodestar/node_modules/readable-stream/lib/_stream_readable.js:631:8)
    at DerivedLogger.add (/home/nico/projects/ethereum/lodestar/node_modules/winston/lib/winston/logger.js:364:10)
    at /home/nico/projects/ethereum/lodestar/node_modules/winston/lib/winston/logger.js:124:44
    at Array.forEach (<anonymous>)
    at DerivedLogger.configure (/home/nico/projects/ethereum/lodestar/node_modules/winston/lib/winston/logger.js:124:18)
    at new Logger (/home/nico/projects/ethereum/lodestar/node_modules/winston/lib/winston/logger.js:42:10)
    at new DerivedLogger (/home/nico/projects/ethereum/lodestar/node_modules/winston/lib/winston/create-logger.js:44:7)
(node:13306) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [DailyRotateFile]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at DailyRotateFile.prependListener (node:events:619:14)
    at prependListener (/home/nico/projects/ethereum/lodestar/node_modules/readable-stream/lib/_stream_readable.js:98:69)
    at DerivedLogger.Readable.pipe (/home/nico/projects/ethereum/lodestar/node_modules/readable-stream/lib/_stream_readable.js:708:3)
    at DerivedLogger.add (/home/nico/projects/ethereum/lodestar/node_modules/winston/lib/winston/logger.js:364:10)
    at /home/nico/projects/ethereum/lodestar/node_modules/winston/lib/winston/logger.js:124:44
    at Array.forEach (<anonymous>)
    at DerivedLogger.configure (/home/nico/projects/ethereum/lodestar/node_modules/winston/lib/winston/logger.js:124:18)
    at new Logger (/home/nico/projects/ethereum/lodestar/node_modules/winston/lib/winston/logger.js:42:10)
```

Related issues

- https://github.com/winstonjs/winston/issues/1334
- https://github.com/winstonjs/winston/issues/2065
- https://github.com/winstonjs/winston/issues/1791
- https://github.com/winstonjs/winston/issues/2247

**Comment by nflaig** [comment]
Only happens if more than 10 child loggers (`logger.child`) are created, can be reproduced by setting both `--metrics` and `--monitoring.endpoint` flag.
