### ISSUE TITLE
v1.9.0-rc.0: Worker max listeners warning

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5552]
### Describe the bug

MaxListenersExceededWarning when running beacon node with attached validator client (does not show up if no VC is attached)

```
(node:67035) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [Worker]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at Worker.addListener (node:events:605:10)
    at Worker.addEventListener (/home/devops/goerli/lodestar/node_modules/@chainsafe/threads/dist/master/implementation.node.js:130:18)
    at /home/devops/goerli/lodestar/node_modules/@chainsafe/threads/dist/master/invocation-proxy.js:64:16
    at new Subscription (/home/devops/goerli/lodestar/node_modules/observable-fns/dist/observable.js:159:40)
    at Observable.subscribe (/home/devops/goerli/lodestar/node_modules/observable-fns/dist/observable.js:210:16)
    at /home/devops/goerli/lodestar/node_modules/observable-fns/dist/multicast.js:31:49
    at new Subscription (/home/devops/goerli/lodestar/node_modules/observable-fns/dist/observable.js:159:40)
    at Observable.subscribe (/home/devops/goerli/lodestar/node_modules/observable-fns/dist/observable.js:210:16)
```

### Expected behavior

No max listeners warnings

### Steps to reproduce

Run beacon node and validator client (with active validators), 

**Edit:** also observed this while running BN without attached validators

### Operating system

Linux

### Lodestar version or commit hash

v1.9.0-rc.0

**Comment by philknows** [comment]
Has anyone been seeing this on `v1.9.1`?

**Comment by nflaig** [comment]
This only happens if network worker thread is enabled, haven't looked into the implementation but it looks like threads library adds a listener for each worker (see stack trace). Need to check if there is a option to increase max listeners.

**Comment by philknows** [comment]
I just haven't been seeing this recently in our `unstable` or `feat1` nodes where we enabled the worker on `v1.9.1` and on `next` tag. So was wondering if this was a stale issue from rc.0.

**Comment by nflaig** [comment]
This log happens only once (at startup) and is only a single line without `--trace-warnings` flag. I can check if this still happens on unstable.

**Comment by nflaig** [comment]
This is a known issue
- https://github.com/andywer/threads.js/issues/312

I created a PR on our fork [@chainsafe/threads](https://www.npmjs.com/package/@chainsafe/threads) to fix it
- https://github.com/ChainSafe/threads.js/pull/2
