### ISSUE TITLE
Validator client unclean disconnect on shutdown

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5706]
### Describe the bug

When shutting down the VC is causes the following error on the BN

```
Jun-25 02:58:26.174[rest]            error: Req req-5 eventstream error  aborted
Error: aborted
    at connResetException (node:internal/errors:717:14)
    at abortIncoming (node:_http_server:754:17)
    at socketOnClose (node:_http_server:748:3)
    at Socket.emit (node:events:525:35)
    at TCP.<anonymous> (node:net:322:12)
```

In rare cases it might also lead to further error on the BN

```
Jun-25 02:58:26.192[]                error: uncaughtException: Cannot set headers after they are sent to the client
Error: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.setHeader (node:_http_outgoing:645:11)
    at ServerResponse.writeHead (node:_http_server:378:21)
    at onSendEnd (/mnt/goerli/goerli/lodestar/node_modules/fastify/lib/reply.js:596:7)
    at onSendHook (/mnt/goerli/goerli/lodestar/node_modules/fastify/lib/reply.js:529:5)
    at fallbackErrorHandler (/mnt/goerli/goerli/lodestar/node_modules/fastify/lib/error-handler.js:127:3)
    at handleError (/mnt/goerli/goerli/lodestar/node_modules/fastify/lib/error-handler.js:61:5)
    at onErrorHook (/mnt/goerli/goerli/lodestar/node_modules/fastify/lib/reply.js:742:5)
    at Reply.send (/mnt/goerli/goerli/lodestar/node_modules/fastify/lib/reply.js:133:5)
    at defaultErrorHandler (/mnt/goerli/goerli/lodestar/node_modules/fastify/lib/error-handler.js:92:9) Cannot set headers after they are sent to the client
Error: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.setHeader (node:_http_outgoing:645:11)
    at ServerResponse.writeHead (node:_http_server:378:21)
    at onSendEnd (/mnt/goerli/goerli/lodestar/node_modules/fastify/lib/reply.js:596:7)
    at onSendHook (/mnt/goerli/goerli/lodestar/node_modules/fastify/lib/reply.js:529:5)
    at fallbackErrorHandler (/mnt/goerli/goerli/lodestar/node_modules/fastify/lib/error-handler.js:127:3)
    at handleError (/mnt/goerli/goerli/lodestar/node_modules/fastify/lib/error-handler.js:61:5)
    at onErrorHook (/mnt/goerli/goerli/lodestar/node_modules/fastify/lib/reply.js:742:5)
    at Reply.send (/mnt/goerli/goerli/lodestar/node_modules/fastify/lib/reply.js:133:5)
    at defaultErrorHandler (/mnt/goerli/goerli/lodestar/node_modules/fastify/lib/error-handler.js:92:9)
```

It looks like the VC abruptly aborts the connection. Might worth to investigate if we can more gracefully close the connection or if that's not possible at all reduce the verbosity of the log on the BN side.

`Error: Cannot set headers after they are sent to the client` should ideally never happen, this is caused when trying to set headers on a request that is already sent or aborted
https://github.com/ChainSafe/lodestar/blob/f5d12a893f5b913a04938275bb248ace1ca47539/packages/api/src/beacon/server/events.ts#L26-L27

### Expected behavior

Cleanly close all connections when shutting down VC, no error logs on the BN side.

### Steps to reproduce

Shutdown VC, observe BN logs

### Operating system

Linux

### Lodestar version or commit hash

v1.9.0

**Comment by nazarhussain** [comment]
For the below error, the API client need to carefully abort. If user create a client and just dispose this error will generate because of the event stream. 

> Error: Cannot set headers after they are sent to the client

**Comment by nflaig** [comment]
> For the below error, the API client need to carefully abort

Independent of how the client disconnects, the server should never try to set headers on a request that is already sent. I am pretty sure this has to be fixed on server side, either by checking `res.raw.headersSent` before setting headers or changing something else in the request/response sequence that prevents this.

**Edit:** The headers are set by fastify internally, see https://github.com/ChainSafe/lodestar/pull/5722#discussion_r1263584693
