### ISSUE TITLE
Broken `trace` logging

### ISSUE THREAD

**Issue by matthewkeil** [ChainSafe/lodestar#5809]
### Describe the bug

It appears that trace logging is broken.  Attempted to add a `logger.trace()` call and e2e tests and the node broke when deployed.

I removed the call and the error went away.  I changed the error to `debug` and the error also went away.  It looks like the name was changed from `silly` to `trace` in #4539 and winston expects the string `silly` to be passed.

We are [setting](https://github.com/ChainSafe/lodestar/blob/2c3d7e14f0082cfe70156e55a9213db952f815c4/packages/logger/src/winston.ts#L56) the [`logLevelNum`](https://github.com/ChainSafe/lodestar/blob/2c3d7e14f0082cfe70156e55a9213db952f815c4/packages/logger/src/interface.ts#L4) which the [docs say](https://github.com/winstonjs/winston#using-custom-logging-levels) should work but it may not be set correctly.

```sh
TypeError: colors[Colorizer.allColors[lookup]] is not a function
    at Colorizer.colorize (/usr/src/lodestar/node_modules/logform/colorize.js:73:49)
    at Colorizer.transform (/usr/src/lodestar/node_modules/logform/colorize.js:98:25)
    at Format.transform (/usr/src/lodestar/node_modules/logform/combine.js:20:24)
    at DerivedLogger._transform (/usr/src/lodestar/node_modules/winston/lib/winston/logger.js:313:29)
    at DerivedLogger.Transform._read (/usr/src/lodestar/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DerivedLogger.Transform._write (/usr/src/lodestar/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/usr/src/lodestar/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/usr/src/lodestar/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at DerivedLogger.Writable.write (/usr/src/lodestar/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at DerivedLogger.log (/usr/src/lodestar/node_modules/winston/lib/winston/logger.js:225:14) colors[Colorizer.allColors[lookup]] is not a function
```

### Expected behavior

A trace log should work and not break the other log levels

### Steps to reproduce

1. Create a `logger.trace`
2. Run e2e tests and should work correctly 

### Operating system

Linux

### Lodestar version or commit hash

unstable

**Comment by matthewkeil** [comment]
It looks like the ColorizeOptions expect a map with matching levels for color lookup

**Comment by nflaig** [comment]
Last time we had discussion on this in https://github.com/ChainSafe/lodestar/pull/5299 there was no push towards adding `trace`, it is not part of the [Logging policy](https://github.com/ChainSafe/lodestar/blob/unstable/CONTRIBUTING.md#logging-policy). It is not supposed to work right now and not used anywhere. 

As far as I understand the renaming in https://github.com/ChainSafe/lodestar/pull/4539 was just done so you could set `--logLevel trace` on CLI, see issue https://github.com/ChainSafe/lodestar/issues/4536.

Before looking into fixing the issue here, I would suggest we first discuss if trace is a log level we should support and then add it to logging policy first.

**Comment by matthewkeil** [comment]
We should remove the option if we are not going to use it.  Broke the node when i deployed trying to trace the network worker message latency to figure out why the grafana dashboard wasnt working.  Or fix it.  I figured out how to and was pretty easy.  Just needed to pass a map to the color options.  Already fixed on `mkeil/fix-log-trace` branch.  Just need to update the unit tests.

**Comment by dapplion** [comment]
From the agreed logging policy we do not support trace right?

**Comment by philknows** [comment]
Currently we do not support trace. It’s not in our contribution md.

**Comment by nflaig** [comment]
We should remove it from types to prevent accidental usage but still allow it to be passed through CLI to not break the use case mentioned in https://github.com/ChainSafe/lodestar/issues/4536.

**Comment by matthewkeil** [comment]
Closing.  Removed `trace` log level in #5861
