### ISSUE TITLE
eth1 chain cache timeout error on startup

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5935]
### Describe the bug

There are quite frequent eth1 chain cache timeout errors on startup

```
 Sep-02 20:36:05.274[eth1]            error: Error updating eth1 chain cache  Timeout request
Error: Timeout request
    at JsonRpcHttpClient.fetchJsonOneUrl (file:///usr/app/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:247:17)
    at JsonRpcHttpClient.fetchJson (file:///usr/app/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:171:16)
    at JsonRpcHttpClient.fetch (file:///usr/app/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts:110:33)
    at Eth1Provider.getBlockNumber (file:///usr/app/packages/beacon-node/src/eth1/provider/eth1Provider.ts:125:28)
    at Eth1DepositDataTracker.update (file:///usr/app/packages/beacon-node/src/eth1/eth1DepositDataTracker.ts:197:32)
    at Eth1DepositDataTracker.runAutoUpdate (file:///usr/app/packages/beacon-node/src/eth1/eth1DepositDataTracker.ts:169:29)
```

### Expected behavior

There should not be any timeout errors when querying the execution client on startup.

### Steps to reproduce

Start beacon node with connected execution client (timeout does not happen consistently)

### Additional context

Could be related to hashing the state on startup which is blocking the event loop causing delay in timers queue

https://github.com/ChainSafe/lodestar/blob/6646e23cfeb5b51ca6a5609befa2b329b993a65c/packages/cli/src/networks/index.ts#L201

https://github.com/ChainSafe/lodestar/blob/6646e23cfeb5b51ca6a5609befa2b329b993a65c/packages/state-transition/src/util/weakSubjectivity.ts#L104

I have not / rarely seen this on goerli but more frequently on mainnet and it was also [reported for holesky](https://discord.com/channels/593655374469660673/743858262864167062/1147639214394060962). This further indicates that it might be related to state size.

### Operating system

Linux

### Lodestar version or commit hash

unstable

**Comment by nflaig** [comment]
Additional information from [rocknet on discord](https://discord.com/channels/593655374469660673/743858262864167062/1147952397180739636) further indicates that the delay 30+ seconds could be caused by hashing the state and causing the request timeout ([default: 30s](https://github.com/ChainSafe/lodestar/blob/6646e23cfeb5b51ca6a5609befa2b329b993a65c/packages/beacon-node/src/eth1/provider/jsonRpcHttpClient.ts#L10)).

- Version message
- 1 Second later: Connected to leveldb
- ~30 seconds later: Initializing beacon from valid db state slot=0
- ~62 seconds later: Error stack trace from above.

**Comment by nflaig** [comment]
I am not seeing this issue anymore, could be due to optimizations to tree root hashing? Closing for now
