### ISSUE TITLE
Cannot download profiles with docker deployment

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#5960]
### Describe the bug

Got this

```
curl -X POST http://localhost:9596/eth/v1/lodestar/write_profile
{"statusCode":500,"error":"Internal Server Error","message":"EACCES: permission denied, open 'network_thread_2023-09-17T07:27:59.957Z.cpuprofile'"}
```

### Expected behavior

after a profile is captured, node should persist it to file system successfully, similar to `getStateV2`

### Operating system

Linux

### Lodestar version or commit hash

v1.11.0

**Comment by twoeths** [comment]
more logs:

```
Sep-17 07:27:59.961[rest]            ^[[31merror^[[39m: Req req-2kkg writeProfile error  EACCES: permission denied, open 'network_thread_2023-09-17T07:27:59.957Z.cpuprofile'
Error: EACCES: permission denied, open 'network_thread_2023-09-17T07:27:59.957Z.cpuprofile'
    at Object.openSync (node:fs:602:3)
    at Object.writeFileSync (node:fs:2334:35)
    at writeProfile (file:///usr/app/packages/beacon-node/lib/network/core/networkCoreWorker.js:120:12)
```
```
curl -X POST http://localhost:9596/eth/v1/lodestar/write_profile?thread=main
{"statusCode":500,"code":"EACCES","error":"Internal Server Error","message":"EACCES: permission denied, open 'main_thread_2023-09-17T07:47:08.932Z.cpuprofile'"}
```

```
Sep-17 07:47:08.952[rest]            ^[[31merror^[[39m: Req req-2lav writeProfile error  EACCES: permission denied, open 'main_thread_2023-09-17T07:47:08.932Z.cpuprofile'
Error: EACCES: permission denied, open 'main_thread_2023-09-17T07:47:08.932Z.cpuprofile'
    at Object.openSync (node:fs:602:3)
    at Object.writeFileSync (node:fs:2334:35)
    at Object.writeProfile (file:///usr/app/packages/beacon-node/src/api/impl/lodestar/index.ts:77:16)
    at Object.handler (file:///usr/app/packages/api/src/utils/server/genericJsonServer.ts:45:23)
```

```
curl -X POST http://localhost:9596/eth/v1/lodestar/write_profile?thread=discv5
{"statusCode":500,"error":"Internal Server Error","message":"EACCES: permission denied, open 'discv5_thread_2023-09-17T07:54:53.328Z.cpuprofile'"}
```

```
Error: EACCES: permission denied, open 'discv5_thread_2023-09-17T07:54:53.328Z.cpuprofile'
    at Object.openSync (node:fs:602:3)
    at Object.writeFileSync (node:fs:2334:35)
    at writeProfile (file:///usr/app/packages/beacon-node/lib/network/discv5/worker.js:93:12)
```

**Comment by dapplion** [comment]
@tuyennhv what full path is it trying to write the file to?

**Comment by twoeths** [comment]
> @tuyennhv what full path is it trying to write the file to?

@dapplion by default it writes the file to `beacon` folder, I did not specify "dirpath" in my curl url

**Comment by twoeths** [comment]
work around way is to log into docker container, change the file permission, then do the curl

```
docker exec -u root -it <container_name_or_id> /bin/sh
chmod 777 .
exit
curl -X POST http://localhost:9596/eth/v1/lodestar/write_profile?thread=main
```

then copy cpuprofile to the host: `docker cp 95777e4156f4:/usr/app/main_thread_2023-12-21T07:05:54.956Z.cpuprofile .`
