### ISSUE TITLE
Archive state epoch frequency is incorrect

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#5976]
### Describe the bug

What is the expected behavior if `--chain.archiveStateEpochFrequency` is set to `1`?

It looks like right now it just stored every 2nd epoch state which is not what I expected
```
Sep-21 14:36:48.675[chain]         verbose: Archived finalized state finalizedEpoch=205185
Sep-21 14:49:36.713[chain]         verbose: Archived finalized state finalizedEpoch=205187
Sep-21 15:02:24.623[chain]         verbose: Archived finalized state finalizedEpoch=205189
Sep-21 15:15:12.682[chain]         verbose: Archived finalized state finalizedEpoch=205191
```

This is due to `>` check here
https://github.com/ChainSafe/lodestar/blob/900f6a732fa7a219f496d1e9c04d4d97ce4b3d59/packages/beacon-node/src/chain/archiver/archiveStates.ts#L52

But looking at comment it might be expected "Minimum number of epochs between archived states" meaning, 1 epoch between each archived epoch. Thus, this has to be set to 0 to archive every epoch?

https://github.com/ChainSafe/lodestar/blob/900f6a732fa7a219f496d1e9c04d4d97ce4b3d59/packages/beacon-node/src/chain/archiver/archiveStates.ts#L17

### Expected behavior

I would have expected that setting `--chain.archiveStateEpochFrequency 1` would archive every epoch. Looking at @dapplion [comment on discord](https://discord.com/channels/593655374469660673/593655641445367808/1144629654846705734) seems to suggest the same.

### Steps to reproduce

Run a beacon with `--chain.archiveStateEpochFrequency 1` flag

### Operating system

Linux

### Lodestar version or commit hash

v1.11.1

**Comment by nflaig** [comment]
Setting `--chain.archiveStateEpochFrequency 0` does not work as this it would result in `NaN` when deleting old states
https://github.com/ChainSafe/lodestar/blob/900f6a732fa7a219f496d1e9c04d4d97ce4b3d59/packages/beacon-node/src/chain/archiver/archiveStates.ts#L56-L59

```
Sep-21 15:47:12.696[chain]           error: Error processing finalized checkpoint epoch=205196 The number NaN cannot be converted to a BigInt because it is not an integer
RangeError: The number NaN cannot be converted to a BigInt because it is not an integer
    at BigInt (<anonymous>)
    at encodeKey (file:///home/nico/projects/ethereum/lodestar/packages/db/src/util.ts:18:16)
    at StateArchiveRepository.encodeKey (file:///home/nico/projects/ethereum/lodestar/packages/db/src/abstractRepository.ts:45:12)
    at StateArchiveRepository.dbFilterOptions (file:///home/nico/projects/ethereum/lodestar/packages/db/src/abstractRepository.ts:273:27)
    at StateArchiveRepository.keys (file:///home/nico/projects/ethereum/lodestar/packages/db/src/abstractRepository.ts:149:42)
    at StatesArchiver.maybeArchiveState (file:///home/nico/projects/ethereum/lodestar/packages/beacon-node/src/chain/archiver/archiveStates.ts:67:59)
    at JobItemQueue.Archiver.processFinalizedCheckpoint [as itemProcessor] (file:///home/nico/projects/ethereum/lodestar/packages/beacon-node/src/chain/archiver/index.ts:104:7)
    at Timeout.JobItemQueue.runJob [as _onTimeout] (file:///home/nico/projects/ethereum/lodestar/packages/beacon-node/src/util/queue/itemQueue.ts:101:22)
```
