### ISSUE TITLE
Macos source build node-gyp error on yarn install

### ISSUE THREAD

**Issue by manylov** [ChainSafe/lodestar#6026]
### Describe the bug

Can not yarn install on macos

got error: 
```
Traceback (most recent call last):
  File "/Users/maksimmanylov/casper/light-clients/lodestar/lodestar/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "/Users/maksimmanylov/casper/light-clients/lodestar/lodestar/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/Users/maksimmanylov/casper/light-clients/lodestar/lodestar/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
```
Seems like node-gyp related issue
https://github.com/nodejs/node-gyp/pull/2888

It blocks development on macOs, are there any ways to fix it? node-gyp fix process looks slow.

### Expected behavior

no errors 

### Steps to reproduce

git clone on macos
yarn install

### Operating system

macOS

### Lodestar version or commit hash

latest

**Comment by matthewkeil** [comment]
I installed python 3.12 and the error is as you mentioned.  The official release for 3.12 was just on Oct 2 so its probably not officially supported by node-gyp yet.  I am on 3.11 and everything installs smoothly.  I can definitely recommend downgrading your python to 3.11 until that bug gets patched.

**Comment by wemeetagain** [comment]
We no longer use node-gyp, and should get rid of it from our devDependencies

**Comment by philknows** [comment]
Closing for https://github.com/ChainSafe/lodestar/issues/7193
