### ISSUE TITLE
`Req req-6w8 registerValidator error - Execution builder not enabled`

### ISSUE THREAD

**Issue by SeaMonkey82** [ChainSafe/lodestar#6082]
### Describe the bug

beacon:
```
Nov-03 08:38:36.900[rest]            error: Req req-6ez registerValidator error - Execution builder not enabled
Error: Execution builder not enabled
    at Object.registerValidator (file:///home/seamonkey/Downloads/holesky/lodestar/packages/beacon-node/src/api/impl/validator/index.ts:1099:15)
    at Object.handler (file:///home/seamonkey/Downloads/holesky/lodestar/packages/api/src/utils/server/genericJsonServer.ts:45:41)
    at preHandlerCallback (/home/seamonkey/Downloads/holesky/lodestar/node_modules/fastify/lib/handleRequest.js:139:37)
    at validationCompleted (/home/seamonkey/Downloads/holesky/lodestar/node_modules/fastify/lib/handleRequest.js:123:5)
    at preValidationCallback (/home/seamonkey/Downloads/holesky/lodestar/node_modules/fastify/lib/handleRequest.js:99:5)
    at handler (/home/seamonkey/Downloads/holesky/lodestar/node_modules/fastify/lib/handleRequest.js:76:7)
    at /home/seamonkey/Downloads/holesky/lodestar/node_modules/fastify/lib/contentTypeParser.js:192:9
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at done (/home/seamonkey/Downloads/holesky/lodestar/node_modules/fastify/lib/contentTypeParser.js:186:14)
    at Parser.defaultJsonParser [as fn] (/home/seamonkey/Downloads/holesky/lodestar/node_modules/fastify/lib/contentTypeParser.js:294:5)
```
validator:
```
Nov-03 08:38:36.042[]                error: Error on pollBeaconProposers - Error on getProposerDuties - Timeout request
Error: Error on getProposerDuties - Timeout request
    at Function.assert (file:///home/seamonkey/Downloads/holesky/lodestar/packages/api/src/utils/client/httpClient.ts:44:13)
    at BlockDutiesService.pollBeaconProposers (file:///home/seamonkey/Downloads/holesky/lodestar/packages/validator/src/services/blockDuties.ts:187:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:540:9)
    at processTimers (node:internal/timers:514:7)
    at BlockDutiesService.pollBeaconProposersAndNotify (file:///home/seamonkey/Downloads/holesky/lodestar/packages/validator/src/services/blockDuties.ts:148:5)
    at BlockDutiesService.runBlockDutiesTask (file:///home/seamonkey/Downloads/holesky/lodestar/packages/validator/src/services/blockDuties.ts:95:9)
    at Clock.runAtMostEvery (file:///home/seamonkey/Downloads/holesky/lodestar/packages/validator/src/util/clock.ts:96:7)
Nov-03 08:38:36.044[]                error: Failed to register proposers with beacon node epoch=8106 - Timeout request
Error: Timeout request
    at Function.assert (file:///home/seamonkey/Downloads/holesky/lodestar/packages/api/src/utils/client/httpClient.ts:44:13)
    at prepareBeaconProposer (file:///home/seamonkey/Downloads/holesky/lodestar/packages/validator/src/services/prepareBeaconProposer.ts:47:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Clock.runAtMostEvery (file:///home/seamonkey/Downloads/holesky/lodestar/packages/validator/src/util/clock.ts:96:7)
```

### Expected behavior

no errors

### Steps to reproduce

`node --trace-deprecation --max-old-space-size=8192 ./packages/cli/bin/lodestar.js beacon --dataDir="/mnt/holesky/lodestar-reth" --eth1 --execution.urls="http://localhost:8570" --jwt-secret="/mnt/holesky/jwtsecret" --port 23501 --enr.ip "1.2.3.4" --enr.tcp 23501 --enr.udp 23501 --rest.port 9606 --network holesky --rest.namespace=beacon,config,events,node,validator,debug --targetPeers 30 --nat --metrics --metrics.port 5086`

`./lodestar validator --graffiti "lodestar-reth seamonkey.tech" --server http://127.0.0.1:9606 --dataDir /mnt/holesky/lodestar-reth --network holesky --suggestedFeeRecipient "0xA721da3d06813E764E94A23E377cC3E1729fCFD5" --externalSigner.url "http://localhost:9000" --externalSigner.pubkeys "a1deb87700e9b811386a883ad6efd2f7212dc6df56677bfe63074f7822e6e2256dd29f44bbe0de216eaf59c2888933cf" --metrics --metrics.port 5087`

### Operating system

Linux

### Lodestar version or commit hash

618895c92922658c77284f9a31273ade7f894e94

**Comment by nflaig** [comment]
Thanks @SeaMonkey82 for opening the issue

- The error on the beacon node side should be resolved by https://github.com/ChainSafe/lodestar/pull/6081
- Not really sure about the validator client error, `pollBeaconProposers` is a different API request and timeout should be unrelated, need to keep an eye on that though if it happens consistently, but currently not seeing it on any of my nodes

**Comment by nflaig** [comment]
Resolved by https://github.com/ChainSafe/lodestar/pull/6081
