### ISSUE TITLE
Doppelganger getLiveness errors on holesky

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6114]
### Describe the bug

On holesky it might happen that `getLiveness` request in doppelganger service throws the following error
```
Nov-13 11:47:12.941[]                error: Error getting liveness data for epoch 10346 - Bad Request: Request epoch 10346 is more than one epoch before or after the current epoch 10348
Error: Bad Request: Request epoch 10346 is more than one epoch before or after the current epoch 10348
    at DoppelgangerService.getLiveness (file:///usr/app/packages/validator/src/services/doppelgangerService.ts:178:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at DoppelgangerService.pollLiveness (file:///usr/app/packages/validator/src/services/doppelgangerService.ts:160:33)
    at Clock.runAtMostEvery (file:///usr/app/packages/validator/src/util/clock.ts:96:7)
```

This happens due to the fact that the doppelganger detection is run at the end of the epoch (3/4 into the last slot)
https://github.com/ChainSafe/lodestar/blob/698e6557e68f69a2b118401272650bdd66074e90/packages/validator/src/services/doppelgangerService.ts#L122-L124

It includes polling validator indices which might take up to 3 seconds (highly depends on host performance)
https://github.com/ChainSafe/lodestar/blob/698e6557e68f69a2b118401272650bdd66074e90/packages/validator/src/services/doppelgangerService.ts#L143

due to the fact that the beacon node is extremly busy at the end of the epoch (epoch transition) and the `getStateValidators` request is really slow
https://github.com/ChainSafe/lodestar/blob/698e6557e68f69a2b118401272650bdd66074e90/packages/validator/src/services/indices.ts#L129

In case this takes more than 3 seconds, the `currentEpoch` which is passed to `getLiveness` API is already the previous epoch and the previous epoch (`currentEpoch - 1`) is 2 epochs in the past. This request will cause the error on the beacon node because there is a strict check that ensures the API is only called for +/- 1 epoch.
https://github.com/ChainSafe/lodestar/blob/698e6557e68f69a2b118401272650bdd66074e90/packages/beacon-node/src/api/impl/validator/index.ts#L1082-L1086

### Expected behavior

Doppelganger protection should consistently work on holesky.

Possible solution could be to poll indices earlier or ideally the validators request should resolve much quicker (requires performance improvements in epoch transition)

### Steps to reproduce

Run beacon node and validator client with `--network holesky` flag and enable doppelganger protection (`--doppelgangerProtection`). It also requires that there a pending / undiscovered pubkeys / validators as otherwise the doppelganger serivce will not try to discover new indices.

### Additional context

Due to this issue it is currently not possible to enable doppelganger protection on the dappnode holesky package. This is not a huge issue at the moment since holesky is just a testnet but once mainnet has a similar validator count will see the same issues there.

### Operating system

Linux

### Lodestar version or commit hash

v1.12.0

**Comment by nflaig** [comment]
This should be resolved with epoch transition time coming down and as shown in https://github.com/ChainSafe/lodestar/issues/6929, the event loop lag at the 8 second in the slot is never above 4 seconds on Holesky so the request should resolve before the next slot.

Haven't seen the issue in a while, closing for now

**Comment by nflaig** [comment]
Reopening as this has been observed on mainnet as well (see [discord comment](https://discord.com/channels/593655374469660673/593655641445367808/1270460760643866665))

**Comment by nflaig** [comment]
Keeping this open until we get user confirmation that it is no longer a problem but I am not able to reproduce this with our latest release (v1.21.0). Even on Holesky there are no issues with doppelganger protection enabled.

**Comment by nflaig** [comment]
Not able to reproduce anymore on v1.21.0 and additionally confirmed by [minikieff on discord](https://discord.com/channels/593655374469660673/593655641445367808/1272075119644381254) that he is no longer facing the issue.
