### ISSUE TITLE
Syncing stuck when using Reth as Execution client - Reth reporting Bad Block

### ISSUE THREAD

**Issue by timjrobinson** [ChainSafe/lodestar#6245]
### Describe the bug

My Lodestar client stopped syncing around 6 days ago. It seems to know about new blocks but is stuck processing slot `8066879` I'm using Reth as the execution client and it is erroring about block `18872589` which is in slot `8066888`. The lodestar client logs are:

```
lodestar-beacon_node-1  | Jan-02 16:56:41.023[]                 info: Syncing - 280000000 days left - 2.04e-9 slots/s - slot: 8115881 - head: 8066879 0x0b5f…3899 - exec-block: valid(18872581 0x4d41…) - finalized: 0x996a…6acc:252088 - peers: 26
lodestar-beacon_node-1  | Jan-02 16:56:47.192[execution]        info: Execution client is synced oldState=SYNCING, newState=SYNCED
lodestar-beacon_node-1  | Jan-02 16:56:52.785[execution]        warn: Execution client is syncing oldState=SYNCED, newState=SYNCING
lodestar-beacon_node-1  | Jan-02 16:56:53.147[]                 info: Syncing - 280000000 days left - 2.04e-9 slots/s - slot: 8115882 - head: 8066879 0x0b5f…3899 - exec-block: valid(18872581 0x4d41…) - finalized: 0x996a…6acc:252088 - peers: 23
lodestar-beacon_node-1  | Jan-02 16:57:04.082[execution]        info: Execution client is synced oldState=SYNCING, newState=SYNCED
lodestar-beacon_node-1  | Jan-02 16:57:05.020[]                 info: Syncing - 280000000 days left - 2.04e-9 slots/s - slot: 8115883 - head: 8066879 0x0b5f…3899 - exec-block: valid(18872581 0x4d41…) - finalized: 0x996a…6acc:252088 - peers: 23
lodestar-beacon_node-1  | Jan-02 16:57:07.887[execution]        warn: Execution client is syncing oldState=SYNCED, newState=SYNCING
lodestar-beacon_node-1  | Jan-02 16:57:14.151[execution]        info: Execution client is synced oldState=SYNCING, newState=SYNCED
lodestar-beacon_node-1  | Jan-02 16:57:17.068[]                 info: Syncing - 280000000 days left - 2.06e-9 slots/s - slot: 8115884 - head: 8066879 0x0b5f…3899 - exec-block: valid(18872581 0x4d41…) - finalized: 0x996a…6acc:252088 - peers: 21
lodestar-beacon_node-1  | Jan-02 16:57:19.847[execution]        warn: Execution client is syncing oldState=SYNCED, newState=SYNCING
lodestar-beacon_node-1  | Jan-02 16:57:29.001[]                 info: Syncing - 280000000 days left - 2.06e-9 slots/s - slot: 8115885 - head: 8066879 0x0b5f…3899 - exec-block: valid(18872581 0x4d41…) - finalized: 0x996a…6acc:252088 - peers: 22
```

Reth logs are:

```
024-01-02T16:50:46.147207Z  INFO try_insert_validated_block{block=(18872584, 0xd76bbb604027fdd59233d74897e5ae7b2b25cbc6875a0efbed9d35cf2ce05132)}: blockchain_tree: return=Ok(Valid)
2024-01-02T16:50:46.147340Z  INFO reth::node::events: Block added to canonical chain number=18872584 hash=0xd76bbb604027fdd59233d74897e5ae7b2b25cbc6875a0efbed9d35cf2ce05132
2024-01-02T16:50:47.187506Z  INFO try_insert_validated_block{block=(18872585, 0xc868ca2532a7b3b1fa2dab8591bde59e4fca09f7ef72941333181444779136c7)}: blockchain_tree: return=Ok(Valid)
2024-01-02T16:50:47.187653Z  INFO reth::node::events: Block added to canonical chain number=18872585 hash=0xc868ca2532a7b3b1fa2dab8591bde59e4fca09f7ef72941333181444779136c7
2024-01-02T16:50:48.356198Z  INFO try_insert_validated_block{block=(18872586, 0x2e73316a3901975439e80337d8aa188f3e30d198b20680a15ee6ca35ebfadc08)}: blockchain_tree: return=Ok(Valid)
2024-01-02T16:50:48.356288Z  INFO reth::node::events: Block added to canonical chain number=18872586 hash=0x2e73316a3901975439e80337d8aa188f3e30d198b20680a15ee6ca35ebfadc08
2024-01-02T16:50:50.623799Z  INFO try_insert_validated_block{block=(18872587, 0x48bca92dda4d9476b0ebbf024c50bf002e1ced833c3e52215475174f411dbc14)}: blockchain_tree: return=Ok(Valid)
2024-01-02T16:50:50.623930Z  INFO reth::node::events: Block added to canonical chain number=18872587 hash=0x48bca92dda4d9476b0ebbf024c50bf002e1ced833c3e52215475174f411dbc14
2024-01-02T16:50:51.847464Z  INFO try_insert_validated_block{block=(18872588, 0xe66a09516ef5ab3aecd4a49d9bb5e63be07cee22f1d4efffbac9fd07f83db72c)}: blockchain_tree: return=Ok(Valid)
2024-01-02T16:50:51.847572Z  INFO reth::node::events: Block added to canonical chain number=18872588 hash=0xe66a09516ef5ab3aecd4a49d9bb5e63be07cee22f1d4efffbac9fd07f83db72c
2024-01-02T16:50:53.070649Z  INFO try_insert_validated_block{block=(18872589, 0x476f922d904f88ad8bc2013875f1c16361c11ceef028c4264b798c4e96f3f520)}: blockchain_tree: return=Err(InsertBlockError { error: Consensus(BodyStateRootDiff { got: 0xac80d9cfaf5e0842ec26c5f5b7b4281e6f142823ae6556c112655bde06815c82, expected: 0x83599347964caf6a248341fb285a1012e917215d8c6d856a67f553f1da3b0560 }), hash: 0x476f922d904f88ad8bc2013875f1c16361c11ceef028c4264b798c4e96f3f520, number: 18872589, parent_hash: 0xe66a09516ef5ab3aecd4a49d9bb5e63be07cee22f1d4efffbac9fd07f83db72c, num_txs: 165, .. })
2024-01-02T16:50:53.070711Z  WARN consensus::engine: Bad block with header hash: 0x476f922d904f88ad8bc2013875f1c16361c11ceef028c4264b798c4e96f3f520, invalid ancestor: Header { parent_hash: 0xe66a09516ef5ab3aecd4a49d9bb5e63be07cee22f1d4efffbac9fd07f83db72c, ommers_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, beneficiary: 0x95222290dd7278aa3ddd389cc1e1d165cc4bafe5, state_root: 0x83599347964caf6a248341fb285a1012e917215d8c6d856a67f553f1da3b0560, transactions_root: 0xba2c7529ae77c0c08f51d93290ac90a4425ae2763b3e8437b1aa117123eb8697, receipts_root: 0xd655c33ec864e90eff3f5eba2711bbb256c86266061de4e4c4f6f3cb52dc81b2, withdrawals_root: Some(0xba0675d648eb450abee4630ad917b927ac1de78ba5bdb40adac4b4afe342d768), logs_bloom: 0x30f3d072e14d1120b08190eae5c956a101562856380684e4000384383c023813455d95a1a4a5a126550819211002ed0e27053d189e547bb10798a335916b410cc5c0b81d2d48882a683ac37eca98ace4428701d4aec88f87e96e1652a965500107267478c266286380bc110310233c79e091395f2a9d4c06ce5ad3d5600a61658f368fdc3a83d3d8014db95b57abb1240a3204618d5da26e747166c030f1083b8af429f75e027926427cd0ca9490c449652a618804711f077551372a142636787bf020f2a51d88c903408890023dbd0f4b215de934010978098d814f68f220a208bbaff82cc8a083015e968c08171a05aa3c9b3831beb6c270093e587820f469, difficulty: 0x0000000000000000000000000000000000000000000000000000000000000000_U256, number: 18872589, gas_limit: 30000000, gas_used: 19268495, timestamp: 1703626679, mix_hash: 0xd492600e498605957ed0969c405c5a8b05813ab55753e01f01f130d118726009, nonce: 0, base_fee_per_gas: Some(19970162705), extra_data: Bytes(0x6265617665726275696c642e6f7267) }
```

I tried unwinding the last 5 blocks of Reth in case it was having issues and it's still error'ing on that same block. 

### Expected behavior

I expect Lodestar and Reth to sync correctly. 

### Steps to reproduce

1. Run Lodestar using `latest` docker container
2. Run Reth using `latest` docker container 
3. See errors in logs about this block not syncing. 

### Operating system

Linux

### Lodestar version or commit hash

v1.13.0/1a816b4

**Comment by timjrobinson** [comment]
I realized there were more debug logs for lodestar in the logs folder. They are this:

```
Jan-03 07:33:41.561[chain]           debug: Block error slot=8066888, code=BLOCK_ERROR_EXECUTION_ERROR, execStatus=INVALID, errorMessage=Block state root (0xac80d9cfaf5e0842ec26c5f5b7b4281e6f142823ae6556c112655bde06815c82) is different from expected: (0x83599347964caf6a248341fb285a1012e917215d8c6d856a67f553f1da3b0560)
Error: BLOCK_ERROR_EXECUTION_ERROR
    at verifyBlockExecutionPayload (file:///usr/app/packages/beacon-node/src/chain/blocks/verifyBlocksExecutionPayloads.ts:321:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at verifyBlocksExecutionPayload (file:///usr/app/packages/beacon-node/src/chain/blocks/verifyBlocksExecutionPayloads.ts:158:28)
    at async Promise.all (index 0)
    at BeaconChain.verifyBlocksInEpoch (file:///usr/app/packages/beacon-node/src/chain/blocks/verifyBlock.ts:91:70)
    at BeaconChain.processBlocks (file:///usr/app/packages/beacon-node/src/chain/blocks/index.ts:75:68)
    at JobItemQueue.runJob (file:///usr/app/packages/beacon-node/src/util/queue/itemQueue.ts:101:22)
Jan-03 07:33:41.561[sync]          verbose: Batch process error id=Finalized, startEpoch=252090, status=Processing, code=BLOCK_ERROR_EXECUTION_ERROR, execStatus=INVALID, errorMessage=Block state root (0xac80d9cfaf5e0842ec26c5f5b7b4281e6f142823ae6556c112655bde06815c82) is different from expected: (0x83599347964caf6a248341fb285a1012e917215d8c6d856a67f553f1da3b0560)
Error: BLOCK_ERROR_EXECUTION_ERROR
    at verifyBlockExecutionPayload (file:///usr/app/packages/beacon-node/src/chain/blocks/verifyBlocksExecutionPayloads.ts:321:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at verifyBlocksExecutionPayload (file:///usr/app/packages/beacon-node/src/chain/blocks/verifyBlocksExecutionPayloads.ts:158:28)
    at async Promise.all (index 0)
    at BeaconChain.verifyBlocksInEpoch (file:///usr/app/packages/beacon-node/src/chain/blocks/verifyBlock.ts:91:70)
    at BeaconChain.processBlocks (file:///usr/app/packages/beacon-node/src/chain/blocks/index.ts:75:68)
    at JobItemQueue.runJob (file:///usr/app/packages/beacon-node/src/util/queue/itemQueue.ts:101:22)
Jan-03 07:33:41.561[sync]          verbose: Batch validation error id=Finalized, startEpoch=252089, status=AwaitingValidation
```

**Comment by timjrobinson** [comment]
I was able to get it syncing again with the flags `--forceCheckpointSync --checkpointSyncUrl https://sync-mainnet.beaconcha.in`. I guess it now has the latest blocks and is syncing backwards.

**Comment by g11tech** [comment]
seems like your `reth` was corrupted and was considering possibly a "canonical block" as bad, this would cause lodestar to stall, checkpoint syncs make lodestar jump ahead and reth starts the backfill and not sure probably resolve the block

however it would be wise to raise this issue to reth team

**Comment by g11tech** [comment]
> I was able to get it syncing again with the flags `--forceCheckpointSync --checkpointSyncUrl https://sync-mainnet.beaconcha.in`. I guess it now has the latest blocks and is syncing backwards.

any update on this?

**Comment by timjrobinson** [comment]
It's working fine again now. I think Reth was working correctly as it didn't need any changes, it just wouldn't proceed because Lodestar was saying the block had a different state root than what it computed.

**Comment by philknows** [comment]
Will close this as it doesn't seem to be an issue with Lodestar here.
