### ISSUE TITLE
Error: ENR has no udp multiaddr

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6320]
### Describe the bug

There is an uncaught expection in discv5

```
Jan-17 09:17:47.140[network]         error: uncaughtException: ENR has no udp multiaddr
Error: ENR has no udp multiaddr
    at getNodeAddress (file:///usr/app/node_modules/@chainsafe/discv5/lib/session/nodeInfo.js:71:23)
    at Discv5.sendRpcRequest (file:///usr/app/node_modules/@chainsafe/discv5/lib/service/service.js:402:26)
    at Discv5.requestEnr (file:///usr/app/node_modules/@chainsafe/discv5/lib/service/service.js:376:14)
    at Discv5.handlePing (file:///usr/app/node_modules/@chainsafe/discv5/lib/service/service.js:613:22)
    at SessionService.handleRpcRequest (file:///usr/app/node_modules/@chainsafe/discv5/lib/service/service.js:597:29)
    at SessionService.emit (node:events:514:28)
    at SessionService.handleMessage (file:///usr/app/node_modules/@chainsafe/discv5/lib/session/service.js:489:18)
    at UDPTransportService.processInboundPacket (file:///usr/app/node_modules/@chainsafe/discv5/lib/session/service.js:234:29)
    at UDPTransportService.emit (node:events:514:28)
    at Socket.handleIncoming (file:///usr/app/node_modules/@chainsafe/discv5/lib/transport/udp.js:121:14) - ENR has no udp multiaddr
Error: ENR has no udp multiaddr
    at getNodeAddress (file:///usr/app/node_modules/@chainsafe/discv5/lib/session/nodeInfo.js:71:23)
    at Discv5.sendRpcRequest (file:///usr/app/node_modules/@chainsafe/discv5/lib/service/service.js:402:26)
    at Discv5.requestEnr (file:///usr/app/node_modules/@chainsafe/discv5/lib/service/service.js:376:14)
    at Discv5.handlePing (file:///usr/app/node_modules/@chainsafe/discv5/lib/service/service.js:613:22)
    at SessionService.handleRpcRequest (file:///usr/app/node_modules/@chainsafe/discv5/lib/service/service.js:597:29)
    at SessionService.emit (node:events:514:28)
    at SessionService.handleMessage (file:///usr/app/node_modules/@chainsafe/discv5/lib/session/service.js:489:18)
    at UDPTransportService.processInboundPacket (file:///usr/app/node_modules/@chainsafe/discv5/lib/session/service.js:234:29)
    at UDPTransportService.emit (node:events:514:28)
    at Socket.handleIncoming (file:///usr/app/node_modules/@chainsafe/discv5/lib/transport/udp.js:121:14)
```

### Expected behavior

No uncaught exceptions, all errors should be handled

### Steps to reproduce

Run Lodestar beacon node

### Operating system

Linux

### Lodestar version or commit hash

v1.14.0-rc.1

**Comment by nflaig** [comment]
This error rarely happens and I have not confirmed it is resolved but confident that it is fixed by upgrading discv5 in https://github.com/ChainSafe/lodestar/pull/6380 which includes a fix to improve error handling (https://github.com/ChainSafe/discv5/pull/284).

Will reopen in case the error still happens on latest unstable.
