### ISSUE TITLE
named stack traces on ssz type errors

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#6356]
**Motivation**

Whenever there's an SSZ error, the stack trace looks like this

```
Error: First offset must equal to fixedEnd 376 != 344
  at readVariableOffsets (/home/lion/Code/eth2.0/lodestar/node_modules/@chainsafe/ssz/src/type/container.ts:448:15)
  at ContainerType.getFieldRanges (/home/lion/Code/eth2.0/lodestar/node_modules/@chainsafe/ssz/src/type/container.ts:399:21)
  at ContainerType.value_deserializeFromBytes (/home/lion/Code/eth2.0/lodestar/node_modules/@chainsafe/ssz/src/type/container.ts:201:30)
  at ContainerType.value_deserializeFromBytes (/home/lion/Code/eth2.0/lodestar/node_modules/@chainsafe/ssz/src/type/container.ts:208:36)
  at ContainerType.deserialize (/home/lion/Code/eth2.0/lodestar/node_modules/@chainsafe/ssz/src/type/abstract.ts:135:17)
```

which sucks because you wonder, which is the offending property? Where should I go look next?

Would be awesome if the stack trace also included the path of what property is causing the error. Previous attempts:
- Add try / catch on every method and concatenate the path of the error, for example: `state.executionPayloadHeader.excessGas`. However this requires adding tons of boilerplate code + has a serious performance penalty.

But what if instead of rendering `ContainerType` in stack trace rows it rendered `BeaconStateCapella`?

- See prior work in https://github.com/ChainSafe/lodestar/pull/4884

**Comment by wemeetagain** [comment]
closing as wontfix
