### ISSUE TITLE
BLOCK_ERROR_DATA_UNAVAILABLE errors if blobs are late

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6402]
### Describe the bug

We currently log errors if our node receives blobs late (>4s)
```
[network]         error: Error receiving block slot=950303, peer=16Uiu2HAm2X8z2WNtF59uA4RTvk7D1qWdhq1wCRFaX9KQZon36KLM, code=BLOCK_ERROR_DATA_UNAVAILABLE
Error: BLOCK_ERROR_DATA_UNAVAILABLE
    at raceWithCutoff (file:///usr/app/packages/beacon-node/src/chain/blocks/verifyBlocksDataAvailability.ts:122:11)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at processTimers (node:internal/timers:514:7)
    at maybeValidateBlobs (file:///usr/app/packages/beacon-node/src/chain/blocks/verifyBlocksDataAvailability.ts:84:13)
    at verifyBlocksDataAvailability (file:///usr/app/packages/beacon-node/src/chain/blocks/verifyBlocksDataAvailability.ts:41:36)
    at async Promise.all (index 1)
    at BeaconChain.verifyBlocksInEpoch (file:///usr/app/packages/beacon-node/src/chain/blocks/verifyBlock.ts:97:9)
    at BeaconChain.processBlocks (file:///usr/app/packages/beacon-node/src/chain/blocks/index.ts:72:7)
    at JobItemQueue.runJob (file:///usr/app/packages/beacon-node/src/util/queue/itemQueue.ts:101:22)
```

### Expected behavior

Should consider reducing verbosity of these logs as they are not critical as Lodestar will try to pull them from other peers instead of waiting for them.

Possible solutions
- log as warn instead of error
- remove stacktrace
- or maybe even move to debug

### Operating system

Linux

### Lodestar version or commit hash

v1.15.0

**Comment by ianw11** [comment]
To be clear, seeing that in the logs does not mean anything is wrong?

If it continues to be printed, a message after `BLOCK_ERROR_DATA_UNAVAILABLE` confirming it won't affect operation would be appreciated.

**Comment by nflaig** [comment]
> To be clear, seeing that in the logs does not mean anything is wrong?

Yes, there is nothing wrong on your end, this happens if we receive a block from a peer but the blobs are not received within 3 seconds of the slot.

We will then throw this error to trigger unknown block/blobs sync to request the data from others peers
https://github.com/ChainSafe/lodestar/blob/1e6757944237305772290a913421b839bf90a9a4/packages/beacon-node/src/chain/blocks/verifyBlocksDataAvailability.ts#L121-L122

https://github.com/ChainSafe/lodestar/blob/1e6757944237305772290a913421b839bf90a9a4/packages/beacon-node/src/network/processor/gossipHandlers.ts#L266

But even though we do that, we still log it as an error which I believe we have to handle differently
https://github.com/ChainSafe/lodestar/blob/1e6757944237305772290a913421b839bf90a9a4/packages/beacon-node/src/network/processor/gossipHandlers.ts#L282

We could consider logging block validation errors due to bad blocks we receive from the network as a warning instead of error, and for this specific case we might even use a debug log as it seems to be quite common error on goerli / holesky.

**Comment by wemeetagain** [comment]
The error log doesn't fit our logging policy. Should probably be a debug level log
