### ISSUE TITLE
v1.21.0-rc.0: unstable peers

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#6989]
### Describe the bug

Peer count is unstable on the beta mainnet node, I used to see it dropped to 35 while inbound peer is 0 or 1

<img width="1695" alt="Screenshot 2024-07-31 at 13 35 08" src="https://github.com/user-attachments/assets/57be6893-d00f-4dbe-b533-c79a5aca967b">

it's likely due to Event Loop Lag on Network worker (which is only ~15ms on the stable mainnet node)

<img width="1329" alt="Screenshot 2024-07-31 at 13 36 06" src="https://github.com/user-attachments/assets/ba847130-f04a-40ba-aed8-0f39c7258662">

### Expected behavior

- Peer count should be ~100 stably
- Inbound peers should be ~90 as in the stable mainnet node (or around that value)
- Event loop lag Network Worker should be ~15ms

### Operating system

Linux

### Lodestar version or commit hash

v1.21.0-rc.0

**Comment by twoeths** [comment]
This is on our unstable mainnet node

<img width="1331" alt="Screenshot 2024-07-31 at 13 39 17" src="https://github.com/user-attachments/assets/f1586d10-9f87-494e-937f-af0fa5ff4060">

the issue started happening from around Jul 27 14:00:00 UTC so #5886 could be the root cause

**Comment by nflaig** [comment]
It does not look that bad on my mainnet nodes

### mainnet-1
![image](https://github.com/user-attachments/assets/656ff45c-1119-4f4f-9cc1-a0f22effd0e7)

### mainnet-2
![image](https://github.com/user-attachments/assets/9209681e-63f4-417d-88e7-1d7bef3f0e80)

### mainnet-3
![image](https://github.com/user-attachments/assets/170a2665-1cd5-4be2-b08f-171d58ea3569)


On all of the nodes I can also see an improved event loop lag metric

![image](https://github.com/user-attachments/assets/1a1ea407-086d-493f-aa59-47c054238b92)

Let me know if there are other metrics to share that might be useful

**Comment by twoeths** [comment]
@nflaig it only happens on a test mainnet node because it subscribes to all subnets, so it has a lot of I/O load
I don't see the issue on our `cip` nodes too

**Comment by nflaig** [comment]
> @nflaig it only happens on a test mainnet node because it subscribes to all subnets, so it has a lot of I/O load I don't see the issue on our `cip` nodes too

Right, that's likely it. Will enable it on one of my mainnet nodes as well now

**Comment by philknows** [comment]
After putting in rc.1 to beta, you can see the stabilization in some peer metrics here:

![Screenshot 2024-08-02 at 11 54 08 AM](https://github.com/user-attachments/assets/d5d74a7a-d6cf-4546-8ea4-b53c9769990f)
![Screenshot 2024-08-02 at 11 58 20 AM](https://github.com/user-attachments/assets/a1c82672-f446-4d94-9bab-4ca92c2780c9)
![Screenshot 2024-08-02
![Screenshot 2024-08-02 at 12 00 47 PM](https://github.com/user-attachments/assets/12114c41-bf52-45dc-ba5a-73936726043a)
![Screenshot 2024-08-02 at 12 00 52 PM](https://github.com/user-attachments/assets/e47c8bec-4124-4f32-9877-61f31a012feb)
![Screenshot 2024-08-02 at 11 58 07 AM](https://github.com/user-attachments/assets/e9e5fdec-c203-4b4c-90be-5727b8b554aa)

**Comment by twoeths** [comment]
attaching a network profile of `cayman/yamux` branch cc @wemeetagain 

[mainnet_yamux_network_thread_2024-08-06.cpuprofile.zip](https://github.com/user-attachments/files/16507271/mainnet_yamux_network_thread_2024-08-06.cpuprofile.zip)

there are so many dial errors in that branch

<img width="1322" alt="Screenshot 2024-08-06 at 15 04 41" src="https://github.com/user-attachments/assets/b25f5a03-84d9-44d9-83a1-4e4f29d04a31">

from the log:
```
grep -e "unexpected end of input" -rn beacon-2024-08-06.log | wc -l
19724
```

```
grep -e "REQUEST_ERROR_DIAL_ERROR" -rn beacon-2024-08-06.log | wc -l
14302
```

sample error stack trace does not seem relate to yamux
```
Aug-06 00:02:30.296[network]       ^[[36mverbose^[[39m: Req  error method=ping, version=1, encoding=ssz_snappy, client=NA, peer=16...kfMnnz, requestId=272488, code=REQUEST_ERROR_DIAL_ERROR, error=unexpected end of input
Error: unexpected end of input
    at Object.read (file:///usr/src/lodestar/node_modules/it-byte-stream/dist/src/index.js:86:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.read (file:///usr/src/lodestar/node_modules/it-length-prefixed-stream/dist/src/index.js:51:37)
    at async read (file:///usr/src/lodestar/node_modules/@libp2p/multistream-select/dist/src/multistream.js:22:17)
    at async Module.readString (file:///usr/src/lodestar/node_modules/@libp2p/multistream-select/dist/src/multistream.js:33:17)
    at async Module.select (file:///usr/src/lodestar/node_modules/@libp2p/multistream-select/dist/src/select.js:72:20)
    at async ConnectionImpl.newStream [as _newStream] (file:///usr/src/lodestar/node_modules/libp2p/dist/src/upgrader.js:330:50)
    at async ConnectionImpl.newStream (file:///usr/src/lodestar/node_modules/libp2p/dist/src/connection/index.js:94:24)
    at async file:///usr/src/lodestar/packages/reqresp/lib/request/index.js:57:26
    at async withTimeout (file:///usr/src/lodestar/packages/utils/lib/timeout.js:12:16)
Error: REQUEST_ERROR_DIAL_ERROR
    at file:///usr/src/lodestar/packages/reqresp/lib/request/index.js:67:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendRequest (file:///usr/src/lodestar/packages/reqresp/lib/request/index.js:55:24)
    at async ReqRespBeaconNode.sendRequest (file:///usr/src/lodestar/packages/reqresp/lib/ReqResp.js:109:13)
    at async collectExactOneTyped (file:///usr/src/lodestar/packages/beacon-node/lib/network/reqresp/utils/collect.js:10:22)
    at async PeerManager.requestPing (file:///usr/src/lodestar/packages/beacon-node/lib/network/peers/peerManager.js:340:31)
```

**Comment by twoeths** [comment]
issue was resolved because we reverted yamux enhancement
