### ISSUE TITLE
Sync - BeaconBlockByRoot issue

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#728]
Got this when trying to sync in `mpetrunic/regular-sync-v2` branch:

```
2020-03-23 14:56:40  [NETWORK]       verbose: send beacon_blocks_by_root request to 16Uiu2HAkyjwFDk7Qr6jo4J7dP9Pn7kDVB3KjvsGPnVai3q2m2Ryt
(node:17651) UnhandledPromiseRejectionWarning: Error: 
    at Timeout.setTimeout (/Users/tuyennguyen/Projects/workshop/lodestar/packages/lodestar/src/network/reqResp.ts:188:51)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by twoeths** [comment]
`mpetrunic/regular-sync-v2` was merged to master.
