### ISSUE TITLE
`yarn install --ignore-optional` unit test failure

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#814]
When using `yarn install --ignore-optional` to avoid installing the spec tests, the unit tests (for the `lodestar` package) no longer run.

See https://github.com/ChainSafe/lodestar/runs/598594473

Steps to reproduce:
`rm -rf node_modules`
`yarn install --ignore-optional`
`lerna run test:unit`

Output:
```
@chainsafe/lodestar: yarn run v1.22.4
@chainsafe/lodestar: $ TS_NODE_PROJECT=tsconfig.test.json nyc --cache-dir .nyc_output/.cache -e .ts mocha --colors 'test/unit/**/*.test.ts'
@chainsafe/lodestar: 2020-04-18 23:52:27  []                error: uncaughtException: Cannot find module 'scrypt.js'
@chainsafe/lodestar: Require stack:
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/node_modules/ganache-core/build/ganache.core.node.js
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/node_modules/ganache-core/index.js
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/packages/lodestar/src/eth1/dev/network.ts
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/packages/lodestar/src/eth1/dev/index.ts
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/packages/lodestar/test/unit/eth1/dev/network.test.ts
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/node_modules/mocha/lib/mocha.js
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/node_modules/mocha/lib/cli/one-and-dones.js
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/node_modules/mocha/lib/cli/options.js
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/node_modules/mocha/bin/mocha
@chainsafe/lodestar: Error: Cannot find module 'scrypt.js'
@chainsafe/lodestar: Require stack:
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/node_modules/ganache-core/build/ganache.core.node.js
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/node_modules/ganache-core/index.js
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/packages/lodestar/src/eth1/dev/network.ts
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/packages/lodestar/src/eth1/dev/index.ts
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/packages/lodestar/test/unit/eth1/dev/network.test.ts
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/node_modules/mocha/lib/mocha.js
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/node_modules/mocha/lib/cli/one-and-dones.js
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/node_modules/mocha/lib/cli/options.js
@chainsafe/lodestar: - /home/runner/work/lodestar/lodestar/node_modules/mocha/bin/mocha
@chainsafe/lodestar:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
@chainsafe/lodestar:     at Function.Module._load (internal/modules/cjs/loader.js:862:27)
@chainsafe/lodestar:     at Module.require (internal/modules/cjs/loader.js:1042:19)

```

**Comment by mpetrunic** [comment]
Probably can be solved by adding scrypt.js as dev depenendency or try updating ganache if they fixed it

**Comment by mpetrunic** [comment]
Is this still a problem?

Didn't we update ganache some times ago?

**Comment by dapplion** [comment]
Unit tests are not failing in master, so is it fixed?

**Comment by wemeetagain** [comment]
if its not failing anymore, yea :tada:
