### ISSUE TITLE
Disconnect after goodbye is sent

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#823]
Currently we don't disconnect once we receive goodbye rpc message as we would close connection before response is sent.

Solution:
"sendResponse" method should resolve promise once response is sent

**Comment by twoeths** [comment]
I also see this error in my environment, can you confirm it's this issue or not @mpetrunic 
```
2020-05-01 12:59:03  [NETWORK]          warn: Failed to send goodbye request. Error: undefined
2020-05-01 12:59:03  [SYNC]             info: initial sync stop
2020-05-01 12:59:03  [NETWORK]       verbose: peer disconnected 16Uiu2HAm6bmYWZLoB52NYw461xS8Yhk1HWtGziNQswCP2Zx8yJz1
(node:85534) UnhandledPromiseRejectionWarning: Error: stream ended before 1 bytes became available
    at /Users/tuyennguyen/Projects/workshop/lodestar/node_modules/it-reader/index.js:37:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /Users/tuyennguyen/Projects/workshop/lodestar/node_modules/it-length-prefixed/src/decode.js:80:20
    at oneChunk (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/multistream-select/src/multistream.js:12:20)
    at Object.exports.read (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/multistream-select/src/multistream.js:34:15)
    at module.exports (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/multistream-select/src/select.js:21:19)
    at ClassIsWrapper.newStream [as _newStream] (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/libp2p/src/upgrader.js:251:40)
    at ClassIsWrapper.newStream (/Users/tuyennguyen/Projects/workshop/lodestar/node_modules/libp2p-interfaces/src/connection/connection.js:172:34)
```

**Comment by twoeths** [comment]
Confirm that's the same issue, working on it ...

**Comment by mpetrunic** [comment]
I think we should ignore this error silently, because that means other side already closed connection. Issue here is that we should disconnect only after we send all goodbye message bytes. But our send response doesn't notify us on that. Solution would be to refactor code to support this but request and response are in different modules because of dependencies so Im not really sure what's the best way to fix this

**Comment by twoeths** [comment]
I see the issue, have to leave it as is right now. The good news is it only happens to `goodbye` request.

**Comment by wemeetagain** [comment]
unstale

**Comment by mpetrunic** [comment]
unstale

**Comment by dapplion** [comment]
https://github.com/ChainSafe/lodestar/pull/2142 would ensure correct behaviour

Goodbyes are sent exclusively with this method ensuring the connection is disconnect after completing the goodbye request or on error
https://github.com/ChainSafe/lodestar/blob/fa5a188e6e58e6279fb86d5aff28e944912d8485/packages/lodestar/src/network/peers/peerManager.ts#L407-L416

When receiving goodbye requests, it ensures that the response handler completes before triggering a disconnection
https://github.com/ChainSafe/lodestar/blob/fa5a188e6e58e6279fb86d5aff28e944912d8485/packages/lodestar/src/network/reqresp/reqResp.ts#L203-L206
