### ISSUE TITLE
Unhandled exception when sending request to unsupported protocol

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/lodestar#872]
**Describe the bug**

When sending request to unsupported rpc protocol (other peer doesn't support encoding),
we get unhandled rejection:

```
(node:26606) UnhandledPromiseRejectionWarning: Error: protocol selection failed
    at module.exports (/home/mpetrunic/projects/eth2/lodestar/node_modules/multistream-select/src/select.js:50:17)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at ClassIsWrapper.newStream [as _newStream] (/home/mpetrunic/projects/eth2/lodestar/node_modules/libp2p/src/upgrader.js:251:40)
    at ClassIsWrapper.newStream (/home/mpetrunic/projects/eth2/lodestar/node_modules/libp2p-interfaces/src/connection/connection.js:172:34)
(node:26606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Expected behavior**

It should be handled and logged (warn) and maybe disconnect.

**Steps to Reproduce**

1. connect to other node
2. send request for unsupported topic

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Version: 
 - Branch: 
 - Commit hash:

**Comment by mpetrunic** [comment]
already fixed
