### ISSUE TITLE
Error: Pubsub has not started

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#935]
Found this in CI:

```
@chainsafe/lodestar-cli:     ✓ should connect 2 dev nodes until blocks found thru init & regular sync (43337ms)
@chainsafe/lodestar-cli:   6 passing (3m)
@chainsafe/lodestar-cli: 2020-05-21 16:27:14  []                error: uncaughtException: Pubsub has not started
@chainsafe/lodestar-cli: Error: Pubsub has not started
@chainsafe/lodestar-cli:     at LodestarGossipsub.unsubscribe (/home/runner/work/lodestar/lodestar/node_modules/libp2p-gossipsub/src/pubsub.js:317:13)
@chainsafe/lodestar-cli:     at unsubscribe (/home/runner/work/lodestar/lodestar/packages/lodestar/src/network/gossip/gossip.ts:165:21)
@chainsafe/lodestar-cli:     at Array.forEach (<anonymous>)
@chainsafe/lodestar-cli:     at Gossip.forEach [as unsubscribe] (/home/runner/work/lodestar/lodestar/packages/lodestar/src/network/gossip/gossip.ts:164:31)
@chainsafe/lodestar-cli:     at Gossip.unsubscribe [as unsubscribeFromAttestationSubnet] (/home/runner/work/lodestar/lodestar/packages/lodestar/src/network/gossip/gossip.ts:148:10)
@chainsafe/lodestar-cli:     at Timeout.unsubscribeFromAttestationSubnet [as _onTimeout] (/home/runner/work/lodestar/lodestar/packages/lodestar/src/sync/utils/attestation-collector.ts:71:25)
@chainsafe/lodestar-cli:     at listOnTimeout (internal/timers.js:551:17)
@chainsafe/lodestar-cli:     at processTimers (internal/timers.js:492:7) 
@chainsafe/lodestar-cli: 2020-05-21 16:27:14  []                error: uncaughtException: Pubsub has not started
```

**Comment by twoeths** [comment]
Duplicated to #1003
