### ISSUE TITLE
Syncing Witti: Initial sync never stops

### ISSUE THREAD

**Issue by wemeetagain** [ChainSafe/lodestar#984]
I synced up to the head of the witti, but instead of transitioning to regular sync / gossiping, initial sync continued past the head without stopping.

Some logs: Blocks are processed until the next fetch asks for blocks that don't yet exist. And that just continues.
```
2020-05-31 19:03:11  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x0584a0a21fc265e
49b5bb0f0a331c13c588181f6120a78b838c653b4cb695fae, slot=36012, epoch=1125                  
2020-05-31 19:03:11  [CHAIN]            info: Processed new chain head newChainHeadRoot=0x122247ea1bd51dc
2b096fcbcda7da91c35be081336c8e412a4b0d31492b4811a, slot=36014, epoch=1125                  
2020-05-31 19:03:11  [CHAIN]            info: Processed new chain head newChainHeadRoot=0xa4e0f227d2474a0
d2e461954a1eb217620fe9d74b38970dab548ccad37c57ffe, slot=36015, epoch=1125                  
2020-05-31 19:03:11  [SYNC]             info: Fetching blocks for 36016...36047 slot range 
2020-05-31 19:03:11  [SYNC]             info: Imported blocks for slots:                   
2020-05-31 19:03:11  [SYNC]             info: Fetching blocks for 36048...36079 slot range 
2020-05-31 19:03:11  [SYNC]             info: Imported blocks for slots:                   
2020-05-31 19:03:11  [SYNC]             info: Fetching blocks for 36080...36111 slot range 
2020-05-31 19:03:11  [SYNC]             info: Received goodbye request from 16Uiu2HAkxuEnKUUCkoEbs4rsi6Bm
HgcitGvq9WfDWCD1YgpSK9Ug, reason=2                                                                       
2020-05-31 19:03:11  [NETWORK]         error: failed to send status(ssz_snappy) to peer 16Uiu2HAm3xiixF2z
KFNB9a5ZHHD8uoLhCZw4fzz6gdSw9b7s8t58. Error: stream ended before 1 bytes became available  
    at /home/cayman/Code/lodestar/node_modules/it-reader/index.js:37:9                     
    at runMicrotasks (<anonymous>)                                                                           at processTicksAndRejections (internal/process/task_queues.js:93:5)                    
    at async /home/cayman/Code/lodestar/node_modules/it-length-prefixed/src/decode.js:80:20
    at async oneChunk (/home/cayman/Code/lodestar/node_modules/multistream-select/src/multistream.js:12:20)                                                                                                           at async Object.exports.read (/home/cayman/Code/lodestar/node_modules/multistream-select/src/multistream.js:34:15)                                                                                            
    at async module.exports (/home/cayman/Code/lodestar/node_modules/multistream-select/src/select.js:21:
19)                                                                                                          at async ClassIsWrapper.newStream [as _newStream] (/home/cayman/Code/lodestar/node_modules/libp2p/src
/upgrader.js:251:40)                                                                                     
    at async ClassIsWrapper.newStream (/home/cayman/Code/lodestar/node_modules/libp2p-interfaces/src/conn
ection/connection.js:172:34)
2020-05-31 19:03:11  [NETWORK]         error: failed to send status(ssz_snappy) to peer 16Uiu2HAkxuEnKUUC
koEbs4rsi6BmHgcitGvq9WfDWCD1YgpSK9Ug. Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
2020-05-31 19:03:11  [SYNC]             info: Imported blocks for slots:  
2020-05-31 19:03:11  [SYNC]             info: Fetching blocks for 36112...36143 slot range 
2020-05-31 19:03:12  [SYNC]             info: Imported blocks for slots:  
2020-05-31 19:03:12  [SYNC]             info: Fetching blocks for 36144...36175 slot range 
2020-05-31 19:03:12  [SYNC]             info: Imported blocks for slots:  
```

**Comment by mpetrunic** [comment]
Arent we suppose to have some logs with initial sync target? 😞

**Comment by wemeetagain** [comment]
It seems like it finished syncing its last targeted block range.

Here's the sync log just before the logs ^
```
2020-05-31 19:03:09  [SYNC]             info: Fetching blocks for 35984...36015 slot range               
2020-05-31 19:03:10  [SYNC]             info: Imported blocks for slots: 35986,35987,35988,35989,35991,35
992,35993,35996,35997,35998,35999,36000,36001,36002,36003,36004,36005,36006,36007,36008,36009,36010,36011
,36012,36014,36015 
```

**Comment by mpetrunic** [comment]
can you put somewhere complete log?

**Comment by wemeetagain** [comment]
There's too many logs, I have to copy by hand. Is there a specific part you want to see?

next time I need to output logs to disk for proper debugging, sorry

**Comment by mpetrunic** [comment]
can you post config somewhere so I can run it myself?

**Comment by wemeetagain** [comment]
Resolved
